-- Generated by Scripts/split_guide_vault.py; rerun the script to update.
if not RXPGuides or type(RXPGuides.RegisterGuide) ~= "function" then return end
local _, rxpGuideVaultAddon = ...
local rxpGuideVaultGame = rxpGuideVaultAddon and rxpGuideVaultAddon.game
if not rxpGuideVaultGame then
    local rxpGuideVaultVersion = select(4, GetBuildInfo())
    if rxpGuideVaultVersion > 60000 then
        rxpGuideVaultGame = "RETAIL"
    elseif rxpGuideVaultVersion > 50000 then
        rxpGuideVaultGame = "MOP"
    elseif rxpGuideVaultVersion > 40000 then
        rxpGuideVaultGame = "CATA"
    elseif rxpGuideVaultVersion > 30000 then
        rxpGuideVaultGame = "WOTLK"
    elseif rxpGuideVaultVersion > 20000 then
        rxpGuideVaultGame = "TBC"
    elseif rxpGuideVaultVersion >= 16000 and rxpGuideVaultVersion < 20000 then
        rxpGuideVaultGame = "FOREVER"
    else
        rxpGuideVaultGame = "CLASSIC"
    end
end
if rxpGuideVaultGame ~= "FOREVER" then return end

RXPGuides.RegisterGuide([[#forever
#version 23
#group RestedXP Forever Guide (A)
#subgroup Speedrun Guide 40-50

<< Alliance Warlock
#name 43-44 Tanaris/Dustwallow
#somname 44-45 Tanaris/Dustwallow
#next 44-48 Feralas

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Bragok|r
    .goto 1413/1,-3769.60,-898.33
    .fly Theramore>> Fly to Theramore
    .target Bragok

step
    .goto 1445/1,-4588.89,-3896.21,40,0
    .goto 1445/1,-4530.09,-3843.11
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Privateer Groy|r
    >>|cRXP_FRIENDLY_Privateer Groy|r |cRXP_WARN_patrols through Theramore Isle|r
    .turnin 623 >> Turn in Akiris by the Bundle
    .target Privateer Groy

step
    .skill firstaid,<225,1
    .goto 1445/1,-4532.19,-3747.21
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Doctor Gustaf VanHowzen|r
    .accept 6624 >> Accept Triage
    .target Doctor Gustaf VanHowzen

step
    .isOnQuest 6624
    .goto 1445/1,-4532.19,-3747.21
    .use 16991 >> |cRXP_WARN_Channel the|r |T133682:0|t[Triage Bandage] |cRXP_WARN_on the |cRXP_FRIENDLY_Alliance Soldiers|r. Prioritize |cRXP_FRIENDLY_Critically Injured Soldiers|r first|r
    .complete 6624,1
    .target Critically Injured Alliance Soldier
    .target Badly Injured Alliance Soldier
    .target Injured Alliance Soldier

step
    .isQuestComplete 6624
    .goto 1445/1,-4532.19,-3747.21
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Doctor Gustaf VanHowzen|r
    .turnin 6624 >> Turn in Triage
    .target Doctor Gustaf VanHowzen

step
    .isQuestComplete 1258
    .goto 1445/1,-4457.64,-3624.75
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Morgan Stern|r
    .turnin 1258 >> Turn in ... and Bugs
    .target Morgan Stern

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Innkeeper Janene|r
    .goto 1445/1,-4470.82,-3616.14
    .home >> Set your Hearthstone to Theramore
    .target Innkeeper Janene

step
    .goto 1445/1,-4517.49,-3828.8300
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Baldruc|r
    .fly Tanaris>> Fly to Tanaris
    .target Baldruc

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Chief Engineer Bilgewhizzle|r and |cRXP_FRIENDLY_Spigot Operator Luglunket|r
    .accept 1690 >> Accept Wastewander Justice
    .target +Chief Engineer Bilgewhizzle
    .goto 1446/1,-3838.63,-7186.64
    .accept 1707 >> Accept Water Pouch Bounty
    .target +Spigot Operator Luglunket
    .goto 1446/1,-3840.28,-7183.47

step
    .goto 1446/1,-3831.45,-7112.58
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Curgle Cranklehop|r
    .accept 3022 >> Accept Handle With Care
    .target Curgle Cranklehop

step
    .goto 1446/1,-3776.80,-7105.91
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Tran'rek|r
    .turnin 2864 >> Turn in Tran'rek
    .target Tran'rek

step
    .goto Tanaris,50.960,27.242
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Shreev|r
    .turnin 1188 >> Turn in Safety First
    .accept 1189 >> Accept Safety First
    .target Shreev

step
    #completewith tend
    >>Kill |cRXP_ENEMY_Rocs|r. Loot them for their |cRXP_LOOT_Gizzards|r
    >>|cRXP_WARN_Don't go out of your way to finish this|r
    .complete 1452,1
    .isOnQuest 1452
    .mob Roc

step
    #completewith PortQ
    >>Kill |cRXP_ENEMY_Wastewander Bandits|r and |cRXP_ENEMY_Wastewander Thieves|r. Loot them for their |cRXP_LOOT_Wastewander Water Pouches|r
    >>|cRXP_WARN_Kill them en-route to Steamwheedle Port. Don't complete this immediately|r
    .goto 1446/1,-4386.35,-7006.60,0
    .goto 1446/1,-4607.15,-7301.00,0
    .complete 1690,1
    .mob +Wastewander Bandit
    .complete 1690,2
    .mob +Wastewander Thief
    .complete 1707,1
    .mob +Wastewander Bandit
    .mob +Wastewander Thief

step
    .goto Tanaris,66.560,22.265
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Haughty Modiste|r
    .accept 8365 >> Accept Pirate Hats Ahoy!
    .target Haughty Modiste

step
    .goto 1446/1,-4840.99,-6903.28
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Yeh'kinya|r
    .accept 3520 >> Accept Screecher Spirits
    .target Yeh'kinya

step
    #label PortQ
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Security Chief Bilgewhizzle|r and |cRXP_FRIENDLY_Stoley|r
    .accept 8366 >> Accept Southsea Shakedown
    .target +Security Chief Bilgewhizzle
    .goto 1446/1,-4845.75,-6973.99
    .turnin 2872 >> Turn in Stoley's Debt
    .accept 2873 >> Accept Stoley's Shipment
    .target +Stoley
    .goto 1446/1,-4849.27,-6977.99

step
    .goto 1446/1,-4368.41,-6952.32,0
    .goto 1446/1,-4624.40,-7220.96,50,0
    .goto 1446/1,-4609.22,-7331.36,50,0
    .goto 1446/1,-4584.38,-7419.22,50,0
    .goto 1446/1,-4549.88,-7264.200,50,0
    .goto 1446/1,-4629.92,-7328.600
    >>Kill |cRXP_ENEMY_Wastewander Bandits|r and |cRXP_ENEMY_Wastewander Thieves|r. Loot them for their |cRXP_LOOT_Wastewander Water Pouches|r
    .complete 1690,1
    .mob +Wastewander Bandit
    .complete 1690,2
    .mob +Wastewander Thief
    .complete 1707,1
    .mob +Wastewander Bandit
    .mob +Wastewander Thief

step
    #label tend
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Chief Engineer Bilgewhizzle|r and |cRXP_FRIENDLY_Spigot Operator Luglunket|r
    .turnin 1690 >> Turn in Wastewander Justice
    .target +Chief Engineer Bilgewhizzle
    .goto 1446/1,-3838.63,-7186.64
    .turnin 1707 >> Turn in Water Pouch Bounty
    .target +Spigot Operator Luglunket
    .goto 1446/1,-3840.28,-7183.47

step
    #completewith NFF
    .goto 1441/1,-3868.15,-6229.03
    .zone Thousand Needles >> Travel to The Shimmering Flats

step
    .goto 1441/1,-3868.15,-6229.03
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Fizzle Brassbolts|r
    .turnin 1137 >> Turn in News for Fizzle
    .target Fizzle Brassbolts

step
    .goto 1441/1,-3855.74,-6233.05
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kravel Koalbeard|r
    >>|cRXP_WARN_This is a timed quest. If it has timed out already, abandon it instead|r
    .turnin 1119 >> Turn in Zanzil's Mixture and a Fool's Stout
    .timer 13,Kravel Koalbeard RP
    .accept 1120 >> Accept Get the Gnomes Drunk
    .isQuestTurnedIn 1118
    .target Kravel Koalbeard

step
    .goto 1441/1,-3846.11,-6223.60
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gnome Pit Boss|r
    .turnin 1120 >> Turn in Get the Gnomes Drunk
    .isQuestTurnedIn 1118
    .target Gnome Pit Boss

step
    .goto 1441/1,-3855.74,-6233.05
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kravel Koalbeard|r
    .accept 1122 >> Accept Report Back to Fizzlebub
    .isQuestTurnedIn 1118
    .target Kravel Koalbeard

step
    .goto 1441/1,-3967.68,-6198.82
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Razzeric|r
    .turnin 1189 >> Turn in Safety First
    .target Razzeric

step
    #label NFF
    .goto 1441/1,-3961.17,-6192.54
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Pozzik|r
    .accept 1190 >> Accept Keeping Pace
    .target Pozzik

step
    #completewith next
    .goto 1441/1,-3944.93,-6226.15
    .target Zamek
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Zamek|r create a diversion
    .turnin 1191 >> Turn in Zamek's Distraction
    .timer 30,Zamek's Distraction RP

step
    .goto 1441/1,-3830.49,-6236.66
    >>Click |cRXP_PICK_Rizzle's Unguarded Plans|r on the ground
    .turnin 1190 >> Turn in Keeping Pace
    .accept 1194 >> Accept Rizzle's Schematics

step
    .goto 1441/1,-3961.17,-6192.54
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Pozzik|r
    .turnin 1194 >> Turn in Rizzle's Schematics
    .target Pozzik

step
    .destroy 5866 >> Delete the |T134575:0|t[Sample of Indurium Ore] you do not need it

step
    .dungeon ZF
    .goto 1441/1,-3871.63,-6228.850
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Wizzle Brassbolts|r
    .accept 2770 >> Accept Gahz'rilla
    .target Wizzle Brassbolts

step
    .dungeon ZF
    .goto 1446/1,-3766.25,-7197.59
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Trenton Lighthammer|r
    .accept 3042 >> Accept Troll Temper
    .target Trenton Lighthammer

step
    .dungeon ZF
    .goto 1446/1,-3838.63,-7186.64
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Chief Engineer Bilgewhizzle|r
    .accept 2768 >> Accept Divino-matic Rod
    .target Chief Engineer Bilgewhizzle

step
    .dungeon ZF
    .goto 1446/1,-3776.80,-7105.91
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Tran'rek|r
    .accept 2865 >> Accept Scarab Shells
    .target Tran'rek

step
    .dungeon ZF
    .goto 1446/1,-5281.28,-8043.44
    .goto 1446/1,-2891.19,-6787.59
    .subzone 978 >> You will now run Zul'Farrak. Grind on |cRXP_ENEMY_Pirates|r while looking for a ZF group

step
    .dungeon ZF
    .goto 1446/1,-2903.54,-6830.88,40,0
    .goto 1446/1,-2891.19,-6787.59
    .subzone 978,2 >> Enter Zul'Farrak

step
    .dungeon ZF
    #completewith Gahzrilla
    >>Kill |cRXP_ENEMY_Trolls|r. Loot them for their |cRXP_LOOT_Troll Temper|r
    .complete 3042,1
    .isOnQuest 3042

step
    .dungeon ZF
    #completewith next
    >>Kill |cRXP_ENEMY_Scarabs|r. Loot them for their |cRXP_LOOT_Uncracked Scarab Shell|r
    .complete 2865,1
    .isOnQuest 2865

step
    .dungeon ZF
    #optional
    >>Kill |cRXP_ENEMY_Theka the Martyr|r. Loot him for the |cRXP_LOOT_First Mosh'aru Tablet|r
    .complete 3527,1
    .mob Theka the Martyr
    .isOnQuest 3527

step
    .dungeon ZF
    >>Kill |cRXP_ENEMY_Scarabs|r. Loot them for their |cRXP_LOOT_Uncracked Scarab Shell|r
    .complete 2865,1
    .isOnQuest 2865

step
    .dungeon ZF
    #completewith NekrumMedallion
    +Ascend the Pyramid
    >>Kill the |cRXP_ENEMY_Sandfury Executioner|r. Loot him for the |cRXP_LOOT_Executioner's Key|r
    >>|cRXP_WARN_Anyone in the party may loot the|r |cRXP_LOOT_Key|r
    >>|cRXP_WARN_Use the|r |cRXP_LOOT_Executioner's Key|r |cRXP_WARN_on one of the |cRXP_PICK_Troll Cages|r to free |cRXP_FRIENDLY_Sergeant Bly|r and his band|r
    .collect 8444,1
    .disablecheckbox
    .isOnQuest 2991,2768
    .mob Sandfury Executioner

step
    .dungeon ZF
    >>Defend |cRXP_FRIENDLY_Sergeant Bly|r and his band, then move down with them after a short period of time
    >>Kill |cRXP_ENEMY_Nekrum Gutchewer|r. Loot him for |cRXP_LOOT_Nekrum's Medallion|r
    >>After you kill |cRXP_ENEMY_Nekrum Gutchewer|r, eat and drink then talk to |cRXP_FRIENDLY_Sergeant Bly|r to fight him
    >>Kill |cRXP_ENEMY_Sergeant Bly|r. Loot him for the |cRXP_LOOT_Divino-matic Rod|r
    .complete 2991,1
    .complete 2768,1
    .isOnQuest 2991
    .isOnQuest 2768
    .skipgossip

step
    .dungeon ZF
    >>Defend |cRXP_FRIENDLY_Sergeant Bly|r and his band, then move down with them after a short period of time
    >>Kill |cRXP_ENEMY_Nekrum Gutchewer|r. Loot him for |cRXP_LOOT_Nekrum's Medallion|r
    .complete 2991,1
    .isOnQuest 2991
    .skipgossip

step
    .dungeon ZF
    #label NekrumMedallion
    >>Defend |cRXP_FRIENDLY_Sergeant Bly|r and his band, then move down with them after a short period of time
    >>Kill |cRXP_ENEMY_Nekrum Gutchewer|r. Eat and drink then talk to |cRXP_FRIENDLY_Sergeant Bly|r to fight him
    >>Kill |cRXP_ENEMY_Sergeant Bly|r. Loot him for the |cRXP_LOOT_Divino-matic Rod|r
    .complete 2768,1
    .isOnQuest 2768
    .skipgossip

step
    .dungeon ZF
    #optional
    >>Kill |cRXP_ENEMY_Hydromancer Velratha|r. Loot her for the |cRXP_LOOT_Tiara of the Deep|r and the |cRXP_LOOT_Second Mosh'aru Tablet|r
    .complete 2846,1
    .complete 3527,2
    .mob Hydromancer Velratha
    .isOnQuest 2846
    .isOnQuest 3527

step
    .dungeon ZF
    >>Kill |cRXP_ENEMY_Hydromancer Velratha|r. Loot her for the |cRXP_LOOT_Tiara of the Deep|r
    .complete 2846,1
    .mob Hydromancer Velratha
    .isOnQuest 2846

step
    .dungeon ZF
    #optional
    >>Kill |cRXP_ENEMY_Hydromancer Velratha|r. Loot her for the |cRXP_LOOT_Second Mosh'aru Tablet|r
    .complete 3527,2
    .mob Hydromancer Velratha
    .isOnQuest 3527

step
    .dungeon ZF
    #label Gahzrilla
    >>|cRXP_WARN_Use the|r |T133056:0|t[Mallet of Zul'Farrak] |cRXP_WARN_on the |cRXP_PICK_Gong of Zul'Farrak|r to summon|r |cRXP_ENEMY_Gahz'rilla|r
    >>Kill |cRXP_ENEMY_Gahz'rilla|r. Loot him for |cRXP_LOOT_Gahz'rilla's Electrified Scale|r
    >>|cRXP_WARN_If no one in your party has the|r |T133056:0|t[Mallet of Zul'Farrak] |cRXP_WARN_you will not be able to summon|r |cRXP_ENEMY_Gahz'rilla|r
    .complete 2770,1
    .mob Gahz'rilla
    .isOnQuest 2770

step
    .dungeon ZF
    >>Kill |cRXP_ENEMY_Trolls|r. Loot them for their |cRXP_LOOT_Troll Temper|r
    .complete 3042,1
    .isOnQuest 3042

step
    .dungeon ZF
    #completewith ZFTurnIn
    .subzone 976 >> Travel to Gadgetzan

step
    .dungeon ZF
    .isQuestComplete 3042
    .goto 1446/1,-3766.25,-7197.59
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Trenton Lighthammer|r
    .turnin 3042 >> Turn in Troll Temper
    .target Trenton Lighthammer

step
    .dungeon ZF
    .isQuestComplete 2768
    .goto 1446/1,-3838.63,-7186.64
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Chief Engineer Bilgewhizzle|r
    .turnin 2768 >> Turn in Divino-matic Rod
    .target Chief Engineer Bilgewhizzle

step
    .dungeon ZF
    .isQuestComplete 2865
    .goto 1446/1,-3776.80,-7105.91
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Tran'rek|r
    .turnin 2865 >> Turn in Scarab Shells
    .target Tran'rek

step
    .dungeon ZF
    #optional
    .isQuestComplete 3527
    .goto 1446/1,-4840.99,-6903.28
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Yeh'kinya|r
    .turnin 3527 >> Turn in The Prophecy of Mosh'aru

    .target Yeh'kinya

step
    .dungeon ZF
    #completewith ZFTurnIn
    .goto 1441/1,-3855.74,-6233.05
    .subzone 2240 >> Travel to the Mirage Raceway

step
    .dungeon ZF
    .isQuestComplete 2770
    .goto 1441/1,-3871.63,-6228.850
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Wizzle Brassbolts|r
    .turnin 2770 >> Turn in Gahz'rilla
    .target Wizzle Brassbolts

step
    .dungeon ZF
    #optional
    .abandon 2770 >> Abandon Gahz'rilla

step
    .hs >> Hearth to Theramore
    >>|cRXP_BUY_Buy food/water if needed|r

step << Warlock
    #completewith next
    .goto 1445/1,-3876.15,-3802.23,45 >> Swim west towards |cRXP_FRIENDLY_Tabetha|r

step << Warlock
    #completewith next
    +|cRXP_WARN_The follow up quest will have |cRXP_FRIENDLY_Tabetha|r summon |cRXP_ENEMY_Demon of the Orb|r which is a level 40 Elite that you need to kill. This quest is simple so long as you don't aggro additional mobs|r
    >>|cRXP_WARN_Kill any mobs around |cRXP_FRIENDLY_Tabetha's|r farm before accepting the next quest|r

step << Warlock
    .isOnQuest 1799
    .goto 1445/1,-3391.10,-4031.69
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Tabetha|r
    .turnin 1799 >> Turn in Fragments of the Orb of Orahil
    .accept 4961 >> Accept Cleansing of the Orb of Orahil
    .target Tabetha

step << Warlock
    #optional
    .isQuestTurnedIn 1799
    .goto 1445/1,-3391.10,-4031.69
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Tabetha|r
    .accept 4961 >> Accept Cleansing of the Orb of Orahil
    .target Tabetha

step << Warlock
    .isOnQuest 4961
    .goto 1445/1,-3383.17,-4019.23
    >>Kill |cRXP_ENEMY_Demon of the Orb|r
    >>|cRXP_WARN_Cast|r |T136183:0|t[Fear] |cRXP_WARN_continously on |cRXP_ENEMY_Demon of the Orb|r until your DoTs kill it|r
    .complete 4961,1
    .mob Demon of the Orb

step << Warlock
    .isOnQuest 4961
    .goto 1445/1,-3391.10,-4031.69
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Tabetha|r
    .turnin 4961 >> Turn in Cleansing of the Orb of Orahil
    .accept 4976 >> Accept Returning the Cleansed Orb
    .target Tabetha

step << Warlock
    #optional
    .isQuestTurnedIn 4961
    .goto 1445/1,-3391.10,-4031.69
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Tabetha|r
    .accept 4976 >> Accept Returning the Cleansed Orb
    .target Tabetha

step
    .goto 1445/1,-2607.64,-4348.41
    >>Click the |cRXP_PICK_Musty Scroll|r on the rock
    .turnin 625 >> Turn in Cortello's Riddle
    .accept 626 >> Accept Cortello's Riddle
    .isQuestTurnedIn 624

step
    #completewith next
    .deathskip >> Die and respawn at the Spirit Healer in Theramore
    .target Spirit Healer

step
    .goto 1445/1,-4517.49,-3828.8300
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Baldruc|r
    .fly Ratchet>> Fly to Ratchet
    .target Baldruc

step << Warlock
    .goto 1413/1,-3711.33,-782.52
    .target Menara Voidrender
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Menara Voidrender|r
    .turnin -4962 >> Turn in Shard of a Felhound
    .turnin -4976 >> Turn in Returning the Cleansed Orb

step << Warlock
    .goto 1413/1,-3711.33,-782.52
    .target Menara Voidrender
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Menara Voidrender|r
    >>|cRXP_WARN_Wait out the RP|r
    .accept 4964 >> Accept The Completed Orb of Dar'Orahil
    .turnin 4964 >> Turn in The Completed Orb of Dar'Orahil
    .isQuestTurnedIn 4962
    .isQuestTurnedIn 4976

step
    .goto 1413/1,-3724.50,-915.76,-1
    .goto The Barrens,62.680,37.395,-1
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Fuzruckle|r or |cRXP_FRIENDLY_Zikkel|r
    .bankdeposit 5807,6257 >> Deposit the following items into your bank:
    >>|T133471:0|t[Fool's Stout Report]
    >>|T133707:0|t[Roc Gizzard] (If you have any)
    .target Fuzruckle
    .target Zikkel
]])
