-- Generated by Scripts/split_guide_vault.py; rerun the script to update.
if not RXPGuides or type(RXPGuides.RegisterGuide) ~= "function" then return end
local _, rxpGuideVaultAddon = ...
local rxpGuideVaultGame = rxpGuideVaultAddon and rxpGuideVaultAddon.game
if not rxpGuideVaultGame then
    local rxpGuideVaultVersion = select(4, GetBuildInfo())
    if rxpGuideVaultVersion > 60000 then
        rxpGuideVaultGame = "RETAIL"
    elseif rxpGuideVaultVersion > 50000 then
        rxpGuideVaultGame = "MOP"
    elseif rxpGuideVaultVersion > 40000 then
        rxpGuideVaultGame = "CATA"
    elseif rxpGuideVaultVersion > 30000 then
        rxpGuideVaultGame = "WOTLK"
    elseif rxpGuideVaultVersion > 20000 then
        rxpGuideVaultGame = "TBC"
    elseif rxpGuideVaultVersion >= 16000 and rxpGuideVaultVersion < 20000 then
        rxpGuideVaultGame = "FOREVER"
    else
        rxpGuideVaultGame = "CLASSIC"
    end
end
if rxpGuideVaultGame ~= "FOREVER" then return end

RXPGuides.RegisterGuide([[#forever
#version 23
#group RestedXP Forever Guide (A)
#subgroup Speedrun Guide 40-50

<< Alliance !Hunter
#name 40-41 Desolace
#next 41-41 Badlands

step
    .goto 1445/1,-4517.49,-3828.8300
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Baldruc|r
    .fly Desolace >> Fly to Desolace
    .target Baldruc

step
    .goto 1443/1,1253.72,255.60
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Innkeeper Lyshaerya|r
    .home >> Set your Hearthstone to Desolace
    .target Innkeeper Lyshaerya

step
    .goto 1443/1,1242.75,215.04
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Brother Anton|r
    .accept 261 >> Accept Down the Scarlet Path
    .target Brother Anton

step
    #optional
    .goto 1443/1,1257.05,163.50
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kreldig Ungor|r
    .turnin 1453 >> Turn in Reclaimers' Business in Desolace
    .target Kreldig Ungor
    .isOnQuest 1453

step
    #optional
    .goto 1443/1,1257.05,163.50
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kreldig Ungor|r
    .accept 1458 >> Accept Reagents for Reclaimers Inc.
    .target Kreldig Ungor
    .isQuestAvailable 1458
    .maxlevel 40

step
    #optional
    .goto 1443/1,953.17,-101.63,70,0
    .goto 1443/1,661.39,-77.05,70,0
    .goto 1443/1,722.54,-222.450,70,0
    .goto 1443/1,802.11,-299.79,70,0
    .goto 1443/1,908.21,-208.96,70,0
    .goto 1443/1,973.40,-85.44
    >>Kill |cRXP_ENEMY_Hatefury Satyrs|r. Loot them for their |cRXP_LOOT_Claws|r and |cRXP_LOOT_Horns|r
    .complete 1458,1
    .complete 1458,2
    .mob Hatefury Trickster
    .mob Hatefury Shadowstalker
    .mob Hatefury Hellcaller
    .mob Hatefury Betrayer
    .isOnQuest 1458

step
    #optional
    .goto 1443/1,1257.05,163.50
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kreldig Ungor|r
    .turnin 1458 >> Turn in Reagents for Reclaimers Inc.
    .target Kreldig Ungor
    .isQuestComplete 1458

step
    .goto 1443/1,1257.05,163.50
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kreldig Ungor|r
    .accept 1459 >> Accept Reagents for Reclaimers Inc.
    .target Kreldig Ungor
    .isQuestAvailable 1459
    .maxlevel 40

step
    >>Kill |cRXP_ENEMY_Scorpashi Snappers|r, |cRXP_ENEMY_Scorpashi Lashers|r and |cRXP_ENEMY_Scorpashi Venomlashs|r. Loot them for their |cRXP_LOOT_Venom|r
    >>Kill |cRXP_ENEMY_Aged Kodos|r. Loot them for their |cRXP_LOOT_Aged Kodo Hides|r
    >>|cRXP_WARN_You may need to kill |cRXP_ENEMY_Gritjaw Basilisks|r to force |cRXP_ENEMY_Scorpashi Snappers|r and |cRXP_ENEMY_Scorpashi Lashers|r to spawn|r
    >>|cRXP_WARN_You must complete this step now|r
    .complete 1459,1
    .mob +Scorpashi Snapper
    .mob +Scorpashi Lasher
    .mob +Scorpashi Venomlash
    .goto 1443/1,1068.27,-1436.60,80,0
    .goto 1443/1,1598.77,-1046.88,80,0
    .goto 1443/1,2372.06,-992.91,80,0
    .goto 1443/1,2273.15,-1802.35
    .complete 1459,2
    .goto 1443/1,1886.96,-1271.720,70,0
    .goto 1443/1,1440.07,-1366.15,70,0
    .goto 1443/1,1362.29,-1611.38,70,0
    .goto 1443/1,1886.96,-1271.720
    .mob +Aged Kodo
    .isOnQuest 1459

step
    #optional
    .goto 1443/1,1257.05,163.50
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kreldig Ungor|r
    .turnin 1459 >> Turn in Reagents for Reclaimers Inc.
    .target Kreldig Ungor
    .isQuestComplete 1459

step
    .goto 1443/1,1257.05,163.50
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kreldig Ungor|r
    .accept 1466 >> Accept Reagents for Reclaimers Inc.
    .target Kreldig Ungor

step
    #completewith next
    .goto 1443/1,2082.98,-1401.23,90 >> Travel to |cRXP_FRIENDLY_Hornizz|r at the Kodo Graveyard

step
    .goto Desolace,47.830,61.825
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Hornizz Brimbuzzle|r
    .accept 6134 >> Accept Ghost-o-plasm Round Up
    .target Hornizz Brimbuzzle

step
    .isQuestTurnedIn 1370
    .goto 1443/1,2604.31,-1923.62
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Uthek the Wise|r
    .turnin 1373 >> Turn in Ongeku
    .accept 1374 >> Accept Khan Jehn
    .target Uthek the Wise

step << Warlock
    .isOnQuest 1799
    #completewith ReclaimersDemons
    >>Kill |cRXP_ENEMY_Burning Blade Summoners|r. Loot them for their |cRXP_LOOT_Infernal Orb|r
    .complete 1799,1
    .mob Burning Blade Summoner

step << Warlock
    .isOnQuest 4962
    #completewith ReclaimersDemons
    .use 12647 >>|cRXP_WARN_Channel the|r |T134129:0|t[Felhas Ruby] |cRXP_WARN_on a |cRXP_ENEMY_Ley Hunter|r, |cRXP_ENEMY_Mana Eater|r or |cRXP_ENEMY_Mage Hunter|r as it is about to die|r
    .complete 4962,1
    .mob Ley Hunter
    .mob Mana Eater
    .mob Mage Hunter

step
    #label ReclaimersDemons
    .goto 1443/1,1908.09,-2063.77,0
    >>Kill |cRXP_ENEMY_Ley Hunters|r, |cRXP_ENEMY_Mana Eaters|r and |cRXP_ENEMY_Mage Hunters|r. Loot them for their |cRXP_LOOT_Brains|r
    >>Kill |cRXP_ENEMY_Nether Sisters|r, |cRXP_ENEMY_Nether Maidens|r and |cRXP_ENEMY_Nether Sorceresses|r. Loot them for their |cRXP_LOOT_Wings|r
    >>Kill |cRXP_ENEMY_Doomwarder Captains|r. Loot them for their |cRXP_LOOT_Blood|r
    >>|cRXP_WARN_Prioritize |cRXP_ENEMY_Doomwarder Captains|r as you may need to wait for their respawns. Regular |cRXP_ENEMY_Doomwarders|r do not drop|r |cRXP_LOOT_Blood|r. You could also ask someone to invite you so you change layers|r
    .complete 1466,1
    .mob +Ley Hunter
    .mob +Mana Eater
    .mob +Mage Hunter
    .goto 1443/1,1958.44,-1994.22,70,0
    .goto 1443/1,1913.48,-2120.13,70,0
    .goto 1443/1,1823.57,-2084.15,70,0
    .goto 1443/1,1823.57,-1874.30,70,0
    .goto 1443/1,1688.69,-1814.34,70,0
    .goto Desolace,53.0,68.6,70,0
    .goto 1443/1,1823.57,-1874.30
    .complete 1466,2
    .mob +Nether Sister
    .mob +Nether Maiden
    .mob +Nether Sorceress
    .goto 1443/1,1778.61,-1892.29,70,0
    .goto 1443/1,1958.44,-1694.42,70,0
    .goto 1443/1,2039.37,-1874.30,70,0
    .goto 1443/1,1778.61,-1892.29,70,0
    .goto 1443/1,1958.44,-1694.42,70,0
    .goto 1443/1,2039.37,-1874.30
    .complete 1466,3
    .goto 1443/1,1908.09,-2063.77
    .mob +Doomwarder Captain

step << Warlock
    .isOnQuest 1799
    #completewith next
    >>Kill |cRXP_ENEMY_Burning Blade Summoners|r. Loot them for their |cRXP_LOOT_Infernal Orb|r
    .complete 1799,1
    .mob Burning Blade Summoner

step << Warlock
    .isOnQuest 4962
    .goto 1443/1,1958.44,-1994.22,70,0
    .goto 1443/1,1913.48,-2120.13,70,0
    .goto 1443/1,1823.57,-2084.15,70,0
    .goto 1443/1,1823.57,-1874.30,70,0
    .goto 1443/1,1688.69,-1814.34,70,0
    .goto Desolace,53.0,68.6,70,0
    .goto 1443/1,1823.57,-1874.30
    .use 12647 >>|cRXP_WARN_Channel the|r |T134129:0|t[Felhas Ruby] |cRXP_WARN_on a |cRXP_ENEMY_Ley Hunter|r, |cRXP_ENEMY_Mana Eater|r or |cRXP_ENEMY_Mage Hunter|r as it is about to die|r
    .complete 4962,1
    .mob Ley Hunter
    .mob Mana Eater
    .mob Mage Hunter

step << Warlock
    .isOnQuest 1799
    .goto 1443/1,1967.43,-1694.42,70,0
    .goto 1443/1,1994.41,-1880.30,70,0
    .goto 1443/1,1877.52,-2054.17,70,0
    .goto Desolace,55.0,77.8
    >>Kill |cRXP_ENEMY_Burning Blade Summoners|r. Loot them for their |cRXP_LOOT_Infernal Orb|r
    .complete 1799,1
    .mob Burning Blade Summoner

step
    #completewith next
    >>Kill |cRXP_ENEMY_Undead Ravagers|r
    .complete 261,1
    .mob Undead Ravager

step
    .goto Desolace,64.00,91.70
    >>|cRXP_WARN_Use the|r |T132763:0|t[Crate of Ghost Magnets] |cRXP_WARN_at the Valley of Bones between the two giant skeleton remains|r
    >>Kill |cRXP_ENEMY_Magrami Spectres|r that spawn from it. Loot them for their |cRXP_LOOT_Ghost-o-plasms|r
    .complete 6134,1
    .mob Magrami Spectre

step
    .goto Desolace,64.30,81.96,70,0
    .goto Desolace,64.00,91.70,70,0
    .goto 1443/1,1539.88,-2228.65,70,0
    .goto Desolace,64.00,91.70
    >>Kill |cRXP_ENEMY_Undead Ravagers|r
    .complete 261,1
    .mob Undead Ravager

step
    .isQuestTurnedIn 1370
    .goto 1443/1,1268.78,-1958.240
    >>Kill |cRXP_ENEMY_Khan Jehn|r. Loot him for his |cRXP_LOOT_Head|r
    .complete 1374,1
    .mob Khan Jehn

step
    .isQuestComplete 6134
    .goto Desolace,47.830,61.825
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Hornizz Brimbuzzle|r
    .turnin 6134 >> Turn in Ghost-o-plasm Round Up
    .target Hornizz Brimbuzzle

step
    .isQuestTurnedIn 1370
    .goto 1443/1,2604.31,-1923.62
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Uthek the Wise|r
    .turnin 1374 >> Turn in Khan Jehn
    .target Uthek the Wise

step
    #optional
    .abandon 6134 >> Abandon Ghost-o-plasm Round Up if you did not complete it

step
    .goto 1443/1,2384.20,-2297.61
    .zone Feralas >> Head to Feralas

step
    #completewith end
    .goto 1444/1,2619.97,-2765.13
    >>|cRXP_WARN_Once you get to Feralas, walk along the mountains to the west to avoid aggroing mobs and then die near the stone obelisks|r
    .deathskip >> Die and respawn at the Spirit Healer
    .target Spirit Healer

step
    #label end
    .goto 1444/1,3340.13,-4370.49
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Fyldren Moonfeather|r
    .fp Feathermoon >> Get the Feathermoon Flight Path
    .target Fyldren Moonfeather

step
    #completewith FlatsEnd
    .goto 1444/1,3340.13,-4370.49
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Fyldren Moonfeather|r
    .fly Tanaris >> Fly to Tanaris
    .target Fyldren Moonfeather

step
    #completewith next
    .goto 1441/1,-3855.74,-6233.05,100 >> Travel to The Shimmering Flats

step
    #label Martek
    .goto 1441/1,-3868.15,-6229.03
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Fizzle Brassbolts|r
    .accept 1106 >> Accept Martek the Exiled
    .target Fizzle Brassbolts

step
    .isOnQuest 1117
    .goto 1441/1,-3855.74,-6233.05
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kravel Koalbeard|r
    .turnin 1117 >> Turn in Rumors for Kravel
    .timer 10,Rumors for Kravel RP
    .accept 1118 >> Accept Back to Booty Bay
    .target Kravel Koalbeard

step
    .isQuestTurnedIn 1117
    .goto 1441/1,-3855.74,-6233.05
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kravel Koalbeard|r
    .accept 1118 >> Accept Back to Booty Bay
    .target Kravel Koalbeard

step
    .goto 1441/1,-3967.68,-6198.82
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Razzeric|r
    .turnin 1187 >> Turn in Razzeric's Tweaking
    .accept 1188 >> Accept Safety First
    .target Razzeric
    .isOnQuest 1187

step
    #optional
    .goto 1441/1,-3967.68,-6198.82
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Razzeric|r
    .accept 1188 >> Accept Safety First
    .target Razzeric
    .isQuestTurnedIn 1187
    .isQuestAvailable 1188

step
    #completewith next
    .hs >> Hearth to Desolace
    >>|cRXP_BUY_Buy food/water if needed|r << !Warrior !Rogue
    >>|cRXP_BUY_Buy food if needed|r << Warrior/Rogue

step
    .goto 1443/1,1242.75,215.04
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Brother Anton|r
    .turnin 261 >> Turn in Down the Scarlet Path
    .target Brother Anton

step
    .goto 1443/1,1257.05,163.50
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kreldig Ungor|r
    .turnin 1466 >> Turn in Reagents for Reclaimers Inc.
    .accept 1467 >> Accept Reagents for Reclaimers Inc.
    .target Kreldig Ungor

step << !Mage
    .goto 1443/1,1326.33,136.40
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Baritanas Skyriver|r
    .fly Theramore >> Fly to Theramore
    .target Baritanas Skyriver

step << !Mage
    .goto 1445/1,-4726.65,-4003.830
    .zone Wetlands >> Take the boat to Menethil Harbor

step << !Mage
    #label end
    .goto Wetlands,9.490,59.694
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Shellei|r
    .fly Ironforge >> Fly to Ironforge
    .target Shellei Brondir

step
    .dungeon SM
    .goto Ironforge,74.980,12.486
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Librarian Mae Paledust|r
    .turnin 1050 >> Turn in Mythology of the Titans
    .target Librarian Mae Paledust
]])
