-- Generated by Scripts/split_guide_vault.py; rerun the script to update.
if not RXPGuides or type(RXPGuides.RegisterGuide) ~= "function" then return end
local _, rxpGuideVaultAddon = ...
local rxpGuideVaultGame = rxpGuideVaultAddon and rxpGuideVaultAddon.game
if not rxpGuideVaultGame then
    local rxpGuideVaultVersion = select(4, GetBuildInfo())
    if rxpGuideVaultVersion > 60000 then
        rxpGuideVaultGame = "RETAIL"
    elseif rxpGuideVaultVersion > 50000 then
        rxpGuideVaultGame = "MOP"
    elseif rxpGuideVaultVersion > 40000 then
        rxpGuideVaultGame = "CATA"
    elseif rxpGuideVaultVersion > 30000 then
        rxpGuideVaultGame = "WOTLK"
    elseif rxpGuideVaultVersion > 20000 then
        rxpGuideVaultGame = "TBC"
    elseif rxpGuideVaultVersion >= 16000 and rxpGuideVaultVersion < 20000 then
        rxpGuideVaultGame = "FOREVER"
    else
        rxpGuideVaultGame = "CLASSIC"
    end
end
if rxpGuideVaultGame ~= "FOREVER" then return end

RXPGuides.RegisterGuide([[#forever
#version 23
#group RestedXP Forever Guide (A)
#subgroup Speedrun Guide 40-50

<< Alliance
#name 44-48 Feralas
#somname 45-47 Feralas
#next 48-49 Tanaris/Hinterlands

step
    #season 0
    #sticky
    #completewith start
    +|cRXP_WARN_There is A LOT of grinding required in this segment, you can substitute some of that for Zul'Farrak/Uldaman/Maraudon runs|r

step
    #season 0
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Bragok|r << Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Bera Stonehammer|r << !Warlock
    .goto 1413/1,-3769.60,-898.33 << Warlock
    .goto 1446/1,-3738.16,-7224.87 << !Warlock
    >>|cRXP_WARN_If you don't have Feathermoon Flight Path, fly to Thalanaar instead and then run there|r
    .fly Feathermoon>> Fly to Feathermoon
    .target Bragok << Warlock
    .target Bera Stonehammer << !Warlock

step
    .goto 1444/1,3312.74,-4345.38
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Pratt McGrubben|r
    .accept 2821 >> Accept The Mark of Quality
    .target Pratt McGrubben

step
    #completewith start
    .goto 1444/1,3284.18,-4364.37
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Mardrack Greenwell|r
    >>|cRXP_WARN_Restock on Food/Water. There is a long grind section ahead|r << !sod
    .vendor 7941 >>|cRXP_BUY_Buy 5 stacks of food/water|r << !sod
    .target Mardrack Greenwell

step
    .goto 1444/1,3289.53,-4381.61
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Innkeeper Shyria|r
    .home >> Set your Hearthstone to Feralas
    .target Innkeeper Shyria

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Latronicus Moonspear|r and |cRXP_FRIENDLY_Shandris Feathermoon|r
    .accept +4124 >> Accept The Missing Courier
    .target Latronicus Moonspear
    .goto 1444/1,3330.33,-4505.880
    .accept 2866 >> Accept The Ruins of Solarsal
    .goto 1444/1,3337.48,-4505.78
    .target +Shandris Feathermoon

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Troyas Moonbreeze|r and |cRXP_FRIENDLY_Angelas Moonbreeze|r
    .accept 2939 >> Accept In Search of Knowledge
    .target +Troyas Moonbreeze
    .goto 1444/1,3233.17,-4474.74
    .accept 2982 >> Accept The High Wilderness
    .goto 1444/1,3229.62,-4479.98
    .target +Angelas Moonbreeze

step
    #label start
    .goto 1444/1,3207.94,-4472.98,10,0
    .goto Feralas,31.860,45.130
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ginro Hearthkindle|r up stairs
    .turnin 4124 >> Turn in The Missing Courier
    .accept 4125 >> Accept The Missing Courier
    .target Ginro Hearthkindle

step
    .goto 1444/1,3612.70,-4791.89
    >>Click the |cRXP_PICK_Solarsal Gazebo|r
    .turnin 2866 >> Turn in The Ruins of Solarsal
    .accept 2867 >> Accept Return to Feathermoon Stronghold

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Shandris Feathermoon|r and |cRXP_FRIENDLY_Latronicus Moonspear|r
    .turnin 2867 >> Turn in Return to Feathermoon Stronghold
    .accept 3130 >> Accept Against the Hatecrest
    .target Latronicus Moonspear
    .goto 1444/1,3337.48,-4505.78
    .turnin 3130 >> Turn in Against the Hatecrest
    .accept 2869 >> Accept Against the Hatecrest
    .goto 1444/1,3330.33,-4505.880
    .target +Shandris Feathermoon

step
    .goto 1444/1,3592.97,-4776.00,70,0
    .goto 1444/1,3620.77,-4924.27,70,0
    .goto 1444/1,3384.47,-4850.13,70,0
    .goto Feralas,29.0,50.4,70,0
    .goto 1444/1,3592.97,-4840.87
    >>Kill |cRXP_ENEMY_Hatecrest Screamers|r, |cRXP_ENEMY_Hatecrest Wave Riders|r, |cRXP_ENEMY_Hatecrest Warriors|r and |cRXP_ENEMY_Hatecrest Sirens|r. Loot them for their |cRXP_LOOT_Naga Scales|r
    .complete 2869,1
    .mob Hatecrest Screamer
    .mob Hatecrest Wave Rider
    .mob Hatecrest Warrior
    .mob Hatecrest Siren

step
    .goto 1444/1,3330.33,-4505.880
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Latronicus Moonspear|r
    .turnin 2869 >> Turn in Against the Hatecrest
    .accept 2870 >> Accept Against Lord Shalzaru
    .target Latronicus Moonspear

step
    #completewith next
    .goto 1444/1,3670.11,-5374.63,40,0
    .goto 1444/1,3625.63,-5490.00,30 >> Travel to the Isle of Dread. Enter Shalzaru's Lair

step
    .goto 1444/1,3460.22,-5637.34
    >>Kill |cRXP_ENEMY_Lord Shalzaru|r. Loot him for the |cRXP_LOOT_Mysterious Relic|r
    .complete 2870,1
    .mob Lord Shalzaru

step
    >> Do loops around the cave grinding |cRXP_ENEMY_Nagas|r until you get the |T132836:0|t[|cRXP_LOOT_OOX-22/FE Distress Beacon|r]
    >>|cRXP_WARN_Don't start the quest for this yet|r
    .collect 8705,1,2766,1

    .mob Hatecrest Sorceress
    .mob Hatecrest Serpent Guard
    .mob Hatecrest Myrmidon

step
    .goto 1444/1,3524.86,-5564.59
    .xp 45+87500 >> Do loops around the cave, grinding |cRXP_ENEMY_Nagas|r to level 45+87500xp
    .mob Hatecrest Sorceress
    .mob Hatecrest Serpent Guard
    .mob Hatecrest Myrmidon

step
    #completewith next
    .goto 1444/1,2750.63,-5844.91,40 >> Exit the naga cave and head southeast towards the ocean
    .goto 1444/1,2575.49,-5820.35,40 >> Swim to the mainland

step
    .goto 1444/1,2283.59,-5376.48
    >>Click on the |cRXP_PICK_Wrecked Row Boat|r in the water
    .turnin 4125 >> Turn in The Missing Courier
    .accept 4127 >> Accept Boat Wreckage

step
    #completewith next
    .hs >> Hearth to Feathermoon Stronghold
    >>|cRXP_BUY_Buy food/water if needed|r << !Warrior !Rogue
    >>|cRXP_BUY_Buy food if needed|r << Warrior/Rogue

step
    .goto 1444/1,3207.94,-4472.98,10,0
    .goto Feralas,31.860,45.130
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ginro Hearthkindle|r up stairs
    .turnin 4127 >> Turn in Boat Wreckage
    .accept 4129 >> Accept The Knife Revealed
    .target Ginro Hearthkindle

step
    .goto 1444/1,3186.60,-4395.51
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Quintis Jonespyre|r atop the tree house
    .turnin 4129 >> Turn in The Knife Revealed
    .timer 12,The Knife Revealed RP
    .accept 4130 >> Accept Psychometric Reading
    .target Quintis Jonespyre

step
    .goto 1444/1,3207.94,-4472.98,10,0
    .goto Feralas,31.860,45.130
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ginro Hearthkindle|r up stairs
    .turnin 4130 >> Turn in Psychometric Reading
    .accept 4131 >> Accept The Woodpaw Gnolls
    .target Ginro Hearthkindle

step
    .goto 1444/1,3330.33,-4505.880
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Latronicus Moonspear|r
    .turnin 2870 >> Turn in Against Lord Shalzaru
    .accept 2871 >> Accept Delivering the Relic
    .target Latronicus Moonspear

step
    .goto 1444/1,3351.32,-4454.450
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Vestia Moonspear|r
    .turnin 2871 >> Turn in Delivering the Relic
    .target Vestia Moonspear

step
    #completewith next
    .goto 1444/1,2309.30,-4446.57,150 >> Swim to the mainland

step
    #completewith spirits
    .goto 1444/1,1824.19,-4631.44,0
    .goto 1444/1,2202.97,-4192.20,0
    .goto 1444/1,1424.57,-4720.40,0
    >>Kill |cRXP_ENEMY_Vale Screechers|r and |cRXP_ENEMY_Rogue Vale Screechers|r
    .use 10699 >> |cRXP_WARN_Use|r |T135474:0|t[Yeh'kinya's Bramble] |cRXP_WARN_on their corpses to summon a|r |cRXP_FRIENDLY_Screecher Spirit|r
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to the |cRXP_FRIENDLY_Screecher Spirit|r
    .complete 3520,1
    .skipgossip
    .mob Vale Screecher
    .mob Rogue Vale Screecher
    .target Screecher Spirit

step
    #completewith spirits
    .goto 1444/1,1355.07,-5100.33,0
    >>Kill |cRXP_ENEMY_Ironfur Bears|r, |cRXP_ENEMY_Grizzled Ironfur Bears|r and |cRXP_ENEMY_Groddoc Apes|r. Loot them for their |cRXP_LOOT_Livers|r
    .complete 1452,2
    .mob +Ironfur Bear
    .mob +Grizzled Ironfur Bear
    .complete 1452,3
    .mob +Groddoc Ape
    .isOnQuest 1452

step
    .goto 1444/1,1590.67,-4476.69
    .zone 1414 >> |cRXP_WARN_You must explore the Dire Maul zone as a pre-requisite to unlock a quest later on. Get close to the Dire Maul zone border until your General Chat changes to Dire Maul|r
    .link https://youtu.be/RM1fMMfj-kA >> |cRXP_WARN_Click here for video reference|r

step
    .goto 1444/1,1575.38,-4981.72,50,0
    .goto Feralas,53.50,55.47
    >>Kill |cRXP_ENEMY_Feral Scar Yetis|r, |cRXP_ENEMY_Enraged Feral Scars|r and |cRXP_ENEMY_Hulking Feral Scars|r. Loot them for their |cRXP_LOOT_Thick Yeti Hides|r
    .complete 2821,1
    .mob Feral Scar Yeti
    .mob Enraged Feral Scar
    .mob Hulking Feral Scar

step
    .use 8705 >> |cRXP_WARN_Use the |T132836:0|t[|cRXP_LOOT_OOX-22/FE Distress Beacon|r] to start the quest|r
    .collect 8705,1,2766
    .accept 2766 >> Accept Find OOX-22/FE!
    .itemcount 8705,1

step
    .isOnQuest 2766
    .goto 1444/1,1733.63,-4947.25
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to the |cRXP_FRIENDLY_Homing Robot OOX-22/FE|r
    .turnin 2766 >> Turn in Find OOX-22/FE!
    .target Homing Robot OOX-22/FE

step
    .isQuestTurnedIn 2766
    .goto 1444/1,1733.63,-4947.25
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to the |cRXP_FRIENDLY_Homing Robot OOX-22/FE|r
    .accept 2767,1 >> Accept Rescue OOX-22/FE!
    .target Homing Robot OOX-22/FE

step
    .isOnQuest 2767
    .goto 1444/1,2267.60,-4376.61
    >>Escort the |cRXP_FRIENDLY_Homing Robot OOX-22/FE|r to safety
    >>|cRXP_WARN_This quest can be hard. You have to fight waves of 3/4 mobs along the way. Skip this step if its too difficult|r
    .complete 2767,1
    .target Homing Robot OOX-22/FE

step
    #loop
    #label Egg
    .goto 1444/1,1712.51,-5812.24,0
    .goto 1444/1,1504.28,-5883.00,0
    .goto 1444/1,1500.46,-5921.54,0
    .goto 1444/1,1556.20,-5889.62,0
    .goto 1444/1,1712.51,-5812.24,10,0
    .goto 1444/1,1504.28,-5883.00,10,0
    .goto 1444/1,1500.46,-5921.54,10,0
    .goto 1444/1,1556.20,-5889.62,0
    >>Loot a |cRXP_LOOT_Hippogryph Egg|r from a nest
    .collect 8564,1,2741,1

step
    #label spirits
    >>Kill |cRXP_ENEMY_Gordunni Shamans|r, |cRXP_ENEMY_Gordunni Warlocks|r and |cRXP_ENEMY_Gordunni Brutes|r
    >>|cRXP_WARN_Prioritize killing |cRXP_ENEMY_Gordunni Shamans|r. You may need to kill other |cRXP_ENEMY_Gordunni Ogres|r to force |cRXP_ENEMY_Gordunni Shamans|r to spawn|r
    .complete 2982,2
    .mob +Gordunni Shaman
    .goto 1444/1,1303.64,-5291.69,60,0
    .goto 1444/1,1381.48,-5474.71,60,0
    .goto 1444/1,1273.75,-5431.15,60,0
    .goto 1444/1,1208.42,-5542.82,60,0
    .goto 1444/1,1307.81,-5460.34
    .goto Feralas,61.70,73.09,0
    .goto 1444/1,1333.52,-5606.76,0
    .complete 2982,1
    .mob +Gordunni Warlock
    .goto 1444/1,1303.64,-5291.69,60,0
    .goto 1444/1,1381.48,-5474.71,60,0
    .goto 1444/1,1273.75,-5431.15,60,0
    .goto 1444/1,1208.42,-5542.82,60,0
    .goto 1444/1,1334.91,-5352.85,60,0
    .goto 1444/1,1200.78,-4965.970,60,0
    .goto 1444/1,1172.28,-4882.570,60,0
    .goto 1444/1,1303.64,-5291.69
    .goto Feralas,61.70,73.09,0
    .goto 1444/1,1333.52,-5606.76,0
    .complete 2982,3
    .mob +Gordunni Brute
    .goto 1444/1,1334.91,-5352.85,60,0
    .goto 1444/1,1200.78,-4965.970,60,0
    .goto 1444/1,1172.28,-4882.570,60,0
    .goto 1444/1,1200.78,-4965.970

step
    #completewith next
    .goto Feralas,58.40,55.57,0
    .goto 1444/1,1460.01,-4873.300,0
    .goto Feralas,55.40,53.49,0
    .goto 1444/1,1484.34,-5176.32,0
    .goto 1444/1,1321.71,-5172.15,0
    >>Kill |cRXP_ENEMY_Ironfur Bears|r, |cRXP_ENEMY_Grizzled Ironfur Bears|r and |cRXP_ENEMY_Groddoc Apes|r. Loot them for their |cRXP_LOOT_Livers|r
    .complete 1452,2
    .mob +Ironfur Bear
    .mob +Grizzled Ironfur Bear
    .complete 1452,3
    .mob +Groddoc Ape
    .isOnQuest 1452

step
    .goto 1444/1,1744.27,-4553.60,60,0
    .goto Feralas,58.0,47.8,60,0
    .goto 1444/1,1216.07,-4720.40,60,0
    .goto 1444/1,1563.57,-4868.67,60,0
    .goto 1444/1,1368.97,-5091.07,60,0
    .goto 1444/1,1229.97,-5248.60
    .goto 1444/1,1744.27,-4553.60,0
    .goto Feralas,58.0,47.8,0
    .goto 1444/1,1216.07,-4720.40,0
    .goto 1444/1,1563.57,-4868.67,0
    .goto 1444/1,1368.97,-5091.07,0
    >>Kill |cRXP_ENEMY_Vale Screechers|r and |cRXP_ENEMY_Rogue Vale Screechers|r
    .use 10699 >> |cRXP_WARN_Use|r |T135474:0|t[Yeh'kinya's Bramble] |cRXP_WARN_on their corpses to summon a|r |cRXP_FRIENDLY_Screecher Spirit|r
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to the |cRXP_FRIENDLY_Screecher Spirit|r
    .complete 3520,1
    .skipgossip
    .mob Vale Screecher
    .mob Rogue Vale Screecher
    .target Screecher Spirit

step
    .goto Feralas,58.40,55.57,55,0
    .goto 1444/1,1460.01,-4873.300,55,0
    .goto Feralas,55.40,53.49,55,0
    .goto 1444/1,1484.34,-5176.32,55,0
    .goto 1444/1,1321.71,-5172.15
    >>Kill |cRXP_ENEMY_Ironfur Bears|r, |cRXP_ENEMY_Grizzled Ironfur Bears|r and |cRXP_ENEMY_Groddoc Apes|r. Loot them for their |cRXP_LOOT_Livers|r
    .complete 1452,2
    .mob +Ironfur Bear
    .mob +Grizzled Ironfur Bear
    .complete 1452,3
    .mob +Groddoc Ape
    .isOnQuest 1452

step
    .goto 1444/1,815.75,-4538.31,0
    .goto 1444/1,815.75,-4538.31,30,0
    .goto 1444/1,858.49,-4481.83
    >>|cRXP_WARN_Kill some of the |cRXP_ENEMY_Grimtotem|r around the giant cage containing |cRXP_FRIENDLY_Captured Sprite Darters|r before accepting this escort quest|r
    >>|cRXP_ENEMY_Grimtotem Raiders|r |cRXP_WARN_cast|r |T132149:0|t[Net] |cRXP_WARN_which immobilizes movement for 10 seconds|r
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kindal Moonweaver|r
    .accept 2969 >> Accept Freedom for All Creatures
    .target Kindal Moonweaver
    .mob Grimtotem Naturalist
    .mob Grimtotem Raider
    .mob Grimtotem Shaman

step
    .goto 1444/1,808.38,-4532.94
    >>Click the |cRXP_PICK_Cage Door|r to release the |cRXP_FRIENDLY_Captured Sprite Darters|r
    >>Kill any |cRXP_ENEMY_Grimtotem|r that are attacking the |cRXP_FRIENDLY_Captured Sprite Darters|r
    >>|cRXP_ENEMY_Grimtotem Raiders|r |cRXP_WARN_cast|r |T132149:0|t[Net] |cRXP_WARN_which immobilizes movement for 10 seconds|r
    .complete 2969,1
    .mob Grimtotem Naturalist
    .mob Grimtotem Raider
    .mob Grimtotem Shaman
    .target Captured Sprite Darter

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kindal Moonweaver|r and |cRXP_FRIENDLY_Jer'kai Moonweaver|r
    .turnin 2969 >> Turn in Freedom for All Creatures
    .target +Kindal Moonweaver
    .goto 1444/1,858.49,-4481.83
    .accept 2970 >> Accept Doling Justice
    .goto 1444/1,858.42,-4479.79
    .target +Jer'kai Moonweaver

step
    #label Grimtotems
    .goto 1444/1,809.49,-4524.87,60,0
    .goto Feralas,68.70,46.91,60,0
    .goto 1444/1,636.44,-4178.300,60,0
    .goto 1444/1,795.59,-4164.400,60,0
    .goto 1444/1,636.44,-4178.300
    .goto 1444/1,795.59,-4164.400,0
    >>Kill |cRXP_ENEMY_Grimtotem Naturalists|r, |cRXP_ENEMY_Grimtotem Raiders|r and |cRXP_ENEMY_Grimtotem Shamans|r
    >>|cRXP_ENEMY_Grimtotem Raiders|r |cRXP_WARN_cast|r |T132149:0|t[Net] |cRXP_WARN_which immobilizes movement for 10 seconds|r
    .complete 2970,1
    .mob +Grimtotem Naturalist
    .complete 2970,2
    .mob +Grimtotem Raider
    .complete 2970,3
    .mob +Grimtotem Shaman

step
    #label DolingJustice
    .goto 1444/1,858.42,-4479.79
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Jer'kai Moonweaver|r
    .turnin 2970 >> Turn in Doling Justice
    .accept 2972 >> Accept Doling Justice
    .target Jer'kai Moonweaver

step
    .goto 1444/1,346.34,-4975.74
    >>Click the |cRXP_PICK_Large Leather Backpacks|r on the tree
    .turnin 4131 >> Turn in The Woodpaw Gnolls
    .accept 4135 >> Accept The Writhing Deep

step
    .goto 1444/1,346.62,-4975.230
    .use 11463 >>|cRXP_WARN_Use the |T133628:0|t[|cRXP_LOOT_Undelivered Parcel|r] to start the quest|r
    .collect 11463,1,4281
    .accept 4281 >> Accept Thalanaar Delivery

step
    #completewith next
    .goto 1444/1,328.55,-5291.69,100,0
    .goto 1444/1,383.46,-5354.24,15 >> Enter The Writhering Deep Hive from the lower southwest entrance

step
    .goto Feralas,72.080,63.713
    >>Click the |cRXP_PICK_Zukk'ash Pod|r
    .turnin 4135 >> Turn in The Writhing Deep
    .accept 4265 >> Accept Freed from the Hive
    .timer 19,Freed from the Hive RP

step
    #label Raschal
    .goto Feralas,72.080,63.713
    >>|cRXP_WARN_Wait out the RP|r
    .complete 4265,1

step
    #season 0
    +Grind until your Hearthstone is off cooldown
    .cooldown item,6948,<0

step
    #season 0
    .goto 1444/1,809.49,-4524.87
    .hs >>Hearth to Feathermoon Stronghold
    >>|cRXP_BUY_Buy food/water if needed|r << !Warrior !Rogue
    >>|cRXP_BUY_Buy food if needed|r << Warrior/Rogue

step
    .goto 1444/1,3312.74,-4345.38
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Pratt McGrubben|r
    .turnin 2821 >> Turn in The Mark of Quality
    .target Pratt McGrubben

step
    .goto 1444/1,3207.94,-4472.98,10,0
    .goto Feralas,31.860,45.130
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ginro Hearthkindle|r up stairs
    .turnin 4265 >> Turn in Freed from the Hive
    .accept 4266 >> Accept A Hero's Welcome
    .target Ginro Hearthkindle

step
    .goto 1444/1,3337.48,-4505.78
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Shandris Feathermoon|r
    .turnin 4266 >> Turn in A Hero's Welcome
    .accept 4267 >> Accept Rise of the Silithid
    .target Shandris Feathermoon

step
    #completewith next << !Mage !Druid
    .goto 1444/1,3621.46,-5494.63
    +Grind |cRXP_ENEMY_Nagas|r until your Hearthstone cooldown is less than 10min, |cRXP_WARN_don't head out to Teldrassil without having your hearthstone ready to go back|r
    >>Grind a little bit more if you need money for a mount (100g) << !Paladin !Warlock

step << !Mage !Druid
    .goto 1444/1,3340.06,-4370.63
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Fyldren Moonfeather|r
    .fly Teldrassil >> Fly to Teldrassil
    .target Fyldren Moonfeather

step
    .goto 1438/1,988.86,8707.47
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Erelas Ambersky|r
    .turnin 3022 >> Turn in Handle With Care
    .accept 3661 >> Accept Favored of Elune?
    .target Erelas Ambersky

step
    .goto 1438/1,1009.58,8720.20,10,0
    .goto 1438/1,993.09,8701.190
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Daryn Lightwind|r up stairs
    .turnin 2939 >> Turn in In Search of Knowledge
    .target Daryn Lightwind

step
    .goto 1438/1,1003.02,8727.53
    >>Click the |cRXP_PICK_Feralas: A History|r book on the ground
    .accept 2940 >> Accept Feralas: A History

step
    .goto 1438/1,993.09,8701.190
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Daryn Lightwind|r
    .turnin 2940 >> Turn in Feralas: A History
    .accept 2941 >> Accept The Borrower
    .target Daryn Lightwind

step
    .goto 1438/1,968.90,8795.34
    .zone Darnassus >> Take the purple portal into Darnassus

step
    .goto 1457/1,2522.86,9583.12,10,0
    .goto 1457/1,2495.63,9634.06
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gracina Spiritmight|r up stairs
    .turnin 4267 >> Turn in Rise of the Silithid
    .target Gracina Spiritmight

step
    .goto 1457/1,2524.62,9662.56
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Tyrande Whisperwind|r
    .turnin 2972 >> Turn in Doling Justice
    .target Tyrande Whisperwind

step
    #ah
    .goto 1457/1,2343.10,9856.95,-1
    .goto 1457/1,2341.74,9872.610,-1
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to a |cRXP_FRIENDLY_Darnassus Auctioneer|r
    >>Buy the following items for a faster turn ins at shortly. Skip this step if you wish to not buy any
    >>|cRXP_WARN_Remember to check your bank for|r |T134298:0|t[Gorilla Fangs] |cRXP_WARN_before you buy any as you may have found some earlier|r
    >>|T133296:0|t[Troll Tribal Necklace]
    >>|T134298:0|t[Gorilla Fang]
    >>|T134130:0|t[Red Power Crystal]
    >>|T134105:0|t[Green Power Crystal]
    >>|T134133:0|t[Blue Power Crystal]
    >>|T134136:0|t[Yellow Power Crystal]
    .collect 9259,5,2880,1
    .collect 2799,10,348,1
    .collect 11186,7,4284,1
    .collect 11185,7,4284,1
    .collect 11184,7,4284,1
    .collect 11188,7,4284,1
    .target Auctioneer Tolon
    .target Auctioneer Golothas

step << Warrior
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Arias'ta Bladesinger|r
    .goto 1457/1,2316.91,9991.88
    .trainer >> Train your class spells
    .target Arias'ta Bladesinger
    .zoneskip Darnassus,1

step << Dwarf !Paladin
    #completewith next
    .goto 1426/0,-1320.37,-5538.45
    +If you still haven't bought your mount and you have 100g, take the boat to Wetlands, fly to Ironforge, head to the Amberstill Ranch in Dun Morogh and buy a mount

step << Gnome !Warlock
    #completewith next
    .goto 1426/0,-621.02,-5453.08
    +If you still haven't bought your mount and you have 100g, take the boat to Wetlands, fly to Ironforge, head to Kharanos in Dun Morogh and buy a mount

step
    #completewith IFUldaAccept
    .dungeon Ulda
    .zone Ironforge >> Make your way to Ironforge to accept the 2 Uldaman quests there, then head to Loch Modan

step
    .dungeon Ulda
    .goto 1455/0,-1303.75,-4631.19
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Prospector Stormpike|r
    .accept 2398 >> Accept The Lost Dwarves
    .target Prospector Stormpike

step
    .dungeon Ulda
    #label IFUldaAccept
    .goto 1455/0,-1300.07,-4618.68
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Krom Stoutarm|r
    .accept 1360 >> Accept Reclaimed Treasures
    .target Krom Stoutarm

step
    .dungeon Ulda
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gryth Thurden|r
    .goto 1455/0,-1152.40,-4821.13
    .fly Loch Modan >> Fly to Loch Modan
    .target Gryth Thurden

step
    .dungeon Ulda
    .isQuestTurnedIn 2500
    .goto Loch Modan,36.50,48.35,15,0
    .goto 1432/0,-3016.18,-5395.87
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ghak Healtouch|r
    .accept 17 >> Accept Uldaman Reagent Run
    .target Ghak Healtouch

step
    .dungeon Ulda
    .isQuestTurnedIn 739
    .goto 1432/0,-3812.32,-5694.63
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Prospector Ironband|r
    .accept 704 >> Accept Agmond's Fate
    .target Prospector Ironband

step
    .dungeon Ulda
    #completewith RockEle
    .goto 1432/0,-3291.27,-5945.74,0
    .goto 1432/0,-3282.17,-5902.140,65,0
    .goto 1418/0,-3303.76,-6018.930
    .zone Badlands >> Travel to Badlands

step
    .dungeon Ulda
    .goto 1418/0,-3398.21,-6452.49
    >>Click the |cRXP_PICK_Crumpled Map|r on the ground
    .accept 720 >> Accept A Sign of Hope

step
    .dungeon Ulda
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Prospector Ryedol|r
    .turnin 720 >> Turn in A Sign of Hope
    .accept 721 >> Accept A Sign of Hope
    .goto 1418/0,-3408.01,-6609.18
    .target Prospector Ryedol

step
    .dungeon Ulda
    .goto 1418/0,-3357.39,-7164.41
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Theldurin the Lost|r
    .accept 709 >> Accept Solution to Doom
    .target Theldurin the Lost

step
    .dungeon Ulda
    .goto Badlands,4.0,80.6
    .goto 1418/0,-2462.24,-7358.87
    .goto Badlands,11.0,88.0
    .goto Badlands,44.70,12.09
    .zone 1415 >> Grind |cRXP_ENEMY_Ogres|r and |cRXP_ENEMY_Greater Rock Elementals|r while looking for a group for Uldaman

step
    .dungeon Ulda
    #completewith HammertoeGrez
    .goto 1415,54.46,57.78
    .zone 1415 >> Travel to Uldaman

step
    .dungeon Ulda
    #completewith HammertoeGrez
    >>Loot the |cRXP_LOOT_Carved Stone Urns|r on the ground
    >>|cRXP_WARN_This can be only be completed OUTSIDE of Uldaman|r
    .complete 704,1
    .isOnQuest 704

step
    .dungeon Ulda
    #completewith HammertoeGrez
    >>Loot the |cRXP_LOOT_Magenta Fungus Caps|r on the ground
    >>|cRXP_WARN_This can be completed INSIDE and OUTSIDE of Uldaman|r
    .complete 17,1
    .isOnQuest 17

step
    .dungeon Ulda
    .goto 1415,54.040,57.665
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Hammertoe Grez|r
    .turnin 721 >> Turn in A Sign of Hope
    .accept 722 >> Accept Amulet of Secrets
    .target Hammertoe Grez

step
    .dungeon Ulda
    .goto 1415,54.12,58.05,30,0
    .goto 1415,54.09,58.21
    >>Kill |cRXP_ENEMY_Magregan Deepshadow|r. Loot him for |cRXP_LOOT_Hammertoe's Amulet|r
    >>|cRXP_WARN_This is completed OUTSIDE of Uldaman|r
    .complete 722,1
    .mob Magregan Deepshadow
    .isOnQuest 722

step
    .dungeon Ulda
    .goto 1415,54.140,58.246
    >>Open the |cRXP_PICK_Ancient Chest|r. Loot it for the |cRXP_LOOT_Tablet of Ryun'eh|r
    >>|cRXP_WARN_This is completed OUTSIDE of Uldaman|r
    .complete 709,1
    .isOnQuest 709

step
    .dungeon Ulda
    .goto 1415,53.874,58.577
    >>Loot |cRXP_LOOT_Krom Stoutarm's Treasure|r on the ground
    >>|cRXP_WARN_This is completed OUTSIDE of Uldaman|r
    .complete 1360,1
    .isOnQuest 1360

step
    .dungeon Ulda
    #label HammertoeGrez
    .goto 1415,54.040,57.665
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Hammertoe Grez|r
    .turnin 722 >> Turn in Amulet of Secrets
    .accept 723 >> Accept Prospect of Faith
    .target Hammertoe Grez
    .isQuestTurnedIn 721

step
    .dungeon Ulda
    .goto 1415,53.85,57.81,55,0
    .goto 1415,53.63,58.01,55,0
    .goto 1415,54.09,58.03,55,0
    .goto 1415,53.85,57.81
    >>Loot the |cRXP_LOOT_Carved Stone Urns|r and |cRXP_LOOT_Magenta Fungus Caps|r on the ground
    >>|cRXP_WARN_Prioritize the |cRXP_LOOT_Carved Stone Urns|r. This can only be completed OUTSIDE of Uldaman. You can finish the |cRXP_LOOT_Magenta Fungus Caps|r once inside|r
    .complete 704,1
    .complete 17,1
    .disablecheckbox
    .isOnQuest 704
    .isOnQuest 17

step
    .dungeon Ulda
    .goto 1415,53.85,57.81,55,0
    .goto 1415,53.63,58.01,55,0
    .goto 1415,54.09,58.03,55,0
    .goto 1415,53.85,57.81
    >>Loot the |cRXP_LOOT_Carved Stone Urns|r on the ground
    >>|cRXP_WARN_This can be only be completed OUTSIDE of Uldaman|r
    .complete 704,1
    .isOnQuest 704

step
    .dungeon Ulda
    .goto 1415,53.850,57.641
    .subzone 1337,2 >> Zone into Uldaman

step
    .dungeon Ulda
    #completewith HiddenChamber
    >>Loot the |cRXP_LOOT_Magenta Fungus Caps|r on the ground
    .complete 17,1
    .isOnQuest 17

step
    .dungeon Ulda
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Baelog|r
    .turnin 2398 >> Turn in The Lost Dwarves
    .accept 2240 >> Accept The Hidden Chamber
    .target Baelog
    .isOnQuest 2398

step
    .dungeon Ulda
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Baelog|r
    .accept 2240 >> Accept The Hidden Chamber
    .target Baelog

step
    .dungeon Ulda
    #completewith next
    >>Open |cRXP_PICK_Baelog's Chest|r. Loot it for the |T133276:0|t[|cRXP_LOOT_Gni'kiv Medallion|r]
    >>Kill |cRXP_ENEMY_Revelosh|r. Loot him for |T135225:0|t[|cRXP_LOOT_The Shaft of Tsol|r]
    >>|cRXP_WARN_Note other party members can loot these items, and then combine them to create the|r |T135138:0|t[Staff of Prehistoria]|cRXP_WARN_. Only one person in the group needs to do this|r
    .collect 7740,1,2240,1
    .collect 7741,1,2240,1
    .use 7740
    .use 7741
    .mob Revelosh
    .isOnQuest 2240

step
    .dungeon Ulda
    #label HiddenChamber
    >>|cRXP_WARN_Use the|r |T133276:0|t[|cRXP_LOOT_Gni'kiv Medallion|r] |cRXP_WARN_and|r |T135225:0|t[|cRXP_LOOT_The Shaft of Tsol|r] |cRXP_WARN_to combine them into the|r |T135138:0|t[Staff of Prehistoria]
    >>|cRXP_WARN_Use the|r |T135138:0|t[Staff of Prehistoria] |cRXP_WARN_on the |cRXP_PICK_Keystone|r to summon|r |cRXP_ENEMY_Ironaya|r
    >>Kill |cRXP_ENEMY_Ironaya|r. |cRXP_WARN_Run into the Hidden Chamber she came from after|r
    .use 7740
    .use 7741
    .use 7733
    .complete 2240,1
    .isOnQuest 2240

step
    .dungeon Ulda
    >>Loot the |cRXP_LOOT_Magenta Fungus Caps|r on the ground
    .complete 17,1
    .isOnQuest 17

step
    .dungeon Ulda
    >>Kill |cRXP_ENEMY_Archaedas|r
    >>Click |cRXP_PICK_The Discs of Norgannon|r
    .accept 2278 >> Accept The Platinum Discs

step
    .dungeon Ulda
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Lore Keeper of Norgannon|r
    .complete 2278,1
    .skipgossip
    .target Lore Keeper of Norgannon

step
    .dungeon Ulda
    >>Click |cRXP_PICK_The Discs of Norgannon|r
    .turnin 2278 >> Turn in The Platinum Discs
    .accept 2279 >> Accept The Platinum Discs

step
    .dungeon Ulda
    +Zone out of Uldaman together as a group to turn in quests in Badlands. The closest exit is the Uldaman backdoor
    .zoneskip Badlands

step
    .dungeon Ulda
    .goto 1418/0,-3357.39,-7164.41
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Theldurin the Lost|r
    .turnin 709 >> Turn in Solution to Doom
    .target Theldurin the Lost
    .isQuestComplete 709

step
    .dungeon Ulda
    #label HammertoeGrez
    .goto 1418/0,-3408.01,-6609.18
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Prospector Ryedol|r
    .turnin 723 >> Turn in Prospect of Faith
    .accept 724 >> Accept Prospect of Faith
    .target Prospector Ryedol
    .isQuestTurnedIn 721

step
    .dungeon Ulda
    #completewith UldaLoch
    .goto 1418/0,-3310.98,-6052.60,0
    .goto 1432/0,-3284.10,-5924.03
    .zone Loch Modan >> Travel to Loch Modan

step
    .dungeon Ulda
    .goto 1432/0,-3812.32,-5694.63
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Prospector Ironband|r
    .turnin 704 >> Turn in Agmond's Fate
    .target Prospector Ironband
    .isQuestComplete 704

step
    .dungeon Ulda
    .goto Loch Modan,36.50,48.35,15,0
    .goto 1432/0,-3016.18,-5395.87
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ghak Healtouch|r
    .turnin 17 >> Turn in Uldaman Reagent Run
    .target Ghak Healtouch
    .isQuestComplete 17

step
    .dungeon Ulda
    #label UldaLoch
    .goto 1432/0,-2929.87,-5424.84
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Thorgrum Borrelson|r
    .fly Ironforge >> Fly to Ironforge
    .target Thorgrum Borrelson

step
    .dungeon Ulda
    .goto Ironforge,69.930,18.548
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_High Explorer Magellas|r
    .turnin 2279 >> Turn in The Platinum Discs
    .accept 2439 >> Accept The Platinum Discs
    .target High Explorer Magellas
    .isQuestTurnedIn 2278

step
    .dungeon Ulda
    .goto 1455/0,-1303.75,-4631.19
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Prospector Stormpike|r
    .turnin 2240 >> Turn in The Hidden Chamber
    .target Prospector Stormpike
    .isQuestComplete 2240

step
    .dungeon Ulda
    .goto 1455/0,-1300.07,-4618.68
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Krom Stoutarm|r
    .turnin 1360 >> Turn in Reclaimed Treasures
    .target Krom Stoutarm
    .isQuestComplete 1360

step
    .dungeon Ulda
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Historian Karnik|r and |cRXP_FRIENDLY_Advisor Belgrum|r
    .turnin 724 >> Turn in Prospect of Faith
    .accept 725 >> Accept Passing Word of a Threat
    .target +Historian Karnik
    .goto 1455/0,-1326.63,-4631.68
    .turnin 725 >> Turn in Passing Word of a Threat
    .accept 726 >> Accept Passing Word of a Threat
    .target +Advisor Belgrum
    .goto 1455/0,-1325.08,-4620.49
    .turnin 726 >> Turn in Passing Word of a Threat

    .target +Historian Karnik
    .goto 1455/0,-1326.63,-4631.68
    .isQuestTurnedIn 721

step
    .dungeon Ulda
    .goto 1455/0,-981.41,-4881.25
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Dinita Stonemantle|r
    .turnin 2439 >> Turn in The Platinum Discs
    .target Dinita Stonemantle
    .isQuestTurnedIn 2278

step
    .dungeon Ulda
    >>|cRXP_WARN_Use the |T133289:0|t[|cRXP_LOOT_Shattered Necklace|r] to start the quest|r
    .accept 2198 >> Accept The Shattered Necklace
    .use 7666
    .itemcount 7666,1

step
    .dungeon Ulda
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Talvash del Kissel|r
    .goto 1455/0,-1001.20,-4588.31
    .turnin 2198 >> Turn in The Shattered Necklace
    .target Talvash del Kissel
    .isOnQuest 2198

step
    .dungeon Ulda
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Talvash del Kissel|r
    .goto 1455/0,-1001.20,-4588.31
    .accept 2199 >> Accept Lore for a Price
    .target Talvash del Kissel
    .isQuestTurnedIn 2198

step
    .dungeon Ulda
    .goto 1455/0,-1001.20,-4588.31
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Talvash del Kissel|r
    >>Bring 5 |T133215:0|t[Silver Bars] to |cRXP_FRIENDLY_Talvash del Kissel|r
    >>|cRXP_WARN_If you are unable to acquire them, abandon this quest|r
    .complete 2199,1
    .turnin 2199 >> Turn in Lore for a Price
    .target Talvash del Kissel
    .isOnQuest 2199

step
    .hs >> Hearth to Feralas
    >>|cRXP_BUY_Buy food/water if needed|r << !Warrior !Rogue
    >>|cRXP_BUY_Buy food if needed|r << Warrior/Rogue

step
    .goto 1444/1,3621.46,-5494.63
    .xp 47 >> Head back to the |cRXP_ENEMY_Naga|r cave and grind to level 47

step
    .goto 1444/1,3621.46,-5494.63
    .xp 48 >> Head back to the |cRXP_ENEMY_Naga|r cave and grind to level 48

step
    .goto 1444/1,3621.46,-5494.63
    .xp 48.5 >> Head back to the |cRXP_ENEMY_Naga|r cave and grind to level 48 + 50%

step
    #completewith FlyTan
    .hs >> Hearth to Feathermoon Stronghold
    >>|cRXP_BUY_Buy food/water if needed|r << !Warrior !Rogue
    >>|cRXP_BUY_Buy food if needed|r << Warrior/Rogue
    .cooldown item,6948,>0,1

step
    .goto 1444/1,3229.62,-4479.98
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Angelas Moonbreeze|r
    .turnin 2982 >> Turn in The High Wilderness
    .accept 3445 >> Accept The Sunken Temple
    .target Angelas Moonbreeze

step
    #completewith next
    .goto 1444/1,3340.06,-4370.63
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Fyldren Moonfeather|r
    .fly Thalanaar>> Fly to Thalanaar
    .target Fyldren Moonfeather

step
    .goto 1444/1,-787.90,-4524.09
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Falfindel Waywarder|r
    .turnin 4281 >> Turn in Thalanaar Delivery
    .use 11463
    .target Falfindel Waywarder

step
    #label FlyTan
    .goto 1444/1,-778.37,-4491.19
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Thyssiana|r
    .fly Tanaris>> Fly to Tanaris
    .target Thyssiana
]])
