-- Generated by Scripts/split_guide_vault.py; rerun the script to update.
if not RXPGuides or type(RXPGuides.RegisterGuide) ~= "function" then return end
local _, rxpGuideVaultAddon = ...
local rxpGuideVaultGame = rxpGuideVaultAddon and rxpGuideVaultAddon.game
if not rxpGuideVaultGame then
    local rxpGuideVaultVersion = select(4, GetBuildInfo())
    if rxpGuideVaultVersion > 60000 then
        rxpGuideVaultGame = "RETAIL"
    elseif rxpGuideVaultVersion > 50000 then
        rxpGuideVaultGame = "MOP"
    elseif rxpGuideVaultVersion > 40000 then
        rxpGuideVaultGame = "CATA"
    elseif rxpGuideVaultVersion > 30000 then
        rxpGuideVaultGame = "WOTLK"
    elseif rxpGuideVaultVersion > 20000 then
        rxpGuideVaultGame = "TBC"
    elseif rxpGuideVaultVersion >= 16000 and rxpGuideVaultVersion < 20000 then
        rxpGuideVaultGame = "FOREVER"
    else
        rxpGuideVaultGame = "CLASSIC"
    end
end
if rxpGuideVaultGame ~= "FOREVER" then return end

RXPGuides.RegisterGuide([[#forever
#version 23
#group RestedXP Forever Guide (A)
#subgroup Speedrun Guide 30-40

<< Alliance
#name 34-35 Stranglethorn Vale I
#next 35-37 Desolace;36-38 Stranglethorn Vale II << !Hunter

step
    .goto 1434/0,539.69,-14298.28
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Wharfmaster Lozgil|r
    .turnin 1180 >>Turn in Goblin Sponsorship
    .accept 1181 >>Accept Goblin Sponsorship
    .target Wharfmaster Lozgil

step
    #season 0,1
    #optional
    .goto Stranglethorn Vale,27.600,77.481
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Scooty|r
    .turnin 2904 >> Turn in A Fine Mess
    .isQuestComplete 2904
    .target Scooty

step
    .isQuestTurnedIn 1038
    .goto 1434/0,474.41,-14320.19
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Caravaneer Ruzzgot|r
    .turnin 1040 >>Turn in Passage to Booty Bay
    .accept 1041 >>Accept The Caravan Road
    .target Caravaneer Ruzzgot

step
    .goto Stranglethorn Vale,27.120,77.208
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Crank Fizzlebub|r
    .accept 605 >>Accept Singing Blue Shards
    .target Crank Fizzlebub

step
    .goto 1434/0,495.34,-14457.65
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Innkeeper Skindle|r
    .home >>Set your Hearthstone to Booty Bay
    .target Innkeeper Skindle

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kebok|r and |cRXP_FRIENDLY_Krazek|r up stairs on the top floor
    .accept 213 >> Accept Hostile Takeover
    .target Kebok
    .goto Stranglethorn Vale,27.000,77.124
    .accept 198 >>Accept Supplies to Private Thorsen
    .accept 201 >>Accept Investigate the Camp
    .accept 616 >>Accept The Haunted Isle
    .goto 1434/0,501.53,-14453.26
    .target Krazek

step
    .goto 1434/0,483.86,-14438.93
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Baron Revilgaz|r
    .turnin 616 >>Turn in The Haunted Isle
    .accept 578 >>Accept The Stone of the Tides
    .turnin 1181 >>Turn in Goblin Sponsorship
    .accept 1182 >>Accept Goblin Sponsorship
    .target Baron Revilgaz

step
    .goto 1434/0,415.32,-14469.64
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Drizzlik|r
    .accept 575 >>Accept Supply and Demand
    .target Drizzlik

step
    .goto 1434/0,425.15,-14491.68
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|t|cRXP_BUY_Talk to|r |cRXP_FRIENDLY_Glyx|r
    .vendor >> |cRXP_BUY_Buy|r |T134832:0|t[Greater Healing Potions] |cRXP_BUY_from him if they're up|r
    .target Glyx Brewright

step
    .destroy 3898 >>Throw away the |T134939:0|t[Library Scrip]

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gyll|r
    .goto Stranglethorn Vale,27.530,77.787
    .fly Westfall >> Fly to Westfall
    .target Gyll

step
    #completewith ThorsenR
    .goto 1431/0,354.89,-10239.93
    .zone Duskwood >> Travel to Duskwood

step
    .isOnQuest 231
    >>Click |cRXP_PICK_A Weathered Grave|r
    .goto 1431/0,354.89,-10239.93
    .turnin 231 >> Turn in A Daughter's Love

step
    .destroy 2154 >> Delete the |T133741:0|t[The Story of Morgan Ladimore]

step
    #completewith ThorsenR
    .goto 1431/0,-370.81,-11292.84,50 >> Travel to northern Stranglethorn Vale

step
    #completewith Fern
    .goto 1434/0,-353.30,-11527.55,0
    >>|cRXP_WARN_Keep an eye out for the special |cRXP_FRIENDLY_Private Thorsen|r event. He will patrol down the road from the Rebel camp every 30 minutes|r
    >>|cRXP_FRIENDLY_Private Thorsen|r |cRXP_WARN_will be attacked by 2 of |cRXP_ENEMY_Kurzen's Agents|r. If you don't see this event, ignore this step|r
    >>Kill both of |cRXP_ENEMY_Kurzen's Agents|r and then accept |cRXP_FRIENDLY_Private Thorsen's|r quest which becomes available after saving him
    .accept 215 >> Accept Jungle Secrets
    .unitscan Private Thorsen
    .mob Kurzen's Agent

step
    #label ThorsenR
    .goto Stranglethorn Vale,37.980,3.410
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Private Thorsen|r at the Rebel Camp
    >>|cRXP_WARN_If |cRXP_FRIENDLY_Private Thorsen|r isn't at the Rebel Camp he may be in progress for his special event. Skip this step. Look for him down the path if you haven't accepted his quest yet|r
    .turnin 198 >>Turn in Supplies to Private Thorsen
    .target Private Thorsen

step
    .goto 1434/0,-205.13,-11310.410
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sergeant Yohwa|r
    .accept 203 >>Accept The Second Rebellion
    .accept 204 >>Accept Bad Medicine
    .target Sergeant Yohwa

step
    .goto Stranglethorn Vale,38.0,3.0
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Lieutenant Doren|r
    .accept 200 >> Accept Bookie Herod
    .isQuestTurnedIn 215
    .target Lieutenant Doren

step
    #completewith Fern
    >>Kill |cRXP_ENEMY_Stone Maw Basilisks|r and |cRXP_ENEMY_Crystal Spine Basilisks|r. Loot them for their |cRXP_LOOT_Shards|r
    >>|cRXP_ENEMY_Stone Maw Basilisks|r |cRXP_WARN_and|r |cRXP_ENEMY_Crystal Spine Basilisks|r |cRXP_WARN_will cast|r |T132154:0|t[Crystal Gaze] |cRXP_WARN_which is a 6 second long stun. Simply move out of their melee range when they begin to cast to avoid it|r
    .goto 1434/0,663.81,-11900.47,0
    .goto 1434/0,-872.80,-11545.24,0
    .complete 605,1
    .mob Stone Maw Basilisk
    .mob Crystal Spine Basilisk
    .isOnQuest 605

step
    #completewith Fern
    .goto 1434/0,140.55,-11543.12,0
    .goto 1434/0,-127.47,-11619.69,0
    .goto 1434/0,-382.72,-11755.82,0
    >>Kill |cRXP_ENEMY_River Crocolisks|r. Loot them for their |cRXP_LOOT_Skin|r
    .complete 575,1
    .mob River Crocolisk

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Barnil Stonepot|r and |cRXP_FRIENDLY_Hemet Nesingwary|r
    .accept 583 >> Accept Welcome to the Jungle
    .target +Barnil Stonepot
    .goto 1434/0,-54.85,-11616.67
    .turnin 583 >> Turn in Welcome to the Jungle
    .target +Hemet Nesingwary
    .goto 1434/0,-54.59,-11628.54

step
    .goto 1434/0,-54.59,-11628.54
    .target Hemet Nesingwary
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Hemet Nesingwary|r
    .turnin 5762 >> Turn in Hemet Nesingwary

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ajeck Rouack|r and |cRXP_FRIENDLY_Sir S. J. Erlgadin|r
    .accept 185 >> Accept Tiger Mastery
    .target +Ajeck Rouack
    .goto 1434/0,-51.91,-11620.50
    .accept 190 >> Accept Panther Mastery
    .target +Sir S. J. Erlgadin
    .goto 1434/0,-48.08,-11617.39

step
    .goto Stranglethorn Vale,35.40,12.50,50,0
    .goto Stranglethorn Vale,33.30,11.90,50,0
    .goto 1434/0,194.15,-11551.620,50,0
    .goto Stranglethorn Vale,35.40,12.50
    >>Kill |cRXP_ENEMY_Young Stranglethorn Tigers|r
    .complete 185,1
    .mob Young Stranglethorn Tiger

step
    .goto 1434/0,-51.53,-11620.12
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ajeck Rouack|r
    .turnin 185 >>Turn in Tiger Mastery
    .accept 186 >>Accept Tiger Mastery
    .target Ajeck Rouack

step
    #completewith next
    .goto 1434/0,-646.26,-11604.80,0
    >>Kill |cRXP_ENEMY_Kurzen Jungle Fighters|r and |cRXP_ENEMY_Kurzen Medicine Men|r. Loot the |cRXP_ENEMY_Kurzen Medicine Men|r for their |cRXP_LOOT_Jungle Remedies|r
    >>|cRXP_ENEMY_Kurzen Medicine Men|r |cRXP_WARN_also drop|r |T134413:0|t[Liferoot]|cRXP_WARN_. Save these for your|r |T132403:0|t[|cFF0070FFWhirlwind Axe|r] |cRXP_WARN_quest later|r << Warrior
    >>|cRXP_WARN_Hold onto any|r |T134332:0|t[Green Hills of Stranglethorn - Pages] |cRXP_WARN_you find. Trade or sell duplicates|r
    .complete 203,1
    .mob +Kurzen Jungle Fighter
    .complete 204,1
    .mob +Kurzen Medicine Man

step
    #label Fern
    .goto 1434/0,-592.40,-11574.51
    >>Open the |cRXP_PICK_Kurzen Supplies|r. Loot it for the |cRXP_LOOT_Venom Fern Extract|r
    .complete 204,2

step
    .isOnQuest 200
    .isQuestTurnedIn 215
    #completewith next
    .goto 1434/0,-646.26,-11604.80,0
    >>Kill |cRXP_ENEMY_Kurzen Jungle Fighters|r and |cRXP_ENEMY_Kurzen Medicine Men|r. Loot the |cRXP_ENEMY_Kurzen Medicine Men|r for their |cRXP_LOOT_Jungle Remedies|r
    >>|cRXP_ENEMY_Kurzen Medicine Men|r |cRXP_WARN_also drop|r |T134413:0|t[Liferoot]|cRXP_WARN_. Save these for your|r |T132403:0|t[|cFF0070FFWhirlwind Axe|r] |cRXP_WARN_quest later|r << Warrior
    >>|cRXP_WARN_Hold onto any|r |T134332:0|t[Green Hills of Stranglethorn - Pages] |cRXP_WARN_you find. Trade or sell duplicates|r
    .complete 203,1
    .mob +Kurzen Jungle Fighter
    .complete 204,1
    .mob +Kurzen Medicine Man

step
    .isOnQuest 200
    .isQuestTurnedIn 215
    .goto 1434/0,-565.79,-11567.45
    >>Click on |cRXP_PICK_Bookie Herod's Records|r upstairs in the house
    .turnin 200 >> Turn in Bookie Herod
    .accept 328 >> Accept The Hidden Key

step
    .goto 1434/0,-646.26,-11604.80
    >>Kill |cRXP_ENEMY_Kurzen Jungle Fighters|r and |cRXP_ENEMY_Kurzen Medicine Men|r. Loot the |cRXP_ENEMY_Kurzen Medicine Men|r for their |cRXP_LOOT_Jungle Remedies|r
    >>|cRXP_ENEMY_Kurzen Medicine Men|r |cRXP_WARN_also drop|r |T134413:0|t[Liferoot]|cRXP_WARN_. Save these for your|r |T132403:0|t[|cFF0070FFWhirlwind Axe|r] |cRXP_WARN_quest later|r << Warrior
    >>|cRXP_WARN_Hold onto any|r |T134332:0|t[Green Hills of Stranglethorn - Pages] |cRXP_WARN_you find. Trade or sell duplicates|r
    .complete 203,1
    .mob +Kurzen Jungle Fighter
    .complete 204,1
    .mob +Kurzen Medicine Man

step
    .goto 1434/0,-762.40,-11841.33
    >>Kill |cRXP_ENEMY_Stranglethorn Tigers|r
    .complete 186,1
    .mob Stranglethorn Tiger

step
    #completewith Prints
    >>Kill |cRXP_ENEMY_Venture Co. Geologists|r. Loot them for their |cRXP_LOOT_Crystals|r
    .complete 213,1
    .mob Venture Co. Geologist

step
    .goto 1434/0,-500.51,-11949.52
    >>Kill |cRXP_ENEMY_Foreman Cozzle|r atop the Oil Rig. Loot him for his |cRXP_LOOT_Key|r
    .collect 5851,1,1182,1
    .mob Foreman Cozzle

step
    #label Prints
    .goto 1434/0,-544.29,-12033.58
    >>Open |cRXP_PICK_Cozzle's Footlocker|r. Loot it for the |cRXP_LOOT_Fuel Regulator Blueprints|r
    .complete 1182,1

step
    .goto 1434/0,-662.22,-12132.32,75,0
    .goto 1434/0,-685.83,-11967.68,75,0
    .goto 1434/0,-549.91,-11891.960,75,0
    .goto 1434/0,-662.22,-12132.32,75,0
    .goto 1434/0,-685.83,-11967.68
    >>Kill |cRXP_ENEMY_Venture Co. Geologists|r. Loot them for their |cRXP_LOOT_Crystals|r
    .complete 213,1
    .mob Venture Co. Geologist

step
    .goto Stranglethorn Vale,41.50,12.00,50,0
    .goto 1434/0,-506.51,-11696.270,50,0
    .goto 1434/0,-422.92,-11584.38,50,0
    .goto 1434/0,-374.42,-11664.36,50,0
    .goto Stranglethorn Vale,41.50,12.00
    >>Kill |cRXP_ENEMY_Young Panthers|r
    .complete 190,1
    .mob Young Panther

step
    .goto 1434/0,-205.13,-11310.410
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sergeant Yohwa|r
    .turnin 203 >> Turn in The Second Rebellion
    .turnin 204 >> Turn in Bad Medicine
    .target Sergeant Yohwa

step
    .goto Stranglethorn Vale,37.740,3.300
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Corporal Kaleb|r
    .accept 210 >> Accept Krazek's Cookery
    .target Corporal Kaleb

step
    .goto 1434/0,-206.72,-11296.89
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Lieutenant Doren|r
    >>|cRXP_WARN_Don't accept the follow up yet|r
    .turnin 215 >> Turn in Jungle Secrets
    .isOnQuest 215
    .target Lieutenant Doren

step
    .goto 1434/0,-204.68,-11314.24
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Private Thorsen|r
    .turnin 198 >>Turn in Supplies to Private Thorsen
    .target Private Thorsen

step
    #completewith next
    .goto 1434/0,140.55,-11543.12,0
    .goto 1434/0,-127.47,-11619.69,0
    .goto 1434/0,-382.72,-11755.82,0
    >>Kill |cRXP_ENEMY_River Crocolisks|r. Loot them for their |cRXP_LOOT_Skin|r
    .complete 575,1
    .mob River Crocolisk

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Hemet Nesingwary|r, |cRXP_FRIENDLY_Ajeck Rouack|r and |cRXP_FRIENDLY_Sir S. J. Erlgadin|r
    .accept 194 >> Accept Raptor Mastery
    .target +Hemet Nesingwary
    .goto 1434/0,-54.59,-11628.54
    .turnin 186 >> Turn in Tiger Mastery
    .accept 187 >> Accept Tiger Mastery
    .target +Ajeck Rouack
    .goto 1434/0,-51.91,-11620.50
    .turnin 190 >>Turn in Panther Mastery
    .accept 191 >> Accept Panther Mastery
    .target +Sir S. J. Erlgadin
    .goto 1434/0,-48.08,-11617.39

step
    .goto 1434/0,140.55,-11543.12,60,0
    .goto 1434/0,-127.47,-11619.69,60,0
    .goto 1434/0,-382.72,-11755.82,60,0
    .goto 1434/0,140.55,-11543.12,60,0
    .goto 1434/0,-127.47,-11619.69,60,0
    .goto 1434/0,-382.72,-11755.82,60,0
    .goto 1434/0,-127.47,-11619.69
    >>Kill |cRXP_ENEMY_River Crocolisks|r. Loot them for their |cRXP_LOOT_Skin|r
    .complete 575,1
    .mob River Crocolisk

step
    #completewith next
    >>Kill |cRXP_ENEMY_Panthers|r
    .complete 191,1
    .mob Panther

step
    .goto 1434/0,209.46,-11875.37,60,0
    .goto 1434/0,184.58,-12016.61,60,0
    .goto 1434/0,28.24,-11959.17,60,0
    .goto 1434/0,209.46,-11875.37,60,0
    .goto 1434/0,184.58,-12016.61
    >>Kill |cRXP_ENEMY_Elder Stranglethorn Tigers|r
    .complete 187,1
    .mob Elder Stranglethorn Tiger

step
    .goto 1434/0,280.93,-11696.27,60,0
    .goto 1434/0,344.75,-11543.12,60,0
    .goto 1434/0,421.32,-11679.25,60,0
    .goto 1434/0,421.32,-11866.43,60,0
    .goto 1434/0,319.22,-11645.22
    >>Kill |cRXP_ENEMY_Panthers|r
    .complete 191,1
    .mob Panther

step
    #completewith next
    .goto 1434/0,475.56,-11956.62,0
    .goto 1434/0,591.70,-11923.01,0
    .goto 1434/0,737.19,-11900.89,0
    >>Kill |cRXP_ENEMY_Crystal Spine Basilisks|r. Loot them for their |cRXP_LOOT_Shards|r
    >>|cRXP_ENEMY_Crystal Spine Basilisks|r |cRXP_WARN_will cast|r |T132154:0|t[Crystal Gaze] |cRXP_WARN_which is a 6 second long stun. Simply move out of their melee range when they begin to cast to avoid it|r
    .complete 605,1
    .mob Crystal Spine Basilisk
    .isOnQuest 605

step
    .goto 1434/0,458.97,-11823.47,60,0
    .goto 1434/0,567.45,-11863.46,60,0
    .goto 1434/0,674.02,-11842.61,60,0
    .goto 1434/0,487.69,-11851.97
    >>Kill |cRXP_ENEMY_Stranglethorn Raptors|r
    .complete 194,1
    .mob Stranglethorn Raptor

step
    .goto 1434/0,475.56,-11956.62,50,0
    .goto 1434/0,591.70,-11923.01,50,0
    .goto 1434/0,737.19,-11900.89,50,0
    .goto 1434/0,591.70,-11923.01
    >>Kill |cRXP_ENEMY_Crystal Spine Basilisks|r. Loot them for their |cRXP_LOOT_Shards|r
    >>|cRXP_ENEMY_Crystal Spine Basilisks|r |cRXP_WARN_will cast|r |T132154:0|t[Crystal Gaze] |cRXP_WARN_which is a 6 second long stun. Simply move out of their melee range when they begin to cast to avoid it|r
    .complete 605,1
    .mob Crystal Spine Basilisk
    .isOnQuest 605

step
    .goto Stranglethorn Vale,21.580,21.842
    .goto Stranglethorn Vale,21.580,21.842 >> Travel to the Haunted Island
    .complete 578,1

step
    #completewith next
    .deathskip >> Die and respawn at the Spirit Healer
    .target Spirit Healer

step
    #completewith next
    .goto 1434/0,-54.59,-11628.54,80 >> Travel to Nesingwary's Expedition

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Hemet Nesingwary|r, |cRXP_FRIENDLY_Ajeck Rouack|r and |cRXP_FRIENDLY_Sir S. J. Erlgadin|r
    .turnin 194 >> Turn in Raptor Mastery
    .accept 195 >>Accept Raptor Mastery
    .target +Hemet Nesingwary
    .goto 1434/0,-54.59,-11628.54
    .turnin 187 >> Turn in Tiger Mastery
    .accept 188 >> Accept Tiger Mastery
    .target +Ajeck Rouack
    .goto 1434/0,-51.91,-11620.50
    .turnin 191 >> Turn in Panther Mastery
    .accept 192 >> Accept Panther Mastery
    .target +Sir S. J. Erlgadin
    .goto 1434/0,-48.08,-11617.39

step
    #completewith next
    .hs >> Hearth to Booty Bay
    >>|cRXP_BUY_Buy food/water if needed|r << !Warrior !Rogue
    >>|cRXP_BUY_Buy food if needed|r << Warrior/Rogue

step
    .goto Stranglethorn Vale,27.120,77.208
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Crank Fizzlebub|r
    .turnin 605 >> Turn in Singing Blue Shards
    .target Crank Fizzlebub

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kebok|r and |cRXP_FRIENDLY_Krazek|r up stairs on the top floor
    .turnin 213 >>Turn in Hostile Takeover
    .target +Kebok
    .goto Stranglethorn Vale,27.000,77.124
    .turnin 201 >> Turn in Investigate the Camp
    .turnin 210 >> Turn in Krazek's Cookery
    .target +Krazek
    .goto 1434/0,501.53,-14453.26

step
    #optional
    .goto 1434/0,501.53,-14453.26
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Krazek|r
    .accept 627 >> Accept Favor for Krazek
    .turnin 627 >> Turn in Favor for Krazek
    .accept 622 >> Accept Return to Corporal Kaleb
    .itemcount 4278,4
    .target Krazek

step
    #optional
    .isQuestTurnedIn 627
    .goto 1434/0,501.53,-14453.26
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Krazek|r
    .accept 622 >> Accept Return to Corporal Kaleb
    .target Krazek

step
    .goto 1434/0,483.41,-14438.930
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Baron Revilgaz|r
    .turnin 1182 >>Turn in Goblin Sponsorship
    .accept 1183 >>Accept Goblin Sponsorship
    .turnin 578 >> Turn in The Stone of the Tides
    .accept 601 >> Accept Water Elementals
    .target Baron Revilgaz

step
    .goto 1434/0,415.32,-14469.64
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Drizzlik|r
    .turnin 575 >> Turn in Supply and Demand
    .accept 577 >> Accept Some Assembly Required
    .target Drizzlik

step
    .goto 1434/0,425.15,-14491.68
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|t|cRXP_BUY_Talk to|r |cRXP_FRIENDLY_Glyx|r
    .vendor >> |cRXP_BUY_Buy|r |T134832:0|t[Greater Healing Potions] |cRXP_BUY_from him if they're up|r
    .target Glyx Brewright

step
    #completewith next
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gyll|r
    .goto Stranglethorn Vale,27.530,77.787
    .fly Duskwood >> Fly to Duskwood
    .target Gyll

step
    .isQuestTurnedIn 1040
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Clerk Daltry|r in the town hall building
    .goto 1431/0,-1126.87,-10559.07
    .turnin 1041 >> Turn in The Caravan Road
    .accept 1042 >> Accept The Carevin Family
    .target Clerk Daltry

step
    .isQuestTurnedIn 1040
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Jonathan Carevin|r
    .goto 1431/0,-1197.07,-10595.07
    .turnin 1042 >> Turn in The Carevin Family
    .accept 1043 >> Accept The Scythe of Elune
    .target Jonathan Carevin

step
    #completewith next
    .goto Duskwood,73.20,76.19,30 >> Travel to Roland's Doom
    .isQuestTurnedIn 1040

step
    .isQuestTurnedIn 1040
    >>Click the |cRXP_PICK_Mound of Dirt|r at the back of the Cave
    .goto 1431/0,-1151.90,-11141.24
    .complete 1043,1

step << !Hunter
    #completewith next
    .deathskip >> Die and respawn at the Spirit Healer
    .target Spirit Healer

step
    #completewith next
    .goto 1431/0,-1197.07,-10595.07,150 >> Travel to Darkshire
    .isQuestTurnedIn 1040

step
    .isQuestTurnedIn 1040
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Jonathan Carevin|r
    .goto 1431/0,-1197.07,-10595.07
    .turnin 1043 >> Turn in The Scythe of Elune

    .target Jonathan Carevin

step << !Mage
    .goto Stranglethorn Vale,27.530,77.787
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gyll|r
    .fly Stormwind>> Fly to Stormwind
    .target Gyll
    .zoneskip Stranglethorn Vale,1

step << !Mage
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Felicia Maline|r
    .goto 1431/0,-1258.79,-10513.83
    .fly Stormwind>> Fly to Stormwind
    .target Felicia Maline
    .zoneskip Duskwood,1

step
    .goto 1453/0,613.93,-8933.64
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Newton Burnside|r
    .bankwithdraw 3721,3521,4521 >> Withdraw the following items from your bank: << Warlock
    .bankwithdraw 3721,3521,4521,5996 >> Withdraw the following items from your bank: << !Warlock
    >>|T133461:0|t[Farren's Report]
    >>|T134939:0|t[Cleverly Encrypted Letter] (If you found it earlier)
    >>|T135234:0|t[Alterac Granite]
    >>|T134797:0|t[Elixir of Water Breathing] (If you have one) << !Warlock
    .target Newton Burnside

step
    .goto 1453/0,613.93,-8933.64
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Newton Burnside|r
    .bankdeposit 2725,2728,2730,2732,2734,2735,2738,2740,2742,2744,2745,2748,2749,2750,2751 >> Deposit the following items into your bank:
    >>Deposit any |T134332:0|t[Green Hills of Stranglethorn - Pages] you found
    .target Newton Burnside

step << !Warlock
    #ah
    .goto 1453/0,613.93,-8933.64
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Newton Burnside|r
    >>|cRXP_BUY_Buy a|r |T134797:0|t[Elixir of Water Breathing] |cRXP_BUY_from the Auction House|r
    .collect 5996,1
    .target Newton Burnside

step << Priest/Paladin
    #completewith next
    .goto StormwindClassic,42.51,33.51,20 >> Travel to the Stormwind Cathedral

step << Paladin
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Arthur the Faithful|r
    .goto StormwindClassic,38.82,31.27,10,0
    .goto StormwindClassic,38.67,32.82
    .trainer >> Train your class spells
    .target Arthur the Faithful

step
    #completewith next
    .goto 1453/0,417.40,-8508.320,40 >> Travel to the Stormwind Keep

step
    .goto Stormwind City,77.30,17.18,25,0
    .goto 1453/0,405.42,-8421.26
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Major Samuelson|r
    .turnin 563 >> Turn in Reassignment
    .target Major Samuelson
    .isOnQuest 563

step
    .goto 1453/0,383.76,-8345.76
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Milton Sheaf|r
    >>|cRXP_WARN_If you found |T133741:0|t[|cRXP_LOOT_An Old History Book|r] you may turn it in|r
    .accept 337 >> Accept An Old History Book
    .turnin 337 >> Turn in An Old History Book
    .accept 538 >> Accept Southshore
    .use 2794
    .itemcount 2794,1
    .target Milton Sheaf

step << Warrior
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Wu|r or |cRXP_FRIENDLY_Ilsa|r
    .goto StormwindClassic,76.08,50.14,15,0
    .goto StormwindClassic,80.22,45.37,15,0
    .goto StormwindClassic,78.68,45.79
    .trainer >> Train your class spells
    .target Wu Shen
    .target Ilsa Corbin

step
    .dungeon Gnomer
    #season 0,1
    .goto StormwindClassic,55.511,12.502
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Shoni the Shilent|r
    .turnin 2928 >> Turn in Gyrodrillmatic Excavationators
    .target Shoni the Shilent
    .isQuestComplete 2928

step << !Mage
    #completewith ReclaimersDesolace
    .goto StormwindClassic,61.149,11.568,25,0
    .goto StormwindClassic,64.0,8.10
    .zone Ironforge >> Enter the Deeprun Tram. Take the Tram to Ironforge
    >>|cRXP_WARN_Level your|r |T135966:0|t[First Aid] |cRXP_WARN_if needed while waiting for the Tram|r

step
    #label ReclaimersDesolace
    .goto 1455/0,-1250.50,-4661.570,25,0
    .goto 1455/0,-1266.48,-4681.36
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Roetten Stonehammer|r
    >>|cRXP_FRIENDLY_Roetten Stonehammer|r |cRXP_WARN_patrols the Hall of Explorers|r
    .accept 1453 >> Accept Reclaimers' Business in Desolace
    .target Roetten Stonehammer

step << Warlock
    .goto 1455/0,-1300.07,-4618.68
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Krom Stoutarm|r
    .turnin 1758 >> Turn in Tome of the Cabal
    .target Krom Stoutarm

step << Warlock
    .goto 1455/0,-1134.20,-4610.39,15,0
    .goto 1455/0,-1130.26,-4601.270
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Jubahl Corpseseeker|r
    .vendor >> |cRXP_BUY_Buy|r |T133738:0|t[Grimoires] |cRXP_BUY_for your|r |T136220:0|t[Succubus] |cRXP_BUY_or|r |T136221:0|t[Voidwalker]
    .target Jubahl Corpseseeker

step << Warlock
    .goto 1455/0,-1117.60,-4615.14,15,0
    .goto 1455/0,-1111.62,-4599.09
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Briarthorn|r
    .trainer >> Train your class spells
    .target Briarthorn

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Prospector Stormpike|r
    .goto 1455/0,-1303.75,-4631.19
    .turnin 514 >>Turn in Letter to Stormpike
    .target Prospector Stormpike

step
    .isQuestComplete 689
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Grand Mason Marblesten|r
    .goto 1455/0,-1022.17,-5033.80
    .turnin 689 >>Turn in A King's Tribute
    .timer 60,Marblesten RP
    .accept 700 >>Accept A King's Tribute
    .target Grand Mason Marblesten

step
    .abandon 689 >> Abandon the quest "A King's Tribute" if you haven't collected the granite chunks in Alterac previously

step
    .isQuestTurnedIn 689
    >>|cRXP_WARN_Wait out the RP|r
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Grand Mason Marblesten|r
    .goto 1455/0,-1022.17,-5033.80
    .accept 700 >>Accept A King's Tribute
    .target Grand Mason Marblesten

step
    .isQuestTurnedIn 689
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_King Magni Bronzebeard|r
    .goto 1455/0,-1022.65,-4865.70
    .turnin 700 >>Turn in A King's Tribute
    .target King Magni Bronzebeard
]])
