-- Generated by Scripts/split_guide_vault.py; rerun the script to update.
if not RXPGuides or type(RXPGuides.RegisterGuide) ~= "function" then return end
local _, rxpGuideVaultAddon = ...
local rxpGuideVaultGame = rxpGuideVaultAddon and rxpGuideVaultAddon.game
if not rxpGuideVaultGame then
    local rxpGuideVaultVersion = select(4, GetBuildInfo())
    if rxpGuideVaultVersion > 60000 then
        rxpGuideVaultGame = "RETAIL"
    elseif rxpGuideVaultVersion > 50000 then
        rxpGuideVaultGame = "MOP"
    elseif rxpGuideVaultVersion > 40000 then
        rxpGuideVaultGame = "CATA"
    elseif rxpGuideVaultVersion > 30000 then
        rxpGuideVaultGame = "WOTLK"
    elseif rxpGuideVaultVersion > 20000 then
        rxpGuideVaultGame = "TBC"
    elseif rxpGuideVaultVersion >= 16000 and rxpGuideVaultVersion < 20000 then
        rxpGuideVaultGame = "FOREVER"
    else
        rxpGuideVaultGame = "CLASSIC"
    end
end
if rxpGuideVaultGame ~= "FOREVER" then return end

RXPGuides.RegisterGuide([[#forever
#version 23
#group RestedXP Forever Guide (A)
#subgroup Speedrun Guide 30-40

<< Alliance
#name 29-32 Duskwood
#next 32-33 Hillsbrad/Arathi

step
    #hidewindow
    #completewith next
    .abandon 277 >> Abandon Fire Taboo

step
    #season 0,1
    #completewith start
    + This segment has a long grinding session, you can substitute that for a Gnomeregan run

step << !Mage !Hunter
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Shellei Brondir|r
    .goto 1437/0,-782.03,-3793.12
    .fly Ironforge>> Fly to Ironforge
    .target Shellei Brondir

step << !Druid !Warrior !Hunter !Mage !Priest !Rogue
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Briarthorn|r << Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Brandur Ironhammer|r << Paladin
    .goto 1455/0,-1117.60,-4615.14,15,0 << Warlock
    .goto 1455/0,-1111.62,-4599.09 << Warlock
    .goto 1455/0,-896.55,-4601.68 << Paladin
    .trainer >> Train your class spells
    .target Briarthorn << Warlock
    .target Brandur Ironhammer << Paladin

step << Warlock
    .goto 1455/0,-1134.20,-4610.39,15,0
    .goto 1455/0,-1130.26,-4601.270
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Jubahl Corpseseeker|r
    .vendor >> |cRXP_BUY_Buy|r |T133738:0|t[Grimoires] |cRXP_BUY_for your|r |T136220:0|t[Succubus] |cRXP_BUY_or your|r |T136221:0|t[Voidwalker]
    .target Jubahl Corpseseeker

step
    .goto Ironforge,63.50,67.30
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sara Balloo|r
    .turnin 637 >> Turn in Sully Balloo's Letter
    .timer 17,Sully Balloo's Letter RP
    .accept 683 >> Accept Sara Balloo's Plea
    .target Sara Balloo

step
    .goto 1455/0,-1022.65,-4865.70
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_King Magni Bronzebeard|r
    .turnin 683 >> Turn in Sara Balloo's Plea
    .accept 686 >> Accept A King's Tribute
    .target King Magni Bronzebeard

step
    .goto 1455/0,-1022.17,-5033.80
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Grand Mason Marblesten|r
    .turnin 686 >> Turn in A King's Tribute
    .accept 689 >> Accept A King's Tribute
    .target Grand Mason Marblesten

step
    .goto 1455/0,-1288.69,-5065.35
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Pilot Longbeard|r
    .accept 1179 >>Accept The Brassbolts Brothers
    .target Pilot Longbeard

step << !Mage
    #completewith Eye
    .goto Ironforge,78.00,52.00,5,0
    .subzone 2257 >> Enter the Deeprun Tram. Take the tram to Stormwind
    >>|cRXP_WARN_Level your|r |T135966:0|t[First Aid] |cRXP_WARN_if needed while waiting for the tram|r

step
    #label BlessedArm
    .goto 1453/0,685.31,-8386.95
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Grimand Elmore|r
    .turnin 322 >> Turn in Blessed Arm
    .accept 325 >> Accept Armed and Ready
    .target Grimand Elmore
    .isQuestTurnedIn 324

step
    #sticky
    #label Eye
    .goto Stormwind City,39.60,27.20
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Archbishop Benedictus|r
    .turnin 293 >> Turn in Cleansing the Eye
    .target Archbishop Benedictus
    .isOnQuest 293

step
    .goto 1453/0,860.47,-8510.92
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Thomas|r
    >>|cRXP_FRIENDLY_Thomas|r |cRXP_WARN_walks around through the Cathedral|r
    .accept 1274 >> Accept The Missing Diplomat
    .target Thomas

step
    #requires Eye
    .goto Stormwind City,78.30,25.45
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Bishop DeLavey|r
    .turnin 1274 >> Turn in The Missing Diplomat
    .accept 1241 >> Accept The Missing Diplomat
    .target Bishop DeLavey

step
    .goto 1453/0,383.76,-8345.76
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Milton Sheaf|r
    >>|cRXP_WARN_If you found |T133741:0|t[|cRXP_LOOT_An Old History Book|r] you may turn it in|r
    .turnin 337 >> Turn in An Old History Book
    .accept 538 >> Accept Southshore
    .use 2794
    .itemcount 2794,1
    .target Milton Sheaf

step
    .goto 1453/0,397.37,-8981.77
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Jorgen|r
    .turnin 1241 >> Turn in The Missing Diplomat
    .accept 1242 >> Accept The Missing Diplomat
    .target Jorgen

step
    .goto Stormwind City,59.90,64.17
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Elling Trias|r
    .turnin 1242 >> Turn in The Missing Diplomat
    .accept 1243 >> Accept The Missing Diplomat
    .target Elling Trias

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Newton Burnside|r
    .goto Stormwind City,57.00,72.88
    .bankwithdraw 916,1451,2378,1130 >> Withdraw the following items from your bank:
    >>|T133688:0|t[A Torn Journal Page]
    >>|T134776:0|t[Bottle of Zombie Juice]
    >>|T133718:0|t[Skeleton Finger]
    >>|T134799:0|t[Vial of Spider Venom]
    .target Newton Burnside

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Newton Burnside|r
    .goto Stormwind City,57.00,72.88
    .bankdeposit 2784,5849,3712 >> Deposit the following items into your bank:
    >>|T134187:0|t[Musquash Root]
    >>|T132765:0|t[Crate of Crash Helmets]
    >>|T134026:0|t[Turtle Meat]
    .target Newton Burnside

step
    #ah
    .goto 1453/0,660.28,-8814.55
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Auctioneer Jaxon|r
    >>Buy the following items for faster turn ins at Duskwood shortly
    >>|T133024:0|t[Bronze Tube]
    .collect 4371,1,174,1
    .bronzetube
    .target Auctioneer Jaxon

step
    #ah
    .goto 1453/0,660.28,-8814.55
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Auctioneer Jaxon|r
    >>|cRXP_BUY_Buy 7|r |T134743:0|t[Jungle Remedy] |cRXP_BUY_from the Auction House for a quest later in Stranglethorn Vale|r
    >>|cRXP_WARN_This is optional, you may also farm them from the mobs later|r
    >>|cRXP_WARN_You may want to buy extra for yourself to use as it cures diseases and removes poisons|r << !Paladin
    .collect 2633,7,204,1
    .target Auctioneer Jaxon

step
    #label start
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Dungar Longdrink|r
    .goto 1453/0,490.12,-8835.67
    .fly Duskwood>> Fly to Duskwood
    .target Dungar Longdrink

step
    .goto 1431/0,-1272.45,-10586.57
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Herble Baubbletump|r
    .vendor >> |cRXP_BUY_Buy a|r |T133024:0|t[Bronze Tube]
    >>|cRXP_WARN_This is a limited supply item. Skip this step if |cRXP_FRIENDLY_Herble Baubbletump|r doesn't have one|r

    .bronzetube
    .target Herble Baubbletump
    .isQuestAvailable 174

step
    .goto Duskwood,79.80,48.02
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Viktori Prism'Antras|r
    >>|cRXP_WARN_Skip this step if you haven't found a bronze tube|r
    .accept 174 >> Accept Look To The Stars
    .turnin 174 >> Turn in Look To The Stars
    .target Viktori Prism'Antras
    .itemcount 4371,1

step
    .goto Duskwood,79.80,48.02
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Viktori Prism'Antras|r
    .accept 175 >> Accept Look To The Stars
    .isQuestTurnedIn 174
    .target Viktori Prism'Antras

step
    .goto 1431/0,-1366.09,-10779.03
    >> Head south towards the chapel
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Blind Mary|r
    .turnin 175 >> Turn in Look To The Stars
    .accept 177 >> Accept Look To The Stars
    .isQuestTurnedIn 174
    .target Blind Mary

step
    .goto 1431/0,-1319.38,-10988.19,30,0
    .goto 1431/0,-1353.13,-11006.37
    >>Kill the |cRXP_ENEMY_Insane Ghoul|r. Loot him for |cRXP_LOOT_Mary's Looking Glass|r
    >>|cRXP_WARN_The |cRXP_ENEMY_Insane Ghoul|r may be inside of the chapel or walking around outside|r
    .complete 177,1
    .mob Insane Ghoul
    .isQuestTurnedIn 174

step
    .goto Duskwood,79.80,48.02
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Viktori Prism'Antras|r
    .turnin 177 >> Turn in Look To The Stars
    .isQuestTurnedIn 174
    .target Viktori Prism'Antras

step
    .goto Duskwood,79.80,48.02
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Viktori Prism'Antras|r
    .accept 181 >> Accept Look To The Stars
    .isQuestTurnedIn 174
    .target Viktori Prism'Antras

step
    .goto 1431/0,-1211.92,-10572.75
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Calor|r
    .accept 173 >> Accept Worgen in the Woods
    .target Calor

step
    .goto 1431/0,-1153.60,-10560.69
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Commander Althea Ebonlocke|r
    >>|cRXP_WARN_She may be dead or busy fighting|r |cRXP_ENEMY_Stitches|r |cRXP_WARN_if he attacks Darkshire. If that happens consider grinding mobs near the town until she respawns or changing your layer (if possible)|r
    .accept 58 >> Accept The Night Watch
    .target Commander Althea Ebonlocke

step
    #optional
    .goto 1431/0,-1108.99,-10576.67
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Councilman Millstipe|r
    .turnin 377 >> Turn in Crime and Punishment
    .target Councilman Millstipe
    .isQuestComplete 377

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Innkeeper Trelayne|r
    .goto 1431/0,-1161.16,-10515.870
    .home >> Set your Hearthstone to Darkshire
    .target Innkeeper Trelayne

step
    .goto 1431/0,-1125.52,-10320.39
    .line Duskwood,74.54,42.90,74.38,40.82,73.87,39.50,72.72,38.91,72.24,37.30,72.20,34.86,72.55,33.54
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Watcher Backus|r. He patrols the road north of Darkshire
    .turnin 1243 >> Turn in The Missing Diplomat
    .accept 1244 >> Accept The Missing Diplomat
    .target Watcher Backus

step
    .goto Duskwood,66.0,44.6,60,0
    .goto 1431/0,-900.07,-10415.07,60,0
    .goto 1431/0,-808.27,-10389.87,60,0
    .goto 1431/0,-819.07,-10544.67,60,0
    .goto 1431/0,-991.87,-10555.47,60,0
    .goto 1431/0,-883.87,-10458.27
    >>Kill |cRXP_ENEMY_Nightbane Shadow Weavers|r
    .complete 173,1
    .mob Nightbane Shadow Weaver

step
    .goto 1431/0,-1199.82,-10581.49
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Calor|r
    .turnin 173 >> Turn in Worgen in the Woods
    .accept 221 >> Accept Worgen in the Woods
    .target Calor

step
    .goto 1431/0,-889.27,-10649.07,60,0
    .goto 1431/0,-819.07,-10440.27,60,0
    .goto 1431/0,-927.07,-10645.47,60,0
    .goto 1431/0,-824.47,-10458.27
    >>Kill |cRXP_ENEMY_Nightbane Dark Runners|r
    >>|cRXP_ENEMY_Nightbane Dark Runners|r |cRXP_WARN_move very fast and have a larger than normal aggro radius|r
    .complete 221,1
    .mob Nightbane Dark Runner

step
    #completewith next
    .goto Elwynn Forest,84.60,69.37,100 >> Travel to the Eastvale Logging Camp

step
    .goto Elwynn Forest,84.60,69.37
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Marshal Haggard|r
    .turnin 74 >> Turn in The Legend of Stalvan
    .accept 75 >> Accept The Legend of Stalvan
    .target Marshal Haggard

step
    .goto Elwynn Forest,85.70,69.53
    >>Head upstairs in the House
    >>Open |cRXP_PICK_Marshal Haggard's Chest|r. Loot it for |cRXP_LOOT_A Faded Journal Page|r
    .complete 75,1

step
    .goto Elwynn Forest,84.60,69.37
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Marshal Haggard|r
    .turnin 75 >> Turn in The Legend of Stalvan
    .accept 78 >> Accept The Legend of Stalvan
    .target Marshal Haggard

step
    #completewith next
    .goto Duskwood,28.10,31.46,100 >> Travel towards |cRXP_FRIENDLY_Abercrombie|r in Duskwood

step
    #completewith next
    >>Kill |cRXP_ENEMY_Black Widow Hatchlings|r on the way to Abercrombie. Loot them for |T134799:0|t[|cRXP_LOOT_Vials of Spider Venom|r]
    >>|cRXP_WARN_Don't go out of your way to complete this objective now, you will complete it later|r
    .complete 101,2
    .mob Black Widow Hatchling

step
    .goto 1431/0,74.42,-10283.11
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Abercrombie|r
    .turnin 159 >> Turn in Juice Delivery
    .accept 133 >> Accept Ghoulish Effigy
    .target Abercrombie

step
    .goto 1431/0,178.31,-10308.870
    >>Kill |cRXP_ENEMY_Plague Spreaders|r. Loot them for their |cRXP_LOOT_Ribs|r and |cRXP_LOOT_Fangs|r
    >>|cRXP_WARN_Other |cRXP_ENEMY_Ghouls|r may also drop |cRXP_LOOT_Ribs|r and |cRXP_LOOT_Fangs|r but focus on|r |cRXP_ENEMY_Plague Spreaders|r
    .complete 58,1
    .mob +Plague Spreader
    .complete 133,1
    .mob +Flesh Eater
    .mob +Rotted One
    .mob +Bone Chewer
    .complete 101,1
    .mob +Flesh Eater
    .mob +Rotted One
    .mob +Bone Chewer

step
    .goto 1431/0,74.42,-10283.11
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Abercrombie|r
    .turnin 133 >> Turn in Ghoulish Effigy
    .accept 134 >> Accept Ogre Thieves
    .target Abercrombie

step
    #completewith next
    >>Kill |cRXP_ENEMY_Black Widow Hatchlings|r on the way south. Loot them for |T134799:0|t[|cRXP_LOOT_Vials of Spider Venom|r]
    >>|cRXP_WARN_Don't go out of your way to complete this objective now, you will complete it later|r
    .complete 101,2
    .mob Black Widow Hatchling

step
    .goto 1431/0,187.33,-11014.02
    >>Open the |cRXP_PICK_Defias Strongbox|r. Loot it for the |cRXP_LOOT_Defias Docket|r
    .complete 1244,1

step
    .goto 1431/0,-68.98,-11091.07
    >>Loot |cRXP_LOOT_Abercrombie's Crate|r on the ground
    .complete 134,1

step
    #completewith next
    .goto 1431/0,-101.68,-11118.33,20 >> Enter the Vul'Gol Ogre Cave
    .isOnQuest 181

step
    .goto 1431/0,-192.13,-11154.870,30,0
    .goto 1431/0,-160.54,-11224.71
    >>Kill |cRXP_ENEMY_Zzarc' Vul|r. Loot him for his |cRXP_LOOT_Monocle|r
    >>|cRXP_ENEMY_Zzarc' Vul|r |cRXP_WARN_has 2 spawn points inside the Cave|r
    .complete 181,1
    .mob Zzarc' Vul
    .isOnQuest 181

step
    #completewith next
    .goto 1431/0,-19.87,-10785.87,0
    .goto 1431/0,-95.47,-10699.47,0
    .goto 1431/0,61.13,-10605.87,0
    .goto 1431/0,-52.27,-10350.27,0
    .goto 1431/0,196.13,-10375.47,0
    >>Kill |cRXP_ENEMY_Black Widow Hatchlings|r and |cRXP_ENEMY_Carrion Recluses|r. Loot them for their |cRXP_LOOT_Spider Venom|r
    .complete 101,2
    .mob Black Widow Hatchling
    .mob Carrion Recluse

step
    .goto 1431/0,213.68,-10522.17,80,0
    .goto 1431/0,282.80,-10563.03,70,0
    .goto 1431/0,426.44,-10561.05,70,0
    .goto 1431/0,410.78,-10487.25,70,0
    .goto Duskwood,18.30,47.75,70,0
    .goto 1431/0,236.36,-10561.41,70,0
    .goto 1431/0,193.97,-10475.01,70,0
    .goto 1431/0,260.66,-10563.93
    >>Kill |cRXP_ENEMY_Skeletal Fiends|r and |cRXP_ENEMY_Skeletal Horrors|r. Loot them for their |cRXP_LOOT_Fingers|r
    .complete 101,3
    .mob Skeletal Fiend
    .mob Skeletal Horror

step
    .goto 1431/0,-19.87,-10785.87,0
    .goto 1431/0,-95.47,-10699.47,0
    .goto 1431/0,61.13,-10605.87,0
    .goto 1431/0,-52.27,-10350.27,0
    .goto 1431/0,-19.87,-10785.87,50,0
    .goto 1431/0,-95.47,-10699.47,50,0
    .goto 1431/0,61.13,-10605.87,50,0
    .goto 1431/0,-52.27,-10350.27,50,0
    .goto 1431/0,196.13,-10375.47
    >>Kill |cRXP_ENEMY_Black Widow Hatchlings|r and |cRXP_ENEMY_Carrion Recluses|r. Finish off looting them for their |cRXP_LOOT_Spider Venom|r
    .complete 101,2
    .mob Black Widow Hatchling
    .mob Carrion Recluse

step
    #label note
    .goto 1431/0,74.42,-10283.11
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Abercrombie|r
    .turnin 134 >> Turn in Ogre Thieves
    .accept 160 >> Accept Note to the Mayor
    .target Abercrombie

step
    >>Click |cRXP_PICK_A Weathered Grave|r
    .goto 1431/0,354.89,-10239.93
    .accept 225 >> Accept The Weathered Grave

step
    .goto 1431/0,623.27,-10329.75
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sven Yorgen|r
    .turnin 325 >> Turn in Armed and Ready
    .accept 55 >> Accept Morbent Fel
    .target Sven Yorgen
    .isQuestTurnedIn 322

step
    .hs >> Hearth to Darkshire
    >>|cRXP_BUY_Buy food/water if needed|r << !Warrior !Rogue
    >>|cRXP_BUY_Buy food if needed|r << Warrior/Rogue

step
    #completewith next
    .goto 1431/0,-1161.21,-10515.97
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Innkeeper Trelayne|r
    .vendor >>|cRXP_BUY_Buy food/water. You'll need at least 2 1/2 stacks for the upcoming segment|r
    .target Innkeeper Trelayne

step
    .goto 1431/0,-1158.46,-10517.31
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Tavernkeep Smitts|r inside the inn
    .turnin 78 >> Turn in The Legend of Stalvan
    .accept 79 >> Accept The Legend of Stalvan
    .target Tavernkeep Smitts

step
    .goto 1431/0,-1153.60,-10560.69
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Commander Althea Ebonlocke|r
    >>|cRXP_WARN_She may be dead or busy fighting|r |cRXP_ENEMY_Stitches|r |cRXP_WARN_if he attacks Darkshire. If that happens consider grinding mobs near the town until she respawns or changing your layer (if possible)|r
    .turnin 58 >> Turn in The Night Watch
    .turnin 79 >> Turn in The Legend of Stalvan
    .accept 80 >> Accept The Legend of Stalvan
    .target Commander Althea Ebonlocke

step
    .goto 1431/0,-1124.98,-10559.97
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Clerk Daltry|r in the town hall building
    .turnin 80 >> Turn in The Legend of Stalvan
    .accept 97 >> Accept The Legend of Stalvan
    .target Clerk Daltry

step
    .goto 1431/0,-1127.95,-10573.65
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sirra Von'Indi|r
    .turnin 225 >> Turn in The Weathered Grave
    .accept 227 >> Accept Morgan Ladimore
    .target Sirra Von'Indi

step
    .goto 1431/0,-1108.78,-10552.05
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Lord Ello Ebonlocke|r
    .turnin 160 >> Turn in Note to the Mayor
    .accept 251 >> Accept Translate Abercrombie's Note
    .target Lord Ello Ebonlocke

step
    .goto 1431/0,-1127.95,-10573.65
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sirra Von'Indi|r
    .turnin 251 >> Turn in Translate Abercrombie's Note
    .target Sirra Von'Indi
    .accept 401 >> Accept Wait for Sirra to Finish
    .turnin 401 >> Turn in Wait for Sirra to Finish
    .accept 252 >> Accept Translation to Ello

step
    .goto 1431/0,-1108.78,-10552.05
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Lord Ello Ebonlocke|r
    .turnin 252 >> Turn in Translation to Ello
    .target Lord Ello Ebonlocke

step
    .goto 1431/0,-1108.78,-10552.05
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Lord Ello Ebonlocke|r
    .accept 253 >> Accept Bride of the Embalmer
    .target Lord Ello Ebonlocke

step
    .goto 1431/0,-1153.60,-10560.69
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Commander Althea Ebonlocke|r
    >>|cRXP_WARN_She may be dead or busy fighting|r |cRXP_ENEMY_Stitches|r |cRXP_WARN_if he attacks Darkshire. If that happens consider grinding mobs near the town until she respawns or changing your layer (if possible)|r
    .turnin 97 >> Turn in The Legend of Stalvan
    .accept 98 >> Accept The Legend of Stalvan
    .turnin 227 >> Turn in Morgan Ladimore
    .accept 228 >> Accept Mor'Ladim
    .target Commander Althea Ebonlocke

step
    #sticky
    .destroy 2154 >> Throw away |T133741:0|t[The Story of Morgan Ladimore]

step
    .goto 1431/0,-1199.82,-10581.49
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Calor|r
    .turnin 221 >> Turn in Worgen in the Woods
    .accept 222 >> Accept Worgen in the Woods
    .target Calor

step
    #label exit1
    .goto 1431/0,-1125.52,-10320.39
    .line Duskwood,74.54,42.90,74.38,40.82,73.87,39.50,72.72,38.91,72.24,37.30,72.20,34.86,72.55,33.54
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Watcher Backus|r. He patrols the road north of Darkshire
    .turnin 1244 >> Turn in The Missing Diplomat
    .accept 1245 >> Accept The Missing Diplomat
    .target Watcher Backus

step
    #sticky
    #label FlowerX
    .goto 1431/0,-1282.06,-10363.80
    >>Loot the |cRXP_LOOT_Tear of Tilloa|r on the ground
    .complete 335,1
    .isOnQuest 335

step
    .goto Duskwood,77.30,36.20
    >> Kill |cRXP_ENEMY_Stalvan Mistmantle|r. Loot him for his |cRXP_LOOT_Family Ring|r
    >>|cRXP_ENEMY_Stalvan Mistmantle|r |cRXP_WARN_can hit quite hard. Kite him back to town and get help from the |cRXP_FRIENDLY_Watchers|r if needed|r
    .complete 98,1
    .mob Stalvan Mistmantle

step
    #requires FlowerX
    .goto 1431/0,-1213.54,-10531.89
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Madame Eva|r inside
    .turnin 98 >> Turn in The Legend of Stalvan << !Hunter
    .turnin 101 >> Turn in The Totem of Infliction
    .target Madame Eva

step
    .goto Duskwood,79.80,48.02
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Viktori Prism'Antras|r
    .turnin 181 >> Turn in Look To The Stars
    .isQuestTurnedIn 174
    .target Viktori Prism'Antras

step
    .goto Duskwood,58.64,80.00,50 >> Head to the worgen area south of the Rotten Orchard

step
    #completewith worgenGrind
    .goto 1431/0,-849.58,-11188.53,0
    .goto Duskwood,61.30,74.36,0
    .goto Duskwood,65.10,73.91,0
    .goto 1431/0,-898.45,-10949.49,0
    >>Kill |cRXP_ENEMY_Nightbane Worgens|r. Loot them for |T133741:0|t[|cRXP_LOOT_An Old History Book|r]
    >>|cRXP_WARN_Don't start the quest for it yet|r
    .collect 2794,1,337

    .mob Nightbane Shadow Weaver
    .mob Nightbane Dark Runner
    .mob Nightbane Tainted One
    .mob Nightbane Worgen

step
    .goto 1431/0,-849.58,-11188.53
    .goto Duskwood,71.9,72.1,0
    >> Kill |cRXP_ENEMY_Nightbane Vile Fangs|r and |cRXP_ENEMY_Nightbane Tainted Ones|r
    >>|cRXP_WARN_Be careful as all the mobs in the area respawn at once after 4.75-6.5 minutes of killing the first one|r
    >>This area is a popular grinding spot for mages and may be contested. If you feel like there's too much competition you can complete this objective in the Roland's Doom area (cave, marked on your map)
    .complete 222,1
    .mob +Nightbane Vile Fang
    .complete 222,2
    .mob +Nightbane Tainted One

step
    #label worgenGrind
    .goto 1431/0,-849.58,-11188.53,0
    .goto Duskwood,61.30,74.36,0
    .goto Duskwood,65.10,73.91,0
    .goto 1431/0,-898.45,-10949.49,0
    .xp 31+38100 >> Grind until 38100/50800 xp into level 31 << !Druid
    >>Kill |cRXP_ENEMY_Nightbane Worgens|r until your Hearthstone cooldown is <25 minutes
    >>|cRXP_WARN_If you know that you will be leveling in one session or generally not getting a lot of rested experience up to level 38, consider grinding to level 32 instead. This will help you reach a level 38 xp gate that is required later on|r
    .mob Nightbane Shadow Weaver
    .mob Nightbane Dark Runner
    .mob Nightbane Tainted One
    .mob Nightbane Worgen

step
    .goto 1431/0,-849.58,-11188.53,0
    .goto Duskwood,61.30,74.36,0
    .goto Duskwood,65.10,73.91,0
    .goto 1431/0,-898.45,-10949.49,0
    >>Keep killing |cRXP_ENEMY_Nightbane Worgens|r. until you loot |T133741:0|t[|cRXP_LOOT_An Old History Book|r]
    >>|cRXP_WARN_Don't start the quest for it yet|r
    .collect 2794,1,337

    .mob Nightbane Shadow Weaver
    .mob Nightbane Dark Runner
    .mob Nightbane Tainted One
    .mob Nightbane Worgen

step
    .goto 1431/0,-849.58,-11188.53,0
    .goto Duskwood,61.30,74.36,0
    .goto Duskwood,65.10,73.91,0
    .goto 1431/0,-898.45,-10949.49,0
    +Keep killing |cRXP_ENEMY_Nightbane Worgens|r until your Hearthstone cooldown is <25 minutes
    >>|cRXP_WARN_This step will autocomplete when your HS cooldown is low enough to continue|r
    .cooldown item,6948,<1500
    .mob Nightbane Shadow Weaver
    .mob Nightbane Dark Runner
    .mob Nightbane Tainted One
    .mob Nightbane Worgen

step
    .goto 1431/0,54.01,-10270.44
    >>Click |cRXP_PICK_Eliza's Grave Dirt|r to summon |cRXP_ENEMY_Eliza|r
    >>Kill |cRXP_ENEMY_Eliza|r. Loot her for the |cRXP_LOOT_Embalmer's Heart|r
    >>|cRXP_ENEMY_Eliza|r |cRXP_WARN_will cast|r |T135846:0|t[Frostbolt] |cRXP_WARN_and|r |T135848:0|t[Frost Nova] |cRXP_WARN_along with summoning multiple|r |cRXP_ENEMY_Guards|r
    >>|cRXP_WARN_You can avoid dealing with |cRXP_ENEMY_Eliza's Guards|r by using the Wagon to jump on top of |cRXP_FRIENDLY_Abercrombie's|r Hut|r << Hunter/Mage/Warlock/Priest
    >>|cRXP_WARN_You can evade |cRXP_ENEMY_Eliza's Guards|r by using the Wagon to jump on top of Abercrombie's Hut. |cRXP_ENEMY_Eliza|r will continue to cast|r |T135846:0|t[Frostbolt] |cRXP_WARN_at you if you do this while she's alive|r << Warrior/Rogue/Druid/Paladin
    .complete 253,1
    .mob Eliza

step
    #completewith next
    >>Clear your way to the 2nd floor of the house
    .cast 8913 >>|cRXP_WARN_Equip|r |T135142:0|t[Morbent's Bane] |cRXP_WARN_in your off-hand|r
    >>|cRXP_WARN_Use|r |T135142:0|t[Morbent's Bane] |cRXP_WARN_on|r |cRXP_ENEMY_Morbent Fel|r |cRXP_WARN_to weaken him|r
    >>|cRXP_WARN_Remember to equip your weapon/off-hand slot after weakening him|r
    .use 7297

step
    .goto Duskwood,16.90,33.40
    >>Kill |cRXP_ENEMY_Morbent Fel|r
    >>|cRXP_WARN_This quest can be difficult. You may skip this step and come back at a higher level if you wish|r
    .complete 55,1
    .use 7297
    .mob Morbent Fel
    .isOnQuest 55

step
    .goto 1431/0,304.40,-10387.71
    >>Kill |cRXP_ENEMY_Mor'Ladim|r. Loot him for his |cRXP_LOOT_Skull|r
    >>|cRXP_ENEMY_Mor'Ladim|r |cRXP_WARN_hits very hard but moves quite slow. Try to kite him around any large trees if required|r
    >>|cRXP_WARN_This quest can be difficult. You may skip this step and come back at a higher level if you wish|r
    .complete 228,1
    .unitscan Mor'Ladim

step
    .goto 1431/0,623.27,-10329.75
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sven Yorgen|r
    .turnin 55 >> Turn in Morbent Fel
    .isQuestComplete 55
    .target Sven Yorgen

step
    .goto 1431/0,304.40,-10387.71
    >>Kill |cRXP_ENEMY_Mor'Ladim|r. Loot him for his |cRXP_LOOT_Skull|r
    >>|cRXP_ENEMY_Mor'Ladim|r |cRXP_WARN_hits very hard but moves quite slow. Try to kite him around any large trees if required|r
    >>|cRXP_WARN_This quest can be difficult. You may skip this step and come back at a higher level if you wish|r
    .complete 228,1
    .unitscan Mor'Ladim

step
    #completewith next
    .goto 1431/0,-370.81,-11292.84,0
    .goto 1434/0,-372.19,-11318.24
    .zone Stranglethorn Vale >> Travel to Stranglethorn Vale

step
    #completewith stvEnd2
    .goto 1434/0,-353.30,-11527.55,0
    >>|cRXP_WARN_Keep an eye out for the special |cRXP_FRIENDLY_Private Thorsen|r event. He will patrol down the road from the Rebel camp every 30 minutes|r
    >>|cRXP_FRIENDLY_Private Thorsen|r |cRXP_WARN_will be attacked by 2 of |cRXP_ENEMY_Kurzen's Agents|r. If you don't see this event, ignore this step|r
    >>Kill both of |cRXP_ENEMY_Kurzen's Agents|r and then accept |cRXP_FRIENDLY_Private Thorsen's|r quest which becomes available after saving him
    .accept 215 >> Accept Jungle Secrets
    .unitscan Private Thorsen
    .mob Kurzen's Agent

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Barnil Stonepot|r and |cRXP_FRIENDLY_Hemet Nesingwary|r
    .accept 583 >> Accept Welcome to the Jungle
    .target +Barnil Stonepot
    .goto 1434/0,-54.85,-11616.67
    .turnin 583 >> Turn in Welcome to the Jungle
    .target +Hemet Nesingwary
    .goto 1434/0,-54.59,-11628.54

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ajeck Rouack|r and |cRXP_FRIENDLY_Sir S. J. Erlgadin|r
    .accept 185 >> Accept Tiger Mastery
    .target +Ajeck Rouack
    .goto 1434/0,-51.91,-11620.50
    .accept 190 >> Accept Panther Mastery
    .target +Sir S. J. Erlgadin
    .goto 1434/0,-48.08,-11617.39

step
    #completewith next
    >>Kill |cRXP_ENEMY_Young Panthers|r
    .complete 190,1
    .mob Young Panther

step
    .goto Stranglethorn Vale,35.40,12.50,50,0
    .goto Stranglethorn Vale,33.30,11.90,50,0
    .goto 1434/0,194.15,-11551.620,50,0
    .goto Stranglethorn Vale,35.40,12.50
    >>Kill |cRXP_ENEMY_Young Stranglethorn Tigers|r
    .complete 185,1
    .mob Young Stranglethorn Tiger

step
    .goto Stranglethorn Vale,41.50,12.00,50,0
    .goto 1434/0,-506.51,-11696.270,50,0
    .goto 1434/0,-422.92,-11584.38,50,0
    .goto 1434/0,-374.42,-11664.36,50,0
    .goto Stranglethorn Vale,41.50,12.00
    >>Kill |cRXP_ENEMY_Young Panthers|r
    .complete 190,1
    .mob Young Panther

step
    #label stvEnd2
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ajeck Rouack|r and |cRXP_FRIENDLY_Sir S. J. Erlgadin|r
    >>|cRXP_WARN_Don't accept the follow ups yet|r
    .turnin 185 >> Turn in Tiger Mastery
    .target +Ajeck Rouack
    .goto 1434/0,-51.91,-11620.50
    .turnin 190 >> Turn in Panther Mastery
    .target +Sir S. J. Erlgadin
    .goto 1434/0,-48.08,-11617.39

step
    .goto 1434/0,-206.72,-11296.89
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Lieutenant Doren|r
    >>|cRXP_WARN_Don't accept the follow up yet|r
    .turnin 215 >> Turn in Jungle Secrets
    .isOnQuest 215
    .target Lieutenant Doren

step
    #completewith next
    .hs >> Hearth to Darkshire
    >>|cRXP_BUY_Buy food/water if needed|r << !Warrior !Rogue
    >>|cRXP_BUY_Buy food if needed|r << Warrior/Rogue
    .cooldown item,6948,>0,1

step
    .goto 1431/0,-1153.60,-10560.69
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Commander Althea Ebonlocke|r
    >>|cRXP_WARN_She may be dead or busy fighting|r |cRXP_ENEMY_Stitches|r |cRXP_WARN_if he attacks Darkshire. If that happens consider grinding mobs near the town until she respawns or changing your layer (if possible)|r
    .turnin 228 >> Turn in Mor'Ladim
    .isQuestComplete 228
    .target Commander Althea Ebonlocke

step
    .goto 1431/0,-1153.60,-10560.69
    .isQuestTurnedIn 228
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Commander Althea Ebonlocke|r
    >>|cRXP_WARN_She may be dead or busy fighting|r |cRXP_ENEMY_Stitches|r |cRXP_WARN_if he attacks Darkshire. If that happens consider grinding mobs near the town until she respawns or changing your layer (if possible)|r
    .accept 229 >> Accept The Daughter Who Lived
    .target Commander Althea Ebonlocke

step
    .goto 1431/0,-1108.78,-10552.05
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Lord Ello Ebonlocke|r
    .turnin 253 >> Turn in Bride of the Embalmer
    .isQuestComplete 253
    .target Lord Ello Ebonlocke

step
    #sticky
    .destroy 3248 >>Throw away the |T134939:0|t[Translated Letter from The Embalmer] you no longer need it

step
    .goto 1431/0,-1179.25,-10546.11
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Watcher Ladimore|r |cRXP_WARN_she patrols around the Darkshire main square|r
    >>|cRXP_FRIENDLY_Watcher Ladimore|r |cRXP_WARN_patrols around in Darkshire|r
    .turnin 229 >> Turn in The Daughter Who Lived
    .accept 231 >> Accept A Daughter's Love
    .isQuestTurnedIn 228
    .target Watcher Ladimore

step
    .goto 1431/0,-1199.82,-10581.49
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Calor|r
    .turnin 222 >> Turn in Worgen in the Woods
    .accept 223 >> Accept Worgen in the Woods
    .target Calor

step
    .goto 1431/0,-1200.31,-10599.03
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Jonathan Carevin|r
    .turnin 223 >> Turn in Worgen in the Woods
    .target Jonathan Carevin

step << !Mage
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Felicia Maline|r
    .goto 1431/0,-1258.90,-10513.71
    .fly Stormwind>> Fly to Stormwind
    .target Felicia Maline

step
    .goto Stormwind City,59.90,64.17
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Elling Trias|r
    .turnin 1245 >> Turn in The Missing Diplomat
    .accept 1246 >> Accept The Missing Diplomat
    .target Elling Trias

step << !Mage
    .goto Stormwind City,57.00,72.88
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Newton Burnside|r
    .bankwithdraw 2784,5849,3712,2794 >> Withdraw the following items:
    >>|T132765:0|t[Crate of Crash Helmets]
    >>|T134026:0|t[Turtle Meat]
    >>|T134187:0|t[Musquash Root]
    >>|T133741:0|t[An Old History Book]
    .target Newton Burnside

step << Warrior
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Wu|r or |cRXP_FRIENDLY_Ilsa|r
    .goto StormwindClassic,76.08,50.14,15,0
    .goto StormwindClassic,80.22,45.37,15,0
    .goto StormwindClassic,78.68,45.79
    .trainer >> Train your class spells
    .target Wu Shen
    .target Ilsa Corbin

step << Warrior
    .goto Stormwind City,78.680,45.802
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Wu Shen|r
    .accept 1718 >> Accept The Islander
    .target Wu Shen

step
    #completewith next
    .goto 1453/0,432.60,-8681.20
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Dashel Stonefist|r
    >>|cRXP_ENEMY_Dashel Stonefist|r |cRXP_WARN_will become hostile after accepting the follow up quest. Defeat him|r
    .turnin 1246 >> Turn in The Missing Diplomat
    .accept 1447,1 >> Accept The Missing Diplomat
    .target Dashel Stonefist

step
    .goto 1453/0,432.60,-8681.20
    >>Defeat |cRXP_ENEMY_Dashel Stonefist|r
    >>|cRXP_ENEMY_Dashel Stonefist|r |cRXP_WARN_will also attack with 2 |cRXP_ENEMY_Old Town Thugs|r. Ignore them and focus on|r |cRXP_ENEMY_Dashel Stonefist|r
    >>|cRXP_WARN_Be careful as the|r |cRXP_ENEMY_Old Town Thugs|r |cRXP_WARN_will reset when you defeat Dashel but then become hostile again after returning to their original locations|r
    .complete 1447,1
    .mob Dashel Stonefist

step
    .goto 1453/0,432.60,-8681.20
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Dashel Stonefist|r
    .turnin 1447 >> Turn in The Missing Diplomat
    .accept 1247 >> Accept The Missing Diplomat
    .target Dashel Stonefist

step
    .goto Stormwind City,59.90,64.17
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Elling Trias|r
    .turnin 1247 >> Turn in The Missing Diplomat
    .accept 1248 >> Accept The Missing Diplomat
    .target Elling Trias

step << !Mage
    .goto 1453/0,801.75,-8999.44
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Collin Mauren|r
    .turnin 1078 >> Turn in Retrieval for Mauren
    .isOnQuest 1078
    .target Collin Mauren

step << !Mage
    .goto 1453/0,845.37,-9008.89
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Archmage Malin|r
    .accept 690 >> Accept Malin's Request
    .target Archmage Malin

step << !Mage
    .goto 1453/0,834.75,-9102.30
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Connor Rivers|r
    .accept 1301 >> Accept James Hyal
    .target Connor Rivers

step
    #season 0,1
    #completewith next
    .goto 1453/0,988.44,-8942.15,20,0
    .goto 1453/0,1015.33,-8978.90,15 >> Go into The Slaughtered Lamb and go downstairs

step
    .goto 1453/0,1025.56,-8983.64
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Zardeth of the Black Claw|r
    .turnin 335 >> Turn in A Noble Brew
    .accept 336 >> Accept A Noble Brew
    .target Zardeth of the Black Claw

step << Warlock
    .goto StormwindClassic,26.117,77.225
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ursula Deline|r
    .trainer >> Train your class spells
    .target Ursula Deline

step << Warlock
    .goto 1453/0,1041.48,-8983.30
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gakin the Darkbinder|r
    .accept 1798 >> Accept Seeking Strahad
    .target Gakin the Darkbinder

step << Warlock
    .goto 1453/0,1041.10,-8980.01
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Demisette Cloyce|r
    >>|cRXP_WARN_Skip this step if you picked up the same quest from Ironforge earlier|r
    .accept 4738 >> Accept In Search of Menara Voidrender
    .target Demisette Cloyce

step << Priest/Paladin
    #completewith next
    .goto StormwindClassic,42.51,33.51,20 >> Travel to the Stormwind Cathedral

step << Paladin
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Arthur the Faithful|r
    .goto StormwindClassic,38.82,31.27,10,0
    .goto StormwindClassic,38.67,32.82
    .trainer >> Train your class spells
    .target Arthur the Faithful

step
    .goto 1453/0,369.73,-8562.730
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Lord Baurles K. Wishock|r
    .turnin 336 >> Turn in A Noble Brew
    .target Lord Baurles K. Wishock

step
    .goto Stormwind City,68.7,29.1,20 >> Head to the Stormwind Keep
    .itemcount 2794,1

step
    .goto Stormwind City,70.2,11.6,20 >> Head to the Stormwind Keep Library
    .itemcount 2794,1

step
    .goto 1453/0,383.76,-8345.76
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Milton Sheaf|r
    >>|cRXP_WARN_If you found |T133741:0|t[|cRXP_LOOT_An Old History Book|r] you may turn it in|r
    .accept 337 >> Accept An Old History Book
    .turnin 337 >> Turn in An Old History Book
    .accept 538 >> Accept Southshore
    .use 2794
    .itemcount 2794,1
    .target Milton Sheaf

step
    .isQuestTurnedIn 337
    .goto 1453/0,383.76,-8345.76
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Milton Sheaf|r
    .accept 538 >> Accept Southshore
    .target Milton Sheaf

step << Warlock
    #completewith next
    .goto 1453/0,988.44,-8942.15,20,0
    .goto 1453/0,1015.33,-8978.90,15 >> Go into The Slaughtered Lamb and go downstairs

step << Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Zardeth of the Black Claw|r and |cRXP_FRIENDLY_Zggi|r
    .accept 397 >> Accept You Have Served Us Well
    .goto 1453/0,1025.56,-8983.64
    .turnin 397 >> Turn in You Have Served Us Well
    .goto 1453/0,1024.24,-8983.920
    .target Zardeth of the Black Claw
    .target Zggi

step
    .dungeon Gnomer
    #season 0,1
    .goto StormwindClassic,55.511,12.502
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Shoni the Shilent|r
    .accept 2928 >> Accept Gyrodrillmatic Excavationators
    .target Shoni the Shilent

step << !Mage
    .goto StormwindClassic,61.149,11.568,25,0
    .goto StormwindClassic,64.0,8.10
    .zone Ironforge >> Enter the Deeprun Tram. Take the Tram to Ironforge
    >>|cRXP_WARN_Level your|r |T135966:0|t[First Aid] |cRXP_WARN_if needed while waiting for the Tram|r

step
    #season 0,1
    .goto Ironforge,69.540,50.325
    .target Tinkmaster Overspark
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Tinkmaster Overspark|r
    .turnin -2923 >> Turn in Tinkmaster Overspark

step
    .dungeon Gnomer
    #season 0,1
    #completewith next
    .goto 1426/0,610.23,-5160.87,0
    +Start Looking for a Gnomeregan group

step
    .dungeon Gnomer
    #season 0,1
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Shellei Brondir|r
    .goto 1437/0,-782.03,-3793.400
    .fly Ironforge >>Fly to Ironforge
    .target Shellei Brondir
    .zoneskip Ironforge

step
    .dungeon Gnomer
    #season 0,1
    #completewith StartGnomer
    .goto 1426/0,610.23,-5160.87,0
    +Start Looking for a Gnomeregan group
    .subzoneskip 133
    .subzoneskip 721,2

step
    .dungeon Gnomer
    #season 0,1
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gnoarn|r, |cRXP_FRIENDLY_Tinkmaster Overspark|r, |cRXP_FRIENDLY_High Tinker Mekkatorque|r, |cRXP_FRIENDLY_Master Mechanic Castpipe|r and |cRXP_FRIENDLY_Klockmort Spannerspan|r
    .accept 2927 >> Accept The Day After
    .target +Gnoarn
    .goto 1455/0,-1260.56,-4835.98
    .turnin -2923 >> Turn in Tinkmaster Overspark
    .accept 2922 >> Accept Save Techbot's Brain!
    .target +Tinkmaster Overspark
    .goto Ironforge,69.540,50.325
    .accept 2929 >> Accept The Grand Betrayal
    .target +High Tinker Mekkatorque
    .goto 1455/0,-1257.09,-4827.60
    .accept 2930 >> Accept Data Rescue
    .target +Master Mechanic Castpipe
    .goto 1455/0,-1265.63,-4823.02
    .accept 2924 >> Accept Essential Artificials
    .target +Klockmort Spannerspan
    .goto 1455/0,-1250.62,-4812.47

step
    .dungeon Gnomer
    #season 0,1
    #completewith next
    .goto 1426/0,-832.79,-5022.97
    .zone Dun Morogh>>Exit Ironforge

step
    .dungeon Gnomer
    #season 0,1
    .goto 1426/0,-463.66,-5474.00,10,0
    .goto 1426/0,-457.85,-5498.29
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ozzie Togglevolt|r
    .turnin 2927 >> Turn in The Day After
    .accept 2926 >> Accept Gnogaine
    .target Ozzie Togglevolt

step
    .dungeon Gnomer
    #season 0,1
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Innkeeper Belm|r inside
    .target Innkeeper Belm
    .goto 1426/0,-531.23,-5601.59
    .home >> Set your Hearthstone to Kharanos

step
    .dungeon Gnomer
    #season 0,1
    #label StartGnomer
    #completewith next
    .goto 1426/0,602.85,-5183.19,0
    .goto 1426/0,602.85,-5183.19,30,0
    .goto 1415,43.42,53.81,45 >> Travel to Gnomeregan

step
    .dungeon Gnomer
    #season 0,1
    .goto 1415,43.40,53.41,50,0
    .goto 1415,43.13,53.36,50,0
    .goto 1415,43.38,52.94,50,0
    .goto 1415,43.40,53.41
    .use 9283 >>|cRXP_WARN_Use the|r |T132788:0|t[Empty Leaden Collection Phial] |cRXP_WARN_on a |cRXP_ENEMY_Irradiated Invader|r or|r |cRXP_ENEMY_Irradiated Pillager|r
    >>|cRXP_WARN_The |cRXP_ENEMY_Irradiated Invader|r or |cRXP_ENEMY_Irradiated Pillager|r must be ALIVE when you use it|r
    >>|cRXP_WARN_This quest is completed while OUTSIDE of the dungeon|r
    .complete 2926,1
    .mob Irradiated Invader
    .mob Irradiated Pillager
    .isOnQuest 2926

step
    .dungeon Gnomer
    #season 0,1
    #completewith next
    .goto 1426/0,-463.66,-5474.00,40 >> Travel to |cRXP_FRIENDLY_Ozzie Togglevolt|r in Kharanos
    >>|cRXP_WARN_You will get a follow up for when you go inside the dungeon|r
    .isOnQuest 2926

step
    .dungeon Gnomer
    #season 0,1
    .goto 1426/0,-463.66,-5474.00,10,0
    .goto 1426/0,-457.85,-5498.29
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ozzie Togglevolt|r
    .turnin 2926 >> Turn in Gnogaine
    .target Ozzie Togglevolt
    .isQuestComplete 2926

step
    .dungeon Gnomer
    #season 0,1
    .goto 1426/0,-457.85,-5498.29
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ozzie Togglevolt|r
    .accept 2962 >> Accept The Only Cure is More Green Glow
    .target Ozzie Togglevolt
    .isQuestTurnedIn 2926

step
    .dungeon Gnomer
    #season 0,1
    #completewith next
    .goto 1426/0,602.85,-5183.19,0
    .goto 1426/0,602.85,-5183.19,30,0
    .goto 1415,43.42,53.81,45 >> Travel to Gnomeregan
    .isOnQuest 2962

step
    .dungeon Gnomer
    #season 0,1
    .goto 1415,43.37,53.11,70,0
    .goto 1415,43.10,52.81
    >>Kill |cRXP_ENEMY_Troggs|r and |cRXP_ENEMY_Gnomes|r. Loot them for a |T133215:0|t[|cRXP_LOOT_White Punch Card|r]
    .collect 9279,1,2930,1,1
    >>Kill |cRXP_ENEMY_Techbot|r. Loot him for his |cRXP_LOOT_Memory Core|r
    >>|cRXP_WARN_This quest is completed while OUTSIDE of the dungeon|r
    .complete 2922,1
    .mob Techbot
    .isOnQuest 2922

step
    .dungeon Gnomer
    #season 0,1
    .goto 1415,43.40,53.41,50,0
    .goto 1415,43.13,53.36,50,0
    .goto 1415,43.38,52.94,50,0
    .goto 1415,43.40,53.41
    >>Kill |cRXP_ENEMY_Troggs|r and |cRXP_ENEMY_Gnomes|r. Loot them for a |T133215:0|t[|cRXP_LOOT_White Punch Card|r]
    .collect 9279,1
    >>|cRXP_WARN_This quest is completed while OUTSIDE of the dungeon|r
    .isOnQuest 2930

step
    .dungeon Gnomer
    #season 0,1
    .goto 1415,43.364,52.892,-1
    .goto 1415,43.411,52.898,-1
    .goto 1415,43.402,52.672,-1
    .goto 1415,43.430,52.675,-1
    >>|cRXP_WARN_Use the|r |T133215:0|t[|cRXP_LOOT_White Punch Card|r] |cRXP_WARN_at the|r |cRXP_PICK_Matrix Punchograph 3005-A|r
    >>|cRXP_WARN_This quest is completed while OUTSIDE of the dungeon|r
    .collect 9280,1,2930,1
    .itemcount 9279,1
    .skipgossip
    .isOnQuest 2930

step
    .dungeon Gnomer
    #season 0,1
    .goto 1415,43.17,53.36,40,0
    .goto 1415,42.78,53.81
    .subzone 721,2 >> Enter the Gnomeregan instance portal

step
    .dungeon Gnomer
    #season 0,1
    #completewith Thermaplugg
    >>Kill all |cRXP_ENEMY_Gnomeregan Mobs|r. Loot them for their |cRXP_LOOT_Robo-mechanical Guts|r
    .complete 2928,1
    .isOnQuest 2928

step
    .dungeon Gnomer
    #season 0,1
    >>|cRXP_WARN_Use the|r |T133215:0|t[|cRXP_LOOT_Yellow Punch Card|r] |cRXP_WARN_at the|r |cRXP_PICK_Matrix Punchograph 3005-B|r
    >>The console looking machine is located at the gnomish safe zone at the bottom floor, next to the big circular room where the slimes are located
    .collect 9282,1,2930,1
    .itemcount 9280,1
    .skipgossip
    .isOnQuest 2930

step
    .dungeon Gnomer
    #season 0,1
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kernobee|r
    >>|cRXP_WARN_This will start an escort quest. |cRXP_FRIENDLY_Kernobee|r spawns randomly in The Dormitory, right outside of the gnomish safe zone|r
    .accept 2904 >> Accept A Fine Mess
    .unitscan Kernobee

step
    .dungeon Gnomer
    #season 0,1
    >>Escort |cRXP_FRIENDLY_Kernobee|r back to the start of the dungeon
    .complete 2904,1
    .isOnQuest 2904

step
    .dungeon Gnomer
    #season 0,1
    .use 9364 >>|cRXP_WARN_Use the|r |T132788:0|t[Heavy Leaden Collection Phial] |cRXP_WARN_on a |cRXP_ENEMY_Irradiated Slime|r or|r |cRXP_ENEMY_Irradiated Horror|r
    >>|cRXP_WARN_The |cRXP_ENEMY_Irradiated Slime|r or |cRXP_ENEMY_Irradiated Horror|r must be ALIVE when you use it|r
    >>|cRXP_WARN_Note: You must turn this quest in within 2 hours of acquiring the|r |T136006:0|t[High Potency Radioactive Fallout]
    .complete 2962,1
    .mob Irradiated Slime
    .mob Irradiated Horror
    .isOnQuest 2962

step
    .dungeon Gnomer
    #season 0,1
    #completewith Thermaplugg
    >>Open the |cRXP_PICK_Artificial Extrapolators|r. Loot them for |cRXP_LOOT_Essential Artificials|r
    .complete 2924,1
    .isOnQuest 2924

step
    .dungeon Gnomer
    #season 0,1
    >>|cRXP_WARN_Use the|r |T133215:0|t[|cRXP_LOOT_Blue Punch Card|r] |cRXP_WARN_at the|r |cRXP_PICK_Matrix Punchograph 3005-C|r
    >>The Punchograph is located on the suspended platform right next to the |cRXP_ENEMY_Electrocutioner 6000|r
    .collect 9281,1,2930,1
    .itemcount 9282,1
    .skipgossip
    .isOnQuest 2930
    .unitscan Electrocutioner 6000

step
    .dungeon Gnomer
    #season 0,1
    >>|cRXP_WARN_Use the|r |T133215:0|t[|cRXP_LOOT_Red Punch Card|r] |cRXP_WARN_at the|r |cRXP_PICK_Matrix Punchograph 3005-D|r
    .complete 2930,1
    .itemcount 9281,1
    .skipgossip
    .isOnQuest 2930

step
    .dungeon Gnomer
    #season 0,1
    #label Thermaplugg
    >>Kill |cRXP_ENEMY_Mekgineer Thermaplugg|r
    .complete 2929,1
    .isOnQuest 2929

step
    .dungeon Gnomer
    #season 0,1
    #completewith Finished
    >>Open the |cRXP_PICK_Artificial Extrapolators|r. Loot them for |cRXP_LOOT_Essential Artificials|r
    >>If you still haven't finished this quest, go back to places where you looted them before, since they respawn after a few minutes
    .complete 2924,1
    .isOnQuest 2924

step
    .dungeon Gnomer
    #season 0,1
    #completewith Finished
    >>Kill all |cRXP_ENEMY_Gnomeregan Mobs|r. Loot them for their |cRXP_LOOT_Robo-mechanical Guts|r
    .complete 2928,1
    .isOnQuest 2928

step
    .dungeon Gnomer
    #season 0,1
    >>|cRXP_WARN_Use the|r |T135230:0|t[|cRXP_LOOT_Grime-Encrusted Ring|r] |cRXP_WARN_to start the quest|r
    .accept 2945 >> Accept Grime-Encrusted Ring
    .collect 9326,1,2945
    .itemcount 9326,1
    .use 9326

step
    .dungeon Gnomer
    #season 0,1
    >>|cRXP_WARN_Take the|r |T135230:0|t[|cRXP_LOOT_Grime-Encrusted Ring|r] |cRXP_WARN_to |cRXP_PICK_The Sparklematic 5200|r in The Clean Zone|r
    *You will have to back track to The Clean Zone near the instance entrance, make sure your teamates are there to help you on your trip back
    .turnin 2945 >> Turn in Grime-Encrusted Ring
    .itemcount 9326,1

step
    .dungeon Gnomer
    #season 0,1
    >>Click the |cRXP_PICK_The Sparklematic 5200|r one more time
    .accept 2947 >> Accept Return of the Ring
    .isQuestTurnedIn 2945

step
    .dungeon Gnomer
    #season 0,1
    .hs >> Hearth to Kharanos
    .zoneskip Dun Morogh
    .zoneskip Ironforge
    .dungeon Gnomer
    #season 0,1
    .goto 1426/0,-463.66,-5474.00,10,0
    .goto 1426/0,-457.85,-5498.29
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ozzie Togglevolt|r
    .turnin 2962 >> Turn in The Only Cure is More Green Glow
    .target Ozzie Togglevolt
    .isQuestComplete 2962

step
    .dungeon Gnomer
    #season 0,1
    #completewith next
    .goto 1426/0,-541.23,-5242.29,40,0
    .goto 1426/0,-669.77,-5216.35,20,0
    .goto Ironforge,14.90,87.10,40,0
    .zone Ironforge >> Travel to Ironforge

step
    .dungeon Gnomer
    #season 0,1
    .goto Ironforge,36.0,4.0
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Talvash del Kissel|r
    .turnin 2947 >> Turn in Return of the Ring
    .accept 2948 >> Accept Gnome Improvement
    .target Talvash del Kissel
    .isOnQuest 2947

step
    .dungeon Gnomer
    #season 0,1
    .goto Ironforge,36.0,4.0
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Talvash del Kissel|r
    >>|cRXP_WARN_If you are able to obtain a|r |T133215:0|t[Silver Bar] |cRXP_WARN_and a|r |T134105:0|t[Moss Agate] |cRXP_WARN_finish this quest. If not, abandon it|r
    .collect 2842,1,2948,1
    .collect 1206,1
    .turnin 2948,2948,1 >> Turn in Gnome Improvement
    .target Talvash del Kissel
    .isOnQuest 2948

step
    .dungeon Gnomer
    #season 0,1
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Tinkmaster Overspark|r, |cRXP_FRIENDLY_High Tinker Mekkatorque|r, |cRXP_FRIENDLY_Master Mechanic Castpipe|r and |cRXP_FRIENDLY_Klockmort Spannerspan|r
    .turnin -2922,1 >> Turn in Save Techbot's Brain!
    .target +Tinkmaster Overspark
    .goto Ironforge,69.540,50.325
    .turnin -2929,1 >> Turn in The Grand Betrayal
    .target +High Tinker Mekkatorque
    .goto 1455/0,-1257.09,-4827.60
    .turnin -2930,1 >> Turn in Data Rescue
    .target +Master Mechanic Castpipe
    .goto 1455/0,-1265.63,-4823.02
    .turnin -2924,1 >> Turn in Essential Artificials
    .target +Klockmort Spannerspan
    .goto 1455/0,-1250.62,-4812.47

step
    .dungeon Gnomer
    #season 0,1
    .abandon 2948 >> Abandon Gnome Improvement

step
    #ah
    .goto Ironforge,25.800,75.500,-1
    .goto Ironforge,24.200,74.600,-1
    .goto Ironforge,23.800,71.800,-1
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to an |cRXP_FRIENDLY_Ironforge Auctioneer|r
    >>|cRXP_BUY_Buy a|r |T133759:0|t[Hillman's Cloak] |cRXP_WARN_and a|r |T132913:0|t[Bolt of Woolen Cloth] |cRXP_BUY_to complete an optional quest coming up in Hillsbrad Foothills|r
    >>|cRXP_BUY_Buy 4|r |T134577:0|t[Lesser Bloodstone Ore] |cRXP_BUY_to complete an optional quest coming up in Stranglethorn Vale|r
    >>|cRXP_WARN_You may also craft the|r |T133759:0|t[Hillman's Cloak] |cRXP_WARN_with Leatherworking|r
    >>|cRXP_WARN_Skip this step if you cannot acquire them|r
    .collect 3719,1,565,1
    .collect 2997,1,565,1
    .collect 4278,4,627,1
    .target Auctioneer Lympkin
    .target Auctioneer Redmuse
    .target Auctioneer Buckler
    .skill leatherworking,<150,1

step
    #ah
    .goto Ironforge,25.800,75.500,-1
    .goto Ironforge,24.200,74.600,-1
    .goto Ironforge,23.800,71.800,-1
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to an |cRXP_FRIENDLY_Ironforge Auctioneer|r
    >>|cRXP_BUY_Buy a|r |T133759:0|t[Hillman's Cloak] |cRXP_WARN_and a|r |T132913:0|t[Bolt of Woolen Cloth] |cRXP_BUY_to complete an optional quest coming up in Hillsbrad Foothills|r
    >>|cRXP_BUY_Buy 4|r |T134577:0|t[Lesser Bloodstone Ore] |cRXP_BUY_to complete an optional quest coming up in Stranglethorn Vale|r
    >>|cRXP_WARN_Skip this step if you cannot acquire them|r
    .collect 3719,1,565,1
    .collect 2997,1,565,1
    .collect 4278,4,627,1
    .target Auctioneer Lympkin
    .target Auctioneer Redmuse
    .target Auctioneer Buckler
    .skill leatherworking,150,1

step
    #label end
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gryth Thurden|r
    .goto Ironforge,55.50,47.70
    .fly Wetlands>> Fly to Wetlands
    .target Gryth Thurden
    .zoneskip Wetlands
]])
