-- Generated by Scripts/split_guide_vault.py; rerun the script to update.
if not RXPGuides or type(RXPGuides.RegisterGuide) ~= "function" then return end
local _, rxpGuideVaultAddon = ...
local rxpGuideVaultGame = rxpGuideVaultAddon and rxpGuideVaultAddon.game
if not rxpGuideVaultGame then
    local rxpGuideVaultVersion = select(4, GetBuildInfo())
    if rxpGuideVaultVersion > 60000 then
        rxpGuideVaultGame = "RETAIL"
    elseif rxpGuideVaultVersion > 50000 then
        rxpGuideVaultGame = "MOP"
    elseif rxpGuideVaultVersion > 40000 then
        rxpGuideVaultGame = "CATA"
    elseif rxpGuideVaultVersion > 30000 then
        rxpGuideVaultGame = "WOTLK"
    elseif rxpGuideVaultVersion > 20000 then
        rxpGuideVaultGame = "TBC"
    elseif rxpGuideVaultVersion >= 16000 and rxpGuideVaultVersion < 20000 then
        rxpGuideVaultGame = "FOREVER"
    else
        rxpGuideVaultGame = "CLASSIC"
    end
end
if rxpGuideVaultGame ~= "FOREVER" then return end

RXPGuides.RegisterGuide([[#forever
#version 23
#group RestedXP Forever Guide (A)
#subgroup Speedrun Guide 20-30

<< Alliance !Hunter
#name 23-24 Wetlands
#next 24-27 Duskwood/Redridge

step << Mage/Warlock/Paladin
    #completewith next
    .goto Wetlands,9.490,59.693
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Shellei Brondir|r
    .fly Ironforge >> Fly to Ironforge
    .target Shellei Brondir

step << Mage/Warlock/Paladin
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Brandur Ironhammer|r << Paladin
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Briarthorn|r << Warlock
    .goto 1455/0,-896.55,-4601.68 << Paladin
    .goto 1455/0,-1117.60,-4615.14,15,0 << Warlock
    .goto 1455/0,-1111.62,-4599.09 << Warlock
    .trainer >> Train your class spells
    .target Brandur Ironhammer << Paladin
    .target Briarthorn << Warlock

step << Warlock
    .goto 1455/0,-1134.20,-4610.39,15,0
    .goto 1455/0,-1130.26,-4601.270
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Jubahl Corpseseeker|r
    .vendor >> |cRXP_BUY_Buy|r |T133738:0|t[Grimoires] |cRXP_BUY_for your pets|r
    .target Jubahl Corpseseeker

step << Mage/Warlock/Paladin
    .goto 1455/0,-1152.47,-4821.17
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gryth Thurden|r
    .fly Wetlands>> Fly to Wetlands
    .target Gryth Thurden
    .zoneskip Wetlands

step
    .goto 1437/0,-741.47,-3683.07
    .target James Halloran
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_James Halloran|r
    .accept 484 >> Accept Young Crocolisk Skins

step
    #optional
    .goto 1437/0,-741.47,-3683.07
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_James Halloran|r
    .turnin 484 >> Turn in Young Crocolisk Skins
    .isQuestComplete 484

step
    .goto 1437/0,-718.35,-3701.89
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Dewin Shimmerdawn|r
    .vendor >> |cRXP_BUY_Buy as many|r |T134831:0|t[Healing Potions] |cRXP_BUY_that are available|r
    >>|cRXP_WARN_This is a limited supply item. Skip this step if |cRXP_FRIENDLY_Dewin Shimmerdawn|r doesn't have any|r
    .target Dewin Shimmerdawn

step
    .goto 1437/0,-735.26,-3761.04
    .target Karl Boran
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Karl Boran|r
    .accept 279 >> Accept Claws from the Deep

step
    .goto 1437/0,-839.93,-3792.30
    .target First Mate Fitzsimmons
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_First Mate Fitzsimmons|r
    .accept 288 >> Accept The Third Fleet
    .accept 463 >> Accept The Greenwarden

step
    #completewith menethilend
    .goto 1437/0,-831.66,-3827.85
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Innkeeper Helbrek|r
    .target Innkeeper Helbrek
    .home >> Set your Hearthstone to Menethil Harbor

step
    .goto 1437/0,-831.66,-3827.85
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Innkeeper Helbrek|r
    >>|cRXP_BUY_Buy a|r |T132792:0|t[Flagon of Dwarven Honeymead]
    .target Innkeeper Helbrek
    .complete 288,1

step
    #completewith next
    .goto 1437/0,-818.34,-3829.67,8 >> Travel upstairs towards |cRXP_FRIENDLY_Archaeologist Flagongut|r

step
    .goto 1437/0,-837.99,-3813.66
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Archaeologist Flagongut|r upstairs
    .target Archaeologist Flagongut
    .turnin 942 >> Turn in The Absent Minded Prospector
    .isOnQuest 942

step
    .goto 1437/0,-823.64,-3807.21
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Samor Festivus|r upstairs
    .vendor >> |cRXP_BUY_Buy as many|r |T134831:0|t[Healing Potions] |cRXP_BUY_that are available|r
    >>|cRXP_WARN_This is a limited supply item. Skip this step if |cRXP_FRIENDLY_Samor Festivus|r doesn't have any|r
    .target Samor Festivus

step
    .goto 1437/0,-839.93,-3792.30
    .target First Mate Fitzsimmons
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_First Mate Fitzsimmons|r
    .turnin 288 >> Turn in The Third Fleet

step
    .goto Wetlands,11.80,57.99
    .target Sida
    >>Talk to |cRXP_FRIENDLY_Sida|r
    .accept 470 >>Accept Digging Through the Ooze

step
    #label menethilend
    .goto 1437/0,-819.67,-3691.42,25,0
    .goto 1437/0,-807.26,-3716.22,25,0
    .goto 1437/0,-827.94,-3724.49,25,0
    .goto 1437/0,-834.60,-3711.73
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Neal Allen|r
    .vendor >> |cRXP_BUY_Buy a|r |T133024:0|t[Bronze Tube]
    >>|cRXP_WARN_This is a limited supply item. Skip this step if |cRXP_FRIENDLY_Neal Allen|r doesn't have one|r

    .target Neal Allen
    .bronzetube

step
    #completewith crocs
    >>Kill |cRXP_ENEMY_Young Wetlands Crocolisks|r. Loot them for their |cRXP_LOOT_Young Crocolisk Skin|r
    .complete 484,1
    .mob Young Wetlands Crocolisk

step
    .goto 1437/0,-1136.44,-3245.73,50,0
    .goto 1437/0,-957.38,-3233.33,50,0
    .goto 1437/0,-1136.44,-3245.73,50,0
    .goto 1437/0,-1062.00,-3234.15
    >>Kill |cRXP_ENEMY_Bluegill Murlocs|r
    >>Kill |cRXP_ENEMY_Gobbler|r. Loot him for his |cRXP_LOOT_Head|r
    >>|cRXP_ENEMY_Gobbler|r |cRXP_WARN_patrols the Marshlands slightly|r
    .complete 279,1
    .complete 279,2
    .mob Bluegill Murloc
    .unitscan Gobbler

step
    .goto Wetlands,26.40,25.76
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Fradd Swiftgear|r
    .vendor >> |cRXP_BUY_Buy a|r |T133024:0|t[Bronze Tube]
    >>|cRXP_WARN_This is a limited supply item. Skip this step if |cRXP_FRIENDLY_Fradd Swiftgear|r doesn't have one|r

    .target Fradd Swiftgear
    .bronzetube

step
    .goto 1437/0,-2453.82,-3233.00
    .target Einar Stonegrip
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Einar Stonegrip|r
    .accept 469 >> Accept Daily Delivery

step
    #completewith next
    .goto Wetlands,50.200,37.734
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kixxle|r
    .vendor >> |cRXP_BUY_Buy as many|r |T134831:0|t[Healing Potions] |cRXP_BUY_that are available|r
    >>|cRXP_WARN_Buy|r |T134413:0|t[Liferoot] |cRXP_WARN_if |cRXP_FRIENDLY_Kixxle|r has any in stock. You need them for the|r |T132403:0|t[|cFF0070FFWhirlwind Axe|r] |cRXP_WARN_quest later|r << Warrior
    >>|cRXP_WARN_If you are planning on running Scarlet Monastery for the|r [|cFF0070FFBonebiter|r]|cRXP_WARN_, you may skip this step|r << Warrior
    >>|cRXP_WARN_These are limited supply items. Skip this step if |cRXP_FRIENDLY_Kixxle|r doesn't have any|r << Warrior
    >>|cRXP_WARN_This is a limited supply item. Skip this step if |cRXP_FRIENDLY_Kixxle|r doesn't have any|r << !Warrior
    .target Kixxle

step
    .goto 1437/0,-2720.72,-3261.440
    .target Rethiel the Greenwarden
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Rethiel the Greenwarden|r
    .turnin 463 >> Turn in The Greenwarden

step
    .goto 1437/0,-2720.72,-3261.440
    .target Rethiel the Greenwarden
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Rethiel the Greenwarden|r
    .accept 276 >> Accept Tramping Paws
    .maxlevel 24,crocs

step
    .goto 1437/0,-3033.36,-3899.24,60,0
    .goto 1437/0,-2967.60,-4059.10,60,0
    .goto 1437/0,-2936.17,-4161.91,60,0
    .goto 1437/0,-2967.60,-4059.10
    >>Kill |cRXP_ENEMY_Mosshide Gnolls|r and |cRXP_ENEMY_Mosshide Mongrels|r
    >>|cRXP_WARN_This is a great place to farm|r |T132911:0|t[Wool Cloth] |cRXP_WARN_to level up your|r |T135966:0|t[First Aid] |cRXP_WARN_or any other profession that may require it|r
    .complete 276,1
    .mob +Mosshide Gnoll
    .complete 276,2
    .mob +Mosshide Mongrel
    .isOnQuest 276

step
    #completewith next
    .goto 1437/0,-3033.36,-3899.24,60,0
    .goto 1437/0,-2967.60,-4059.10,60,0
    .goto 1437/0,-2936.17,-4161.91,60,0
    .goto 1437/0,-3033.36,-3899.24,60,0
    .goto 1437/0,-2967.60,-4059.10,60,0
    .goto 1437/0,-2936.17,-4161.91,60,0
    .goto 1437/0,-3033.36,-3899.24,60,0
    .goto 1437/0,-2967.60,-4059.10,60,0
    .goto 1437/0,-2936.17,-4161.91,60,0
    .goto 1437/0,-3033.36,-3899.24,60,0
    .goto 1437/0,-2967.60,-4059.10,60,0
    .goto 1437/0,-2936.17,-4161.91,60,0
    .goto 1437/0,-3033.36,-3899.24,60,0
    .goto 1437/0,-2967.60,-4059.10,60,0
    .goto 1437/0,-2936.17,-4161.91,60,0
    .goto 1437/0,-3033.36,-3899.24,60,0
    .goto 1437/0,-2967.60,-4059.10,60,0
    .goto 1437/0,-2936.17,-4161.91,60,0
    .goto 1437/0,-3033.36,-3899.24,60,0
    .goto 1437/0,-2967.60,-4059.10,60,0
    .goto 1437/0,-2936.17,-4161.91,60,0
    .goto 1437/0,-3033.36,-3899.24,60,0
    .goto 1437/0,-2967.60,-4059.10,60,0
    .goto 1437/0,-2936.17,-4161.91,60,0
    .goto 1437/0,-3033.36,-3899.24,60,0
    .goto 1437/0,-2967.60,-4059.10,60,0
    .goto 1437/0,-2936.17,-4161.91,60,0
    .goto 1437/0,-3033.36,-3899.24,60,0
    .goto 1437/0,-2967.60,-4059.10,60,0
    .goto 1437/0,-2936.17,-4161.91,60,0
    .goto 1437/0,-2967.60,-4059.10
    +Keep grinding |cRXP_ENEMY_Gnolls|r until your hearth has <2 minutes left
    .cooldown item,6948,<120
    .mob Mosshide Gnoll
    .mob Mosshide Mongrel
    .dungeon !SFK

step
    #label crocs
    .goto 1437/0,-2720.72,-3261.440
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Rethiel the Greenwarden|r
    .target Rethiel the Greenwarden
    .turnin 276 >> Turn in Tramping Paws
    .isQuestComplete 276

step
    .goto 1437/0,-2720.72,-3261.440
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Rethiel the Greenwarden|r
    .target Rethiel the Greenwarden
    .accept 277 >> Accept Fire Taboo
    .isQuestTurnedIn 276

step
    .goto 1437/0,-2589.63,-3286.25,55,0
    .goto 1437/0,-2808.80,-3548.09,55,0
    .goto 1437/0,-2957.68,-3840.25,55,0
    .goto Wetlands,64.0,72.2
    >>Kill |cRXP_ENEMY_Young Wetlands Crocolisks|r. Loot them for their |cRXP_LOOT_Young Crocolisk Skin|r
    .complete 484,1
    .mob Young Wetlands Crocolisk

step
    .dungeon SFK
    #completewith next
    .goto 1437/0,-1663.29,-3002.35,0
    .goto 1437/0,-1952.77,-2963.77,0
    .goto Wetlands,43.0,33.2,0
    .zone Arathi Highlands >> Grind |cRXP_ENEMY_Mosshides Gnolls|r while looking for a group for Shadowfang Keep

step
    .dungeon SFK
    .goto 1417/0,-2415.03,-1453.330,90,0
    .goto 1417/0,-1782.87,-1260.13,90,0
    .goto 1417/0,-1633.11,-859.09,70,0
    .goto 1424/0,-512.15,-715.14
    >>There are no quests for Shadowfang Keep. You will have to run from Wetlands to Silverpine Forest. Ensure you stay on the road while running through Arathi Highlands, and watchout for the |cRXP_ENEMY_Forsaken Courier|r
    >>|cRXP_WARN_You don't need to get the Arathi Highlands flight path yet|r
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Darla Harris|r
    .fp Southshore >> Get the Southshore Flight Path
    .target Cedrik Prose
    .target Darla Harris
    .unitscan Forsaken Courier

step
    .dungeon SFK
    .goto 1424/0,594.03,-596.69,0
    .goto 1421/0,1561.68,-235.09,0
    .goto 1424/0,594.03,-596.69,100,0
    .goto 1421/0,1468.02,-287.17,100,0
    .goto 1421/0,1572.10,-230.87
    .subzone 209,2 >> Enter Shadowfang Keep

step
    +There are no quests for Shadowfang Keep
    >>Clear Shadowfang Keep. Leave when you are finished
    .zoneskip 209,1
    .dungeon SFK

step
    .goto 1437/0,-3032.11,-4314.33
    .hs >> Hearth to Menethil Harbor
    >>|cRXP_BUY_Buy food/water if needed|r << !Warrior !Rogue
    >>|cRXP_BUY_Buy food if needed|r << Warrior/Rogue
    .subzoneskip 150
    .subzoneskip 2103
    .subzoneskip 2104
    .zoneskip Loch Modan
    .dungeon SFK

step
    .goto 1437/0,-2949.82,-4113.67,-1
    .goto 1437/0,-1161.67,-3241.87,-1
    .xp 24 >> Grind to level 24

step
    #completewith next
    .hs >> Hearth to Menethil Harbor
    >>|cRXP_BUY_Buy food/water if needed|r << !Warrior !Rogue
    >>|cRXP_BUY_Buy food if needed|r << Warrior/Rogue
    .cooldown item,6948,>0,1
    .dungeon !SFK

step
    .goto 1437/0,-735.26,-3761.04
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Karl Boran|r
    .turnin 279 >> Turn in Claws from the Deep
    .target Karl Boran
    .zoneskip Loch Modan

step
    .goto 1437/0,-741.47,-3683.07
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_James Halloran|r
    .turnin 469 >> Turn in Daily Delivery
    .turnin 484 >> Turn in Young Crocolisk Skins

    .target James Halloran
    .zoneskip Loch Modan

step
    .goto Wetlands,9.490,59.693,-1
    .goto 1432/0,-2929.87,-5424.84,-1
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Shellei Brondir|r
    .fly Ironforge >> Fly to Ironforge
    .target Shellei Brondir
    .target Thorgrum Borrelson

step
    #optional
    #sticky
    #label Powers
    >>|cRXP_WARN_Use the |T133743:0|t[|cRXP_LOOT_Book: The Powers Below|r] to start the quest|r
    .accept 968 >> Accept The Powers Below
    .use 5352
    .itemcount 5352,1

step
    #ssf
    >>Gather 4 |T134850:0|t[Minor Mana Potions] and 2 |T134822:0|t[Elixir of Minor Fortitudes]
    >>|cRXP_WARN_Use your|r |T136240:0|t[Alchemy] |cRXP_WARN_profession to craft them if possible|r
    >>|cRXP_WARN_If you are unable to acquire them, skip this step|r
    .collect 2455,4,1073,1
    .collect 2458,2,1073,1
    .skill alchemy,<1,1
    .isOnQuest 1072

step
    #ah
    .goto 1455/0,-910.77,-4957.87,0
    >>Gather 4 |T134850:0|t[Minor Mana Potions] and 2 |T134822:0|t[Elixir of Minor Fortitudes]
    >>|cRXP_WARN_You can buy these from the Auction House or trade players for them|r
    >>|cRXP_WARN_If you are unable to acquire them, skip this step|r
    .collect 2455,4,1073,1
    .collect 2458,2,1073,1
    .isOnQuest 1072

step << Warrior
    .goto 1455/0,-1197.27,-5041.49
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Buliwyf Stonehand|r inside
    .train 197 >> Train 2h Axes
    .target Buliwyf Stonehand

step << !Druid
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Bilban Tosslespanner|r << Warrior
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Brandur Ironhammer|r << Paladin
    .goto 1455/0,-1234.65,-5035.67 << Warrior
    .goto 1455/0,-896.55,-4601.68 << Paladin
    .trainer >> Train your class spells
    .target Bilban Tosslespanner << Warrior
    .target Brandur Ironhammer << Paladin

step
    #requires Powers
    .goto 1455/0,-1115.43,-4598.86
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gerrig Bonegrip|r
    .turnin 968 >> Turn in The Powers Below
    .target Gerrig Bonegrip
    .isOnQuest 968

step
    .goto 1455/0,-1249.98,-4793.47
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gearcutter Cogspinner|r
    .vendor >> |cRXP_BUY_Buy a|r |T133024:0|t[Bronze Tube]
    >>|cRXP_WARN_This is a limited supply item. Skip this step if |cRXP_FRIENDLY_Gearcutter Cogspinner|r doesn't have one|r

    .target Gearcutter Cogspinner
    .bronzetube

step
    .goto 1455/0,-1283.47,-4842.91
    .target Lomac Gearstrip
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Lomac Gearstrip|r
    .turnin 1072 >> Turn in An Old Colleague
    .isOnQuest 1072

step
    .isQuestTurnedIn 1072
    .goto 1455/0,-1283.47,-4842.91
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Lomac Gearstrip|r
    .accept 1073 >> Accept Ineptitude + Chemicals = Fun
    .turnin 1073 >> Turn in Ineptitude + Chemicals = Fun
    .itemcount 2455,4
    .itemcount 2458,2
    .target Lomac Gearstrip

step
    .goto 1455/0,-1319.29,-4839.80,10,0
    .zone Stormwind City >> Take the tram to Stormwind
]])
