-- Generated by Scripts/split_guide_vault.py; rerun the script to update.
if not RXPGuides or type(RXPGuides.RegisterGuide) ~= "function" then return end
local _, rxpGuideVaultAddon = ...
local rxpGuideVaultGame = rxpGuideVaultAddon and rxpGuideVaultAddon.game
if not rxpGuideVaultGame then
    local rxpGuideVaultVersion = select(4, GetBuildInfo())
    if rxpGuideVaultVersion > 60000 then
        rxpGuideVaultGame = "RETAIL"
    elseif rxpGuideVaultVersion > 50000 then
        rxpGuideVaultGame = "MOP"
    elseif rxpGuideVaultVersion > 40000 then
        rxpGuideVaultGame = "CATA"
    elseif rxpGuideVaultVersion > 30000 then
        rxpGuideVaultGame = "WOTLK"
    elseif rxpGuideVaultVersion > 20000 then
        rxpGuideVaultGame = "TBC"
    elseif rxpGuideVaultVersion >= 16000 and rxpGuideVaultVersion < 20000 then
        rxpGuideVaultGame = "FOREVER"
    else
        rxpGuideVaultGame = "CLASSIC"
    end
end
if rxpGuideVaultGame ~= "FOREVER" then return end

RXPGuides.RegisterGuide([[#forever
#version 23
#group RestedXP Forever Guide (A)
#subgroup Speedrun Guide 20-30

<< Alliance !Hunter
#name 21-23 Stonetalon/Ashenvale
#next 23-24 Wetlands

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Pelturas Whitemoon|r
    .target Pelturas Whitemoon
    .goto 1440/1,-454.43,2682.24
    .accept 1033 >> Accept Elune's Tear

step
    .goto 1440/1,-974.00,2890.19
    >>Loot |cRXP_LOOT_Elune's Tear|r on the ground
    .complete 1033,1

step
    .goto 1440/1,-454.43,2682.24
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Pelturas Whitemoon|r
    .target Pelturas Whitemoon
    .turnin 1033 >> Turn in Elune's Tear
    .timer 17,Elune's Tear RP
    .accept 1034 >> Accept The Ruins of Stardust

step
    .goto Ashenvale,33.30,67.79
    >>Loot the |cRXP_PICK_Stardust Covered Bushes|r for the |cRXP_LOOT_Handful of Stardust|r
    >>|cRXP_WARN_Their spawn locations are scattered throughout the island|r
    .complete 1034,1

step
    #completewith mountainskip
    .goto 1440/1,-126.30,2203.69,15 >> Head to the base of the mountain
    .goto 1440/1,-99.78,2305.170,15 >>Run straight north while climbing the mountain
    .subzoneskip 418,1

step
    #completewith next
    .goto Ashenvale,27.50,60.76,8 >> Climb the hill next to the big tree to the right of the Fire Scar Shrine entrance
    >>Jump over the tree root and hug the right to avoid aggroing mobs

step
    .goto 1440/1,242.76,2340.53
    >>Kill |cRXP_ENEMY_Ilkrud Magthrull|r. Loot him for his |cRXP_LOOT_Tome|r
    >>|cRXP_ENEMY_Ilkrud Magthrull|r |cRXP_WARN_will cast|r |T136221:0|t[Ilkrud's Guardians] |cRXP_WARN_which is a 5 second long cast and will summon 2 Voidwalkers. Stop this cast if you're able to|r
    >>|cRXP_WARN_Clear an exit path if needed so you can reset them along with the |cRXP_ENEMY_Succubus|r if needed. You may skip this if it's too difficult and do it in the later Ashenvale section|r
    .complete 973,1
    .mob Ilkrud Magthrull

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Therysil|r
    .target Therysil
    .goto 1440/1,394.43,2677.63
    .turnin 945 >> Turn in Therylune's Escape
    .isQuestComplete 945

step
    .goto 1440/1,189.71,3185.77
    .target Delgren the Purifier
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Delgren the Purifier|r
    .turnin 973 >> Turn in The Tower of Althalaxx
    .isQuestComplete 973

step
    #label mountainskip
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Talen|r
    .target Talen
    .goto 1440/1,847.11,3470.21
    .accept 1007 >> Accept The Ancient Statuette

step
    #completewith nagas
    >>Kill |cRXP_ENEMY_Wrathtail Nagas|r. Loot them for their |cRXP_LOOT_Heads|r
    >>|cRXP_WARN_Don't go out of your way to complete this yet|r
    .mob Wrathtail Wave Rider
    .mob Wrathtail Sorceress
    .complete 1008,1

step
    .goto Ashenvale,14.20,20.64
    >>Loot the |cRXP_LOOT_Ancient Statuette|r on the ground
    .complete 1007,1

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Talen|r
    .target Talen
    .goto 1440/1,847.11,3470.21
    .turnin 1007 >> Turn in The Ancient Statuette
    .timer 22,The Ancient Statuette RP
    .accept 1009 >> Accept Ruuzel

step
    #optional
    .goto 1440/1,1323.55,4159.35
    >>Kill |cRXP_ENEMY_Ruuzel|r. Loot her for the |cRXP_LOOT_Ring of Zoram|r
    >>|cRXP_ENEMY_Ruuzel|r |cRXP_WARN_patrols the island with a |cRXP_ENEMY_Wrathtail Myrmidon|r and |cRXP_ENEMY_Wrathtail Sea Witch|r. Kill one of them and then reset them if needed|r
    >>|cRXP_WARN_If you have any|r |T133717:0|t[Bombs]|cRXP_WARN_/|r[Grenades] |cRXP_WARN_you can also use them to split pull|r |cRXP_ENEMY_Ruuzel|r
    >>|cRXP_WARN_You can also use|r |T136186:0|t[Rain of Fire] |cRXP_WARN_to split pull|r |cRXP_ENEMY_Ruuzel|r << Warlock
    >>|cRXP_ENEMY_Lady Vespia|r |cRXP_WARN_is a rarespawn that can also drop the |cRXP_LOOT_Ring of Zoram|r if you see her|r
    .link https://www.youtube.com/watch?v=H-IwZ6P-ldY >> |cRXP_WARN_Click here for video reference on "Split pulling"|r
    .unitscan Lady Vespia
    .mob Ruuzel
    .complete 1009,1
    .skill engineering,<1,1

step
    #label nagas
    .goto 1440/1,1323.55,4159.35
    >>Kill |cRXP_ENEMY_Ruuzel|r. Loot her for the |cRXP_LOOT_Ring of Zoram|r
    >>|cRXP_ENEMY_Ruuzel|r |cRXP_WARN_patrols the island with a |cRXP_ENEMY_Wrathtail Myrmidon|r and |cRXP_ENEMY_Wrathtail Sea Witch|r. Kill one of them and then reset them if needed|r
    >>|cRXP_ENEMY_Lady Vespia|r |cRXP_WARN_is a rarespawn that can also drop the |cRXP_LOOT_Ring of Zoram|r if you see her|r
    >>|cRXP_WARN_You can also use|r |T136186:0|t[Rain of Fire] |cRXP_WARN_to split pull|r |cRXP_ENEMY_Ruuzel|r << Warlock
    .link https://www.youtube.com/watch?v=H-IwZ6P-ldY >> |cRXP_WARN_Click here for video reference on "Split pulling"|r << Mage/Warlock
    .unitscan Lady Vespia
    .mob Ruuzel
    .complete 1009,1

step
    .goto Ashenvale,7.00,15.20,0
    .goto 1440/1,866.14,4013.71,0
    .goto 1440/1,843.07,3863.42,0
    .goto 1440/1,942.84,3710.83,0
    .goto 1440/1,1072.01,3518.64,0
    .goto Ashenvale,7.00,15.20,70,0
    .goto 1440/1,866.14,4013.71,70,0
    .goto 1440/1,843.07,3863.42,70,0
    .goto 1440/1,942.84,3710.83,70,0
    .goto 1440/1,1072.01,3518.64,70,0
    .goto 1440/1,942.84,3710.83,70,0
    .goto 1440/1,843.07,3863.42,70,0
    .goto 1440/1,866.14,4013.71,70,0
    >>Kill |cRXP_ENEMY_Wrathtail Nagas|r. Loot them for their |cRXP_LOOT_Heads|r
    .mob Wrathtail Wave Rider
    .mob Wrathtail Sorceress
    .mob Wrathtail Myrmidon
    .mob Wrathtail Priestess
    .mob Wrathtail Razortail
    .mob Wrathtail Sea Witch
    .complete 1008,1

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Talen|r
    .target Talen
    .goto 1440/1,847.11,3470.21
    .turnin 1009 >> Turn in Ruuzel

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Teronis' Corpse|r
    .target Teronis' Corpse
    .goto 1440/1,528.79,3045.86
    .turnin 991 >> Turn in Raene's Cleansing
    .accept 1023 >> Accept Raene's Cleansing

step
    .goto 1440/1,523.02,2988.59,50,0
    .goto 1440/1,579.54,3055.08,50,0
    .goto 1440/1,488.42,3073.53,50,0
    .goto 1440/1,528.79,3045.86
    >>Kill |cRXP_ENEMY_Saltspittle Murlocs|r. Loot them for the |cRXP_LOOT_Glowing Gem|r
    .mob Saltspittle Warrior
    .mob Saltspittle Muckdweller
    .mob Saltspittle Oracle
    .mob Saltspittle Puddlejumper
    .complete 1023,1

step << !Warlock
    #completewith next
    .deathskip >> Die at the east side of the lake and respawn at the Spirit Healer
    .target Spirit Healer

step << !Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Pelturas Whitemoon|r
    .target Pelturas Whitemoon
    .goto 1440/1,-454.43,2682.24
    .turnin 1034 >> Turn in The Ruins of Stardust

step << !Warlock
    .goto 1440/1,-433.09,2781.02
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Innkeeper Kimlya|r
    .home 415>> Set your Hearthstone to Astranaar
    .target Innkeeper Kimlya

step << !Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Raene Wolfrunner|r
    .target Raene Wolfrunner
    .goto 1440/1,-411.18,2767.19
    .turnin 1023 >> Turn in Raene's Cleansing
    .accept 1025 >> Accept An Aggressive Defense

step << !Warlock
    #completewith next
    #label Journal
    .destroy 5505 >> Destroy |T133741:0|t[Teronis' Journal]. You no longer need it

step << !Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Shindrell Swiftfire|r
    .target Shindrell Swiftfire
    .goto 1440/1,-299.30,2796.01
    .turnin 1008 >> Turn in The Zoram Strand

step << !Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Shindrell Swiftfire|r
    .target Shindrell Swiftfire
    .goto 1440/1,-299.30,2796.01
    .accept 1134 >> Accept Pridewings of Stonetalon

step << !Warlock
    #completewith AbsentMinded
    .goto 1440/1,-284.31,2828.30
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Daelyshia|r
    .fly Auberdine >> Fly to Darkshore
    .target Daelyshia

step << !Warlock
    #requires Journal
    .goto 1439/1,543.06,6342.57
    .target Gwennyth Bly'Leggonde
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gwennyth Bly'Leggonde|r
    .turnin -4730 >> Turn in Beached Sea Creature
    .turnin -4731 >> Turn in Beached Sea Turtle
    .turnin -4732 >> Turn in Beached Sea Turtle
    .turnin -4733 >> Turn in Beached Sea Creature

step << !Warlock
    #map Darkshore
    .goto Felwood,18.50,19.87
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gubber Blump|r
    .turnin 1138 >> Turn in Fruit of the Sea
    .isQuestComplete 1138
    .target Gubber Blump

step << !Warlock
    .goto Darkshore,37.70,43.39
    .target Sentinel Glynda Nal'Shea
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sentinel Glynda Nal'Shea|r
    .turnin 4740 >> Turn in WANTED: Murkdeep!
    .isQuestComplete 4740

step << !Warlock
    .goto 1439/1,362.93,6434.71
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Terenthis|r
    .turnin 995 >> Turn in Escape Through Stealth
    .target Terenthis
    .isQuestComplete 995

step << !Warlock
    .goto 1439,38.325,43.039
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gershala Nightwhisper|r
    .turnin 3765 >> Turn in The Corruption Abroad
    .target Gershala Nightwhisper
    .isOnQuest 3765

step << !Warlock
    #label AbsentMinded
    .goto 1439/1,489.35,6506.76
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Archaeologist Hollee|r
    .turnin 731 >> Turn in The Absent Minded Prospector
    .target Archaeologist Hollee
    .accept 741 >> Accept The Absent Minded Prospector
    .isQuestComplete 731

step << !Warlock
    #optional
    .goto 1439/1,489.35,6506.76
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Archaeologist Hollee|r
    .target Archaeologist Hollee
    .accept 741 >> Accept The Absent Minded Prospector

step << !Warlock !NightElf
    #completewith next
    .goto 1439/1,796.54,6490.16,60 >> Travel to the Auberdine Docks. Wait for the Rut'theran Village boat

step << !Warlock !NightElf
    .goto 1439/1,769.16,6577.500
    .zone Teldrassil >> Take the boat to Rut'theran Village
    .zoneskip Darnassus

step << !Warlock !NightElf
    .goto 1438/1,841.56,8640.79
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Vesprystus|r
    .fp Teldrassil >> Get the Rut'theran Village Flight Path
    .target Vesprystus

step << !Warlock
    #completewith next
    .goto 1438/1,968.90,8795.34
    .zone Darnassus >> Take the purple portal into Darnassus

step << Warrior
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Arias'ta Bladesinger|r
    .goto 1457/1,2316.91,9991.88
    .trainer >> Train your class spells
    .target Arias'ta Bladesinger

step << !Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Chief Archaeologist Greywhisker|r
    .target Chief Archaeologist Greywhisker
    .goto Teldrassil,23.70,64.51
    .turnin 741 >> Turn in The Absent Minded Prospector
    .accept 942 >> Accept The Absent Minded Prospector
    .isOnQuest 741

step << !Warlock
    #optional
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Chief Archaeologist Greywhisker|r
    .target Chief Archaeologist Greywhisker
    .goto Teldrassil,23.70,64.51
    .accept 942 >> Accept The Absent Minded Prospector

step << !Warlock
    .hs >> Hearth to Astranaar
    >>|cRXP_BUY_Buy food/water if needed|r << !Warrior !Rogue
    >>|cRXP_BUY_Buy food if needed|r << Warrior/Rogue
    .cooldown item,6948,>0,1

step << Warlock
    #completewith next
    .goto 1440/1,-299.30,2796.01
    .subzone 415 >> Travel to Astranaar

step << Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Shindrell Swiftfire|r
    .target Shindrell Swiftfire
    .goto 1440/1,-299.30,2796.01
    .turnin 1008 >> Turn in The Zoram Strand
    .accept 1134 >> Accept Pridewings of Stonetalon

step << Warlock
    .goto 1440/1,-309.63,2717.68
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Haljan Oakheart|r
    >>|cRXP_BUY_Buy a|r |T135237:0|t[Flint and Tinder] |cRXP_BUY_along with 2|r |T135435:0|t[Simple Wood]
    >>|cRXP_WARN_Don't skip this step, you'll need this for a quest later|r
    .collect 4471,1
    .collect 4470,2
    .target Haljan Oakheart

step << Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Raene Wolfrunner|r
    .target Raene Wolfrunner
    .goto 1440/1,-411.18,2767.19
    .turnin 1023 >> Turn in Raene's Cleansing
    .accept 1025 >> Accept An Aggressive Defense

step << Warlock
    .destroy 5505 >> Destroy |T133741:0|t[Teronis' Journal]. You no longer need it

step << Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Pelturas Whitemoon|r
    .target Pelturas Whitemoon
    .goto 1440/1,-454.43,2682.24
    .turnin 1034 >> Turn in The Ruins of Stardust

step
    .dungeon WC
    #completewith TravelRatchet
    .goto 1440/1,528.79,3045.86,0
    .zone The Barrens >> Grind |cRXP_ENEMY_Saltspittle Murlocs|r while looking for a group for The Wailing Caverns. Their location is marked on your map
    .mob Saltspittle Warrior
    .mob Saltspittle Muckdweller
    .mob Saltspittle Oracle
    .mob Saltspittle Puddlejumper

step
    .dungeon WC
    #label TravelRatchet
    .goto 1440/1,-2319.94,1333.85,50,0
    .goto 1413/1,-2340.39,1246.31,35,0
    .goto 1413/1,-2349.51,747.700,50,0
    .goto 1413/1,-2835.91,158.55,120,0
    .goto 1413/1,-3370.95,-108.99,120,0
    .goto 1413/1,-3769.90,-928.32
    .subzone 392 >> Travel to Ratchet in The Barrens. Follow the Arrow to avoid |cRXP_ENEMY_Barrens Guards|r

step
    .dungeon WC
    .goto 1413/1,-3769.60,-898.33
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Bragok|r
    .fp Ratchet >> Get the Ratchet Flight Path
    .target Bragok

step
    .dungeon WC
    .goto 1413/1,-3769.90,-928.32
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Crane Operator Bigglefuzz|r
    .accept 959 >> Accept Trouble at the Docks
    .target Crane Operator Bigglefuzz

step << Warlock
    .goto 1413/1,-2373.53,-2244.98
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Takar the Seer|r
    .turnin 1716 >> Turn in Devourer of Souls
    .target Takar the Seer
    .accept 1738 >> Accept Heartswood
    .accept 65602 >> Accept What is Love?
    .dungeon WC

step
    .dungeon WC
    #completewith next
    .goto 1413/1,-2134.68,-781.92,0
    .goto 1413/1,-2134.68,-781.92,20,0
    .goto 1413/1,-2140.76,-729.89,15,0
    .goto 1414,51.92,55.27,45,0
    .goto 1414,51.82,55.56,20 >> Travel to The Wailing Caverns. Ascend the mountain then drop down into the hidden cave above the entrance of The Wailing Caverns. Follow the Arrow to get to |cRXP_FRIENDLY_Nalpak|r and |cRXP_FRIENDLY_Ebru|r

step
    .dungeon WC
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Nalpak|r and |cRXP_FRIENDLY_Ebru|r
    .accept 1486 >> Accept Deviate Hides
    .goto 1414,51.912,55.422
    .target +Nalpak
    .accept 1487 >> Accept Deviate Eradication
    .goto 1414,51.918,55.444
    .target +Ebru

step
    .dungeon WC
    #completewith EnterWC
    >>Kill all types of |cRXP_ENEMY_Deviate|r creatures. Loot them for their |cRXP_LOOT_Deviate Hides|r
    >>|cRXP_WARN_This can be completed INSIDE and OUTSIDE of Wailing Caverns|r
    .complete 1486,1
    .isOnQuest 1486

step
    .dungeon WC
    .goto 1414,52.04,55.37,20,0
    .goto 1414,52.14,55.14,20,0
    .goto 1414,51.82,54.85,20,0
    .goto 1414,52.04,55.37,20,0
    .goto 1414,52.14,55.14,20,0
    .goto 1414,51.82,54.85,20,0
    .goto 1414,52.04,55.37,20,0
    .goto 1414,52.14,55.14,20,0
    .goto 1414,51.82,54.85
    >>Kill |cRXP_ENEMY_Mad Magglish|r. Loot him for the |cRXP_LOOT_99-Year-Old Port|r
    >>|cRXP_ENEMY_Mad Magglish|r |cRXP_WARN_can spawn in a few locations|r
    >>|cRXP_WARN_This quest is completed OUTSIDE of Wailing Caverns|r
    .complete 959,1
    .isOnQuest 959
    .mob Mad Magglish

step
    .dungeon WC
    #label EnterWC
    .goto 1414,52.37,55.20
    +Zone into The Wailing Caverns
    .zoneskip 1414,1

step
    .dungeon WC
    >>Kill all types of |cRXP_ENEMY_Deviate|r creatures. Loot them for their |cRXP_LOOT_Deviate Hides|r
    .complete 1487,1
    .complete 1487,2
    .complete 1487,3
    .complete 1487,4
    .complete 1486,1
    .disablecheckbox
    .isOnQuest 1487
    .isOnQuest 1486

step
    .dungeon WC
    >>Kill all types of |cRXP_ENEMY_Deviate|r creatures
    .complete 1487,1
    .complete 1487,2
    .complete 1487,3
    .complete 1487,4
    .isOnQuest 1487

step
    .dungeon WC
    #completewith next
    >>Kill all types of |cRXP_ENEMY_Deviate|r creatures. Loot them for their |cRXP_LOOT_Deviate Hides|r
    .complete 1486,1
    .isOnQuest 1486

step
    .dungeon WC
    >>Kill |cRXP_ENEMY_Lord Cobrahn|r, |cRXP_ENEMY_Lord Pythas|r, |cRXP_ENEMY_Lord Serpentis|r and |cRXP_ENEMY_Lady Anacondra|r then talk to the |cRXP_FRIENDLY_Disciple of Naralex|r at the start of the instance to start his escort
    >>Escort the |cRXP_FRIENDLY_Disciple of Naralex|r through Wailing Caverns and complete the ritual of awakening
    >>Kill |cRXP_ENEMY_Mutanus the Devourer|r. Loot him for the |T135229:0|t[|cRXP_LOOT_Glowing Shard|r]
    >>|cRXP_WARN_Use the |T135229:0|t[|cRXP_LOOT_Glowing Shard|r] to start the quest|r
    .collect 10441,1,6981,1
    .accept 6981 >> Accept The Glowing Shard
    .use 10441
    .skipgossip
    .target Disciple of Naralex
    .mob Mutanus the Devourer

step
    .dungeon WC
    >>Kill all types of |cRXP_ENEMY_Deviate|r creatures. Loot them for their |cRXP_LOOT_Deviate Hides|r
    >>|cRXP_WARN_This can be completed INSIDE and OUTSIDE of Wailing Caverns|r
    .complete 1486,1
    .isOnQuest 1486

step
    .dungeon WC
    #completewith RatchetTurnin
    .goto 1413/1,-3759.46,-902.04
    .subzone 392 >> Travel to Ratchet. You will turn in the quests above WC soon
    .isOnQuest 6981,959

step
    .dungeon WC
    .goto 1413/1,-3759.46,-902.04
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sputtervalve|r
    .complete 6981,1
    .skipgossip 1
    .target Sputtervalve
    .isOnQuest 6981

step
    .dungeon WC
    #label RatchetTurnin
    .goto 1413/1,-3769.90,-928.32
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Crane Operator Bigglefuzz|r
    .turnin 959 >> Turn in Trouble at the Docks
    .target Crane Operator Bigglefuzz
    .isQuestComplete 959

step
    .dungeon WC
    #completewith next
    .goto 1413/1,-2454.90,-766.38,35,0
    .goto The Barrens,48.60,33.34,35,0
    .goto 1413/1,-2259.73,-602.27,15 >> Ascend the steep mountain above The Wailing Caverns. Follow the Arrow
    .isQuestComplete 6981

step
    .dungeon WC
    .goto 1413/1,-2259.73,-602.27
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Falla Sagewind|r
    .turnin 6981 >> Turn in The Glowing Shard
    .target Falla Sagewind
    .isQuestComplete 6981

step
    .dungeon WC
    #completewith NalpakEbru
    .goto 1414,51.92,55.27,45,0
    .goto 1414,51.82,55.56,20 >> Drop down into the hidden cave above the entrance of The Wailing Caverns. Follow the Arrow to get to |cRXP_FRIENDLY_Nalpak|r and |cRXP_FRIENDLY_Ebru|r

step
    .dungeon WC
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Nalpak|r and |cRXP_FRIENDLY_Ebru|r
    .turnin 1486 >> Turn in Deviate Hides
    .goto 1414,51.912,55.422
    .target +Nalpak
    .turnin 1487 >> Turn in Deviate Eradication
    .goto 1414,51.918,55.444
    .target +Ebru
    .isQuestComplete 1486
    .isQuestComplete 1487

step
    .dungeon WC
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Nalpak|r and |cRXP_FRIENDLY_Ebru|r
    .turnin 1487 >> Turn in Deviate Eradication
    .goto 1414,51.918,55.444
    .target Ebru
    .isQuestComplete 1487

step
    .dungeon WC
    #label NalpakEbru
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Nalpak|r and |cRXP_FRIENDLY_Ebru|r
    .turnin 1486 >> Turn in Deviate Hides
    .goto 1414,51.912,55.422
    .target Nalpak
    .isQuestComplete 1486

step
    .dungeon WC
    .hs >> Hearth to Astranaar << !Warlock
    .hs >> Hearth to Auberdine << Warlock

step << Warlock
    #map Darkshore
    .goto Felwood,18.50,19.87
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gubber Blump|r
    .turnin 1138 >> Turn in Fruit of the Sea
    .isQuestComplete 1138
    .target Gubber Blump
    .dungeon WC

step << Warlock
    .goto 1439/1,543.06,6342.57
    .target Gwennyth Bly'Leggonde
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gwennyth Bly'Leggonde|r
    .turnin -4730 >> Turn in Beached Sea Creature
    .turnin -4731 >> Turn in Beached Sea Turtle
    .turnin -4732 >> Turn in Beached Sea Turtle
    .turnin -4733 >> Turn in Beached Sea Creature
    .dungeon WC

step << Warlock
    .goto Darkshore,37.70,43.39
    .target Sentinel Glynda Nal'Shea
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sentinel Glynda Nal'Shea|r
    .turnin 4740 >> Turn in WANTED: Murkdeep!
    .dungeon WC

step << Warlock
    .goto 1439/1,362.93,6434.71
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Terenthis|r
    .turnin 995 >> Turn in Escape Through Stealth
    .target Terenthis
    .isQuestComplete 995
    .dungeon WC

step << Warlock
    .goto 1439,38.325,43.039
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gershala Nightwhisper|r
    .turnin 3765 >> Turn in The Corruption Abroad
    .target Gershala Nightwhisper
    .isOnQuest 3765
    .dungeon WC

step << Warlock
    .goto 1439/1,489.35,6506.76
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Archaeologist Hollee|r
    .turnin 731 >> Turn in The Absent Minded Prospector
    .target Archaeologist Hollee
    .accept 741 >> Accept The Absent Minded Prospector
    .dungeon WC
    .isQuestComplete 731

step << Warlock
    #optional
    .goto 1439/1,489.35,6506.76
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Archaeologist Hollee|r
    .target Archaeologist Hollee
    .accept 741 >> Accept The Absent Minded Prospector
    .dungeon WC

step << Warlock
    #completewith next
    .goto 1439/1,796.54,6490.16,60 >> Travel to the Auberdine Docks. Wait for the Rut'theran Village boat
    .dungeon WC

step << Warlock
    .goto 1439/1,769.16,6577.500
    .zone Teldrassil >> Take the boat to Rut'theran Village
    .zoneskip Darnassus
    .dungeon WC

step << Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Chief Archaeologist Greywhisker|r
    .target Chief Archaeologist Greywhisker
    .goto Teldrassil,23.70,64.51
    .turnin 741 >> Turn in The Absent Minded Prospector
    .accept 942 >> Accept The Absent Minded Prospector
    .isOnQuest 741
    .dungeon WC

step << Warlock
    #optional
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Chief Archaeologist Greywhisker|r
    .target Chief Archaeologist Greywhisker
    .goto Teldrassil,23.70,64.51
    .accept 942 >> Accept The Absent Minded Prospector
    .isOnQuest 741
    .dungeon WC

step << Warlock
    #completewith next
    .goto 1457/1,2626.51,9946.11
    .zone Teldrassil >> Travel through the purple portal to Rut'theran Village
    .zoneskip Ashenvale
    .zoneskip Darkshore
    .dungeon WC

step << Warlock
    .goto 1438/1,841.56,8640.79
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Vesprystus|r
    .fp Teldrassil >> Get the Rut'theran Village Flight Path
    .fly Ashenvale >> Fly to Ashenvale
    .target Vesprystus
    .zoneskip Ashenvale
    .dungeon WC

step << !Warlock
    .goto Ashenvale,42.50,71.70
    .zone Stonetalon Mountains >> Travel to Stonetalon Mountains

step
    #sticky
    #completewith wyv1
    >>Kill |cRXP_ENEMY_Young Pridewings|r. Loot them for their |cRXP_LOOT_Pridewing Venom Sacs|r
    .complete 1134,1
    .unitscan Young Pridewing

step << !Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kaela Shadowspear|r
    .target Kaela Shadowspear
    .goto 1442/1,320.77,740.06
    .turnin 1070 >> Turn in On Guard in Stonetalon
    .accept 1085 >> Accept On Guard in Stonetalon

step << !Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gaxim Rustfizzle|r
    .target Gaxim Rustfizzle
    .goto 1442/1,339.47,730.23
    .turnin 1085 >> Turn in On Guard in Stonetalon
    .accept 1071 >> Accept A Gnome's Respite

step << !Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ziz Fizziks|r
    .target Ziz Fizziks
    .goto 1442/1,365.20,878.22
    .accept 1093 >> Accept Super Reaper 6000

step << !Warlock
    #sticky
    #label sr6000
    .goto 1442/1,200.59,1190.850,60,0
    .goto 1442/1,-12.81,1226.35,60,0
    .goto 1442/1,-13.79,1437.68,60,0
    .goto 1442/1,-12.81,1226.35,60,0
    .goto 1442/1,200.59,1190.850
    .goto 1442/1,-12.81,1226.35,0
    >>Kill |cRXP_ENEMY_Venture Co. Operators|r. Loot them for the |cRXP_LOOT_Blueprints|r
    .complete 1093,1
    .unitscan Venture Co. Operator

step << !Warlock
    .goto 1442/1,200.59,1190.850,60,0
    .goto 1442/1,-12.81,1226.35,60,0
    .goto 1442/1,-13.79,1437.68,60,0
    .goto 1442/1,-12.81,1226.35,60,0
    .goto 1442/1,200.59,1190.850
    .goto 1442/1,-12.81,1226.35,0
    >>Kill |cRXP_ENEMY_Venture Co. Deforesters|r and |cRXP_ENEMY_Venture Co. Loggers|r
    .complete 1071,1
    .mob +Venture Co. Logger
    .complete 1071,2
    .mob +Venture Co. Deforester

step
    #requires sr6000
    .goto 1442/1,365.20,878.22
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ziz Fizziks|r
    .target Ziz Fizziks
    .turnin 1093 >> Turn in Super Reaper 6000
    .dungeon WC << Warlock

step << !Warlock
    #label wyv1
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gaxim Rustfizzle|r
    .goto 1442/1,339.47,730.23
    .turnin 1071 >> Turn in A Gnome's Respite
    .accept 1072 >> Accept An Old Colleague
    .accept 1075 >> Accept A Scroll from Mauren
    .target Gaxim Rustfizzle

step
    .goto 1442/1,606.88,1611.24,60,0
    .goto 1442/1,644.97,1717.39,40,0
    .goto 1442/1,581.49,1675.38
    >>Kill |cRXP_ENEMY_Pridewing Wyverns|r and |cRXP_ENEMY_Pridewing Consorts|r. Loot them for their |cRXP_LOOT_Pridewing Venom Sacs|r
    .mob Pridewing Wyvern
    .mob Pridewing Consort
    .complete 1134,1

step << !Warlock
    #completewith next
    .goto 1442/1,1433.97,2652.9100,100 >> Travel to Stonetalon Peak
    .zoneskip Stonetalon Mountains,1

step << !Warlock
    .goto 1442/1,1433.97,2652.9100
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Keeper Albagorm|r
    .target Keeper Albagorm
    .turnin 1056 >> Turn in Journey to Stonetalon Peak

step << !Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Teloren|r
    .target Teloren
    .goto 1442/1,1466.44,2682.84
    .fp Stonetalon >> Get the Stonetalon Flight Path
    .disablecheckbox
    .fly Ashenvale >> Fly to Ashenvale

step << Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Teloren|r
    .target Teloren
    .goto 1442/1,1466.44,2682.84
    .fp Stonetalon >> Get the Stonetalon Flight Path

step << Warlock
    .goto 1442/1,1507.61,2677.30
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Illyanie|r
    .vendor >> |cRXP_WARN_Vendor trash|r
    .target Illyanie
    .dungeon !WC

step << Warlock
    #completewith next
    >>Ensure you have at least 4 |T134075:0|t[Soul Shards] before dying intentionally, you're about to spirit res 4 times total
    .deathskip >> Die and respawn at the Spirit Healer
    .target Spirit Healer
    .dungeon !WC

step << Warlock
    .goto The Barrens,35.10,27.80
    .zone The Barrens >>Run southeast to The Barrens
    .dungeon !WC

step << Warlock
    #completewith next
    .goto 1413/1,-2494.42,-583.28,0
    .deathskip >> Once you get to The Barrens, Die and respawn at the Crossroads Graveyard
    .target Spirit Healer
    .dungeon !WC

step << Warlock
    .goto 1413/1,-2373.53,-2244.98
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Takar the Seer|r
    .turnin 1716 >> Turn in Devourer of Souls
    .target Takar the Seer
    .accept 1738 >> Accept Heartswood
    .accept 65602 >> Accept What is Love?
    .dungeon !WC

step << Warlock
    #completewith next
    .goto The Barrens,56.60,51.60
    .deathskip >> Run northeast. When the zone text changes to Raptor Grounds, Die and respawn at Ratchet
    >>Do your best to avoid the |cRXP_ENEMY_Quilboars|r
    .dungeon !WC

step << Warlock
    #completewith next
    .goto 1413/1,-3759.06,-901.50,100 >> Travel to Ratchet
    .dungeon !WC

step << Warlock
    .goto 1413/1,-3759.46,-902.04
    .target Sputtervalve
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sputtervalve|r
    .turnin 1094 >> Turn in Further Instructions
    .isOnQuest 1094
    .dungeon !WC

step << Warlock
    .goto 1413/1,-3769.60,-898.33
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Bragok|r
    .fp Ratchet>> Get the Ratchet Flight Path
    .target Bragok
    .dungeon !WC

step << Warlock
    .hs >> Hearth to Darkshore
    >>|cRXP_BUY_Buy food/water if needed|r << !Warrior !Rogue
    .dungeon !WC

step << Warlock
    #map Darkshore
    .goto Felwood,18.50,19.87
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gubber Blump|r
    .turnin 1138 >> Turn in Fruit of the Sea
    .isQuestComplete 1138
    .target Gubber Blump
    .dungeon !WC

step << Warlock
    .goto 1439/1,543.06,6342.57
    .target Gwennyth Bly'Leggonde
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gwennyth Bly'Leggonde|r
    .turnin -4730 >> Turn in Beached Sea Creature
    .turnin -4731 >> Turn in Beached Sea Turtle
    .turnin -4732 >> Turn in Beached Sea Turtle
    .turnin -4733 >> Turn in Beached Sea Creature
    .dungeon !WC

step << Warlock
    .goto Darkshore,37.70,43.39
    .target Sentinel Glynda Nal'Shea
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sentinel Glynda Nal'Shea|r
    .turnin 4740 >> Turn in WANTED: Murkdeep!
    .dungeon !WC

step << Warlock
    .goto 1439/1,362.93,6434.71
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Terenthis|r
    .turnin 995 >> Turn in Escape Through Stealth
    .target Terenthis
    .isQuestComplete 995
    .dungeon !WC

step << Warlock
    .goto 1439,38.325,43.039
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gershala Nightwhisper|r
    .turnin 3765 >> Turn in The Corruption Abroad
    .target Gershala Nightwhisper
    .isOnQuest 3765
    .dungeon !WC

step << Warlock
    .goto 1439/1,489.35,6506.76
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Archaeologist Hollee|r
    .turnin 731 >> Turn in The Absent Minded Prospector
    .target Archaeologist Hollee
    .accept 741 >> Accept The Absent Minded Prospector
    .dungeon !WC
    .isQuestComplete 731

step << Warlock
    #optional
    .goto 1439/1,489.35,6506.76
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Archaeologist Hollee|r
    .target Archaeologist Hollee
    .accept 741 >> Accept The Absent Minded Prospector
    .dungeon !WC

step << Warlock
    #completewith next
    .goto 1439/1,796.54,6490.16,60 >> Travel to the Auberdine Docks. Wait for the Rut'theran Village boat
    .dungeon !WC

step << Warlock
    .goto 1439/1,769.16,6577.500
    .zone Teldrassil >> Take the boat to Rut'theran Village
    .zoneskip Darnassus
    .dungeon !WC

step << Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Chief Archaeologist Greywhisker|r
    .target Chief Archaeologist Greywhisker
    .goto Teldrassil,23.70,64.51
    .turnin 741 >> Turn in The Absent Minded Prospector
    .accept 942 >> Accept The Absent Minded Prospector
    .dungeon !WC
    .isOnQuest 741

step << Warlock
    #optional
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Chief Archaeologist Greywhisker|r
    .target Chief Archaeologist Greywhisker
    .goto Teldrassil,23.70,64.51
    .accept 942 >> Accept The Absent Minded Prospector
    .dungeon !WC

step << Warlock
    #completewith next
    .goto 1457/1,2626.51,9946.11
    .zone Teldrassil >> Travel through the purple portal to Rut'theran Village
    .zoneskip Ashenvale
    .zoneskip Darkshore
    .dungeon !WC

step << Warlock
    .goto 1438/1,841.56,8640.79
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Vesprystus|r
    .fp Teldrassil >> Get the Rut'theran Village Flight Path
    .fly Ashenvale >> Fly to Ashenvale
    .target Vesprystus
    .zoneskip Ashenvale
    .dungeon !WC

step
    .goto 1440/1,-299.30,2796.01
    .target Shindrell Swiftfire
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Shindrell Swiftfire|r
    .turnin 1134 >> Turn in Pridewings of Stonetalon

step
    .goto 1440/1,-411.18,2767.19
    .target Raene Wolfrunner
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Raene Wolfrunner|r
    .accept 1054 >> Accept Culling the Threat

step
    #completewith next
    >>Kill a few |cRXP_ENEMY_Foulweald Warriors|r and |cRXP_ENEMY_Foulweald Totemics|r before heading south toward the |cRXP_ENEMY_Water Elementals|r
    >>|cRXP_WARN_Be careful as the|r |cRXP_ENEMY_Foulweald Ursas|r |cRXP_WARN_can|r |T132152:0|t[Thrash] |cRXP_WARN_hitting you 3 times at once|r
    >>|cRXP_WARN_You will kill the rest after finishing the Elemental Bracers quest|r
    .complete 1025,4,5
    .mob +Foulweald Warrior
    .goto 1440/1,-1187.95,2368.97,70,0
    .goto 1440/1,-1399.58,2232.52,70,0
    .goto 1440/1,-1423.80,2301.71,70,0
    .goto 1440/1,-1187.95,2368.97
    .complete 1025,3,4
    .mob +Foulweald Totemic
    .goto 1440/1,-1187.95,2368.97,70,0
    .goto 1440/1,-1399.58,2232.52,70,0
    .goto 1440/1,-1423.80,2301.71,70,0
    .goto 1440/1,-1187.95,2368.97
    .complete 1025,2
    .disablecheckbox
    .complete 1025,1
    .disablecheckbox
    .mob Foulweald Ursa
    .mob Foulweald Den Watcher

step
    .goto 1440/1,-1171.22,2089.53
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sentinel Velene Starstrike|r
    .accept 1016 >> Accept Elemental Bracers
    .target Sentinel Velene Starstrike

step
    #optional
    #completewith next
    .cast 7178 >> |cRXP_WARN_Use your|r |T134797:0|t[Elixir of Water Breathing]
    .itemcount 5996,1
    .use 5996

step
    .goto 1440/1,-882.31,1979.60,60,0
    .goto Ashenvale,48.90,70.05,60,0
    .goto 1440/1,-1257.15,1962.69,60,0
    .goto Ashenvale,48.90,70.05
    >>Kill |cRXP_ENEMY_Befouled Water Elementals|r. Loot them for their |cRXP_LOOT_Bracers|r
    >>|cRXP_WARN_The |cRXP_ENEMY_Befouled Water Elementals|r cast|r |T135848:0|t[Frost Nova]|cRXP_WARN_. Pay attention to your breath timer if you dive underwater to kill them|r
    .collect 12220,5,1016,1
    .mob Befouled Water Elemental

step
    .use 5456 >> |cRXP_WARN_Use the|r |T134943:0|t[Divining Scroll] |cRXP_WARN_to create the|r |T134938:0|t[Divined Scroll]
    .complete 1016,1

step
    .goto 1440/1,-1171.22,2089.53
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sentinel Velene Starstrike|r
    .turnin 1016 >> Turn in Elemental Bracers
    .target Sentinel Velene Starstrike

step
    .goto 1440/1,-1187.95,2368.97,70,0
    .goto 1440/1,-1399.58,2232.52,70,0
    .goto 1440/1,-1423.80,2301.71,70,0
    .goto 1440/1,-1555.28,2227.52,70,0
    .goto 1440/1,-1187.95,2368.97
    >>Kill |cRXP_ENEMY_Foulweald Warriors|r, |cRXP_ENEMY_Foulweald Totemics|r, |cRXP_ENEMY_Foulweald Ursas|r and a |cRXP_ENEMY_Foulweald Den Watcher|r
    >>|cRXP_WARN_Be careful as the|r |cRXP_ENEMY_Foulweald Ursas|r |cRXP_WARN_can|r |T132152:0|t[Thrash] |cRXP_WARN_hitting you 3 times at once|r
    >>The |cRXP_ENEMY_Foulweald Totemics|r share spawns with |cRXP_ENEMY_Foulweald Warriors|r. You may have to backtrack and kill respawns if you weren't lucky with the spawns
    .complete 1025,4
    .mob +Foulweald Warrior
    .complete 1025,3
    .mob +Foulweald Totemic
    .complete 1025,2
    .mob +Foulweald Ursa
    .complete 1025,1
    .mob +Foulweald Den Watcher

step
    #completewith next
    .zone Azshara >> Travel to Azshara

step
    .goto Azshara,11.90,77.57
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Jarrodenus|r
    .fp Azshara>> Get the Azshara flight path
    .fly Ashenvale>> Fly to Ashenvale
    .target Jarrodenus

step
    #completewith next
    .goto 1440/1,-300.46,2970.140,30,0
    .goto 1440/1,-343.13,3079.30,30,0
    .goto 1440/1,-392.15,3193.84,30,0
    .goto 1440/1,-423.86,3229.20,30 >> Travel to Thistlefur Village. Follow the Arrow for a shortcut

step
    .goto 1440/1,-379.46,3266.49,0
    .goto Ashenvale,37.00,33.77,0
    .goto 1440/1,-369.08,3446.760,0
    .goto 1440/1,-533.43,3276.87,0
    .goto 1440/1,-379.46,3266.49,60,0
    .goto Ashenvale,37.00,33.77,60,0
    .goto 1440/1,-369.08,3446.760,60,0
    .goto 1440/1,-533.43,3276.87,60,0
    .goto 1440/1,-583.31,3277.29
    >>Kill |cRXP_ENEMY_Dal Bloodclaw|r. Loot him for his |cRXP_LOOT_Skull|r
    >>|cRXP_ENEMY_Dal Bloodclaw|r |cRXP_WARN_patrols Thistlefur Village|r
    .complete 1054,1
    .unitscan Dal Bloodclaw

step << !Warlock
    .deathskip >> Die and respawn at the Spirit Healer
    .target Spirit Healer

step << Warlock
    #completewith next
    .goto 1440/1,158.57,2945.15,100,0
    .goto Ashenvale,31.50,31.50,40 >> Travel to The Ruins of Ordil'Aran

step << Warlock
    .goto Ashenvale,31.50,31.50
    >>Loot the |cRXP_LOOT_Heartswood|r giant tree
    .complete 1738,1

step << Warlock
    .goto 1440/1,155.69,3811.15
    >>Loot the |cRXP_LOOT_Unlit Torch|r on the table
    .collect 190307,1,65602,1

step << Warlock
    .goto 1440/1,155.69,3811.15
    >>|cRXP_WARN_Create a campfire, then use the Unlit Torch on top of it|r
    .collect 190308,1,65602,1
    .use 190307
    .usespell 818

step << Warlock
    .goto 1440/1,165.49,3826.91
    >>Use the Burning Torch on the cart outside next to where you looted the torch, then go upstairs and loot the statue
    .complete 65602,1

step << Warlock
    #completewith end
    .goto 1440/1,287.17,3170.01
    .deathskip >> Run to the base of the mountain southwest of the big tower and die then respawn back at Astranaar
    .target Spirit Healer

step
    .goto 1440/1,-411.18,2767.19
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Raene Wolfrunner|r
    .turnin 1025 >> Turn in An Aggressive Defense
    .turnin 1054 >> Turn in Culling the Threat
    .target Raene Wolfrunner

step
    #label end
    .goto 1440/1,-284.31,2828.69
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Daelyshia|r
    .fly Darkshore>> Fly to Darkshore
    .target Daelyshia

step
    .goto 1439/1,816.85,6424.66
    >>|cRXP_WARN_Level your|r |T135966:0|t[First Aid] |cRXP_WARN_and|r |T133971:0|t[Cooking] |cRXP_WARN_while waiting for the Menethil Harbor boat|r
    .zone Wetlands >> Take the boat to Menethil Harbor
]])
