-- Generated by Scripts/split_guide_vault.py; rerun the script to update.
if not RXPGuides or type(RXPGuides.RegisterGuide) ~= "function" then return end
local _, rxpGuideVaultAddon = ...
local rxpGuideVaultGame = rxpGuideVaultAddon and rxpGuideVaultAddon.game
if not rxpGuideVaultGame then
    local rxpGuideVaultVersion = select(4, GetBuildInfo())
    if rxpGuideVaultVersion > 60000 then
        rxpGuideVaultGame = "RETAIL"
    elseif rxpGuideVaultVersion > 50000 then
        rxpGuideVaultGame = "MOP"
    elseif rxpGuideVaultVersion > 40000 then
        rxpGuideVaultGame = "CATA"
    elseif rxpGuideVaultVersion > 30000 then
        rxpGuideVaultGame = "WOTLK"
    elseif rxpGuideVaultVersion > 20000 then
        rxpGuideVaultGame = "TBC"
    elseif rxpGuideVaultVersion >= 16000 and rxpGuideVaultVersion < 20000 then
        rxpGuideVaultGame = "FOREVER"
    else
        rxpGuideVaultGame = "CLASSIC"
    end
end
if rxpGuideVaultGame ~= "FOREVER" then return end

RXPGuides.RegisterGuide([[#forever
#version 23
#group RestedXP Forever Guide (A)
#subgroup Speedrun Guide 20-30

<< Alliance
#name 24-27 Duskwood/Redridge
#next 27-29 Wetlands/Hillsbrad;RestedXP Forever Guide (A)\29-32 Duskwood

step
    .goto 1453/0,638.80,-8341.95
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Billibub Cogspinner|r
    .vendor >> |cRXP_BUY_Buy a|r |T133024:0|t[Bronze Tube] |cRXP_BUY_from him if its up|r
    >>|cRXP_WARN_This is a limited supply item. Skip this step if |cRXP_FRIENDLY_Billibub Cogspinner|r doesn't have one|r

    .bronzetube
    .target Billibub Cogspinner

step
    .goto 1453/0,517.94,-8821.82
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Felicia Gump|r inside
    >>|cRXP_BUY_Buy|r |T133849:0|t[Stormwind Seasoning Herbs] from her
    .collect 2665,1,90,1
    .skill cooking,<50,1
    .target Felicia Gump

step << Warlock
    #sticky
    #completewith next
    .goto 1453/0,988.44,-8942.15,20,0
    .goto 1453/0,1015.33,-8978.90,15 >> Go into The Slaughtered Lamb. Go downstairs

step << Warlock
    .goto StormwindClassic,26.117,77.225
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ursula Deline|r
    .trainer >> Train your class spells
    .target Ursula Deline

step << Warlock
    .goto StormwindClassic,25.665,77.649
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Spackle Thornberry|r
    .vendor >> |cRXP_BUY_Buy|r |T133738:0|t[Grimoires] |cRXP_BUY_for your|r |T136220:0|t[Succubus]|cRXP_BUY_ which you will have in a second. If you have extra gold also buy them for your|r |T136221:0|t[Voidwalker]
    .target Spackle Thornberry

step << Warlock
    .goto 1453/0,1041.54,-8982.94
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gakin the Darkbinder|r
    .turnin 1738 >> Turn in Heartswood
    .turnin 65602 >> Turn in What Is Love?
    .accept 1739 >> Accept The Binding
    .accept 65603 >> Accept The Binding
    .target Gakin the Darkbinder
    .isOnQuest 65602

step << Warlock
    #optional
    .goto 1453/0,1041.54,-8982.94
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gakin the Darkbinder|r
    .turnin 1738 >> Turn in Heartswood
    .accept 1739 >> Accept The Binding
    .accept 65603 >> Accept The Binding
    .target Gakin the Darkbinder
    .isQuestTurnedIn 65602

step << Warlock
    #optional
    .goto 1453/0,1041.54,-8982.94
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gakin the Darkbinder|r
    .turnin 1738 >> Turn in Heartswood
    .accept 1739 >> Accept The Binding
    .target Gakin the Darkbinder

step << Warlock
    #completewith next
    .goto StormwindClassic,25.2,80.7,18,0
    .goto StormwindClassic,23.2,79.5,18,0
    .goto StormwindClassic,26.3,79.5,18,0
    .goto StormwindClassic,25.154,77.406
    >>|cRXP_WARN_Travel to the bottom of The Slaughtered Lamb|r
    .cast 8674 >> |cRXP_WARN_Use the|r |T136065:0|t[Heartswood Core] |cRXP_WARN_to call forth a|r |cRXP_ENEMY_Summoned Succubus|r
    .use 6913

step << Warlock
    .goto StormwindClassic,25.154,77.406
    .use 6913 >> Kill the |cRXP_ENEMY_Summoned Succubus|r
    .complete 1739,1
    .mob Summoned Succubus

step << Warlock
    .goto StormwindClassic,25.154,77.406
    >>|cRXP_WARN_Travel to the bottom of The Slaughtered Lamb|r
    .use 190186 >> |cRXP_WARN_Use the|r |T136065:0|t[Wooden Figurine] |cRXP_WARN_to call forth a|r |cRXP_ENEMY_Summoned Incubus|r
    .complete 1739,1
    .mob Summoned Incubus
    .isQuestTurnedIn 65602

step << Warlock
    #completewith next
    +|cRXP_WARN_You may now use either the|r |T136220:0|t[Succubus] |cRXP_WARN_or|r |T136221:0|t[Voidwalker] |cRXP_WARN_as your pet|r
    >>|cRXP_WARN_The|r |T136220:0|t[Succubus] |cRXP_WARN_deals significant damage whereas the|r |T136221:0|t[Voidwalker] |cRXP_WARN_provides more survivability|r

step << Warlock
    .goto 1453/0,1041.54,-8982.94
    .target Gakin the Darkbinder
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gakin the Darkbinder|r
    .turnin 1739 >> Turn in The Binding
    .turnin -65603 >> Turn in The Binding

step
    .goto 1453/0,801.75,-8999.44
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Collin Mauren|r
    .turnin 1075 >> Turn in A Scroll from Mauren
    .target Collin Mauren
    .isOnQuest 1075

step
    #optional
    .goto 1453/0,801.75,-8999.44
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Collin Mauren|r
    .accept 1076 >> Accept Devils in Westfall
    .target Collin Mauren
    .isQuestTurnedIn 1075

step
    .goto 1453/0,613.93,-8933.64
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Newton Burnside|r
    .bankwithdraw 2251,1015 >> Withdraw the following items from your bank:
    >>|T133970:0|t[Lean Wolf Flanks]
    >>|T134321:0|t[Gooey Spider Legs]
    .target Newton Burnside

step
    .goto StormwindClassic,57.12,57.69
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Woo Ping|r
    .train 201 >> Train 1h Swords << Mage/Rogue/Warlock
    .train 202 >> Train 2h Swords << Warrior/Paladin/Hunter
    .target Woo Ping

step
    #ah
    .goto 1453/0,660.28,-8814.55
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Auctioneer Jaxon|r
    >>Buy the following items for faster turn ins at Duskwood shortly
    >>This will save you time as you won't need to run around looking for mobs to kill. Skip this step if you wish to not buy any
    >>|cRXP_WARN_Note: You should also level your|r |T133971:0|t[Cooking] |cRXP_WARN_to 50 for an easy 2,000XP quest in Duskwood. Buy as many|r |T133970:0|t[Chunk of Boar Meat] |cRXP_WARN_or|r |T133970:0|t|cRXP_LOOT_[Stringy Wolf Meat]|r |cRXP_WARN_as you need to level it to 50. You can cook them once you get to the Inn at Duskwood|r
    >>|T133024:0|t[Bronze Tube]
    >>|T133970:0|t[Lean Wolf Flank]
    >>|T134321:0|t[Gooey Spider Leg]
    >>|T132794:0|t[Flask of Oil]
    .collect 4371,1,174,1
    .collect 1015,10,90,1
    .collect 2251,6,93,1
    .collect 814,5,103,1
    .bronzetube
    .skill cooking,50,1
    .target Auctioneer Jaxon

step
    #ah
    .goto 1453/0,660.28,-8814.55
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Auctioneer Jaxon|r
    >>Buy the following items for faster turn ins at Duskwood shortly
    >>This will save you time as you won't need to run around looking for mobs to kill. Skip this step if you wish to not buy any
    >>|T133024:0|t[Bronze Tube]
    >>|T133970:0|t[Lean Wolf Flank]
    >>|T134321:0|t[Gooey Spider Leg]
    >>|T132794:0|t[Flask of Oil]
    .collect 4371,1,174,1
    .collect 1015,10,90,1
    .collect 2251,6,93,1
    .collect 814,5,103,1
    .bronzetube
    .skill cooking,<50,1
    .target Auctioneer Jaxon

step
    #ah
    .goto 1453/0,660.28,-8814.55
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Auctioneer Jaxon|r
    >>Buy the following items for faster turn ins at Duskwood shortly
    >>This will save you time as you won't need to run around looking for mobs to kill. Skip this step if you wish to not buy any
    >>|cRXP_WARN_Note: You should also level your|r |T133971:0|t[Cooking] |cRXP_WARN_to 50 for an easy 2,000XP quest in Duskwood. Buy as many|r |T133970:0|t[Chunk of Boar Meat] |cRXP_WARN_or|r |T133970:0|t|cRXP_LOOT_[Stringy Wolf Meat]|r |cRXP_WARN_as you need to level it to 50. You can cook them once you get to the Inn at Duskwood|r
    >>|T133970:0|t[Lean Wolf Flank]
    >>|T134321:0|t[Gooey Spider Leg]
    >>|T132794:0|t[Flask of Oil]
    .collect 1015,10,90,1
    .collect 2251,6,93,1
    .collect 814,5,103,1
    .skill cooking,50,1
    .target Auctioneer Jaxon

step
    #ah
    .goto 1453/0,660.28,-8814.55
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Auctioneer Jaxon|r
    >>Buy the following items for faster turn ins at Duskwood shortly
    >>This will save you time as you won't need to run around looking for mobs to kill. Skip this step if you wish to not buy any
    >>|T133970:0|t[Lean Wolf Flank]
    >>|T134321:0|t[Gooey Spider Leg]
    >>|T132794:0|t[Flask of Oil]
    .collect 1015,10,90,1
    .collect 2251,6,93,1
    .collect 814,5,103,1
    .skill cooking,<50,1
    .target Auctioneer Jaxon

step << !NightElf
    #completewith next
    .goto StormwindClassic,66.277,62.137
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Dungar Longdrink|r
    .fly Redridge >> Fly to Redridge Mountains
    .target Dungar Longdrink
    .zoneskip Stormwind City,1
    .xp <25,1

step
    #completewith next
    .subzone 42 >> Travel to Darkshire
    .xp <25,1

step << !Human
    .maxlevel 24
    .dungeon !DM
    #completewith next
    .goto 1453/0,423.99,-9077.500
    .zone Elwynn Forest >> Head to Elwynn Forest

step << !Human
    .maxlevel 24
    .dungeon DM
    #completewith next
    .goto StormwindClassic,66.277,62.137
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Dungar Longdrink|r
    .fly Westfall >> Fly to Westfall
    .target Dungar Longdrink

step
    .maxlevel 24
    .goto 1431/0,624.81,-10316.08
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Lars|r
    >>|cRXP_WARN_Do NOT accept the quest Sven's Revenge from|r |cRXP_FRIENDLY_Sven Yorgen|r
    .accept 226 >> Accept Wolves at Our Heels
    .target Lars

step
    #completewith MadEva
    .goto Duskwood,48.0,17.2,0
    .goto 1431/0,74.63,-10233.27,0
    .goto Duskwood,48.0,17.2,85,0
    .goto 1431/0,-1213.54,-10531.89,50 >> Travel to Darkshire
    .isOnQuest 226

step
    #completewith MadEva
    #label Wolves
    >>Kill |cRXP_ENEMY_Starving Dire Wolves|r and |cRXP_ENEMY_Rabid Dire Wolves|r en route. Loot them for their |cRXP_LOOT_Lean Wolf Flanks|r
    >>|cRXP_WARN_Be careful as |cRXP_ENEMY_Starving Dire Wolves|r have|r |T132150:0|t[Increased Aggro Range] |cRXP_WARN_and|r |cRXP_ENEMY_Rabid Dire Wolves|r cast|r |T135914:0|t[Rabies] |cRXP_WARN_(Reduces ALL health regen by 50%)|r
    >>|cRXP_WARN_You don't have to kill all |cRXP_ENEMY_Wolves|r now. Save the |cRXP_LOOT_Lean Wolf Flanks|r for a later quest|r
    .complete 226,1
    .mob +Starving Dire Wolf
    .complete 226,2
    .mob +Rabid Dire Wolf
    .collect 1015,10,90,1
    .mob +Starving Dire Wolf
    .mob +Rabid Dire Wolf
    .skill cooking,<50,1
    .isOnQuest 226
    .subzoneskip 42

step
    #completewith MadEva
    #label Wolves
    >>Kill |cRXP_ENEMY_Starving Dire Wolves|r and |cRXP_ENEMY_Rabid Dire Wolves|r en route
    >>|cRXP_WARN_Be careful as |cRXP_ENEMY_Starving Dire Wolves|r have|r |T132150:0|t[Increased Aggro Range] |cRXP_WARN_and|r |cRXP_ENEMY_Rabid Dire Wolves|r cast|r |T135914:0|t[Rabies] |cRXP_WARN_(Reduces ALL health regen by 50%)|r
    >>|cRXP_WARN_You don't have to kill all |cRXP_ENEMY_Wolves|r now|r
    .complete 226,1
    .mob +Starving Dire Wolf
    .complete 226,2
    .mob +Rabid Dire Wolf
    .skill cooking,50,1
    .isOnQuest 226
    .subzoneskip 42

step
    .abandon 148 >> Abandon Supplies from Darkshire. You will miss out on free XP if you turn this in now. It will be completed soon

step
    #label MadEva
    .goto 1431/0,-1213.54,-10531.89
    .target Madame Eva
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Madame Eva|r inside
    .accept 66 >> Accept The Legend of Stalvan
    .accept 101 >> Accept The Totem of Infliction

step
    .goto 1431/0,-1161.21,-10515.97
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Innkeeper Trelayne|r
    .home >> Set your Hearthstone to Duskwood
    .target Innkeeper Trelayne

step
    .goto 1431/0,-1160.08,-10509.57
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Chef Grual|r in the inn's kitchen
    >>|cRXP_WARN_You need 50 skill in cooking to accept this quest|r
    .accept 90 >> Accept Seasoned Wolf Kabobs
    .turnin 90 >> Turn in Seasoned Wolf Kabobs
    .skill cooking,<50,1
    .itemcount 1015,10
    .target Chef Grual

step
    .goto 1431/0,-1153.60,-10560.69
    .target Commander Althea Ebonlocke
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Commander Althea Ebonlocke|r
    >>|cRXP_WARN_She may be dead or busy fighting|r |cRXP_ENEMY_Stitches|r |cRXP_WARN_if he attacks Darkshire. If that happens consider grinding mobs near the town until she respawns or changing your layer (if possible)|r
    .accept 56 >> Accept The Night Watch

step
    .goto 1431/0,-1124.98,-10559.97
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Clerk Daltry|r in the town hall building
    .turnin 66 >> Turn in The Legend of Stalvan
    .target Clerk Daltry
    .accept 67 >> Accept The Legend of Stalvan

step
    .goto 1431/0,-1200.58,-10593.09
    .target Elaine Carevin
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Elaine Carevin|r
    .accept 163 >> Accept Raven Hill
    .accept 165 >> Accept The Hermit

step
    .abandon 95 >> Abandon Sven's Revenge

step
    .goto 1431/0,-1200.58,-10593.09
    .target Elaine Carevin
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Elaine Carevin|r
    .accept 164 >> Accept Deliveries to Sven
    >>|cRXP_WARN_If you can't pick up this quest you need to abandon Sven's Revenge from your quest log|r

step
    .goto 1431/0,-1258.79,-10513.83
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Felicia Maline|r
    .fp Duskwood>> Get the Duskwood Flight Path
    .target Felicia Maline

step
    .goto 1431/0,-1272.45,-10586.57
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Herble Baubbletump|r
    .vendor >> |cRXP_BUY_Buy a|r |T133024:0|t[Bronze Tube]
    >>|cRXP_WARN_This is a limited supply item. Skip this step if |cRXP_FRIENDLY_Herble Baubbletump|r doesn't have one|r

    .bronzetube
    .target Herble Baubbletump

step
    .goto Duskwood,79.80,48.02
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Viktori Prism'Antras|r
    .accept 174 >> Accept Look To The Stars
    .turnin 174 >> Turn in Look To The Stars
    .itemcount 4371,1
    .target Viktori Prism'Antras

step
    .goto Duskwood,79.80,48.02
    .target Viktori Prism'Antras
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Viktori Prism'Antras|r
    .accept 175 >> Accept Look To The Stars
    .isQuestTurnedIn 174

step
    .goto 1431/0,-1366.09,-10779.03
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Blind Mary|r
    .turnin 175 >> Turn in Look To The Stars
    .accept 177 >> Accept Look To The Stars
    .target Blind Mary
    .isQuestTurnedIn 174

step
    #completewith HistoryBook1
    >>|cRXP_WARN_Keep at eye out for |T133741:0|t[|cRXP_LOOT_An Old History Book|r]. This is a zone-wide drop in Duskwood|r
    >>|cRXP_WARN_Don't start the quest for it yet|r
    .collect 2794,1,337,1

step
    #completewith next
    >>Kill |cRXP_ENEMY_Skeletal Warriors|r and |cRXP_ENEMY_Skeletal Mages|r
    >>|cRXP_ENEMY_Skeletal Warriors|r |cRXP_WARN_apply|r |T132316:0|t[Hamstring]
    >>|cRXP_ENEMY_Skeletal Mages|r |cRXP_WARN_cast|r |T135846:0|t[Frostbolt] |cRXP_WARN_and also snare with|r |T135843:0|t[Frost Armor]
    .complete 56,1
    .mob +Skeletal Warrior
    .complete 56,2
    .mob +Skeletal Mage

step
    .goto 1431/0,-1319.38,-10988.19,30,0
    .goto 1431/0,-1353.13,-11006.37
    >>Kill the |cRXP_ENEMY_Insane Ghoul|r. Loot him for |cRXP_LOOT_Mary's Looking Glass|r
    >>|cRXP_WARN_The |cRXP_ENEMY_Insane Ghoul|r may be inside of the chapel or walking around outside|r
    .complete 177,1
    .mob Insane Ghoul
    .isQuestTurnedIn 174

step
    .goto 1431/0,-1336.12,-10964.25,50,0
    .goto 1431/0,-1258.90,-11000.070,50,0
    .goto 1431/0,-1309.93,-11043.270,50,0
    .goto 1431/0,-1309.93,-10981.71
    #label HistoryBook1
    >>Kill |cRXP_ENEMY_Skeletal Warriors|r and |cRXP_ENEMY_Skeletal Mages|r
    >>|cRXP_ENEMY_Skeletal Warriors|r |cRXP_WARN_apply|r |T132316:0|t[Hamstring]
    >>|cRXP_ENEMY_Skeletal Mages|r |cRXP_WARN_cast|r |T135846:0|t[Frostbolt] |cRXP_WARN_and also snare with|r |T135843:0|t[Frost Armor]
    .complete 56,1
    .mob +Skeletal Warrior
    .complete 56,2
    .mob +Skeletal Mage

step
    #completewith RavenHill
    +|cRXP_WARN_Be careful not to run into |cRXP_ENEMY_Stitches|r the Abomination who may be patrolling the road between Raven Hill and Darkshire|r
    >>He spawns after a player completes the Hermit questline and is |cRXP_WARN_extremely lethal if pulled|r
    .unitscan Stitches
    .line Duskwood,34.2,60.4,40.6,63.2,44.6,65.7,50.9,66.7,52.8,68.6,54.7,68.7,58.1,65.9,61.7,61.6,65.8,60.0,71.1,59.3,74.2,56.1,75.2,52.2,74.5,46.9

step
    .goto 1431/0,-384.91,-10923.21
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Watcher Dodds|r
    >>|cRXP_WARN_If |cRXP_FRIENDLY_Watcher Dodds|r has been killed due to |cRXP_ENEMY_Stiches|r, skip this step|r
    .accept 245 >> Accept Eight-Legged Menaces
    .target Watcher Dodds
    .maxlevel 23

step
    #label RavenHill
    .goto 1431/0,341.85,-10728.54
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Jitters|r
    .turnin 163 >> Turn in Raven Hill
    .accept 5 >> Accept Jitters' Growling Gut
    .target Jitters

step
    #label Wolves
    #completewith BliztikCheck
    .goto Duskwood,18.040,54.350
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Bliztik|r upstairs
    .vendor >> |cRXP_BUY_Buy as many|r |T134831:0|t[Healing Potions] |cRXP_BUY_that are available|r
    >>|cRXP_WARN_This is a limited supply item. Skip this step if |cRXP_FRIENDLY_Bliztik|r doesn't have any|r
    .target Bliztik

step
    #sticky
    #completewith WestfallTravel

    >>Kill |cRXP_ENEMY_Pygmy Venom Web Spiders|r
    >>|cRXP_WARN_Don't go out of your way to do this quest, skip it if necessary|r
    .complete 245,1
    .mob Pygmy Venom Web Spider
    .isOnQuest 245

step
    .goto 1431/0,563.87,-10788.93,80,0
    .goto 1431/0,537.95,-10563.93,70,0
    .goto Duskwood,9.20,39.04,70,0
    .goto 1431/0,472.61,-10240.11,70,0
    .goto 1431/0,218.27,-10223.91,70,0
    .goto 1431/0,-143.80,-10160.73
    >>Kill |cRXP_ENEMY_Starving Dire Wolves|r and |cRXP_ENEMY_Rabid Dire Wolves|r. Loot them for their |cRXP_LOOT_Lean Wolf Flanks|r
    .complete 226,1
    .mob +Starving Dire Wolf
    .complete 226,2
    .mob +Rabid Dire Wolf
    .collect 1015,10,90,1,1
    .mob +Starving Dire Wolf
    .mob +Rabid Dire Wolf
    .skill cooking,<50,1
    .isOnQuest 226

step
    .goto 1431/0,563.87,-10788.93,80,0
    .goto 1431/0,537.95,-10563.93,70,0
    .goto Duskwood,9.20,39.04,70,0
    .goto 1431/0,472.61,-10240.11,70,0
    .goto 1431/0,218.27,-10223.91,70,0
    .goto 1431/0,-143.80,-10160.73
    >>Kill |cRXP_ENEMY_Starving Dire Wolves|r and |cRXP_ENEMY_Rabid Dire Wolves|r
    .complete 226,1
    .mob +Starving Dire Wolf
    .complete 226,2
    .mob +Rabid Dire Wolf
    .skill cooking,50,1,1
    .mob Starving Dire Wolf
    .mob Rabid Dire Wolf
    .isOnQuest 226

step
    #completewith Flanks
    .isQuestAvailable 90
    >>Kill |cRXP_ENEMY_Wolves|r throughout Duskwood. Loot them for their |cRXP_LOOT_Lean Wolf Flanks|r
    .collect 1015,10,90,1
    .skill cooking,<50,1
    .mob Starving Dire Wolf
    .mob Rabid Dire Wolf
    .mob Young Black Ravager
    .mob Black Ravager
    .mob Black Ravager Mastiff

step
    #label BliztikCheck
    .goto 1431/0,623.27,-10329.75
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sven Yorgen|r
    .turnin 164 >> Turn in Deliveries to Sven
    .target Sven Yorgen
    .accept 95 >> Accept Sven's Revenge

step
    .goto 1431/0,624.81,-10316.08
    .target Lars
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Lars|r
    .turnin -226 >> Turn in Wolves at Our Heels

step
    #label TheHermit
    .goto 1431/0,74.42,-10283.11
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Abercrombie|r
    .turnin 165 >> Turn in The Hermit
    .target Abercrombie
    .accept 148 >> Accept Supplies from Darkshire

step
    #label Flanks
    .goto 1431/0,-73.87,-10803.87,100,0
    .goto 1431/0,503.93,-10973.07,100,0
    .goto 1431/0,547.13,-10382.67,100,0
    .goto 1431/0,487.73,-10717.47
    >>Kill |cRXP_ENEMY_Spiders|r in Duskwood. Loot them for their |cRXP_LOOT_Gooey Spider Legs|r
    .collect 2251,6,93,1
    .mob Pygmy Venom Web Spider
    .mob Venom Web Spider
    .mob Green Recluse
    .mob Black Widow Hatchling

step
    #completewith MoonbrookSt
    .goto 1431/0,-73.87,-10803.87,100,0
    .goto 1431/0,503.93,-10973.07,100,0
    .goto 1431/0,547.13,-10382.67,100,0
    .goto 1431/0,487.73,-10717.47
    +|cRXP_WARN_Grind until your Hearthstone cooldown is <5min|r
    .cooldown item,6948,<300

step
    #completewith MoonbrookSt
    #label WestfallTravel
    .zone Westfall >> Travel to Westfall

step
    #completewith next << !Rogue
    .goto 1436/0,790.67,-10599.33,60,0
    .goto 1436/0,895.67,-10193.33,60,0
    .goto 1436/0,1427.67,-10557.33
    .goto 1436/0,783.67,-10613.33,0
    .goto 1436/0,853.67,-10202.67,0
    .goto 1436/0,1105.67,-10356.67,0
    .goto 1436/0,1378.67,-10534.00,0
    .goto 1436/0,1490.67,-10380.00,0
    .goto Westfall,41.0,21.0,0
    .goto 1436/0,1763.67,-10202.67,0
    .goto 1436/0,1833.67,-10580.67,0
    .goto 1436/0,1525.67,-10804.67,0
    .goto 1436/0,1658.67,-10832.67,0
    .goto 1436/0,1798.67,-10972.67,0
    >>Kill |cRXP_ENEMY_Dust Devils|r. Loot them for their |cRXP_LOOT_Debris|r
    >>|cRXP_ENEMY_Dust Devils|r |cRXP_WARN_can spawn throughout all of Westfall. Their spawn locations are marked on the map|r
    .complete 1076,1
    .unitscan Dust Devil
    .isOnQuest 1076

step
    .goto 1436/0,1037.42,-10628.27
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Thor|r
    .fp Westfall >> Get the Westfall flight path
    .target Thor

step
    .goto 1436/0,790.67,-10599.33,60,0
    .goto 1436/0,895.67,-10193.33,60,0
    .goto 1436/0,1427.67,-10557.33
    .goto 1436/0,783.67,-10613.33,0
    .goto 1436/0,853.67,-10202.67,0
    .goto 1436/0,1105.67,-10356.67,0
    .goto 1436/0,1378.67,-10534.00,0
    .goto 1436/0,1490.67,-10380.00,0
    .goto Westfall,41.0,21.0,0
    .goto 1436/0,1763.67,-10202.67,0
    .goto 1436/0,1833.67,-10580.67,0
    .goto 1436/0,1525.67,-10804.67,0
    .goto 1436/0,1658.67,-10832.67,0
    .goto 1436/0,1798.67,-10972.67,0
    >>Kill |cRXP_ENEMY_Dust Devils|r. Loot them for their |cRXP_LOOT_Debris|r
    >>|cRXP_ENEMY_Dust Devils|r |cRXP_WARN_can spawn throughout all of Westfall. Their spawn locations are marked on the map|r
    .complete 1076,1
    .isOnQuest 1076
    .unitscan Dust Devil

step
    #label MoonbrookSt
    .goto 1436/0,1563.82,-10956.80
    >>Click the |cRXP_PICK_Old Footlocker|r on the ground
    .turnin 67 >> Turn in The Legend of Stalvan
    .accept 68 >> Accept The Legend of Stalvan

step
    #completewith next
    +Look for |cRXP_ENEMY_Old Murk-Eye|r along the coast and kite him toward |cRXP_FRIENDLY_Captain Grayson|r if you see him
    .itemcount 814,5
    .unitscan Old Murk-Eye

step
    .goto 1436/0,1966.32,-11407.13
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Captain Grayson|r
    .accept 104 >> Accept The Coastal Menace
    .accept 103 >> Accept Keeper of the Flame
    .target Captain Grayson
    .itemcount 814,5

step
    .goto 1436/0,1811.62,-11358.37,55,0
    .goto 1436/0,1982.42,-11264.330,60,0
    .goto 1436/0,2026.52,-11058.30,60,0
    .goto 1436/0,2091.97,-10937.20,60,0
    .goto 1436/0,1811.62,-11358.37
    .line 1436/0,1811.62,-11358.37,33.88,83.32,33.08,82.86,32.56,82.71,32.08,82.49,31.91,82.36,31.55,81.88,30.86,81.42,30.63,81.16,30.33,80.81,30.02,80.11,29.68,79.22,29.32,78.19,29.29,77.60,29.27,77.31,29.18,76.26,29.07,75.29,28.95,74.14,28.85,73.29,28.79,72.48,28.37,71.94,27.84,71.29,27.44,70.25,27.29,69.47,27.13,68.65,27.09,67.57,27.07,67.01,26.74,66.09,27.07,67.01,27.09,67.57,27.13,68.65,27.29,69.47,27.44,70.25,27.84,71.29,28.37,71.94,28.79,72.48,28.85,73.29,28.95,74.14,29.07,75.29,29.18,76.26,29.27,77.31,29.29,77.60,29.32,78.19,29.68,79.22,30.02,80.11,30.33,80.81,30.63,81.16,30.86,81.42,31.55,81.88,31.91,82.36,32.08,82.49,32.56,82.71,33.08,82.86,33.88,83.32,34.43,83.93
    >>Kill |cRXP_ENEMY_Old Murk-Eye|r. Loot him for his |cRXP_LOOT_Scale|r
    >>|cRXP_ENEMY_Old Murk-Eye|r |cRXP_WARN_patrols up and down the Longshore. If you don't see him along the Longshore, wait for him to spawn in the most southern |cRXP_ENEMY_Murloc|r camp|r
    .complete 104,1
    .unitscan Old Murk-Eye
    .isOnQuest 104

step
    .goto 1436/0,1966.32,-11407.13
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Captain Grayson|r
    .turnin 104 >> Turn in The Coastal Menace
    .turnin 103 >> Turn in Keeper of the Flame
    .target Captain Grayson
    .isQuestComplete 104
    .itemcount 814,5

step
    .goto 1436/0,1966.32,-11407.13
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Captain Grayson|r
    .turnin 103 >> Turn in Keeper of the Flame
    .itemcount 814,5
    .target Captain Grayson
    .addquestitem 814,103

step
    .goto 1436/0,1966.32,-11407.13
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Captain Grayson|r
    .turnin 104 >> Turn in The Coastal Menace
    .target Captain Grayson
    .isQuestComplete 104

step << Paladin
    .goto 1436/0,1529.17,-11467.33
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Daphne Stilwell|r
    .turnin 1650 >>Turn in The Tome of Valor
    .target Daphne Stilwell
    .accept 1651 >>Accept The Tome of Valor

step << Paladin
    .goto 1436/0,1529.17,-11467.33
    .complete 1651,1
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Daphne Stilwell|r
    .turnin 1651 >>Turn in The Tome of Valor
    .target Daphne Stilwell
    .accept 1652 >>Accept The Tome of Valor

step << !Rogue
    .hs >> Hearth to Darkshire
    >>|cRXP_BUY_Buy food/water if needed|r << !Warrior !Rogue
    >>|cRXP_BUY_Buy food if needed|r << Warrior/Rogue
    .cooldown item,6948,>0,1

step << !Rogue
    #completewith next
    .goto 1436/0,1037.42,-10628.27
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Thor|r
    .fly Darkshire >> Fly to Darkshire
    .target Thor
    .zoneskip Duskwood

step
    .goto 1431/0,-1160.08,-10509.57
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Chef Grual|r in the inn's kitchen
    >>|cRXP_WARN_You need 50 skill in cooking to accept this quest|r
    .accept 90 >> Accept Seasoned Wolf Kabobs
    .turnin 90 >> Turn in Seasoned Wolf Kabobs
    .skill cooking,<50,1
    .itemcount 1015,10
    .target Chef Grual

step
    .goto 1431/0,-1161.43,-10498.77
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Chef Grual|r in the inn's kitchen
    .turnin 5 >> Turn in Jitters' Growling Gut
    .target Chef Grual
    .accept 93 >> Accept Dusky Crab Cakes

step
    .goto 1431/0,-1161.43,-10498.77
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Chef Grual|r in the inn's kitchen
    .target Chef Grual
    .turnin 93 >> Turn in Dusky Crab Cakes
    .isQuestComplete 93

step
    .goto 1431/0,-1153.60,-10560.69
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Commander Althea Ebonlocke|r
    >>|cRXP_WARN_She may be dead or busy fighting|r |cRXP_ENEMY_Stitches|r |cRXP_WARN_if he attacks Darkshire. If that happens consider grinding mobs near the town until she respawns or changing your layer (if possible)|r
    .turnin 56 >> Turn in The Night Watch
    .target Commander Althea Ebonlocke
    .accept 57 >> Accept The Night Watch

step
    .goto 1431/0,-1124.98,-10559.97
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Clerk Daltry|r in the town hall building
    .turnin 68 >> Turn in The Legend of Stalvan
    .target Clerk Daltry
    .accept 69 >> Accept The Legend of Stalvan

step
    .dungeon Stockades
    .goto 1431/0,-1108.99,-10576.67
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Councilman Millstipe|r
    .accept 377 >> Accept Crime and Punishment
    .target Councilman Millstipe

step
    .goto 1431/0,-1213.54,-10531.89
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Madame Eva|r
    .turnin 148 >> Turn in Supplies from Darkshire
    .target Madame Eva
    .accept 149 >> Accept Ghost Hair Thread

step
    .isQuestComplete 177
    .goto Duskwood,79.80,48.02
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Viktori Prism'Antras|r
    .turnin 177 >> Turn in Look To The Stars
    .target Viktori Prism'Antras

step << !Hunter
    #completewith FlyBackDuskwood
    .goto 1431/0,-1258.79,-10513.83
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Felicia Maline|r
    .fly Redridge >> Fly to Redridge Mountains
    .target Felicia Maline
    .maxlevel 25

step << !Hunter
    .dungeon Stockades
    .goto 1431/0,-1258.79,-10513.83
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Felicia Maline|r
    .fly Redridge >> Fly to Redridge Mountains
    .target Felicia Maline

step
    .goto Redridge Mountains,33.50,48.96
    .target Marshal Marris
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Marshal Marris|r
    .accept 20 >> Accept Blackrock Menace
    .maxlevel 25

step
    .dungeon Stockades
    .goto 1433/0,-2140.85,-9249.440
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Guard Berton|r
    .accept 386 >> Accept What Comes Around...
    .target Guard Berton

step
    .goto 1433/0,-2172.68,-9260.98
    .target Dockmaster Baren
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Dockmaster Baren|r
    .accept 127 >> Accept Selling Fish
    .accept 150 >> Accept Murloc Poachers
    .maxlevel 25

step
    #completewith next
    .goto 1433/0,-2795.18,-9325.02,0
    >>Kill |cRXP_ENEMY_Murloc Scouts|r and |cRXP_ENEMY_Murloc Tidecallers|r. Loot them for their |cRXP_LOOT_Fins|r and |cRXP_LOOT_Sunfish|r
    .collect 1468,8,150,1
    .complete 127,1
    .mob Murloc Scout
    .mob Murloc Tidecaller
    .isOnQuest 150
    .isOnQuest 127

step
    #label orcs
    >>Kill |cRXP_ENEMY_Blackrock Grunts|r and |cRXP_ENEMY_Blackrock Outrunners|r. Loot them for their |cRXP_LOOT_Axes|r
    >>|cRXP_WARN_Be aware the |cRXP_ENEMY_Blackrock Outrunners|r will cast|r |T132149:0|t[Net] |cRXP_WARN_on you|r
    >>|cRXP_WARN_Alternate between killing |cRXP_ENEMY_Orcs|r and the |cRXP_ENEMY_Murlocs|r marked on the map southwest|r
    .goto 1433/0,-2911.54,-9204.99
    .complete 20,1
    .isOnQuest 20
    .mob Blackrock Grunt
    .mob Blackrock Outrunner

step
    .goto 1433/0,-2795.18,-9325.02
    >>Kill |cRXP_ENEMY_Murloc Scouts|r and |cRXP_ENEMY_Murloc Tidecallers|r. Loot them for their |cRXP_LOOT_Fins|r and |cRXP_LOOT_Sunfish|r
    .collect 1468,8,150,1
    .complete 127,1
    .mob Murloc Scout
    .mob Murloc Tidecaller
    .isOnQuest 150
    .isOnQuest 127

step
    .goto Redridge Mountains,33.50,48.96
    .target Marshal Marris
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Marshal Marris|r
    .turnin 20 >> Turn in Blackrock Menace
    .isQuestComplete 20

step
    .goto 1433/0,-2172.68,-9260.98
    .target Dockmaster Baren
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Dockmaster Baren|r
    .turnin 127 >> Turn in Selling Fish
    .isQuestComplete 127

step
    .goto 1433/0,-2172.68,-9260.98
    .target Dockmaster Baren
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Dockmaster Baren|r
    .turnin 150 >> Turn in Murloc Poachers
    .isQuestComplete 150

step
    #label FlyBackDuskwood
    .goto Redridge Mountains,30.590,59.410
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ariena Stormfeather|r
    .fly Duskwood >> Fly to Duskwood
    .target Ariena Stormfeather
    .zoneskip Redridge Mountains,1

step
    #completewith Flanks2
    .isQuestAvailable 90
    >>Kill |cRXP_ENEMY_Wolves|r throughout Duskwood. Loot them for their |cRXP_LOOT_Lean Wolf Flanks|r
    .collect 1015,10,90,1
    .skill cooking,<50,1
    .mob Starving Dire Wolf
    .mob Rabid Dire Wolf
    .mob Young Black Ravager
    .mob Black Ravager
    .mob Black Ravager Mastiff

step
    .goto 1431/0,-1380.13,-10780.11
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Blind Mary|r
    .turnin 149 >> Turn in Ghost Hair Thread
    .target Blind Mary
    .accept 154 >> Accept Return the Comb

step
    .goto 1431/0,-1213.54,-10531.89
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Madame Eva|r inside
    .turnin 154 >> Turn in Return the Comb
    .target Madame Eva
    .accept 157 >> Accept Deliver the Thread

step
    #completewith RavenHillTwo
    +|cRXP_WARN_Be careful not to run into |cRXP_ENEMY_Stitches|r the Abomination who may be patrolling the road between Raven Hill and Darkshire|r
    >>He spawns after a player completes the Hermit questline and is |cRXP_WARN_extremely lethal if pulled|r
    .unitscan Stitches
    .line Duskwood,34.2,60.4,40.6,63.2,44.6,65.7,50.9,66.7,52.8,68.6,54.7,68.7,58.1,65.9,61.7,61.6,65.8,60.0,71.1,59.3,74.2,56.1,75.2,52.2,74.5,46.9

step
    .goto 1431/0,-512.62,-11115.45
    >>Click the |cRXP_PICK_Mound of loose dirt|r on the ground
    .turnin 95 >> Turn in Sven's Revenge
    .accept 230 >> Accept Sven's Camp

step
    .goto 1431/0,-384.91,-10923.21
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Watcher Dodds|r
    .turnin 245 >> Turn in Eight-Legged Menaces
    .isQuestComplete 245
    .target Watcher Dodds

step
    .abandon 245 >> Abandon Eight-Legged Menaces if you haven't killed all 15 spiders

step
    #completewith next
    >>Kill |cRXP_ENEMY_Black Widow Hatchlings|r on the way to Abercrombie. Loot them for |T134799:0|t[|cRXP_LOOT_Vials of Spider Venom|r]
    >>|cRXP_WARN_Don't go out of your way to complete this objective now, you will complete it later|r
    .complete 101,2
    .mob Black Widow Hatchling

step
    #label RavenHillTwo
    .goto 1431/0,74.42,-10283.11
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Abercrombie|r
    .turnin 157 >> Turn in Deliver the Thread
    .target Abercrombie
    .accept 158 >> Accept Zombie Juice

step
    .goto 1431/0,623.27,-10329.75
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sven Yorgen|r
    .turnin 230 >> Turn in Sven's Camp
    .target Sven Yorgen
    .accept 262 >> Accept The Shadowy Figure

step
    #label Flanks2
    .goto 1431/0,256.88,-10559.070
    .xp 25+29845 >> Grind to 29845+/34000xp

step
    #completewith RunStocks
    .dungeon Stockades
    +You are about to head to Stormwind soon, try to find a group for The Stockades

step
    #completewith next
    .subzone 87 >> Travel to Goldshire
    .isOnQuest 69

step << Warrior
    .goto 1429/0,109.36,-9461.84
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Lyria Du Lac|r
    .trainer >> Train your class spells
    .target Lyria Du Lac

step << Paladin
    .goto 1429/0,109.04,-9468.16
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Brother Wilhelm|r
    .trainer >> Train your class spells
    .target Brother Wilhelm

step
    .goto 1429/0,16.20,-9462.65
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Innkeeper Farley|r
    .turnin 69 >> Turn in The Legend of Stalvan
    .accept 70 >> Accept The Legend of Stalvan
    .target Innkeeper Farley

step
    #completewith next
    .goto 1429/0,12.52,-9479.85,9 >> Go upstairs

step
    .goto 1429/0,-2.23,-9463.11
    >>Open the |cRXP_PICK_Storage Chest|r. Loot it for |cRXP_LOOT_An Undelivered Letter|r
    .complete 70,1

step << !Mage
    #label RunStocks
    #completewith next
    .zone Stormwind City >> Travel to Stormwind City

step << !Hunter
    .goto 1453/0,801.86,-8999.43
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Collin Mauren|r
    .accept 1078 >> Accept Retrieval for Mauren
    .target Collin Mauren

step
    .goto 1453/0,801.86,-8999.43
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Collin Mauren|r
    .turnin 1076 >> Turn in Devils in Westfall
    .isQuestComplete 1076
    .target Collin Mauren

step
    #optional
    #completewith SlaughteredLamb
    .abandon 1076 >> Abandon Devils in Westfall if you haven't completed the quest by now

step
    .dungeon Stockades
    .goto StormwindClassic,69.25,39.63,40,0
    .goto StormwindClassic,71.28,41.37,40,0
    .goto StormwindClassic,73.33,45.65,40,0
    .goto StormwindClassic,72.44,47.70,40,0
    .goto StormwindClassic,69.25,39.63,40,0
    .goto StormwindClassic,71.28,41.37,40,0
    .goto StormwindClassic,73.33,45.65,40,0
    .goto StormwindClassic,72.44,47.70
    .line StormwindClassic,69.25,39.63,71.28,41.37,73.33,45.65,72.44,47.70,73.33,45.65,71.28,41.37,69.25,39.63
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Nikova Raskol|r
    >>|cRXP_FRIENDLY_Nikova Raskol|r |cRXP_WARN_patrols in Old Town|r
    .accept 388 >> Accept The Color of Blood
    .unitscan Nikova Raskol

step
    .goto StormwindClassic,42.435,59.236,10,0
    .goto StormwindClassic,41.102,58.091
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Warden Thelwater|r
    .accept 391 >> Accept The Stockade Riots
    .accept 387 >> Accept Quell The Uprising
    .target Warden Thelwater
    .isQuestTurnedIn 389
    .dungeon Stockades

step
    .goto StormwindClassic,42.435,59.236,10,0
    .goto StormwindClassic,41.102,58.091
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Warden Thelwater|r
    .accept 387 >> Accept Quell The Uprising
    .target Warden Thelwater
    .dungeon Stockades

step
    .dungeon Stockades
    .goto StormwindClassic,39.834,54.360
    +Find a group for The Stockades. Zone in once your group is ready
    .zoneskip Stormwind City,1

step
    .dungeon Stockades
    #label stock1
    #sticky
    >>Kill the |cRXP_ENEMY_Defias|r. Loot them for their |cRXP_LOOT_Bandanas|r
    .complete 387,1
    .complete 387,2
    .complete 387,3
    .complete 388,1

step
    .dungeon Stockades
    #label stock2
    #sticky
    >>Kill |cRXP_ENEMY_Targorr the Dread|r. Loot him for his |cRXP_LOOT_Head|r. |cRXP_ENEMY_Targorr|r has a random spawn location
    >>Kill |cRXP_ENEMY_Dextren Ward|r on the west prison wing. Loot him for his |cRXP_LOOT_Hand|r
    .complete -386,1
    .mob +Targorr the Dread
    .complete -377,1
    .mob +Dextren Ward

step
    .dungeon Stockades
    #label Bazil
    >>Kill |cRXP_ENEMY_Bazil Thredd|r on the east prison wing. Loot him for his |cRXP_LOOT_Head|r
    >>|cRXP_WARN_Ensure you have 3|r |T132905:0|t[Silk Cloth] |cRXP_WARN_for the follow up of this quest chain|r
    .complete 391,1
    .collect 4306,3,2746,1
    .isOnQuest 391
    .mob Bazil Thredd

step
    .dungeon Stockades
    #requires stock1

step
    .dungeon Stockades
    #requires stock2
    .goto StormwindClassic,41.102,58.091
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Warden Thelwater|r
    .turnin 387 >> Turn in Quell The Uprising
    .turnin 391 >> Turn in The Stockade Riots
    .accept 392 >> Accept The Curious Visitor
    .target Warden Thelwater
    .isQuestTurnedIn 389

step
    .dungeon Stockades
    .goto StormwindClassic,41.102,58.091
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Warden Thelwater|r
    .turnin 387 >> Turn in Quell The Uprising
    .target Warden Thelwater

step
    .dungeon Stockades
    .goto StormwindClassic,49.194,30.283
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Baros Alexston|r
    .turnin 392 >> Turn in The Curious Visitor
    .accept 393 >> Accept Shadow of the Past
    .target Baros Alexston
    .isQuestTurnedIn 389

step
    .dungeon Stockades
    .goto StormwindClassic,69.25,39.63,40,0
    .goto StormwindClassic,71.28,41.37,40,0
    .goto StormwindClassic,73.33,45.65,40,0
    .goto StormwindClassic,72.44,47.70,40,0
    .goto StormwindClassic,69.25,39.63,40,0
    .goto StormwindClassic,71.28,41.37,40,0
    .goto StormwindClassic,73.33,45.65,40,0
    .goto StormwindClassic,72.44,47.70
    .line StormwindClassic,69.25,39.63,71.28,41.37,73.33,45.65,72.44,47.70,73.33,45.65,71.28,41.37,69.25,39.63
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Nikova Raskol|r
    >>|cRXP_FRIENDLY_Nikova Raskol|r |cRXP_WARN_patrols in Old Town|r
    .turnin 388 >> Turn in The Color of Blood
    .unitscan Nikova Raskol

step
    .dungeon Stockades
    #completewith next
    .goto StormwindClassic,74.90,54.00,20,0
    .goto StormwindClassic,78.43,60.15,20,0
    .goto StormwindClassic,78.67,60.13,5 >> Enter the SI:7 Headquarters. Travel up stairs toward |cRXP_FRIENDLY_Master Mathias Shaw|r
    .isQuestTurnedIn 389

step
    .dungeon Stockades
    .goto StormwindClassic,75.78,59.84
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Master Mathias Shaw|r
    .turnin 393 >> Turn in Shadow of the Past
    .accept 350 >> Accept Look to an Old Friend
    .target Master Mathias Shaw
    .isQuestTurnedIn 389

step
    .dungeon Stockades
    .goto StormwindClassic,61.166,64.051,8,0
    .goto StormwindClassic,59.908,64.177
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Elling Trias|r up stairs
    .turnin 350 >> Turn in Look to an Old Friend
    .accept 2745 >> Accept Infiltrating the Castle
    .target Elling Trias
    .isQuestTurnedIn 389

step
    .dungeon Stockades
    #completewith next
    .goto StormwindClassic,70.347,27.208,15,0
    .goto StormwindClassic,72.005,21.542,20 >> Travel to the Stormwind Keep
    .isQuestTurnedIn 391

step
    .dungeon Stockades
    .goto StormwindClassic,69.205,14.404
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Tyrion|r
    .turnin 2745 >> Turn in Infiltrating the Castle
    .accept 2746 >> Accept Items of Some Consequence
    .target Tyrion
    .isQuestTurnedIn 391

step
    .dungeon Stockades
    #completewith next
    .goto 1429/0,411.42,-9093.77,50 >> Exit Stormwind. Travel to Clara's Farm House in Elwynn Forest
    .isQuestTurnedIn 391

step
    .dungeon Stockades
    #ah
    >>Loot |cRXP_LOOT_Clara's Fresh Apples|r on the table
    >>|cRXP_WARN_If you still need|r |T132905:0|t[Silk Cloth] |cRXP_WARN_buy some from the Auction House|r
    .complete 2746,2
    .goto 1429/0,357.00,-9262.65
    .complete 2746,1
    .isQuestTurnedIn 391

step
    .dungeon Stockades
    #ssf
    >>Loot |cRXP_LOOT_Clara's Fresh Apples|r on the table
    .complete 2746,2
    .goto 1429/0,357.00,-9262.65
    .complete 2746,1
    .isQuestTurnedIn 391

step
    .dungeon Stockades
    #completewith next
    .goto StormwindClassic,70.347,27.208,15,0
    .goto StormwindClassic,72.005,21.542,20 >> Travel to the Stormwind Keep
    .isQuestTurnedIn 391

step
    .dungeon Stockades
    .goto StormwindClassic,69.205,14.404
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Tyrion|r
    >>|cRXP_WARN_Ensure your party has all turned in Items of Some Consequence before you accept The Attack!|r
    >>|cRXP_WARN_Automatic quest accept has been turned off for this step. Note you may not be able to accept the quest if someone else is in the process of doing it|r
    .turnin 2746 >> Turn in Items of Some Consequence
    .accept 434,1 >> Accept The Attack!
    .timer 124,The Attack! RP
    .target Tyrion
    .isQuestTurnedIn 391

step
    .dungeon Stockades
    .goto StormwindClassic,68.024,14.075
    >>|cRXP_WARN_Wait in the center of the courtyard for |cRXP_ENEMY_Lord Gregor Lescovar|r and |cRXP_ENEMY_Marzon the Silent Blade|r to arrive. This takes roughly 2 minutes|r
    >>Kill |cRXP_ENEMY_Lord Gregor Lescovar|r and |cRXP_ENEMY_Marzon the Silent Blade|r
    .complete 434,1
    .mob +Lord Gregor Lescovar
    .complete 434,2
    .mob +Marzon the Silent Blade
    .complete 434,3
    .isQuestTurnedIn 391

step
    .dungeon Stockades
    .goto StormwindClassic,61.166,64.051,8,0
    .goto StormwindClassic,59.908,64.177
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Elling Trias|r up stairs
    .turnin 434 >> Turn in The Attack!
    .accept 394 >> Accept The Head of the Beast
    .target Elling Trias
    .isQuestTurnedIn 391

step
    .dungeon Stockades
    #completewith next
    .goto StormwindClassic,74.90,54.00,20,0
    .goto StormwindClassic,78.43,60.15,20,0
    .goto StormwindClassic,78.67,60.13,5 >> Enter the SI:7 Headquarters. Travel up stairs toward |cRXP_FRIENDLY_Master Mathias Shaw|r
    .isQuestTurnedIn 391

step
    .dungeon Stockades
    .goto StormwindClassic,75.78,59.84
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Master Mathias Shaw|r
    .turnin 394 >> Turn in The Head of the Beast
    .accept 395 >> Accept Brotherhood's End
    .target Master Mathias Shaw
    .isQuestTurnedIn 391

step
    .dungeon Stockades
    .goto StormwindClassic,49.194,30.283
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Baros Alexston|r
    .turnin 395 >> Turn in Brotherhood's End
    .accept 396 >> Accept An Audience with the King
    .target Baros Alexston
    .isQuestTurnedIn 391

step
    .dungeon Stockades
    #completewith next
    .goto StormwindClassic,70.347,27.208,20 >> Travel to the Stormwind Keep
    .isQuestTurnedIn 391

step
    .dungeon Stockades
    .goto StormwindClassic,78.105,17.750
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Lady Katrana Prestor|r
    .turnin 396 >> Turn in An Audience with the King
    .target Lady Katrana Prestor
    .isQuestTurnedIn 391

step
    #label SlaughteredLamb
    #completewith next
    .goto 1453/0,988.44,-8942.15,20,0
    .goto 1453/0,1015.33,-8978.90,15 >> Head to the Slaughtered Lamb and go downstairs

step
    .goto 1453/0,1025.55,-8983.92
    .target Zardeth of the Black Claw
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Zardeth of the Black Claw|r
    .accept 335 >> Accept A Noble Brew

step << Warlock
    .goto StormwindClassic,26.117,77.225
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ursula Deline|r
    .trainer >> Train your class spells
    .target Ursula Deline

step
    #completewith next
    .goto 1453/0,1015.33,-8978.90,15 >> Exit the Slaughtered Lamb

step
    .goto 1453/0,984.04,-8833.91
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Caretaker Folsom|r
    .turnin 70 >> Turn in The Legend of Stalvan
    .target Caretaker Folsom
    .accept 72 >> Accept The Legend of Stalvan

step
    .goto 1453/0,985.22,-8830.29
    >>Click the |cRXP_PICK_Sealed Crate|r on the ground
    .turnin 72 >> Turn in The Legend of Stalvan
    .accept 74 >> Accept The Legend of Stalvan

step << Priest/Paladin
    #completewith next
    .goto StormwindClassic,42.51,33.51,20 >> Travel to the Stormwind Cathedral

step << Paladin
    .goto 1453/0,845.82,-8545.87
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Duthorian Rall|r
    .target Duthorian Rall
    .turnin 1652 >>Turn in The Tome of Valor

step << Paladin
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Arthur the Faithful|r
    .goto StormwindClassic,38.82,31.27,10,0
    .goto StormwindClassic,38.67,32.82
    .trainer >> Train your class spells
    .target Arthur the Faithful

step << Warrior
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Wu|r or |cRXP_FRIENDLY_Ilsa|r
    .goto StormwindClassic,76.08,50.14,15,0
    .goto StormwindClassic,80.22,45.37,15,0
    .goto StormwindClassic,78.68,45.79
    .trainer >> Train your class spells
    .target Wu Shen
    .target Ilsa Corbin

step
    #completewith ShadowyRot
    .goto 1453/0,490.03,-8835.82
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Dungar Longdrink|r
    .fly Darkshire >> Fly to Duskwood
    .target Dungar Longdrink

step
    .goto 1431/0,-1272.45,-10586.57
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Herble Baubbletump|r
    .vendor >> |cRXP_BUY_Buy a|r |T133024:0|t[Bronze Tube]
    >>|cRXP_WARN_This is a limited supply item. Skip this step if |cRXP_FRIENDLY_Herble Baubbletump|r doesn't have one|r

    .bronzetube
    .target Herble Baubbletump

step
    .goto Duskwood,79.80,48.02
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Viktori Prism'Antras|r
    .accept 174 >> Accept Look To The Stars
    .turnin 174 >> Turn in Look To The Stars
    .itemcount 4371,1
    .target Viktori Prism'Antras

step
    .goto Duskwood,79.80,48.02
    .target Viktori Prism'Antras
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Viktori Prism'Antras|r
    .accept 175 >> Accept Look To The Stars
    .isQuestTurnedIn 174

step
    .goto 1431/0,-1366.09,-10779.03
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Blind Mary|r
    .turnin 175 >> Turn in Look To The Stars
    .accept 177 >> Accept Look To The Stars
    .target Blind Mary
    .isQuestTurnedIn 174

step
    #completewith next
    >>|cRXP_WARN_Keep at eye out for |T133741:0|t[|cRXP_LOOT_An Old History Book|r]. This is a zone-wide drop in Duskwood|r
    >>|cRXP_WARN_Don't start the quest for it yet|r
    .collect 2794,1,337,1

step
    .goto 1431/0,-1319.38,-10988.19,30,0
    .goto 1431/0,-1353.13,-11006.37
    >>Kill the |cRXP_ENEMY_Insane Ghoul|r. Loot him for |cRXP_LOOT_Mary's Looking Glass|r
    >>|cRXP_WARN_The |cRXP_ENEMY_Insane Ghoul|r may be inside of the chapel or walking around outside|r
    .complete 177,1
    .mob Insane Ghoul
    .isQuestTurnedIn 174

step
    .isQuestComplete 177
    .goto Duskwood,79.80,48.02
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Viktori Prism'Antras|r
    .turnin 177 >> Turn in Look To The Stars
    .target Viktori Prism'Antras

step
    .goto 1431/0,-1199.82,-10581.49
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Calor|r
    .accept 173 >> Accept Worgen in the Woods
    .target Calor

step
    .goto 1431/0,-1213.54,-10531.89
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Madame Eva|r inside
    .turnin 262 >> Turn in The Shadowy Figure
    .target Madame Eva
    .accept 265 >> Accept The Shadowy Search Continues

step
    .goto 1431/0,-1124.98,-10559.97
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Clerk Daltry|r in the town hall building
    .turnin 265 >> Turn in The Shadowy Search Continues
    .target Clerk Daltry
    .accept 266 >> Accept Inquire at the Inn

step
    .dungeon Stockades
    .goto 1431/0,-1108.99,-10576.67
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Councilman Millstipe|r
    .turnin 377 >> Turn in Crime and Punishment
    .target Councilman Millstipe

step
    #label ShadowyRot
    .goto 1431/0,-1158.46,-10517.31
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Tavernkeep Smitts|r inside the inn
    .turnin 158 >> Turn in Zombie Juice
    .target Tavernkeep Smitts
    .accept 156 >> Accept Gather Rot Blossoms
    .turnin 266 >> Turn in Inquire at the Inn
    .accept 453 >> Accept Finding the Shadowy Figure

step
    .goto 1431/0,-1160.08,-10509.57
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Chef Grual|r in the inn's kitchen
    >>|cRXP_WARN_You need 50 skill in cooking to accept this quest|r
    .accept 90 >> Accept Seasoned Wolf Kabobs
    .turnin 90 >> Turn in Seasoned Wolf Kabobs
    .skill cooking,<50,1
    .itemcount 1015,10
    .target Chef Grual

step
    .goto 1431/0,-1161.43,-10498.77
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Chef Grual|r in the inn's kitchen
    .target Chef Grual
    .turnin 93 >> Turn in Dusky Crab Cakes
    .accept 240 >> Accept Return to Jitters

step
    #completewith Flanks3
    .isQuestAvailable 90
    >>Kill |cRXP_ENEMY_Wolves|r throughout Duskwood. Loot them for their |cRXP_LOOT_Lean Wolf Flanks|r
    .collect 1015,10,90,1
    .skill cooking,<50,1
    .mob Starving Dire Wolf
    .mob Rabid Dire Wolf
    .mob Young Black Ravager
    .mob Black Ravager
    .mob Black Ravager Mastiff

step
    #completewith next
    +|cRXP_WARN_Be careful not to run into |cRXP_ENEMY_Stitches|r the Abomination who may be patrolling the road between Raven Hill and Darkshire|r
    >>He spawns after a player completes the Hermit questline and is |cRXP_WARN_extremely lethal if pulled|r
    .unitscan Stitches
    .line Duskwood,34.2,60.4,40.6,63.2,44.6,65.7,50.9,66.7,52.8,68.6,54.7,68.7,58.1,65.9,61.7,61.6,65.8,60.0,71.1,59.3,74.2,56.1,75.2,52.2,74.5,46.9

step
    #completewith next
    .goto 1431/0,213.68,-10522.17,150 >> Travel to Raven Hill Cemetery

step
    .goto 1431/0,337.34,-10731.15
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Jitters|r
    .turnin 453 >> Turn in Finding the Shadowy Figure
    .target Jitters
    .accept 268 >> Accept Return to Sven
    .turnin 240 >> Turn in Return to Jitters

step
    #completewith HistoryBook
    >>|cRXP_WARN_Keep at eye out for |T133741:0|t[|cRXP_LOOT_An Old History Book|r]. This is a zone-wide drop in Duskwood|r
    >>|cRXP_WARN_Don't start the quest for it yet|r
    .collect 2794,1,337,1

step
    .goto 1431/0,213.68,-10522.17,80,0
    .goto 1431/0,282.80,-10563.03,70,0
    .goto 1431/0,426.44,-10561.05,70,0
    .goto 1431/0,410.78,-10487.25,70,0
    .goto Duskwood,18.30,47.75,70,0
    .goto 1431/0,236.36,-10561.41,70,0
    .goto 1431/0,193.97,-10475.01,70,0
    .goto 1431/0,260.66,-10563.93
    >>Kill |cRXP_ENEMY_Skeletal Fiends|r and |cRXP_ENEMY_Skeletal Horrors|r. Loot them for their |cRXP_LOOT_Rot Blossoms|r
    .complete 57,1
    .mob +Skeletal Fiend
    .complete 57,2
    .mob +Skeletal Horror
    .complete 156,1
    .mob +Skeletal Fiend
    .mob +Skeletal Horror

step
    #label Flanks3
    .goto 1431/0,623.27,-10329.75
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sven Yorgen|r
    .turnin 268 >> Turn in Return to Sven
    .accept 323 >> Accept Proving Your Worth
    .target Sven Yorgen

step
    .goto 1431/0,401.06,-10414.89
    >>Kill |cRXP_ENEMY_Skeletal Raiders|r, |cRXP_ENEMY_Skeletal Healers|r and |cRXP_ENEMY_Skeletal Warders|r
    >>|cRXP_WARN_Enter the Dawning Wood Catacombs for the|r |cRXP_ENEMY_Skeletal Warders|r
    >>|cRXP_ENEMY_Mor'Ladim|r |cRXP_WARN_a level 35 Elite patrols around the cemetery. Be cautious of him|r
    .complete 323,1
    .mob +Skeletal Raider
    .complete 323,2
    .mob +Skeletal Healer
    .complete 323,3
    .mob +keletal Warder
    .unitscan Mor'Ladim

step
    #completewith next
    +Grind mobs until your |T134414:0|t[Hearthstone] is off cooldown. |cRXP_WARN_Don't hearth before turning in Proving Your Worth and accepting the follow-up!|r
    .cooldown item,6948,<0,1

step
    .goto 1431/0,623.27,-10329.75
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sven Yorgen|r
    .turnin 323 >> Turn in Proving Your Worth
    .target Sven Yorgen
    .accept 269 >> Accept Seeking Wisdom

step
    #completewith dusk2
    >> Grind mobs until your Hearthstone is off cooldown
    .hs >> Hearth to Darkshire
    >>|cRXP_BUY_Buy food/water if needed|r << !Warrior !Rogue
    >>|cRXP_BUY_Buy food if needed|r << Warrior/Rogue

step
    #completewith next
    .fly Duskwood >> If you haven't found a |T133024:0|t[Bronze Tube], save your Hearthstone cooldown and fly from Westfall to Duskwood
    .bronzetube

step
    #label dusk2
    .goto 1431/0,-1158.46,-10517.31
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Tavernkeep Smitts|r inside the inn
    .turnin 156 >> Turn in Gather Rot Blossoms
    .accept 159 >> Accept Juice Delivery
    .target Tavernkeep Smitts

step
    .goto 1431/0,-1160.08,-10509.57
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Chef Grual|r in the inn's kitchen
    >>|cRXP_WARN_You need 50 skill in cooking to accept this quest|r
    .accept 90 >> Accept Seasoned Wolf Kabobs
    .turnin 90 >> Turn in Seasoned Wolf Kabobs
    .skill cooking,<50,1
    .itemcount 1015,10
    .target Chef Grual

step
    .goto 1431/0,-1153.60,-10560.69
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Commander Althea Ebonlocke|r
    >>|cRXP_WARN_She may be dead or busy fighting|r |cRXP_ENEMY_Stitches|r |cRXP_WARN_if he attacks Darkshire. If that happens consider grinding mobs near the town until she respawns or changing your layer (if possible)|r
    .turnin 57 >> Turn in The Night Watch
    .accept 58 >> Accept The Night Watch
    .target Commander Althea Ebonlocke

step
    .dungeon Stockades
    .goto 1431/0,-1258.79,-10513.83
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Felicia Maline|r
    .fly Redridge >> Fly to Redridge Mountains
    .target Felicia Maline
    .zoneskip Redridge Mountains

step
    #season 0,1
    #label HistoryBook
    #completewith RRstart2
    .goto 1431/0,-1258.79,-10513.83
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Felicia Maline|r
    >>Run along the road north to Redridge if you don't have the Redridge Flight Path yet
    .fly Redridge >> Fly to Redridge Mountains
    .target Felicia Maline
    .zoneskip Redridge Mountains
    .maxlevel 27

step
    #sticky
    .home >> Set your Hearthstone to Redridge if you haven't found a |T133024:0|t[Bronze Tube]
    >>Skip this step if you purchased it already
    .bronzetube
    .maxlevel 27

step
    .goto 1433/0,-2255.30,-9412.62
    .target Guard Howe
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Guard Howe|r
    .accept 128 >> Accept Blackrock Bounty
    .maxlevel 27

step << Hunter/Warlock
    .solo
    #label RRstart2
    .goto Redridge Mountains,33.50,48.96
    .target Marshal Marris
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Marshal Marris|r
    .accept 19 >> Accept Tharil'zun
    .isQuestTurnedIn 20
    .maxlevel 27

step
    .group
    #label RRstart2
    .goto Redridge Mountains,33.50,48.96
    .target Marshal Marris
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Marshal Marris|r
    .accept 19 >> Accept Tharil'zun
    .accept 115 >> Accept Shadow Magic
    .isQuestTurnedIn 20
    .maxlevel 27

step << !Hunter
    .goto Redridge Mountains,31.00,47.30
    .target Verner Osgood
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Verner Osgood|r
    .accept 126 >> Accept Howling in the Hills
    .isQuestTurnedIn 124
    .maxlevel 27

step
    .group
    .goto 1433/0,-2213.88,-9243.53
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tClick on |cRXP_FRIENDLY_The Wanted Poster|r
    .accept 169 >> Accept Wanted: Gath'Ilzogg
    .maxlevel 27

step
    .goto 1433/0,-2215.79,-9215.85
    .target Bailiff Conacher
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Bailiff Conacher|r
    .accept 91 >> Accept Solomon's Law
    .maxlevel 27

step
    .goto 1433/0,-2151.53,-9247.27
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tClick on |cRXP_FRIENDLY_The Wanted Poster|r
    .accept 180 >> Accept Wanted: Lieutenant Fangore
    .maxlevel 27

step
    #optional
    .isQuestComplete 386
    .goto 1433/0,-2140.85,-9249.440
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Guard Berton|r
    .turnin 386 >> Turn in What Comes Around...
    .target Guard Berton
    .maxlevel 27

step
    .goto 1433/0,-2045.16,-9245.67
    .target Martie Jainrose
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Martie Jainrose|r
    .accept 34 >> Accept An Unwelcome Guest
    .maxlevel 27

step
    .goto 1433/0,-1911.22,-9288.820
    >>Kill |cRXP_ENEMY_Bellygrub|r. Loot him for his |cRXP_LOOT_Tusk|r
    .complete 34,1
    .mob Bellygrub
    .isOnQuest 34

step
    #label RRstart2 << !Hunter !Warlock
    .goto 1433/0,-2045.16,-9245.67
    .target Martie Jainrose
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Martie Jainrose|r
    .turnin 34 >> Turn in An Unwelcome Guest
    .isQuestComplete 34

step
    .goto 1433/0,-2086.84,-9016.32,80,0
    .goto 1433/0,-2169.55,-8890.36
    >>Kill |cRXP_ENEMY_Yowler|r. Loot him for his |cRXP_LOOT_Paw|r
    .complete 126,1
    .mob Yowler
    .isOnQuest 126

step
    #completewith Pendants
    .goto 1433/0,-3311.19,-9111.45
    >>Kill |cRXP_ENEMY_Lieutenant Fangore|r. Loot him for his |cRXP_LOOT_Paw|r
    >>|cRXP_ENEMY_Lieutenant Fangore|r |cRXP_WARN_will engage with 2 additional|r |cRXP_ENEMY_Gnolls|r
    >>|cRXP_ENEMY_Lieutenant Fangore|r |cRXP_WARN_is immune to Shadow damage. Ensure you have party members that can help, otherwise you may skip this step|r << Warlock/Priest
    .complete 180,1
    .isOnQuest 180
    .mob Lieutenant Fangore

step
    #sticky
    #label Eye
    .goto Redridge Mountains,84.50,46.80
    >>Click the |cRXP_PICK_Old Lion Statue|r
    .turnin 94 >> Turn in A Watchful Eye
    .isOnQuest 94
    .zoneskip Redridge Mountains,1

step
    .group
    .goto Redridge Mountains,84.50,46.80
    >>Click the |cRXP_PICK_Old Lion Statue|r
    .accept 248 >> Accept Looking Further
    .isQuestTurnedIn 94

step
    #label Pendants
    .goto 1433/0,-3209.60,-9176.90,60,0
    .goto 1433/0,-3309.45,-9106.10,60,0
    .goto 1433/0,-3322.48,-9245.10,60,0
    .goto 1433/0,-3255.83,-9187.18,60,0
    .goto 1433/0,-3253.66,-9100.74
    >>Kill the |cRXP_ENEMY_Shadowhides|r. Loot them for their |cRXP_LOOT_Pendants|r
    .complete 91,1
    .mob Rabid Shadowhide Gnoll
    .mob Shadowhide Gnoll
    .mob Shadowhide Assassin
    .mob Shadowhide Warrior
    .mob Shadowhide Darkweaver
    .mob Shadowhide Slayer
    .isOnQuest 91

step
    #label fangore
    .goto 1433/0,-3311.19,-9111.45
    >>Kill |cRXP_ENEMY_Lieutenant Fangore|r. Loot him for his |cRXP_LOOT_Paw|r
    >>|cRXP_ENEMY_Lieutenant Fangore|r |cRXP_WARN_will engage with 2 additional|r |cRXP_ENEMY_Gnolls|r
    >>|cRXP_ENEMY_Lieutenant Fangore|r |cRXP_WARN_is immune to Shadow damage. Ensure you have party members that can help, otherwise you may skip this step|r << Warlock/Priest
    .complete 180,1
    .isOnQuest 180
    .mob Lieutenant Fangore

step
    .group 3
    #completewith Gath
    >>Kill |cRXP_ENEMY_Blackrock Shadowcasters|r. Loot them for their |cRXP_LOOT_Orbs|r
    .complete 115,1
    .mob Blackrock Shadowcaster
    .isOnQuest 115

step
    .group 3
    #completewith next
    .goto Redridge Mountains,71.40,55.07
    >>Kill |cRXP_ENEMY_Tharil'zun|r. Loot him for his |cRXP_LOOT_Head|r
    .complete 19,1
    .mob Tharil'zun
    .isOnQuest 19

step
    #label Gath
    .group 5
    .goto 1433/0,-3081.71,-9382.89
    >>Enter Stonewatch Keep
    >>Kill |cRXP_ENEMY_Gath'Ilzogg|r. Loot him for his |cRXP_LOOT_Head|r
    .complete 169,1
    .mob Gath'Ilzogg
    .isOnQuest 169

step
    #completewith next
    >>Kill |cRXP_ENEMY_Blackrock Shadowcasters|r. Loot them for their |cRXP_LOOT_Orbs|r
    .complete 115,1
    .mob Blackrock Shadowcaster
    .isOnQuest 115

step
    .group 3
    .goto Redridge Mountains,71.40,55.07
    >>Kill |cRXP_ENEMY_Tharil'zun|r. Loot him for his |cRXP_LOOT_Head|r
    .complete 19,1
    .mob Tharil'zun
    .isOnQuest 19

step
    .group 3
    .goto 1433/0,-3018.35,-9389.60
    >>Kill |cRXP_ENEMY_Blackrock Shadowcasters|r. Loot them for their |cRXP_LOOT_Orbs|r
    .complete 115,1
    .mob Blackrock Shadowcaster
    .isOnQuest 115

step << Hunter/Warlock
    .solo
    #requires Eye
    .goto Redridge Mountains,71.40,55.07
    >>Kill |cRXP_ENEMY_Tharil'zun|r. Loot him for his |cRXP_LOOT_Head|r
    >>Kite |cRXP_ENEMY_Tharil'zun|r towards Burning Steppes if needed. You can pull him from down below with your pet
    >>This quest can be very hard, skip this step if you have to
    .link https://youtu.be/YACKgdPlSGY >> |cRXP_WARN_Click here for video reference|r << Warlock
    .complete 19,1
    .mob Tharil'zun
    .isOnQuest 19

step
    .group 3
    .goto 1433/0,-2943.80,-9296.640
    >>Click |cRXP_PICK_An Empty Jar|r on the barrel at the top of Stonewatch Tower
    >>|cRXP_WARN_Don't accept the follow up|r
    .turnin 248 >> Turn in Looking Further
    .isOnQuest 248

step
    #requires Eye
    .goto 1433/0,-2197.99,-8766.120
    >>Kill |cRXP_ENEMY_Blackrock Champions|r
    .complete 128,1
    .isOnQuest 128

step
    #sticky
    .goto 1428/0,-2554.93,-8504.68,90,0
    .goto 1428/0,-2201.67,-7459.93
    .maxlevel 27
    .vendor >> If you haven't found a |T133024:0|t[Bronze Tube], skip the escort quest, run north to Burning Steppes, die on purpose, buy a |T133024:0|t[Bronze Tube] from |cRXP_FRIENDLY_Yuka|r in the cave at Flame's Crest and Hearth back to Redridge
    .bronzetube
    .target Yuka Screwspigot

step
    .goto 1433/0,-2187.09,-8756.89
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Corporal Keeshan|r in the back of Render's Rock
    .accept 219 >> Accept Missing In Action
    .target Corporal Keeshan
    .maxlevel 27

step
    .goto 1433/0,-2296.20,-9277.22
    >>Escort |cRXP_FRIENDLY_Corporal Keeshan|r back to Lakeshire
    >>|cRXP_WARN_Be careful to not pull too many mobs right after you leave the cave|r
    .complete 219,1
    .isOnQuest 219
    .target Corporal Keeshan

step
    .goto Redridge Mountains,33.50,48.96
    .target Marshal Marris
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Marshal Marris|r
    .turnin 19 >> Turn in Tharil'zun
    .isQuestComplete 19

step
    .goto Redridge Mountains,33.50,48.96
    .target Marshal Marris
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Marshal Marris|r
    .turnin 115 >> Turn in Shadow Magic
    .isQuestComplete 115

step
    .goto 1433/0,-2221.65,-9218.60
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Magistrate Solomon|r
    .turnin 169 >> Turn in Wanted: Gath'Ilzogg
    .target Magistrate Solomon
    .isQuestComplete 169

step
    .goto Redridge Mountains,33.50,48.96
    .target Marshal Marris
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Marshal Marris|r
    .turnin 219 >> Turn in Missing In Action
    .isQuestComplete 219

step
    .goto 1433/0,-2215.79,-9215.85
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Bailiff Conacher|r
    .turnin 91 >> Turn in Solomon's Law
    .isQuestComplete 91
    .target Bailiff Conacher

step
    .goto 1433/0,-2221.65,-9218.60
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Magistrate Solomon|r
    .turnin 180 >> Turn in Wanted: Lieutenant Fangore
    .isQuestComplete 180
    .target Magistrate Solomon

step
    .goto 1433/0,-2243.14,-9259.43
    .target Verner Osgood
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Verner Osgood|r
    .turnin 126 >> Turn in Howling in the Hills
    .isQuestComplete 126

step
    #label RedridgeEndTwo
    .goto 1433/0,-2255.30,-9412.62
    .target Guard Howe
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Guard Howe|r
    .turnin 128 >> Turn in Blackrock Bounty
    .isQuestComplete 128

step
    #optional
    .abandon 19 >> Abandon Tharil'zun, you won't be heading back to Redridge

step
    #label end
    .goto Redridge Mountains,30.590,59.410
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ariena Stormfeather|r
    .fly Stormwind >> Fly to Stormwind
    .target Ariena Stormfeather
    .zoneskip Stormwind City
]])
