-- Generated by Scripts/split_guide_vault.py; rerun the script to update.
if not RXPGuides or type(RXPGuides.RegisterGuide) ~= "function" then return end
local _, rxpGuideVaultAddon = ...
local rxpGuideVaultGame = rxpGuideVaultAddon and rxpGuideVaultAddon.game
if not rxpGuideVaultGame then
    local rxpGuideVaultVersion = select(4, GetBuildInfo())
    if rxpGuideVaultVersion > 60000 then
        rxpGuideVaultGame = "RETAIL"
    elseif rxpGuideVaultVersion > 50000 then
        rxpGuideVaultGame = "MOP"
    elseif rxpGuideVaultVersion > 40000 then
        rxpGuideVaultGame = "CATA"
    elseif rxpGuideVaultVersion > 30000 then
        rxpGuideVaultGame = "WOTLK"
    elseif rxpGuideVaultVersion > 20000 then
        rxpGuideVaultGame = "TBC"
    elseif rxpGuideVaultVersion >= 16000 and rxpGuideVaultVersion < 20000 then
        rxpGuideVaultGame = "FOREVER"
    else
        rxpGuideVaultGame = "CLASSIC"
    end
end
if rxpGuideVaultGame ~= "FOREVER" then return end

RXPGuides.RegisterGuide([[#forever
#version 23
#group RestedXP Forever Guide (A)
#subgroup Speedrun Guide 30-40

<< Alliance
#name 36-38 Stranglethorn Vale II
#next 38-39 Swamp of Sorrows

step
    #sticky
    #label BankD1
    .goto 1434/0,527.31,-14426.160,-1
    .goto 1434/0,528.84,-14421.95,-1
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Viznik|r or |cRXP_FRIENDLY_Rickle|r
    .bankdeposit 6253,3518,5539,6245,5827,3404 >>Deposit the following items into your bank:
    >>|T133633:0|t[Karnitol's Satchel]
    >>|T134940:0|t[Decrypted Letter]
    >>|T133460:0|t[Letter of Commendation]
    >>|T133469:0|t[Fizzle Brassbolts' Letter]
    >>|T134304:0|t[Buzzard Wing]
    .target Viznik Goldgrubber
    .target Rickle Goldgrubber

step
    #sticky
    #label BankW1
    .goto 1434/0,527.31,-14426.160,-1
    .goto 1434/0,528.84,-14421.95,-1
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Viznik|r or |cRXP_FRIENDLY_Rickle|r
    .bankwithdraw 2719,5996 >> Withdraw the |T134238:0|t[Small Brass Key] from your bank (if you have it) << !Warlock
    .bankwithdraw 2719 >> Withdraw the |T134238:0|t[Small Brass Key] from your bank (if you have it) << Warlock
    >>Withdraw the |T134797:0|t[Elixir of Water Breathing] from your bank (if you have them) << !Warlock
    >>If you don't have one or other of the items, skip this step
    .target Viznik Goldgrubber
    .target Rickle Goldgrubber

step << !Warlock
    #ah
    #requires BankW1
    .goto 1434/0,524.06,-14417.66
    >>If you didn't have any |T134797:0|t[Elixir of Water Breathing] in your bank, try buying some from the Auction House. Skip this step if you can't find them.
    .collect 5996,1

step
    #requires BankW1
    .goto 1434/0,495.34,-14457.65
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Innkeeper Skindle|r
    .home >>Set your Hearthstone to Booty Bay

    .target Innkeeper Skindle

step
    #requires BankW1
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Krazek|r upstairs on the top floor
    .turnin 1115 >> Turn in The Rumormonger
    .goto 1434/0,501.53,-14453.26
    .target Krazek
    .isOnQuest 1115

step
    #requires BankW1
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kebok|r up stairs on the top floor
    .accept 189 >> Accept Bloodscalp Ears
    .goto Stranglethorn Vale,27.000,77.124
    .target Kebok

step
    .goto 1434/0,483.41,-14438.930
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Baron Revilgaz|r
    .accept 601 >> Accept Water Elementals
    .target Baron Revilgaz

step
    .goto 1434/0,415.32,-14469.64
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Drizzlik|r
    .accept 577 >> Accept Some Assembly Required
    .target Drizzlik
    .isQuestTurnedIn 575

step
    .goto 1434/0,425.15,-14491.68
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|t|cRXP_BUY_Talk to|r |cRXP_FRIENDLY_Glyx|r
    .vendor >> |cRXP_BUY_Buy|r |T134832:0|t[Greater Healing Potions] |cRXP_BUY_from him if they're up|r
    .target Glyx Brewright

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gyll|r
    .goto Stranglethorn Vale,27.530,77.787
    .fly Westfall >> Fly to Westfall
    .target Gyll

step
    .goto 1431/0,623.27,-10329.75
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sven Yorgen|r
    .turnin 325 >> Turn in Armed and Ready
    .accept 55 >> Accept Morbent Fel
    .target Sven Yorgen
    .isOnQuest 325

step
    #optional
    .goto 1431/0,623.27,-10329.75
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sven Yorgen|r
    .accept 55 >> Accept Morbent Fel
    .target Sven Yorgen
    .isQuestTurnedIn 325
    .isQuestAvailable 55

step
    .goto 1431/0,304.40,-10387.71
    >>Kill |cRXP_ENEMY_Mor'Ladim|r. Loot him for his |cRXP_LOOT_Skull|r
    >>|cRXP_ENEMY_Mor'Ladim|r |cRXP_WARN_hits very hard but moves quite slow. Try to kite him around any large trees if required|r
    .complete 228,1
    .unitscan Mor'Ladim
    .isOnQuest 228

step
    #completewith next
    >>Clear your way to the 2nd floor of the house
    .cast 8913 >>|cRXP_WARN_Equip|r |T135142:0|t[Morbent's Bane] |cRXP_WARN_in your off-hand|r
    >>|cRXP_WARN_Use|r |T135142:0|t[Morbent's Bane] |cRXP_WARN_on|r |cRXP_ENEMY_Morbent Fel|r |cRXP_WARN_to weaken him|r
    >>|cRXP_WARN_Remember to equip your weapon/off-hand slot after weakening him|r
    .use 7297

step
    .goto Duskwood,16.90,33.40
    >>Kill |cRXP_ENEMY_Morbent Fel|r
    >>|cRXP_WARN_This quest can be difficult. If you aren't confident doing it, you may skip this step|r
    .complete 55,1
    .use 7297
    .mob Morbent Fel
    .isOnQuest 55

step
    .goto 1431/0,623.27,-10329.75
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sven Yorgen|r
    .turnin 55 >> Turn in Morbent Fel
    .isQuestComplete 55
    .target Sven Yorgen

step
    .abandon 55 >> Abandon Morbent Fel

step
    #completewith next
    .goto 1431/0,-370.81,-11292.84,0
    .goto 1434/0,-372.19,-11318.24,40,0
    .goto 1434/0,-244.24,-11383.59
    .subzone 99 >> Travel to the Rebel Camp in northern Stranglethorn Vale

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sergeant Yohwa|r and |cRXP_FRIENDLY_Brother Nimetz|r
    .accept 574 >> Accept Special Forces
    .target +Sergeant Yohwa
    .goto 1434/0,-205.13,-11310.410
    .accept 207 >> Accept Kurzen's Mystery
    .target +Brother Nimetz
    .goto 1434/0,-193.32,-11320.16

step
    .isQuestTurnedIn 215
    .goto 1434/0,-206.72,-11296.89
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Lieutenant Doren|r
    .accept 200 >> Accept Bookie Herod
    .target Lieutenant Doren

step
    #optional
    .isOnQuest 622
    .goto Stranglethorn Vale,37.740,3.300
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Corporal Kaleb|r
    .turnin 622 >> Turn in Return to Corporal Kaleb
    .target Corporal Kaleb

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Hemet Nesingwary|r, |cRXP_FRIENDLY_Ajeck Rouack|r and |cRXP_FRIENDLY_Sir S. J. Erlgadin|r
    .accept 195 >> Accept Raptor Mastery
    .target +Hemet Nesingwary
    .goto 1434/0,-54.59,-11628.54
    .accept 188 >> Accept Tiger Mastery
    .target +Ajeck Rouack
    .goto 1434/0,-51.91,-11620.50
    .accept 192 >> Accept Panther Mastery
    .target +Sir S. J. Erlgadin
    .goto 1434/0,-48.08,-11617.39
    .isQuestTurnedIn 194
    .isQuestTurnedIn 187
    .isQuestTurnedIn 191

step
    #optional
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Hemet Nesingwary|r
    .accept 195 >> Accept Raptor Mastery
    .target +Hemet Nesingwary
    .goto 1434/0,-54.59,-11628.54
    .isQuestTurnedIn 194

step
    #optional
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ajeck Rouack|r
    .accept 188 >> Accept Tiger Mastery
    .target +Ajeck Rouack
    .goto 1434/0,-51.91,-11620.50
    .isQuestTurnedIn 187

step
    #optional
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sir S. J. Erlgadin|r
    .accept 192 >> Accept Panther Mastery
    .target +Sir S. J. Erlgadin
    .goto 1434/0,-48.08,-11617.39
    .isQuestTurnedIn 191

step
    .isQuestTurnedIn 215
    .goto 1434/0,-565.79,-11567.45
    >>Click on |cRXP_PICK_Bookie Herod's Records|r upstairs in the house
    .turnin 200 >> Turn in Bookie Herod
    .accept 328 >> Accept The Hidden Key

step
    #completewith SpecialForces
    .goto Stranglethorn Vale,46.30,7.61,30 >> Enter The Stockpile (Kurzen's Cave)

step
    #completewith next
    .isQuestTurnedIn 215
    .goto 1434/0,-945.35,-11490.45
    >>Click |cRXP_PICK_Bookie Herod's Strongbox|r on the ground
    .turnin 328 >> Turn in The Hidden Key
    .accept 329 >> Accept The Spy Revealed!

step
    #label SpecialForces
    .goto 1434/0,-743.26,-11461.86,40,0
    .goto 1434/0,-835.15,-11499.30,40,0
    .goto 1434/0,-743.26,-11461.86
    >>Kill |cRXP_ENEMY_Kurzen Commandos|r and |cRXP_ENEMY_Kurzen Headshrinkers|r. Loot them for their |T132905:0|t[Silk Cloth]
    >>|cRXP_WARN_Be cautious of |cRXP_ENEMY_Kurzen Commandos|r in|r |T132320:0|t[Stealth]
    >>|cRXP_WARN_Save 15|r |T132905:0|t[Silk Cloth] |cRXP_WARN_for a quest for later in Searing Gorge. You don't need to collect all 15 now|r
    .collect 4306,15,4449,1,1
    .complete 574,1
    .mob +Kurzen Commando
    .complete 574,2
    .mob +Kurzen Headshrinker

step
    .isQuestTurnedIn 215
    .goto 1434/0,-945.35,-11490.45
    >>Click |cRXP_PICK_Bookie Herod's Strongbox|r on the ground
    .turnin 328 >> Turn in The Hidden Key
    .accept 329 >> Accept The Spy Revealed!

step << Warrior
    #ah
    .goto 1434/0,-618.82,-11577.15
    >>Kill |cRXP_ENEMY_Kurzen Medicine Men|r. Loot them for their |T134413:0|t[Liferoot]
    >>|cRXP_WARN_This is for your|r |T132403:0|t[|cFF0070FFWhirlwind Axe|r] |cRXP_WARN_quest. You may also buy them from the Auction House if you wish. If you will buy them from the Auction House, skip this step|r
    >>|cRXP_WARN_If you are planning on running Scarlet Monastery for the|r [|cFF0070FFBonebiter|r]|cRXP_WARN_, you may skip this step|r
    .complete 1712,1
    .isOnQuest 1712
    .mob Kurzen Medicine Man

step << Warrior
    .goto 1434/0,-618.82,-11577.15
    >>Kill |cRXP_ENEMY_Kurzen Medicine Men|r. Loot them for their |T134413:0|t[Liferoot]
    >>|cRXP_WARN_This is for your|r |T132403:0|t[|cFF0070FFWhirlwind Axe|r] |cRXP_WARN_quest|r
    >>|cRXP_WARN_If you are planning on running Scarlet Monastery for the|r [|cFF0070FFBonebiter|r]|cRXP_WARN_, you may skip this step|r
    .complete 1712,1
    .isOnQuest 1712
    .mob Kurzen Medicine Man

step
    #loop
    .goto 1434/0,-883.01,-12145.08,0,55
    .goto 1434/0,-892.58,-12017.88,0,55
    .goto 1434/0,-897.05,-12167.63,0,55
    .goto 1434/0,-816.64,-12189.75,0,55
    .goto Stranglethorn Vale,48.0,27.6,0,55
    .goto 1434/0,-682.64,-12457.76,0,55
    .goto Stranglethorn Vale,45.0,26.2,0,55
    .goto 1434/0,-82.16,-12755.13,0,55
    >>Kill |cRXP_ENEMY_Shadowmaw Panthers|r
    >>|cRXP_ENEMY_Shadowmaw Panthers|r |cRXP_WARN_are in|r |T132320:0|t[Stealth]
    >>|cRXP_WARN_You can find more further south-west if needed. The location is marked on your map|r
    >>|cRXP_WARN_They also share spawns with|r |cRXP_ENEMY_Stranglethorn Tigresses|r|cRXP_WARN_. This means if you see an empty area with no |cRXP_ENEMY_Tigresses|r there is likely a panther there|r
    .complete 192,1
    .mob Shadowmaw Panther
    .isOnQuest 192

step
    #completewith next
    >>Kill |cRXP_ENEMY_Lashtail Raptors|r
    >>|cRXP_ENEMY_Lashtail Raptors|r |cRXP_WARN_cast|r |T132109:0|t[Lash] |cRXP_WARN_which is a 2 second stun|r
    >>|cRXP_WARN_They can also|r |T132343:0|t[Disarm] |cRXP_WARN_you for 5 seconds|r << Warrior/Rogue/Paladin
    .complete 195,1
    .mob Lashtail Raptor
    .isOnQuest 195

step
    .goto 1434/0,-375.06,-12098.29,70,0
    .goto 1434/0,-313.16,-12437.34,70,0
    .goto 1434/0,-145.97,-12555.610,70,0
    .goto 1434/0,-274.24,-12325.88,70,0
    .goto 1434/0,-306.78,-12100.410,70,0
    .goto 1434/0,-333.58,-11835.38,75,0
    .goto 1434/0,-274.24,-12325.88
    >>Kill |cRXP_ENEMY_Snapjaw Crocolisk|r. Loot them for their |cRXP_LOOT_Skin|r
    .complete 577,1
    .mob Snapjaw Crocolisk
    .isOnQuest 577

step
    .goto Stranglethorn Vale,38.10,20.50,70,0
    .goto 1434/0,-138.95,-12228.040,70,0
    .goto 1434/0,35.89,-12281.64,70,0
    .goto 1434/0,219.04,-12116.58
    >>Kill |cRXP_ENEMY_Lashtail Raptors|r
    >>|cRXP_ENEMY_Lashtail Raptors|r |cRXP_WARN_cast|r |T132109:0|t[Lash] |cRXP_WARN_which is a 2 second stun|r
    >>|cRXP_WARN_They can also|r |T132343:0|t[Disarm] |cRXP_WARN_you for 5 seconds|r << Warrior/Rogue/Paladin
    .complete 195,1
    .mob Lashtail Raptor
    .isOnQuest 195

step
    >>Kill |cRXP_ENEMY_Sin'Dall|r. Loot her for her |cRXP_LOOT_Paw|r
    >>|cRXP_ENEMY_Sin'Dall|r |cRXP_WARN_can be on top of the Plateau, or patrolling around it|r
    .goto 1434/0,164.16,-11902.17
    .complete 188,1
    .unitscan Sin'Dall
    .isOnQuest 188

step << Warrior
    #completewith KurzenMystery1
    .goto 1434/0,601.27,-11702.65,75,0
    .goto 1434/0,588.51,-11595.02,75,0
    .goto Stranglethorn Vale,24.00,12.34
    .goto 1434/0,592.34,-11566.94,0
    >>Kill |cRXP_ENEMY_Bloodscalp Trolls|r. Loot them for their |cRXP_LOOT_Ears|r and |cRXP_LOOT_Tusks|r
    >>|cRXP_WARN_Save 15|r |T132905:0|t[Silk Cloth] |cRXP_WARN_for a quest for later in Searing Gorge. You don't need to collect all 15 now|r
    .complete 189,1
    .complete 1712,2
    .collect 4306,15,4449,1,1
    .mob Bloodscalp Scout
    .mob Bloodscalp Hunter
    .mob Bloodscalp Beastmaster
    .mob Bloodscalp Mystic
    .isOnQuest 1712

step << Warrior
    .isOnQuest 1712
    #completewith next
    .goto 1434/0,340.22,-11982.10,70 >> Travel to the Bal'lal Ruins

step << Warrior
    .isOnQuest 1712
    .goto 1434/0,340.22,-11982.10
    >>Open the |cRXP_PICK_Moon Over the Vale|r. Loot it for |cRXP_LOOT_The First Troll Legend|r
    .complete 207,1

step << Warrior
    .isOnQuest 1712
    #completewith next
    .goto 1434/0,643.45,-11547.58,150 >> Travel to the Ruins of Zul'Kunda

step << Warrior
    .isOnQuest 1712
    .goto 1434/0,643.45,-11547.58
    >>Open |cRXP_PICK_The Emperor's Tomb|r. Loot it for |cRXP_LOOT_The Fourth Troll Legend|r
    .complete 207,4

step << Warrior
    #label KurzenMystery1
    .isOnQuest 1712
    .goto 1434/0,756.97,-11679.68
    >>Open the |cRXP_PICK_Fall of Gurubashi|r. Loot it for |cRXP_LOOT_The Third Troll Legend|r
    .complete 207,3

step << Warrior
    .isOnQuest 1712
    .goto 1434/0,601.27,-11702.65,75,0
    .goto 1434/0,588.51,-11595.02,75,0
    .goto Stranglethorn Vale,24.00,12.34
    .goto 1434/0,592.34,-11566.94,0
    >>Kill |cRXP_ENEMY_Bloodscalp Trolls|r. Loot them for their |cRXP_LOOT_Ears|r and |cRXP_LOOT_Tusks|r
    >>|cRXP_WARN_Save 15|r |T132905:0|t[Silk Cloth] |cRXP_WARN_for a quest for later in Searing Gorge. You don't need to collect all 15 now|r
    .complete 189,1
    .complete 1712,2
    .collect 4306,15,4449,1,1
    .mob Bloodscalp Scout
    .mob Bloodscalp Hunter
    .mob Bloodscalp Beastmaster
    .mob Bloodscalp Mystic

step
    #completewith KurzenMystery2
    .goto 1434/0,592.34,-11566.94,0
    >>Kill |cRXP_ENEMY_Bloodscalp Trolls|r. Loot them for their |cRXP_LOOT_Ears|r
    >>|cRXP_WARN_Save 15|r |T132905:0|t[Silk Cloth] |cRXP_WARN_for a quest for later in Searing Gorge. You don't need to collect all 15 now|r
    .complete 189,1
    .collect 4306,15,4449,1,1
    .mob Bloodscalp Scout
    .mob Bloodscalp Hunter
    .mob Bloodscalp Beastmaster
    .mob Bloodscalp Mystic

step
    #optional
    #completewith next
    .goto 1434/0,340.22,-11982.10,70 >> Travel to the Bal'lal Ruins

step
    .goto 1434/0,340.22,-11982.10
    >>Open the |cRXP_PICK_Moon Over the Vale|r. Loot it for |cRXP_LOOT_The First Troll Legend|r
    .complete 207,1

step
    #optional
    #completewith next
    .goto 1434/0,643.45,-11547.58,150 >> Travel to the Ruins of Zul'Kunda

step
    .goto 1434/0,643.45,-11547.58
    >>Open |cRXP_PICK_The Emperor's Tomb|r. Loot it for |cRXP_LOOT_The Fourth Troll Legend|r
    .complete 207,4

step
    #label KurzenMystery2
    .goto 1434/0,756.97,-11679.68
    >>Open the |cRXP_PICK_Fall of Gurubashi|r. Loot it for |cRXP_LOOT_The Third Troll Legend|r
    .complete 207,3

step
    .goto 1434/0,601.27,-11702.65,75,0
    .goto 1434/0,588.51,-11595.02,75,0
    .goto Stranglethorn Vale,24.00,12.34
    .goto 1434/0,592.34,-11566.94,0
    >>Kill |cRXP_ENEMY_Bloodscalp Trolls|r. Loot them for their |cRXP_LOOT_Ears|r
    >>|cRXP_WARN_Save 15|r |T132905:0|t[Silk Cloth] |cRXP_WARN_for a quest for later in Searing Gorge. You don't need to collect all 15 now|r
    .complete 189,1
    .collect 4306,15,4449,1,1
    .mob Bloodscalp Scout
    .mob Bloodscalp Hunter
    .mob Bloodscalp Beastmaster
    .mob Bloodscalp Mystic

step
    #optional
    #completewith next
    .goto Stranglethorn Vale,21.10,22.84,125 >> Travel to the Haunted Island

step
    .goto Stranglethorn Vale,21.10,22.84
    >>Kill |cRXP_ENEMY_Lesser Water Elementals|r. Loot them for their |cRXP_LOOT_Bracers|r
    .complete 601,1
    .mob Lesser Water Elemental

step
    #completewith UnderwaterLegend
    .cast 7178 >> |cRXP_WARN_Use your|r |T134797:0|t[Elixir of Water Breathing] |cRXP_WARN_if you have one|r
    .itemcount 5996,1
    .use 5996
    .aura 7178

step
    #ah
    #completewith UnderwaterLegend
    .goto 1434/0,631.90,-12406.71,0
    .goto 1434/0,459.61,-12410.97,0
    .goto 1434/0,600.00,-12194.00,0
    .goto 1434/0,465.99,-12198.26,0
    .goto 1434/0,483.22,-12252.71,0
    .goto Stranglethorn Vale,26.40,27.16,0
    .goto 1434/0,529.16,-12422.45,0
    .goto 1434/0,564.26,-12420.75,0
    .goto 1434/0,582.77,-12436.07,0
    .goto 1434/0,653.60,-12446.70,0
    .goto 1434/0,685.50,-12387.99,0
    .goto 1434/0,605.10,-12339.07,0
    >>Open the |cRXP_PICK_Giant Clams|r. Loot them for |cRXP_LOOT_Blue Pearls|r. You may also buy these from the Auction House
    >>|cRXP_WARN_Skip this step if you don't have a|r |T134797:0|t[Elixir of Water Breathing] |cRXP_WARN_or |T626007:0|t|cFF8788EEWarlock|r in your group|r << !Warlock !Druid
    .use 5996
    .collect 4611,9,705,1

step
    #ssf
    #completewith UnderwaterLegend
    .goto 1434/0,631.90,-12406.71,0
    .goto 1434/0,459.61,-12410.97,0
    .goto 1434/0,600.00,-12194.00,0
    .goto 1434/0,465.99,-12198.26,0
    .goto 1434/0,483.22,-12252.71,0
    .goto Stranglethorn Vale,26.40,27.16,0
    .goto 1434/0,529.16,-12422.45,0
    .goto 1434/0,564.26,-12420.75,0
    .goto 1434/0,582.77,-12436.07,0
    .goto 1434/0,653.60,-12446.70,0
    .goto 1434/0,685.50,-12387.99,0
    .goto 1434/0,605.10,-12339.07,0
    >>Open the |cRXP_PICK_Giant Clams|r. Loot them for |cRXP_LOOT_Blue Pearls|r
    >>|cRXP_WARN_Skip this step if you don't have a|r |T134797:0|t[Elixir of Water Breathing] |cRXP_WARN_or |T626007:0|t|cFF8788EEWarlock|r in your group|r << !Warlock !Druid
    .use 5996
    .collect 4611,9,705,1

step
    #label UnderwaterLegend
    .goto 1434/0,640.52,-12141.72
    >>Open |cRXP_PICK_Gri'lek the Wanderer|r underwater. Loot it for |cRXP_LOOT_The Second Troll Legend|r
    .complete 207,2

step
    #ah
    .goto 1434/0,631.90,-12406.71,90,0
    .goto 1434/0,459.61,-12410.97,90,0
    .goto 1434/0,600.00,-12194.00,90,0
    .goto 1434/0,465.99,-12198.26
    >>Open the |cRXP_PICK_Giant Clams|r. Loot them for |cRXP_LOOT_Blue Pearls|r. You may also buy these from the Auction House
    >>|cRXP_WARN_Skip this step if you don't have a|r |T134797:0|t[Elixir of Water Breathing] |cRXP_WARN_or |T626007:0|t|cFF8788EEWarlock|r in your group|r << !Warlock !Druid
    .use 5996
    .collect 4611,9,705,1

step
    #ssf
    .goto 1434/0,631.90,-12406.71,90,0
    .goto 1434/0,459.61,-12410.97,90,0
    .goto 1434/0,600.00,-12194.00,90,0
    .goto 1434/0,465.99,-12198.26
    >>Open the |cRXP_PICK_Giant Clams|r. Loot them for |cRXP_LOOT_Blue Pearls|r
    >>|cRXP_WARN_Skip this step if you don't have a|r |T134797:0|t[Elixir of Water Breathing] |cRXP_WARN_or |T626007:0|t|cFF8788EEWarlock|r in your group|r << !Warlock !Druid
    .use 5996
    .collect 4611,9,705,1

step
    #optional
    .goto 1434/0,592.34,-11566.94
    .xp 37+53000 >>Grind until you are 53000/76100 xp into level 37
    .isQuestComplete 329

step
    #optional
    .goto 1434/0,592.34,-11566.94
    .xp 37+57500 >>Grind until you are 57500/76100 xp into level 37
    .isQuestAvailable 215

step
    #completewith next
    .deathskip >> Die and respawn at the Spirit Healer
    .target Spirit Healer

step
    #completewith next
    .goto 1434/0,-242.33,-11355.93,50 >> Travel to the Rebel Camp

step
    .goto 1434/0,-193.32,-11320.16
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Brother Nimetz|r
    .turnin 207 >> Turn in Kurzen's Mystery
    .accept 205 >> Accept Troll Witchery
    .target Brother Nimetz

step
    .isQuestTurnedIn 215
    .goto 1434/0,-206.72,-11296.89
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Lieutenant Doren|r
    .turnin 574 >> Turn in Special Forces
    .accept 202 >> Accept Colonel Kurzen
    .turnin 329 >> Turn in The Spy Revealed!
    .accept 330 >> Accept Patrol Schedules
    .target Lieutenant Doren

step
    .goto 1434/0,-206.72,-11296.89
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Lieutenant Doren|r
    .turnin 574 >> Turn in Special Forces
    .accept 202 >> Accept Colonel Kurzen
    .target Lieutenant Doren

step
    .isQuestTurnedIn 215
    .goto 1434/0,-182.35,-11312.97
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Corporal Sethman|r
    .turnin 330 >> Turn in Patrol Schedules
    .accept 331 >> Accept Report to Doren
    .target Corporal Sethman

step
    .isQuestTurnedIn 215
    .goto 1434/0,-206.72,-11296.89
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Lieutenant Doren|r
    .turnin 331 >> Turn in Report to Doren
    .target Lieutenant Doren

step
    #completewith next
    .goto 1434/0,-54.59,-11628.54,80 >> Travel to Nesingwary's Expedition

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Hemet Nesingwary|r, |cRXP_FRIENDLY_Ajeck Rouack|r and |cRXP_FRIENDLY_Sir S. J. Erlgadin|r
    .turnin 195 >> Turn in Raptor Mastery
    .accept 196 >> Accept Raptor Mastery
    .target +Hemet Nesingwary
    .goto 1434/0,-54.59,-11628.54
    .turnin 188 >> Turn in Tiger Mastery
    .target +Ajeck Rouack
    .goto 1434/0,-51.91,-11620.50
    .turnin 192 >> Turn in Panther Mastery
    .accept 193 >> Accept Panther Mastery
    .target +Sir S. J. Erlgadin
    .goto 1434/0,-48.08,-11617.39
    .isQuestTurnedIn 194
    .isQuestTurnedIn 187
    .isQuestTurnedIn 191

step
    #optional
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Hemet Nesingwary|r
    .turnin 195 >> Turn in Raptor Mastery
    .target +Hemet Nesingwary
    .goto 1434/0,-54.59,-11628.54
    .isOnQuest 195

step
    #optional
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Hemet Nesingwary|r
    .accept 196 >> Accept Raptor Mastery
    .target +Hemet Nesingwary
    .goto 1434/0,-54.59,-11628.54
    .isQuestAvailable 196
    .isQuestTurnedIn 195

step
    #optional
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Ajeck Rouack|r
    .turnin 188 >> Turn in Tiger Mastery
    .target +Ajeck Rouack
    .goto 1434/0,-51.91,-11620.50
    .isOnQuest 188

step
    #optional
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sir S. J. Erlgadin|r
    .turnin 192 >> Turn in Panther Mastery
    .target +Sir S. J. Erlgadin
    .goto 1434/0,-48.08,-11617.39
    .isOnQuest 192

step
    #optional
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sir S. J. Erlgadin|r
    .accept 193 >> Accept Panther Mastery
    .target +Sir S. J. Erlgadin
    .goto 1434/0,-48.08,-11617.39
    .isQuestAvailable 193
    .isQuestTurnedIn 192

step
    #completewith BBTurnins
    .hs >> Hearth to Booty Bay
    >>|cRXP_BUY_Buy food/water if needed|r << !Warrior !Rogue
    >>|cRXP_BUY_Buy food if needed|r << Warrior/Rogue

step
    .isQuestTurnedIn 1114
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kebok|r and |cRXP_FRIENDLY_Krazek|r up stairs on the top floor
    .turnin 189 >> Turn in Bloodscalp Ears
    .target +Kebok
    .goto Stranglethorn Vale,27.000,77.124
    .accept 1116 >> Accept Dream Dust in the Swamp
    .target +Krazek
    .goto 1434/0,501.53,-14453.26

step
    .goto Stranglethorn Vale,27.000,77.124
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kebok|r up stairs on the top floor
    .turnin 189 >>Turn in Bloodscalp Ears
    .target Kebok

step
    #completewith end
    +Keep the |T133711:0|t[|cRXP_LOOT_Goblin Fishing Poles|r]. They are useful for splitpulling mobs
    .link https://www.youtube.com/watch?v=H-IwZ6P-ldY >> Click here to watch a video about splitpulling (useful to learn)

step
    #label BBTurnins
    .goto 1434/0,483.41,-14438.930
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Baron Revilgaz|r
    .turnin 601 >> Turn in Water Elementals
    .accept 602 >> Accept Magical Analysis
    .target Baron Revilgaz

step
    .goto 1434/0,415.32,-14469.64
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Drizzlik|r
    .turnin 577 >> Turn in Some Assembly Required
    .target Drizzlik
    .isOnQuest 577

step
    .goto 1434/0,425.15,-14491.68
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|t|cRXP_BUY_Talk to|r |cRXP_FRIENDLY_Glyx|r
    .vendor >> |cRXP_BUY_Buy|r |T134832:0|t[Greater Healing Potions] |cRXP_BUY_from him if they're up|r
    .target Glyx Brewright

step
    .xp 38 >> Make sure you are level 38 before starting the next segment

step << !Mage
    #label end
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gyll|r
    .goto Stranglethorn Vale,27.530,77.787
    .fly Stormwind>> Fly to Stormwind
    .target Gyll

step << Warrior
    .goto StormwindClassic,58.362,61.678
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Thurman Mullby|r
    >>|cRXP_BUY_Buy 400|r |T135427:0|t[Wicked Throwing Daggers]
    .collect 15327,400
    .target Thurman Mullby
]])
