-- Generated by Scripts/split_guide_vault.py; rerun the script to update.
if not RXPGuides or type(RXPGuides.RegisterGuide) ~= "function" then return end
local _, rxpGuideVaultAddon = ...
local rxpGuideVaultGame = rxpGuideVaultAddon and rxpGuideVaultAddon.game
if not rxpGuideVaultGame then
    local rxpGuideVaultVersion = select(4, GetBuildInfo())
    if rxpGuideVaultVersion > 60000 then
        rxpGuideVaultGame = "RETAIL"
    elseif rxpGuideVaultVersion > 50000 then
        rxpGuideVaultGame = "MOP"
    elseif rxpGuideVaultVersion > 40000 then
        rxpGuideVaultGame = "CATA"
    elseif rxpGuideVaultVersion > 30000 then
        rxpGuideVaultGame = "WOTLK"
    elseif rxpGuideVaultVersion > 20000 then
        rxpGuideVaultGame = "TBC"
    elseif rxpGuideVaultVersion >= 16000 and rxpGuideVaultVersion < 20000 then
        rxpGuideVaultGame = "FOREVER"
    else
        rxpGuideVaultGame = "CLASSIC"
    end
end
if rxpGuideVaultGame ~= "FOREVER" then return end

RXPGuides.RegisterGuide([[#forever
#version 23
#group RestedXP Forever Guide (A)
#subgroup Speedrun Guide 50-60

<< Alliance
#name 51-52 WPL
#next 52-52 Felwood

step
    #sticky
    #completewith next
    .zone Ironforge >> Head to Ironforge

step
    #completewith CHam
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Courier Hammerfall|r
    >>|cRXP_FRIENDLY_Courier Hammerfall|r |cRXP_WARN_patrols through all of Ironforge|r
    .accept 5090 >> Accept A Call to Arms: The Plaguelands!
    .unitscan Courier Hammerfall

step
    .goto 1455/0,-1312.63,-4692.64
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Laris Geardawdle|r
    .accept 4512 >> Accept A Little Slime Goes a Long Way
    .target Laris Geardawdle

step
    .isQuestTurnedIn 3181
    .goto 1455/0,-1281.50,-4654.29,30,0
    .goto 1455/0,-1322.53,-4708.42,30,0
    .goto 1455/0,-1219.83,-4591.400,30,0
    .goto 1455/0,-1281.50,-4654.29
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Curator Thorius|r
    >>|cRXP_FRIENDLY_Curator Thorius|r |cRXP_WARN_patrols through the Hall of Explorers|r
    .turnin 3182 >> Turn in Proof of Deed
    .accept 3201 >> Accept At Last!
    .target Curator Thorius

step
    .goto 1455/0,-1281.50,-4654.29,30,0
    .goto 1455/0,-1322.53,-4708.42,30,0
    .goto 1455/0,-1219.83,-4591.400,30,0
    .goto 1455/0,-1281.50,-4654.29
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Curator Thorius|r
    >>|cRXP_FRIENDLY_Curator Thorius|r |cRXP_WARN_patrols through the Hall of Explorers|r
    .turnin 3368 >> Turn in Suntara Stones

    .target Curator Thorius
    .isOnQuest 3368

step
    .goto 1455/0,-1326.63,-4631.68
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Historian Karnik|r
    .accept 3448 >> Accept Passing the Burden
    .target Historian Karnik

step << Warlock
    .goto 1455/0,-1134.20,-4610.39,15,0
    .goto 1455/0,-1130.26,-4601.270
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Jubahl Corpseseeker|r
    .vendor >> |cRXP_BUY_Buy|r |T133738:0|t[Grimoires] |cRXP_BUY_for your pets|r
    .target Jubahl Corpseseeker

step << Warlock
    .goto 1455/0,-1111.62,-4599.09
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Briarthorn|r
    .trainer >> Train your class spells
    .target Briarthorn

step << Warlock
    .goto 1455/0,-1111.62,-4599.09
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Briarthorn|r
    .trainer >> Train your class spells
    .accept 8419 >> Accept An Imp's Request
    .target Briarthorn

step
    .goto 1455/0,-958.37,-4594.67
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Tymor|r
    .turnin 3448 >> Turn in Passing the Burden
    .accept 3449 >> Accept Arcane Runes
    .accept 3450 >> Accept An Easy Pickup
    .target Tymor

step << Paladin
    .goto 1455/0,-896.43,-4601.70
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Brandur Ironhammer|r
    .trainer >> Train your class spells
    .target Brandur Ironhammer
    .accept 8415 >> Accept Chillwind Point

step << Paladin
    .goto 1455/0,-896.43,-4601.70
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Brandur Ironhammer|r
    .trainer >> Train your class spells
    .target Brandur Ironhammer

step
    .goto Ironforge,18.10,51.60
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Innkeeper Firebrew|r
    .home Ironforge >> Set your Hearthstone to Ironforge
    .target Innkeeper Firebrew

step
    .goto Ironforge,35.90,60.17
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Bailey Stonemantle|r
    .bankwithdraw 10819,9328,9330 >> Withdraw the following items from your bank:
    >>|T132927:0|t[Wildkin Feather]
    >>|T134442:0|t[Super Snapper FX]
    >>|T134300:0|t[Snapshot of Gammerita]
    .target Bailey Stonemantle

step
    #sticky
    .goto 1455/0,-1299.30,-4823.59
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Bubulo Acerbus|r
    >>Do the Gnomeregan cloth turn ins. You'll need 3 stacks of each cloth. Skip this step if you're unable to complete all of them
    .turnin 7807 >> Turn in A Donation of Wool
    .turnin 7808 >> Turn in A Donation of Silk
    .turnin 7809 >> Turn in A Donation of Mageweave
    .turnin 7811 >> Turn in A Donation of Runecloth
    .zoneskip Ironforge,1
    .target Bubulo Acerbus

step
    #sticky
    .goto 1455/0,-1055.33,-4735.83
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Mistina Steelshield|r
    >>Do the Ironforge cloth turn ins. You'll need 3 stacks of each cloth. Skip this step if you're unable to complete all of them
    .turnin 7802 >> Turn in A Donation of Wool
    .turnin 7803 >> Turn in A Donation of Silk
    .turnin 7804 >> Turn in A Donation of Mageweave
    .turnin 7805 >> Turn in A Donation of Runecloth
    .zoneskip Ironforge,1
    .target Mistina Steelshield

step
    #ah
    .goto Ironforge,25.800,75.500,-1
    .goto Ironforge,24.200,74.600,-1
    .goto Ironforge,23.800,71.800,-1
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to an |cRXP_FRIENDLY_Ironforge Auctioneer|r
    >>|cRXP_BUY_Buy a|r |T133021:0|t[Mithril Casing] |cRXP_BUY_from the Auction House. You will need this later for a quest in Un'Goro Crater|r
    >>|cRXP_WARN_Skip this step if you can't acquire one|r
    .collect 10561,1,4244,1
    .target Auctioneer Lympkin
    .target Auctioneer Redmuse
    .target Auctioneer Buckler

step << Warrior
    .goto 1455/0,-1234.65,-5035.67
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Bilban Tosslespanner|r
    .trainer >> Train your class spells
    .target Bilban Tosslespanner

step
    #label CHam
    .goto Ironforge,70.860,94.570
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Xiggs Fuselighter|r
    .turnin 3450 >> Turn in An Easy Pickup
    .accept 3451 >> Accept Signal for Pickup
    .turnin 3451 >> Turn in Signal for Pickup
    .target Xiggs Fuselighter

step
    .goto 1455/0,-977.66,-4674.76,70,0
    .goto 1455/0,-915.99,-4894.25,70,0
    .goto 1455/0,-1225.92,-4979.72,70,0
    .goto 1455/0,-1271.77,-4822.49,70,0
    .goto Ironforge,65.0,22.6,70,0
    .goto 1455/0,-1112.07,-4624.11,70,0
    .goto 1455/0,-971.34,-4680.04,70,0
    .goto 1455/0,-1036.17,-4777.12,70,0
    .goto 1455/0,-1118.39,-4867.87,70,0
    .goto 1455/0,-1154.76,-4754.96,70,0
    .goto Ironforge,33.0,22.4
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Courier Hammerfall|r
    >>|cRXP_FRIENDLY_Courier Hammerfall|r |cRXP_WARN_patrols through all of Ironforge|r
    .accept 5090 >> Accept A Call to Arms: The Plaguelands!
    .unitscan Courier Hammerfall

step
    #completewith next
    .isOnQuest 3201
    .goto 1455/0,-1152.32,-4821.18
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gryth Thurden|r
    .fly Loch Modan >> Fly to Loch Modan
    .target Gryth Thurden

step
    .isOnQuest 3201
    .goto 1432/0,-2495.38,-6033.38
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Mountaineer Pebblebitty|r
    .turnin 3201 >> Turn in At Last!
    .target Mountaineer Pebblebitty

step
    .goto 1432/0,-2929.87,-5424.84
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Thorgrum|r
    .fly Hinterlands>> Fly to The Hinterlands
    .zoneskip Loch Modan,1
    .target Thorgrum Borrelson

step
    .goto 1455/0,-1152.32,-4821.18
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gryth Thurden|r
    .fly Hinterlands>> Fly to The Hinterlands
    .zoneskip Ironforge,1
    .target Gryth Thurden

step
    .goto 1425/0,-1950.45,325.19
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gryphon Master Talonaxe|r
    .turnin 2989 >> Turn in The Altar of Zul
    .target Gryphon Master Talonaxe
    .isOnQuest 2989

step
    .goto 1425/0,-2146.11,322.78
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Fraggar Thundermantle|r
    .target Fraggar Thundermantle
    .turnin 2877 >> Turn in Skulk Rock Clean-up
    .isOnQuest 2877

step
    #label Tragan
    .goto 1425/0,-3139.26,-64.35
    >>Loot the |cRXP_LOOT_Violet Tragan|r underwater
    .complete 2641,1

step
    #completewith FlyWPL
    .goto 1425/0,-2001.23,282.07
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Guthrum Thunderfist|r
    .fly Western Plaguelands>> Fly to Western Plaguelands
    .target Guthrum Thunderfist

step
    #optional
    .isOnQuest 5066
    .goto 1422/0,-1419.52,957.78
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Commander Ashlam Valorfist|r
    .turnin 5066 >> Turn in A Call to Arms: The Plaguelands!
    .accept 5092 >> Accept Clear the Way
    .target Commander Ashlam Valorfist

step
    #optional
    .isQuestTurnedIn 5066
    .goto 1422/0,-1419.52,957.78
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Commander Ashlam Valorfist|r
    .accept 5092 >> Accept Clear the Way
    .target Commander Ashlam Valorfist

step
    #optional
    .isOnQuest 5091
    .goto 1422/0,-1419.52,957.78
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Commander Ashlam Valorfist|r
    .turnin 5091 >> Turn in A Call to Arms: The Plaguelands!
    .accept 5092 >> Accept Clear the Way
    .target Commander Ashlam Valorfist

step
    #optional
    .isQuestTurnedIn 5091
    .goto 1422/0,-1419.52,957.78
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Commander Ashlam Valorfist|r
    .accept 5092 >> Accept Clear the Way
    .target Commander Ashlam Valorfist

step
    .isOnQuest 5090
    .goto 1422/0,-1419.52,957.78
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Commander Ashlam Valorfist|r
    .turnin 5090 >> Turn in A Call to Arms: The Plaguelands!
    .accept 5092 >> Accept Clear the Way
    .target Commander Ashlam Valorfist

step
    .isQuestTurnedIn 5090
    .goto 1422/0,-1419.52,957.78
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Commander Ashlam Valorfist|r
    .accept 5092 >> Accept Clear the Way
    .target Commander Ashlam Valorfist

step << Paladin
    .goto 1422/0,-1419.52,957.78
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Commander Ashlam Valorfist|r
    .turnin 8415 >> Turn in Chillwind Point
    .accept 8414 >> Accept Dispelling Evil
    .target Commander Ashlam Valorfist

step
    .goto 1422/0,-1430.96,971.68
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Argent Officer Pureheart|r
    .accept 5401 >> Accept Argent Dawn Commission
    .turnin 5401 >> Turn in Argent Dawn Commission
    .target Argent Officer Pureheart

step
    #completewith next
    .cast 17670 >> |cRXP_WARN_Equip the|r |T133440:0|t[Argent Dawn Commission] |cRXP_WARN_to start collecting|r |T133447:0|t[Scourgestones]
    .use 12846

step << Paladin
    #completewith BLTN
    >>Kill any of the |cRXP_ENEMY_Scourge|r. Loot them for their |cRXP_LOOT_Minion's Scourgestones|r
    .complete 8414,1

step
    #label FlyWPL
    .goto 1422/0,-1686.46,1049.25,70,0
    .goto 1422/0,-1733.76,1162.200
    >>Kill |cRXP_ENEMY_Skeletal Flayers|r and |cRXP_ENEMY_Slavering Ghouls|r
    .complete 5092,1
    .mob +Skeletal Flayer
    .complete 5092,2
    .mob +Slavering Ghoul

step << Paladin
    #optional
    .isQuestComplete 8414
    .goto 1422/0,-1818.90,991.63
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_High Priest Thel'danis|r
    .turnin 8414 >> Turn in Dispelling Evil
    .accept 8416 >> Accept Inert Scourgestones
    .target High Priest Thel'danis

step << Paladin
    #optional
    .isQuestTurnedIn 8414
    .goto 1422/0,-1818.90,991.63
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_High Priest Thel'danis|r
    .accept 8416 >> Accept Inert Scourgestones
    .target High Priest Thel'danis

step
    .goto 1422/0,-1419.52,957.78
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Commander Ashlam Valorfist|r
    .turnin 5092 >> Turn in Clear the Way
    .accept 5215 >> Accept The Scourge Cauldrons
    .target Commander Ashlam Valorfist

step << Paladin
    #optional
    .isOnQuest 8416
    .goto 1422/0,-1419.52,957.78
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Commander Ashlam Valorfist|r
    .turnin 8416 >> Turn in Inert Scourgestones
    .target Commander Ashlam Valorfist

step << Paladin
    .dungeon ST
    .isQuestTurnedIn 8416
    .goto 1422/0,-1419.52,957.78
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Commander Ashlam Valorfist|r
    .accept 8418 >> Accept Forging the Mightstone
    .target Commander Ashlam Valorfist

step
    .goto 1422/0,-1431.13,944.30
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_High Priestess MacDonnell|r
    .turnin 5215 >> Turn in The Scourge Cauldrons
    .accept 5216 >> Accept Target: Felstone Field
    .target High Priestess MacDonnell

step
    .goto 1422/0,-1174.98,1728.51
    >>Kill |cRXP_ENEMY_Cauldron Lord Bilemaw|r. Loot him for the |cRXP_LOOT_Felstone Field Cauldron Key|r
    >>|cRXP_ENEMY_Cauldron Lord Bilemaw|r |cRXP_WARN_may spawn as you approach the|r |cRXP_PICK_Cauldron|r
    .complete 5216,1
    .unitscan Cauldron Lord Bilemaw

step
    .goto 1422/0,-1182.68,1736.680
    >>Click on the |cRXP_PICK_Scourge Cauldron|r
    .turnin 5216 >> Turn in Target: Felstone Field
    .accept 5217 >> Accept Return to Chillwind Camp

step
    #completewith next
    .goto 1422/0,-1219.48,1801.75,12 >>Go inside the house

step
    .goto Western Plaguelands,38.40,54.05
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Janice Felstone|r up stairs
    .accept 5021 >>Accept Better Late Than Never
    .target Janice Felstone

step
    #completewith next
    .goto 1422/0,-1219.48,1802.61,8,0
    >>Exit the house
    .goto 1422/0,-1242.27,1780.54,6 >>Go inside the barn

step
    #label BLTN
    .goto 1422/0,-1248.29,1783.12
    >>Click |cRXP_PICK_Janice's Parcel|r on the ground
    >>|cRXP_WARN_This has a 5 second cast time|r
    >>|cRXP_WARN_You can do this from behind the wall to avoid aggroing anything inside|r
    >>|cRXP_WARN_Avoid aggroing the |cRXP_ENEMY_Scarlets|r outside the barn. If you do, run away|r
    .turnin 5021 >>Turn in Better Late Than Never
    .accept 5022 >>Accept Better Late Than Never

step << Paladin
    .isOnQuest 8414
    .goto 1422/0,-1182.68,1736.680
    >>Kill any of the |cRXP_ENEMY_Scourge|r. Loot them for their |cRXP_LOOT_Minion's Scourgestones|r
    .complete 8414,1

step
    #completewith next
    .deathskip >> Die and respawn at the Chillwind Camp Spirit Healer
    .target Spirit Healer

step
    #completewith next
    .subzone 3197 >> Travel to Chillwind Camp

step
    .goto 1422/0,-1431.13,944.30
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_High Priestess MacDonnell|r
    .turnin 5217 >> Turn in Return to Chillwind Camp
    .target High Priestess MacDonnell

step << Paladin
    .goto 1422/0,-1818.90,991.63
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_High Priest Thel'danis|r
    .turnin 8414 >> Turn in Dispelling Evil
    .accept 8416 >> Accept Inert Scourgestones
    .target High Priest Thel'danis

step << Paladin
    .goto 1422/0,-1419.52,957.78
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Commander Ashlam Valorfist|r
    .turnin 8416 >> Turn in Inert Scourgestones
    .target Commander Ashlam Valorfist

step << Paladin
    .dungeon ST
    .isQuestTurnedIn 8416
    .goto 1422/0,-1419.52,957.78
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Commander Ashlam Valorfist|r
    .accept 8418 >> Accept Forging the Mightstone
    .target Commander Ashlam Valorfist

step << !Mage !Druid
    .goto 1422/0,-1429.07,928.25
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Bibilfaz Featherwhistle|r
    .fly Wetlands>> Fly to Wetlands
    .zoneskip Western Plaguelands,1
    .target Bibilfaz Featherwhistle
]])
