-- Generated by Scripts/split_guide_vault.py; rerun the script to update.
if not RXPGuides or type(RXPGuides.RegisterGuide) ~= "function" then return end
local _, rxpGuideVaultAddon = ...
local rxpGuideVaultGame = rxpGuideVaultAddon and rxpGuideVaultAddon.game
if not rxpGuideVaultGame then
    local rxpGuideVaultVersion = select(4, GetBuildInfo())
    if rxpGuideVaultVersion > 60000 then
        rxpGuideVaultGame = "RETAIL"
    elseif rxpGuideVaultVersion > 50000 then
        rxpGuideVaultGame = "MOP"
    elseif rxpGuideVaultVersion > 40000 then
        rxpGuideVaultGame = "CATA"
    elseif rxpGuideVaultVersion > 30000 then
        rxpGuideVaultGame = "WOTLK"
    elseif rxpGuideVaultVersion > 20000 then
        rxpGuideVaultGame = "TBC"
    elseif rxpGuideVaultVersion >= 16000 and rxpGuideVaultVersion < 20000 then
        rxpGuideVaultGame = "FOREVER"
    else
        rxpGuideVaultGame = "CLASSIC"
    end
end
if rxpGuideVaultGame ~= "FOREVER" then return end

RXPGuides.RegisterGuide([[#forever
#version 23
#group RestedXP Forever Guide (A)
#subgroup Speedrun Guide 40-50

<< Alliance
#name 41-43 STV/Swamp of Sorrows
#somname 41-44 STV/Swamp of Sorrows
#next 43-44 Tanaris << !Warlock
#next 43-44 Tanaris/Dustwallow << Warlock

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Bailey Stonemantle|r
    .goto Ironforge,35.90,60.17
    .bankwithdraw 3684,3660,5826,4502 >> Withdraw the following items from your bank:
    >>|T134332:0|t[Kravel's Scheme]
    >>|T134116:0|t[Sample Elven Gem]
    >>|T132767:0|t[Perenolde Tiara] (If you have it)
    >>|T132761:0|t[Tomes of Alterac] (If you have it)
    .target Bailey Stonemantle

step << !Druid !Hunter !Warrior
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Briarthorn|r << Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Brandur Ironhammer|r << Paladin
    .goto 1455/0,-1117.60,-4615.14,15,0 << Warlock
    .goto 1455/0,-1111.62,-4599.09 << Warlock
    .goto 1455/0,-896.55,-4601.68 << Paladin
    .trainer >> Train your class spells
    .target Briarthorn << Warlock
    .target Brandur Ironhammer << Paladin

step << Warlock
    .goto 1455/0,-1134.20,-4610.39,15,0
    .goto 1455/0,-1130.26,-4601.270
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Jubahl Corpseseeker|r
    .vendor >> |cRXP_BUY_Buy|r |T133738:0|t[Grimoires] |cRXP_BUY_for your pets|r
    .target Jubahl Corpseseeker

step << Warrior/Hunter
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Bilban Tosslespanner|r << Warrior
    .goto 1455/0,-1234.65,-5035.67 << Warrior
    .trainer >> Train your class spells
    .target Bilban Tosslespanner << Warrior

step
    #completewith start
    .goto Ironforge,78.00,52.00,5,0
    .zone Stormwind City >> Enter the Deeprun Tram. Take the tram to Stormwind
    >>|cRXP_WARN_Level your|r |T135966:0|t[First Aid] |cRXP_WARN_if needed while waiting for the tram|r

step
    .goto Stormwind City,74.010,30.231
    .target Count Remington Ridgewell
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Count Remington Ridgewell|r
    .turnin 543 >> Turn in The Perenolde Tiara
    .isQuestComplete 543

step
    .goto 1453/0,383.76,-8345.76
    .target Milton Sheaf
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Milton Sheaf|r
    .turnin 542 >> Turn in Return to Milton
    .isOnQuest 542

step
    .dungeon RFD
    .goto 1453/0,848.75,-8522.65
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Archbishop Benedictus|r
    .turnin 3636 >> Turn in Bring the Light
    .target Archbishop Benedictus
    .isQuestComplete 3636

step
    #completewith next
    .goto 1453/0,870.96,-9018.52,15 >> Travel towards |cRXP_FRIENDLY_High Sorcerer Andromath|r in the Mage Tower

step
    .goto 1453/0,876.60,-9010.72
    .target High Sorcerer Andromath
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_High Sorcerer Andromath|r
    .accept 1477 >> Accept Vital Supplies

step
    #ah
    .goto 1453/0,613.93,-8933.64
    .goto 1453/0,660.28,-8814.55
    +|cRXP_WARN_Check your bank for any missing|r |T134332:0|t[Green Hills of Stranglethorn - Pages] |cRXP_WARN_and buy any that you still need from the Auction House|r
    >>|cRXP_WARN_Chapter.1 requires: Pages 1,4,6,8|r
    >>|cRXP_WARN_Chapter.2 requires: Pages 10,11,14,16|r
    >>|cRXP_WARN_Chapter.3 requires: Pages 18,20,21,24|r
    >>|cRXP_WARN_Chapter.4 requires: Pages 25,26,27|r
    >>|cRXP_WARN_Place any newly bought Pages into your bank. Skip this step if you aren't able to acquire them|r
    .target Newton Burnside
    .target Auctioneer Jaxon

step << Warlock
    .goto StormwindClassic,52.623,65.701
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Innkeeper Allison|r
    .home >> Set your Hearthstone to Stormwind City
    .target Innkeeper Allison

step << Warlock
    #completewith next
    .goto StormwindClassic,66.277,62.137
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Dungar Longdrink|r
    .fly Westfall >> Fly to Westfall
    .target Dungar Longdrink

step << Warlock
    #completewith next
    .goto 1434/0,-54.59,-11628.54,100 >> Travel to Nesingwary's Expedition in STV

step << Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sir S. J. Erlgadin|r and |cRXP_FRIENDLY_Hemet Nesingwary|r
    .accept 193 >> Accept Panther Mastery
    .target +Sir S. J. Erlgadin
    .goto 1434/0,-48.08,-11617.39
    .accept 196 >> Accept Raptor Mastery
    .target +Hemet Nesingwary
    .goto 1434/0,-54.59,-11628.54

step << Warlock
    .hs >> Hearth to Stormwind
    >>|cRXP_BUY_Buy food/water if needed|r
    .zoneskip Stormwind City

step
    #label start
    .goto 1453/0,490.03,-8835.82
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Dungar Longdrink|r
    .fly Booty Bay>> Fly to Booty Bay
    .target Dungar Longdrink

step
    .isQuestComplete 1116
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Krazek|r up stairs
    .goto 1434/0,501.53,-14453.26
    .turnin 1116 >>Turn in Dream Dust in the Swamp
    .target Krazek

step
    #optional
    .goto 1434/0,501.53,-14453.26
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Krazek|r
    .accept 627 >> Accept Favor for Krazek
    .turnin 627 >> Turn in Favor for Krazek
    .accept 622 >> Accept Return to Corporal Kaleb
    .itemcount 4278,4
    .target Krazek

step
    #optional
    .isQuestTurnedIn 627
    .goto 1434/0,501.53,-14453.26
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Krazek|r
    .accept 622 >> Accept Return to Corporal Kaleb
    .target Krazek

step
    .goto Stranglethorn Vale,27.000,77.124
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kebok|r
    .accept 209 >> Accept Skullsplitter Tusks
    .target Kebok

step
    .goto 1434/0,486.86,-14444.76
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Fleet Master Seahorn|r
    .turnin 669 >> Turn in Sunken Treasure
    .target Fleet Master Seahorn
    .isOnQuest 669

step
    .goto 1434/0,479.84,-14466.96
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Catelyn the Blade|r inside the Inn
    .turnin 603 >> Turn in Ansirem's Key
    .accept 610 >> Accept "Pretty Boy" Duncan
    .target Catelyn the Blade
    .isOnQuest 603

step
    #optional
    .goto 1434/0,479.84,-14466.96
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Catelyn the Blade|r inside the Inn
    .accept 610 >> Accept "Pretty Boy" Duncan
    .target Catelyn the Blade
    .isQuestTurnedIn 603

step
    .goto Stranglethorn Vale,27.120,77.208
    .target Crank Fizzlebub
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Crank Fizzlebub|r
    .accept 600 >> Accept Venture Company Mining
    .accept 621 >> Accept Zanzil's Secret
    .isQuestTurnedIn 605

step
    #optional
    .goto Stranglethorn Vale,27.120,77.208
    .target Crank Fizzlebub
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Crank Fizzlebub|r
    .accept 621 >> Accept Zanzil's Secret

step
    .goto Stranglethorn Vale,27.120,77.208
    .target Crank Fizzlebub
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Crank Fizzlebub|r
    .turnin 1118 >> Turn in Back to Booty Bay
    .timer 6,Back to Booty Bay RP
    .isOnQuest 1118

step
    .goto 1434/0,495.41,-14457.650
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Innkeeper Skindle|r
    .home >> Set your Hearthstone to Booty Bay
    .target Innkeeper Skindle

step
    .goto 1434/0,513.47,-14418.21
    .target Privateer Bloads
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Privateer Bloads|r
    .accept 617 >> Accept Akiris by the Bundle

step
    .goto 1434/0,447.99,-14447.48
    .target "Sea Wolf" MacKinley
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_"Sea Wolf" MacKinley|r
    .accept 606 >> Accept Scaring Shaky

step
    .goto 1434/0,415.32,-14469.64
    .target Drizzlik
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Drizzlik|r
    .accept 628 >> Accept Excelsior
    .isQuestTurnedIn 577

step
    .goto 1434/0,425.15,-14491.68
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|t|cRXP_BUY_Talk to|r |cRXP_FRIENDLY_Glyx|r
    .vendor >> |cRXP_BUY_Buy|r |T134832:0|t[Greater Healing Potions] |cRXP_BUY_from him if they're up|r
    .target Glyx Brewright

step
    .goto 1434/0,427.96,-14411.15
    .target First Mate Crazz
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_First Mate Crazz|r
    .accept 595 >> Accept The Bloodsail Buccaneers

step
    #completewith next
    >>Kill |cRXP_ENEMY_"Pretty Boy" Duncan|r. Loot him for |cRXP_LOOT_Catelyn's Blade|r
    .complete 610,1
    .mob "Pretty Boy" Duncan
    .isOnQuest 610

step
    .goto 1434/0,480.16,-14126.29
    >>Click the |cRXP_PICK_Bloodsail Correspondence|r on top of the barrel
    .turnin 595 >> Turn in The Bloodsail Buccaneers
    .accept 597 >> Accept The Bloodsail Buccaneers

step
    .goto Stranglethorn Vale,27.40,69.39
    >>Kill |cRXP_ENEMY_"Pretty Boy" Duncan|r. Loot him for |cRXP_LOOT_Catelyn's Blade|r
    .complete 610,1
    .mob "Pretty Boy" Duncan
    .isOnQuest 610

step
    .goto 1434/0,427.96,-14411.15
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_First Mate Crazz|r
    .turnin 597 >> Turn in The Bloodsail Buccaneers
    .accept 599 >> Accept The Bloodsail Buccaneers
    .target First Mate Crazz

step
    .goto 1434/0,479.84,-14466.96
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Catelyn the Blade|r
    .turnin 610 >> Turn in "Pretty Boy" Duncan
    .accept 611 >> Accept The Curse of the Tides
    .target Catelyn the Blade
    .isOnQuest 610

step
    #optional
    .goto 1434/0,479.84,-14466.96
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Catelyn the Blade|r
    .accept 611 >> Accept The Curse of the Tides
    .target Catelyn the Blade
    .isQuestTurnedIn 611

step << !Warlock
    .goto Stranglethorn Vale,26.920,77.347
    .target Deeg
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Deeg|r
    .accept 587 >> Accept Up to Snuff

step
    .goto 1434/0,486.86,-14444.76
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Fleet Master Seahorn|r
    .turnin 599 >> Turn in The Bloodsail Buccaneers
    .target Fleet Master Seahorn

step
    .goto 1434/0,396.37,-14397.62
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Dizzy One-Eye|r
    .accept 576 >> Accept Keep An Eye Out
    .target Dizzy One-Eye

step
    #completewith next
    >>Keep any |T134298:0|t[|cRXP_LOOT_Gorilla Fangs|r] you might loot. You will need 10 for a quest later
    .collect 2799,10

step
    .goto 1434/0,186.49,-14030.95,70,0
    .goto 1434/0,85.67,-13941.19,70,0
    .goto 1434/0,87.58,-13846.32,70,0
    .goto 1434/0,33.98,-13923.32,70,0
    .goto 1434/0,186.49,-14030.95,70,0
    .goto 1434/0,85.67,-13941.19
    >>Kill |cRXP_ENEMY_Elder Mistvale Gorillas|r. Loot them for their |cRXP_LOOT_Mistvale Giblets|r and |cRXP_LOOT_Gorilla Fangs|r
    .complete 606,1
    .mob Elder Mistvale Gorilla

step
    .goto 1434/0,480.67,-13273.71,70,0
    .goto 1434/0,425.79,-13179.69,70,0
    .goto 1434/0,391.97,-13028.67,70,0
    .goto 1434/0,228.61,-13015.060,70,0
    .goto 1434/0,188.41,-12907.85
    >>Kill |cRXP_ENEMY_Jungle Stalkers|r
    .complete 196,1
    .mob Jungle Stalker
    .isOnQuest 196

step
    #optional
    .goto 1434/0,407.92,-13163.10,0
    .goto 1434/0,234.99,-13005.27,0
    .goto 1434/0,407.92,-13163.10,55,0
    .goto 1434/0,388.78,-13032.50,55,0
    .goto 1434/0,234.99,-13005.27,55,0
    .goto 1434/0,194.15,-12927.42,55,0
    .goto 1434/0,234.99,-13005.27,55,0
    .goto 1434/0,388.78,-13032.50,55,0
    .goto 1434/0,407.92,-13163.10,55,0
    .goto 1434/0,459.61,-12844.89,0
    .goto 1434/0,395.80,-12972.52,0
    .goto 1434/0,89.50,-12844.89,0
    .goto 1434/0,204.36,-12887.43,0
    .goto 1434/0,234.99,-13005.27
    >>Kill |cRXP_ENEMY_Tethis|r. Loot him for his |cRXP_LOOT_Talon|r
    >>|cRXP_ENEMY_Tethis|r |cRXP_WARN_can spawn in any of the spots marked on your map|r
    .isOnQuest 197
    .complete 197,1
    .unitscan Tethis

step
    .goto 1434/0,-436.96,-13027.40,40,0
    .goto 1434/0,-445.89,-12920.19,40,0
    .goto 1434/0,-436.96,-13027.40
    >>Kill |cRXP_ENEMY_Venture Co. Foremen|r, |cRXP_ENEMY_Venture Co. Surveyors|r, |cRXP_ENEMY_Venture Co. Strip Miners|r and |cRXP_ENEMY_Venture Co. Tinkerers|r. Loot them for their |cRXP_LOOT_Singing Blue Crystals|r
    .complete 600,1
    .mob Venture Co. Foreman
    .mob Venture Co. Surveyor
    .mob Venture Co. Strip Miner
    .mob Venture Co. Tinkerer
    .isOnQuest 600

step
    #label SpellfrostFrostfire
    .goto 1434/0,-463.76,-12701.10,50,0
    .goto 1434/0,-727.94,-12539.44,50,0
    .goto 1434/0,-463.76,-12701.10,50,0
    .goto 1434/0,-727.94,-12539.44
    .goto 1434/0,-463.76,-12701.10,0
    .goto 1434/0,-805.79,-12878.920,0
    .goto 1434/0,-700.50,-12966.99,0
    >>Kill any |cRXP_ENEMY_Skullsplitter Trolls|r. Loot them for their |cRXP_LOOT_Skullsplitter Tusks|r
    >>Kill |cRXP_ENEMY_Skullsplitter Mystics|r and |cRXP_ENEMY_Skullsplitter Witch Doctors|r. Loot them for their |cRXP_LOOT_Skullsplitter Fetishes|r
    .complete 209,1
    .complete 205,1
    .mob Skullsplitter Mystic
    .mob Skullsplitter Witch Doctor

step
    .goto 1434/0,-791.12,-12359.92,35,0
    .goto 1434/0,-957.03,-12215.27,35,0
    .goto 1434/0,-867.69,-11985.55,35,0
    .goto 1434/0,-940.44,-12196.98
    .goto 1434/0,-791.12,-12359.92,0
    .goto 1434/0,-957.03,-12215.27,0
    .goto 1434/0,-867.69,-11985.55,0
    >>Kill |cRXP_ENEMY_Bhag'thera|r. Loot him for the |cRXP_LOOT_Fang of Bhag'thera|r
    >>|cRXP_ENEMY_Bhag'thera|r |cRXP_WARN_can spawn north or west of the Mosh'Ogg Ogre Mound|r
    .complete 193,1
    .unitscan Bhag'thera
    .isOnQuest 193

step
    #completewith next
    .goto Stranglethorn Vale,46.30,7.61,30 >> Enter The Stockpile (Kurzen's Cave)

step
    .isOnQuest 202
    >>Kill |cRXP_ENEMY_Kurzen Elites|r and |cRXP_ENEMY_Kurzen Subchiefs|r
    >>Kill |cRXP_ENEMY_Colonel Kurzen|r. Loot him for his |cRXP_LOOT_Head|r
    >>|cRXP_WARN_If you can't kill |cRXP_ENEMY_Colonel Kurzen|r skip this step|r
    .complete 202,1
    .mob +Kurzen Elite
    .complete 202,2
    .mob +Kurzen Subchief
    .complete 202,3
    .mob +Colonel Kurzen

step
    .goto 1434/0,-193.32,-11320.16
    .target Brother Nimetz
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Brother Nimetz|r
    .turnin 205 >> Turn in Troll Witchery

step
    .goto 1434/0,-206.72,-11296.89
    .target Lieutenant Doren
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Lieutenant Doren|r
    .turnin 202 >> Turn in Colonel Kurzen
    .isQuestComplete 202

step
    #optional
    .isOnQuest 622
    .goto Stranglethorn Vale,37.740,3.300
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Corporal Kaleb|r
    .turnin 622 >> Turn in Return to Corporal Kaleb
    .target Corporal Kaleb

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sir S. J. Erlgadin|r
    .turnin 193 >> Turn in Panther Mastery
    .target Sir S. J. Erlgadin
    .goto 1434/0,-48.08,-11617.39
    .isOnQuest 193

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Hemet Nesingwary|r
    .turnin 196 >> Turn in Raptor Mastery
    .target Hemet Nesingwary
    .goto 1434/0,-54.59,-11628.54
    .isOnQuest 196

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Hemet Nesingwary|r
    .accept 197 >> Accept Raptor Mastery
    .target Hemet Nesingwary
    .goto 1434/0,-54.59,-11628.54
    .isQuestAvailable 197
    .isQuestTurnedIn 196

step
    .goto 1434/0,845.67,-11873.67,70,0
    .goto 1434/0,776.12,-11946.84,70,0
    .goto 1434/0,591.70,-11986.40,70,0
    .goto Stranglethorn Vale,29.00,21.44,70,0
    .goto 1434/0,305.18,-12313.97,70,0
    .goto Stranglethorn Vale,29.00,21.44,70,0
    .goto 1434/0,591.70,-11986.40,70,0
    .goto 1434/0,776.12,-11946.84,70,0
    .goto 1434/0,845.67,-11873.67
    >>Kill a |cRXP_ENEMY_Elder Saltwater Crocolisk|r. Loot it for its |cRXP_LOOT_Elder Crocolisk Skin|r
    .complete 628,1
    .unitscan Elder Saltwater Crocolisk
    .isOnQuest 628

step << !Warlock
    #completewith Gazban
    #optional
    +|cRXP_WARN_PAY CLOSE ATTENTION TO YOUR BREATH BAR|r
    .isOnQuest 611
    .itemcount 5996,<1

step << !Warlock !Druid
    #completewith Gazban
    #optional
    .cast 7178 >> |cRXP_WARN_Use your|r |T134797:0|t[Elixir of Water Breathing] |cRXP_WARN_if you have one|r
    >>|cRXP_WARN_PAY CLOSE ATTENTION TO YOUR BREATH BAR IF YOU DO NOT HAVE ONE!|r
    .use 5996
    .aura 7178
    .isOnQuest 611
    .itemcount 5996,1

step
    #completewith Gazban
    #optional
    .goto 1434/0,628.26,-12172.14
    .cast 3678 >> |cRXP_WARN_Use|r |T135637:0|t[Catelyn's Blade] |cRXP_WARN_on the |cRXP_PICK_Altar of the Tides|r underwater to summon|r |cRXP_ENEMY_Gazban|r
    .use 4027
    .isOnQuest 611

step
    #label Gazban
    .goto 1434/0,628.26,-12172.14
    >>Kill |cRXP_ENEMY_Gazban|r. Loot him for the |cRXP_LOOT_Stone of the Tides|r
    .complete 611,1
    .isOnQuest 611
    .mob Gazban

step
    #completewith BBTurnin
    .hs >> Hearth to Booty Bay
    >>|cRXP_BUY_Buy food/water if needed|r << !Warrior !Rogue
    >>|cRXP_BUY_Buy food if needed|r << Warrior/Rogue

step
    .goto Stranglethorn Vale,27.120,77.208
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Crank Fizzlebub|r
    .turnin 600 >> Turn in Venture Company Mining
    .target Crank Fizzlebub
    .isOnQuest 600

step << Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Krazek|r and |cRXP_FRIENDLY_Kebok|r
    .accept 587 >> Accept Up to Snuff
    .target +Krazek
    .goto Stranglethorn Vale,26.920,77.347
    .turnin 209 >> Turn in Skullsplitter Tusks
    .target +Kebok
    .goto Stranglethorn Vale,27.000,77.124

step << !Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kebok|r
    .turnin 209 >> Turn in Skullsplitter Tusks
    .goto Stranglethorn Vale,27.000,77.124
    .target Kebok

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Fleet Master Seahorn|r and |cRXP_FRIENDLY_Baron Revilgaz|r
    .accept 604 >> Accept The Bloodsail Buccaneers
    .target +Fleet Master Seahorn
    .goto 1434/0,486.86,-14444.76
    .turnin 611 >> Turn in The Curse of the Tides
    .target +Baron Revilgaz
    .goto 1434/0,483.41,-14438.930
    .isOnQuest 611

step
    #optional
    #label BBTurnin
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Fleet Master Seahorn|r
    .accept 604 >> Accept The Bloodsail Buccaneers
    .target Fleet Master Seahorn
    .goto 1434/0,486.86,-14444.76

step
    .goto 1434/0,527.31,-14426.160,-1
    .goto 1434/0,528.84,-14421.95,-1
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Viznik|r or |cRXP_FRIENDLY_Rickle|r
    .bankwithdraw 6065,2725,2728,2730,2732,2734,2735,2738,2740,2742,2744,2745,2748,2749,2750,2751 >> Withdraw the following items from your bank:
    >>Any |T134332:0|t[Green Hills of Stranglethorn - Pages] you found
    >>|T133461:0|t[Khadgar's Essays on Dimensional Convergence] (If you have it)
    .target Viznik Goldgrubber
    .target Rickle Goldgrubber

step
    #ah
    .goto 1434/0,524.19,-14416.72
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Auctioneer O'reely|r
    +|cRXP_WARN_Buy any|r |T134332:0|t[Green Hills of Stranglethorn - Pages] |cRXP_WARN_you are missing|r
    >>|cRXP_WARN_Ch.1: 1,4,6,8|r
    >>|cRXP_WARN_Ch.2: 10,11,14,16|r
    >>|cRXP_WARN_Ch.3: 18,20,21,24|r
    >>|cRXP_WARN_Ch.4: 25,26,27|r
    >>|cRXP_WARN_Skip this step if you aren't able to acquire them|r
    .target Auctioneer O'reely

step
    .goto 1434/0,504.53,-14299.390
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_"Shaky" Phillipe|r
    .turnin 606 >> Turn in Scaring Shaky
    .target "Shaky" Phillipe
    .accept 607 >> Accept Return to MacKinley

step
    .goto 1434/0,447.99,-14447.48
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_"Sea Wolf" MacKinley|r
    .turnin 607 >> Turn in Return to MacKinley
    .accept 609 >> Accept Voodoo Dues
    .target "Sea Wolf" MacKinley

step
    #label start2
    .goto 1434/0,415.32,-14469.64
    .target Drizzlik
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Drizzlik|r
    .turnin 628 >> Turn in Excelsior
    .isOnQuest 628

step
    .goto 1434/0,425.15,-14491.68
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|t|cRXP_BUY_Talk to|r |cRXP_FRIENDLY_Glyx|r
    .vendor >> |cRXP_BUY_Buy|r |T134832:0|t[Greater Healing Potions] |cRXP_BUY_from him if they're up|r
    .target Glyx Brewright

step
    #completewith Reed
    #label ReedGotoOne
    #optional
    .goto 1434/0,459.61,-14146.67,50 >> Head past the pirate camp north of Booty Bay

step
    #requires ReedGotoOne
    #completewith Reed
    .goto 1434/0,555.33,-14019.04,50 >> Head through the bridge to the island

step
    #label Reed
    .goto 1434/0,495.34,-13848.870,60,0
    .goto 1434/0,541.29,-13729.760,60,0
    .goto 1434/0,617.86,-13724.23,60,0
    .goto 1434/0,645.30,-13903.75,60,0
    .goto 1434/0,562.35,-13825.48
    >>Kill |cRXP_ENEMY_Naga Explorers|r on the island. Loot them for their |cRXP_LOOT_Akiris Reeds|r
    .complete 617,1
    .mob Naga Explorer

step
    .goto 1434/0,121.40,-14321.09,100 >> Head to the beach east of booty bay

step
    #completewith Bloodsails
    >>Open the |cRXP_PICK_Half-Buried Bottles|r along the coast. Loot them for a |T133469:0|t[|cRXP_LOOT_Carefully Folded Note|r]
    >>|cRXP_WARN_Don't start the quest for this yet|r

    .collect 4098,1,594,1

step
    #completewith next
    >>Kill the |cRXP_ENEMY_Bloodsail|r. Loot them for their |cRXP_LOOT_Snuff|r and |cRXP_LOOT_Dizzy's Eye|r
    .complete 587,1
    .complete 576,1
    .mob Bloodsail Swashbuckler
    .mob Bloodsail Mage
    .mob Bloodsail Raider
    .mob Bloodsail Warlock

step
    #label Bloodsails
    .goto 1434/0,194.15,-14548.68,100,0
    .goto 1434/0,334.54,-14636.32,75,0
    .goto 1434/0,498.53,-14708.220,70,0
    .goto 1434/0,334.54,-14636.32,75,0
    .goto 1434/0,498.53,-14708.220
    >>Kill |cRXP_ENEMY_Bloodsail Swashbucklers|r
    >>Loot the |cRXP_LOOT_Bloodsail Charts|r and |cRXP_LOOT_Bloodsail Orders|r. These can spawn randomly at one of the camps or in the small rowboat
    .complete 604,1
    .complete 604,2
    .complete 604,3
    .mob Bloodsail Swashbuckler

step
    #completewith CRiddle
    >>Open the |cRXP_PICK_Half-Buried Bottles|r along the coast. Loot them for a |T133469:0|t[|cRXP_LOOT_Carefully Folded Note|r]
    >>|cRXP_WARN_Don't start the quest for this yet|r

    .collect 4098,1,594,1

step
    #completewith CRiddle
    >>Kill the |cRXP_ENEMY_Bloodsail|r. Loot them for their |cRXP_LOOT_Snuff|r and |cRXP_LOOT_Dizzy's Eye|r
    .complete 587,1
    .complete 576,1
    .mob Bloodsail Swashbuckler
    .mob Bloodsail Mage
    .mob Bloodsail Raider
    .mob Bloodsail Warlock

step
    .goto 1434/0,194.15,-14548.68,100,0
    .goto 1434/0,334.54,-14636.32,75,0
    .goto 1434/0,498.53,-14708.220,70,0
    .goto 1434/0,334.54,-14636.32,75,0
    .goto 1434/0,498.53,-14708.220
    >>Kill |cRXP_ENEMY_Bloodsail Swashbucklers|r
    >>Loot the |cRXP_LOOT_Bloodsail Charts|r and |cRXP_LOOT_Bloodsail Orders|r. These can spawn randomly at one of the camps or in the small rowboat
    .complete 604,1
    .complete 604,2
    .complete 604,3
    .mob Bloodsail Swashbuckler

step
    #label CRiddle
    >>|cRXP_WARN_Search the Bloodsail Ships for|r |T134939:0|t[|cRXP_LOOT_Cortello's Riddle|r]|cRXP_WARN_. It can spawn on any of the 3 ships|r
    >>|cRXP_WARN_Use |T134939:0|t[|cRXP_LOOT_Cortello's Riddle|r] to start the quest|r
    .goto 1434/0,353.04,-14926.03,0
    .goto 1434/0,269.45,-15024.30,0
    .goto 1434/0,122.04,-14922.20,0
    .goto 1434/0,261.79,-14937.94
    .collect 4056,1,624,1
    .accept 624 >> Accept Cortello's Riddle
    .use 4056

step
    #completewith next
    >>Open the |cRXP_PICK_Half-Buried Bottles|r along the coast. Loot them for a |T133469:0|t[|cRXP_LOOT_Carefully Folded Note|r]
    >>|cRXP_WARN_Don't start the quest for this yet|r

    .collect 4098,1,594,1

step
    .goto 1434/0,194.15,-14548.68,100,0
    .goto 1434/0,334.54,-14636.32,75,0
    .goto 1434/0,498.53,-14708.220,70,0
    .goto 1434/0,334.54,-14636.32,75,0
    .goto 1434/0,498.53,-14708.220
    >>Kill the |cRXP_ENEMY_Bloodsail|r. Loot them for their |cRXP_LOOT_Snuff|r and |cRXP_LOOT_Dizzy's Eye|r
    .complete 587,1
    .complete 576,1
    .mob Bloodsail Swashbuckler
    .mob Bloodsail Mage
    .mob Bloodsail Raider
    .mob Bloodsail Warlock

step
    #completewith Chucky
    .goto 1434/0,-331.03,-13646.38
    .subzone 311 >> Travel to the Ruins of Aboraz

step
    #completewith next
    .goto 1434/0,-331.03,-13646.38,0
    .goto 1434/0,-7.50,-13374.11,0
    >>Kill the |cRXP_ENEMY_Zanzils|r. Loot them for their |cRXP_LOOT_Mixtures|r
    .complete 621,1
    .mob Zanzil Witch Doctor
    .mob Zanzil Zombie
    .mob Zanzil Hunter
    .mob Zanzil Naga

step
    #label Chucky
    .goto 1434/0,-331.03,-13646.38
    >>Kill |cRXP_ENEMY_Chucky "Ten Thumbs"|r. Loot him for his |cRXP_LOOT_Huge Ring|r
    .complete 609,3
    .mob Chucky "Ten Thumbs"

step
    #completewith FinalZanzil
    .goto 1434/0,-7.50,-13374.11
    .subzone 477 >> Travel to the Ruins of Jubuwal

step
    #completewith FinalZanzil
    .goto 1434/0,-331.03,-13646.38,0
    .goto 1434/0,-7.50,-13374.11,0
    >>Kill the |cRXP_ENEMY_Zanzils|r. Loot them for their |cRXP_LOOT_Mixtures|r
    .complete 621,1
    .mob Zanzil Witch Doctor
    .mob Zanzil Zombie
    .mob Zanzil Hunter
    .mob Zanzil Naga

step
    #completewith next
    .goto 1434/0,-7.50,-13374.11
    >>Kill |cRXP_ENEMY_Jon-Jon the Crow|r. Loot him for his |cRXP_LOOT_Golden Spyglass|r
    .complete 609,2
    .mob Jon-Jon the Crow

step
    .goto 1434/0,-29.20,-13350.29
    >>Kill |cRXP_ENEMY_Maury "Club Foot" Wilkins|r. Loot him for his |cRXP_LOOT_Clubbed Foot|r
    .complete 609,1
    .mob Maury "Club Foot" Wilkins

step
    #label FinalZanzil
    .goto 1434/0,-7.50,-13374.11
    >>Kill |cRXP_ENEMY_Jon-Jon the Crow|r. Loot him for his |cRXP_LOOT_Golden Spyglass|r
    .complete 609,2
    .mob Jon-Jon the Crow

step
    .goto 1434/0,-7.50,-13374.11,70,0
    .goto 1434/0,-331.03,-13646.38,70,0
    .goto 1434/0,-7.50,-13374.11,70,0
    .goto 1434/0,-331.03,-13646.38,70,0
    .goto 1434/0,-7.50,-13374.11
    .goto 1434/0,-331.03,-13646.38,0
    >>Kill the |cRXP_ENEMY_Zanzils|r. Loot them for their |cRXP_LOOT_Mixtures|r
    .complete 621,1
    .mob Zanzil Witch Doctor
    .mob Zanzil Zombie
    .mob Zanzil Hunter
    .mob Zanzil Naga

step
    .goto 1434/0,407.92,-13163.10,0
    .goto 1434/0,234.99,-13005.27,0
    .goto 1434/0,407.92,-13163.10,55,0
    .goto 1434/0,388.78,-13032.50,55,0
    .goto 1434/0,234.99,-13005.27,55,0
    .goto 1434/0,194.15,-12927.42,55,0
    .goto 1434/0,234.99,-13005.27,55,0
    .goto 1434/0,388.78,-13032.50,55,0
    .goto 1434/0,407.92,-13163.10,55,0
    .goto 1434/0,459.61,-12844.89,0
    .goto 1434/0,395.80,-12972.52,0
    .goto 1434/0,89.50,-12844.89,0
    .goto 1434/0,204.36,-12887.43,0
    .goto 1434/0,234.99,-13005.27
    >>Kill |cRXP_ENEMY_Tethis|r. Loot him for his |cRXP_LOOT_Talon|r
    >>|cRXP_ENEMY_Tethis|r |cRXP_WARN_can spawn in any of the spots marked on your map|r
    .complete 197,1
    .unitscan Tethis
    .isOnQuest 197

step
    #completewith PagesTurnIn
    .goto 1434/0,-54.59,-11628.54,80 >> Travel to Nesingwary's Expedition

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Sir S. J. Erlgadin|r and |cRXP_FRIENDLY_Hemet Nesingwary|r
    .turnin 197 >> Turn in Raptor Mastery
    .accept 208 >> Accept Big Game Hunter
    .goto 1434/0,-54.59,-11628.54
    .target Hemet Nesingwary
    .isOnQuest 197

step
    #optional
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Hemet Nesingwary|r
    .accept 208 >> Accept Big Game Hunter
    .goto 1434/0,-54.59,-11628.54
    .target Hemet Nesingwary
    .isQuestTurnedIn 197
    .isQuestTurnedIn 193
    .isQuestTurnedIn 188

step
    #label PagesTurnIn
    .goto 1434/0,-54.85,-11616.63
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Barnil Stonepot|r
    >>|cRXP_WARN_Turn in all your|r |T134332:0|t[Green Hills of Stranglethorn - Pages]
    >>|cRXP_WARN_Skip this step if you don't have all the|r |T133677:0|t[Green Hills of Stranglethorn - Chapters]
    .accept 338 >> Accept The Green Hills of Stranglethorn
    .accept 339 >> Accept Chapter I
    .accept 340 >> Accept Chapter II
    .accept 341 >> Accept Chapter III
    .accept 342 >> Accept Chapter IV
    .turnin 339 >> Turn in Chapter I
    .turnin 340 >> Turn in Chapter II
    .turnin 341 >> Turn in Chapter III
    .turnin 342 >> Turn in Chapter IV
    .turnin 338 >> Turn in The Green Hills of Stranglethorn
    .target Barnil Stonepot

step
    #optional
    #completewith next
    +|cRXP_WARN_Use the|r |T133581:0|t[Flash Bomb] |cRXP_WARN_on |cRXP_ENEMY_King Bangalash|r when he is at 55%|r
    .itemcount 4852,1
    .use 4852

step
    .goto Stranglethorn Vale,38.20,35.57
    >>Kill |cRXP_ENEMY_King Bangalash|r. Loot him for the |cRXP_LOOT_Head of Bangalash|r
    >>|cRXP_ENEMY_King Bangalash|r |cRXP_WARN_will spawn 2 |cRXP_ENEMY_Panthers|r at 50% health. Try to CC him just before 50% if possible so it prevents him from spawning any|r
    >>If you saved the |T133581:0|t[|cRXP_LOOT_Flash Bomb|r] from the Badlands you can use it to |T136183:0|t[|cRXP_FRIENDLY_Fear|r] him. |cRXP_WARN_This fear DOES NOT break on damage making it very useful for bringing him below the 50% threshold while CCd|r
    .complete 208,1
    .mob King Bangalash
    .use 4852
    .isOnQuest 208

step
    .goto 1434/0,-54.59,-11628.54
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Hemet Nesingwary|r
    .turnin 208 >> Turn in Big Game Hunter
    .target Hemet Nesingwary
    .isQuestComplete 208

step
    #completewith next
    .goto 1431/0,-370.87,-11271.87
    .zone Duskwood >> Travel north into Duskwood and head to Darkshire

step
    .goto 1431/0,-1212.70,-10547.53
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Watchmaster Sorigal|r
    .turnin 1477 >> Turn in Vital Supplies
    .accept 1395 >> Accept Supplies for Nethergarde
    .target Watchmaster Sorigal

step
    .goto 1431/0,-1555.36,-10454.670,50,0
    .goto 1430/0,-2033.83,-10443.330,60,0
    .goto 1430/0,-2294.08,-10558.50,50 >> Travel to Swamp of Sorrows
    .zoneskip Swamp of Sorrows

step
    .goto 1435/0,-2747.50,-10357.59
    >>Click |cRXP_PICK_A Soggy Scroll|r in the water under the bridge
    .turnin 624 >> Turn in Cortello's Riddle
    .accept 625 >> Accept Cortello's Riddle
    .isOnQuest 624

step
    .goto 1435/0,-2747.50,-10357.59
    >>Click |cRXP_PICK_A Soggy Scroll|r in the water under the bridge
    .accept 625 >> Accept Cortello's Riddle
    .isQuestTurnedIn 624

step
    .isOnQuest 1364
    #completewith mazens
    >>Kill |cRXP_ENEMY_Swampwalkers|r, |cRXP_ENEMY_Swampwalker Elders|r, |cRXP_ENEMY_Tangled Horrors|r and |cRXP_ENEMY_Mire Lords|r. Loot them for |cRXP_LOOT_Khadgar's Essays|r
    .complete 1364,1
    .mob Swampwalker
    .mob Swampwalker Elder
    .mob Tangled Horror
    .mob Mire Lord

step
    .goto 1435/0,-2836.27,-10535.58
    .target Watcher Biggs
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Watcher Biggs|r
    .accept 1398 >> Accept Driftwood
    .isQuestTurnedIn 1421

step
    #completewith next
    .goto 1435/0,-4053.56,-9726.350,0
    .goto 1435/0,-4296.70,-9985.54,0
    .goto 1435/0,-4398.08,-10365.23,0
    .goto 1435/0,-4107.92,-11023.69,0
    >>Loot |cRXP_LOOT_Sundried Driftwood|r on the ground along the coast
    .complete 1398,1
    .isOnQuest 1398

step
    .goto 1435/0,-4053.56,-9726.350,70,0
    .goto 1435/0,-4296.70,-9985.54,70,0
    .goto 1435/0,-4398.08,-10365.23,70,0
    .goto 1435/0,-4323.07,-10692.32,70,0
    .goto 1435/0,-4107.92,-11023.69,70,0
    .goto 1435/0,-4323.07,-10692.32,70,0
    .goto 1435/0,-4398.08,-10365.23,70,0
    .goto 1435/0,-4296.70,-9985.54,70,0
    .goto 1435/0,-4053.56,-9726.350,70,0
    .goto 1435/0,-4296.70,-9985.54,70,0
    .goto 1435/0,-4398.08,-10365.23,70,0
    .goto 1435/0,-4323.07,-10692.32
    >>Kill |cRXP_ENEMY_Silt Crawlers|r and |cRXP_ENEMY_Monstrous Crawlers|r. Loot them for their |cRXP_LOOT_Pristine Crawler Legs|r
    .complete 1258,1
    .mob Silt Crawler
    .mob Monstrous Crawler
    .isOnQuest 1258

step
    #label mazens
    .goto 1435/0,-4053.56,-9726.350,0
    .goto 1435/0,-4296.70,-9985.54,0
    .goto 1435/0,-4398.08,-10365.23,0
    .goto 1435/0,-4107.92,-11023.69,0
    .goto 1435/0,-4053.56,-9726.350,70,0
    .goto 1435/0,-4296.70,-9985.54,70,0
    .goto 1435/0,-4398.08,-10365.23,70,0
    .goto 1435/0,-4323.07,-10692.32,70,0
    .goto 1435/0,-4107.92,-11023.69,70,0
    .goto 1435/0,-4323.07,-10692.32,70,0
    .goto 1435/0,-4398.08,-10365.23,70,0
    .goto 1435/0,-4296.70,-9985.54,70,0
    .goto 1435/0,-4053.56,-9726.350,70,0
    .goto 1435/0,-4296.70,-9985.54,70,0
    .goto 1435/0,-4398.08,-10365.23,70,0
    .goto 1435/0,-4323.07,-10692.32
    >>Loot |cRXP_LOOT_Sundried Driftwood|r on the ground along the coast
    .complete 1398,1
    .isOnQuest 1398

step
    .isOnQuest 1364
    .goto 1435/0,-2383.25,-10104.36,70,0
    .goto 1435/0,-2566.29,-10191.36
    >>Kill |cRXP_ENEMY_Swampwalkers|r, |cRXP_ENEMY_Swampwalker Elders|r, |cRXP_ENEMY_Tangled Horrors|r and |cRXP_ENEMY_Mire Lords|r. Loot them for |cRXP_LOOT_Khadgar's Essays|r
    >>|cRXP_WARN_The drop rate of this item is very low. Once there is no more to kill in Misty Valley, skip this step|r
    .complete 1364,1
    .mob Swampwalker
    .mob Swampwalker Elder
    .mob Tangled Horror
    .mob Mire Lord

step
    .goto 1435/0,-2836.27,-10535.58
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Watcher Biggs|r
    .turnin 1398 >> Turn in Driftwood
    .target Watcher Biggs
    .isOnQuest 1398

step
    #optional
    .goto 1435/0,-2836.27,-10535.58
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Watcher Biggs|r
    .accept 1425 >> Accept Deliver the Shipment
    .target Watcher Biggs
    .isQuestAvailable 1425
    .isQuestTurnedIn 1398

step
    #completewith ExitBL
    .goto 1435/0,-2985.13,-10650.11,0
    .goto 1419/0,-2983.00,-10732.60
    .zone Blasted Lands >> Travel to the Blasted Lands

step
    .isQuestComplete 1364
    .goto 1419/0,-3507.81,-10994.68
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Watcher Mahar Ba|r atop the Tower
    .turnin 1364 >> Turn in Mazen's Behest
    .target Watcher Mahar Ba

step
    .isOnQuest 1425,1395
    .goto 1419/0,-3470.12,-11044.29
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Quartermaster Lungertz|r
    .turnin 1425 >> Turn in Deliver the Shipment
    .turnin 1395 >> Turn in Supplies for Nethergarde
    .target Quartermaster Lungertz

step
    #optional
    .goto 1419/0,-3437.26,-11110.26
    .abandon 1364 >> Abandon Mazen's Behest

step
    #label ExitBL
    .goto 1419/0,-3437.09,-11110.19
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Alexandra Constantine|r
    .fp Blasted Lands >> Get the Blasted Lands Flight Path
    .fly Booty Bay >> Fly to Booty Bay
    .target Alexandra Constantine

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Deeg|r and |cRXP_FRIENDLY_Krazek|r
    .turnin 587 >> Turn in Up to Snuff
    .target +Deeg
    .goto Stranglethorn Vale,26.920,77.347
    .accept 2864 >> Accept Tran'rek
    .target +Krazek
    .goto 1434/0,501.53,-14453.26

step
    .goto 1434/0,486.86,-14444.76
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Fleet Master Seahorn|r
    .turnin 604 >> Turn in The Bloodsail Buccaneers
    .target Fleet Master Seahorn

step
    .isQuestTurnedIn 1118
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Whiskey Slim|r and |cRXP_FRIENDLY_Crank Fizzlebub|r
    .accept 580 >> Accept Whiskey Slim's Lost Grog
    .target +Whiskey Slim
    .goto 1434/0,489.28,-14463.64
    .turnin 621 >> Turn in Zanzil's Secret
    .accept 1119 >> Accept Zanzil's Mixture and a Fool's Stout
    .target +Crank Fizzlebub
    .goto Stranglethorn Vale,27.120,77.208

step
    #completewith end
    .isOnQuest 1119
    +|cRXP_WARN_Note the Zanzil's Mixture and a Fool's Stout quest has a 2 hour timer that also ticks while you're offline. |r

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Whiskey Slim|r and |cRXP_FRIENDLY_Crank Fizzlebub|r
    .accept 580 >> Accept Whiskey Slim's Lost Grog
    .target +Whiskey Slim
    .goto 1434/0,489.28,-14463.64
    .turnin 621 >> Turn in Zanzil's Secret
    .target +Crank Fizzlebub
    .goto Stranglethorn Vale,27.120,77.208

step
    .goto 1434/0,513.47,-14418.21
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Privateer Bloads|r
    .turnin 617 >> Turn in Akiris by the Bundle
    .accept 623 >> Accept Akiris by the Bundle
    .target Privateer Bloads

step
    .goto 1434/0,527.31,-14426.160,-1
    .goto 1434/0,528.84,-14421.95,-1
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Viznik|r or |cRXP_FRIENDLY_Rickle|r
    .bankdeposit 2799,4098 >> Deposit the following items into your bank:
    >>|T134298:0|t[Gorilla Fangs] (If you have any)
    >>|T133469:0|t[Carefully Folded Note] (If you have it)
    .target Viznik Goldgrubber
    .target Rickle Goldgrubber

step
    .goto 1434/0,527.31,-14426.160,-1
    .goto 1434/0,528.84,-14421.95,-1
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Viznik|r or |cRXP_FRIENDLY_Rickle|r
    .bankwithdraw 5862 >> Withdraw the following items from your bank:
    >>|T132385:0|t[Seaforium Booster]
    .target Viznik Goldgrubber
    .target Rickle Goldgrubber

step
    .goto 1434/0,447.99,-14447.48
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_"Sea Wolf" MacKinley|r
    .turnin 609 >> Turn in Voodoo Dues
    .accept 2872 >> Accept Stoley's Debt
    .target "Sea Wolf" MacKinley

step
    #label end
    .goto 1434/0,396.37,-14397.62
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Dizzy One-Eye|r
    .turnin 576 >> Turn in Keep An Eye Out
    .target Dizzy One-Eye

step
    .goto 1434/0,574.47,-14278.55
    .zone The Barrens >> Take the Boat to Ratchet
]])
