-- Generated by Scripts/split_guide_vault.py; rerun the script to update.
if not RXPGuides or type(RXPGuides.RegisterGuide) ~= "function" then return end
local _, rxpGuideVaultAddon = ...
local rxpGuideVaultGame = rxpGuideVaultAddon and rxpGuideVaultAddon.game
if not rxpGuideVaultGame then
    local rxpGuideVaultVersion = select(4, GetBuildInfo())
    if rxpGuideVaultVersion > 60000 then
        rxpGuideVaultGame = "RETAIL"
    elseif rxpGuideVaultVersion > 50000 then
        rxpGuideVaultGame = "MOP"
    elseif rxpGuideVaultVersion > 40000 then
        rxpGuideVaultGame = "CATA"
    elseif rxpGuideVaultVersion > 30000 then
        rxpGuideVaultGame = "WOTLK"
    elseif rxpGuideVaultVersion > 20000 then
        rxpGuideVaultGame = "TBC"
    elseif rxpGuideVaultVersion >= 16000 and rxpGuideVaultVersion < 20000 then
        rxpGuideVaultGame = "FOREVER"
    else
        rxpGuideVaultGame = "CLASSIC"
    end
end
if rxpGuideVaultGame ~= "FOREVER" then return end

RXPGuides.RegisterGuide([[#forever
#version 23
#group RestedXP Forever Guide (A)
#subgroup Speedrun Guide 30-40

<< Alliance
#name 33-34 Thousand Needles
#next 34-35 Stranglethorn Vale I

step
    #completewith next
    .goto Wetlands,7.270,62.527,25 >> Travel to the Menethil Harbor Dock

step
    .goto 1437/0,-599.46,-3895.60
    .zone Dustwallow Marsh >> Take the boat to Theramore
    >>|cRXP_WARN_Level your|r |T135966:0|t[First Aid] |cRXP_WARN_while waiting|r
    .zoneskip Tanaris
    .zoneskip Thousand Needles
    .zoneskip The Barrens

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Baldruc|r
    .goto 1445/1,-4517.49,-3828.8300
    .fp Theramore >> Get the Theramore Flight Path
    .target Baldruc

step
    #label JamesHyjal
    .goto 1445/1,-4538.54,-3721.70
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Clerk Lendry|r upstairs in the Keep
    .turnin 1302 >> Turn in James Hyal
    .target Clerk Lendry
    .isOnQuest 1302

step
    #label MDiplomat
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Commander Samaul|r
    .turnin 1264 >> Turn in The Missing Diplomat
    .accept 1265 >> Accept The Missing Diplomat
    .goto 1445/1,-4540.96,-3732.230
    .target Commander Samaul

step
    .goto 1445/1,-4448.19,-3645.68
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Guard Byron|r
    .accept 1282 >> Accept They Call Him Smiling Jim
    .target Guard Byron
    .isQuestAvailable 1302

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Innkeeper Janene|r
    .goto 1445/1,-4470.82,-3616.14
    .home >> Set your Hearthstone to Theramore
    .target Innkeeper Janene

step
    .goto 1445/1,-4464.10,-3613.48
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Fiora Longears|r
    .accept 1135 >> Accept Highperch Venom
    .maxlevel 33 << !Hunter !Rogue
    .target Fiora Longears

step
    .goto 1445/1,-4462.94,-3834.54
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Helenia Olden|r
    >>|cRXP_BUY_Buy 3|r |T134059:0|t[Soothing Spices] |cRXP_BUY_from her|r
    .collect 3713,3,1218,1
    .target Helenia Olden

step
    .goto 1445/1,-4110.30,-3474.28 >> Travel to the Sentry Point Tower
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Archmage Tervosh|r
    >>|cRXP_WARN_Stay in |cRXP_FRIENDLY_Archmage Tervosh's|r Line of Sight as he will buff you with|r |T135880:0|t[Proudmoore's Defense] |cRXP_WARN_which gives 10 Stamina and 40 Armor|r
    .complete 1265,1
    .goto 1445/1,-4106.73,-3476.84
    .turnin 1265 >> Turn in The Missing Diplomat
    .accept 1266 >> Accept The Missing Diplomat
    .goto 1445/1,-4106.73,-3476.84
    .target Archmage Tervosh

step
    .goto 1445/1,-3885.44,-2952.780
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_"Swamp Eye" Jarl|r
    .accept 1218 >> Accept Soothing Spices
    .turnin 1218 >> Turn in Soothing Spices
    .target "Swamp Eye" Jarl

step
    #label OrcReport
    .goto 1445/1,-3885.71,-2940.43
    >>Click the |cRXP_PICK_Loose Dirt|r
    .accept 1219 >> Accept The Orc Report

step
    .goto 1445/1,-3350.10,-2896.08
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Private Hendel|r
    .turnin 1266 >> Turn in The Missing Diplomat
    .accept 1324,1 >> Accept The Missing Diplomat
    .target Private Hendel
    .isQuestTurnedIn 1264

step
    .goto 1445/1,-3350.10,-2896.08
    >>Defeat |cRXP_ENEMY_Private Hendel|r. He will attack you along with 2 |cRXP_ENEMY_Theramore Sentries|r
    >>They will both reset once you subdue |cRXP_ENEMY_Private Hendel|r
    .complete 1324,1
    .isOnQuest 1324
    .mob Private Hendel

step
    .isQuestComplete 1324
    .goto 1445/1,-3347.63,-2883.55
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Archmage Tervosh|r |cRXP_WARN_first and then to|r |cRXP_FRIENDLY_Lady Jaina Proudmoore|r
    .turnin 1324 >> Turn in The Missing Diplomat
    .target +Archmage Tervosh
    .turnin 1267 >> Turn in The Missing Diplomat
    .target +Lady Jaina Proudmoore

step
    #sticky
    .abandon 1324 >> Abandon The Missing Diplomat quest if you still have it in your quest log

step
    .goto 1445/1,-2820.58,-3372.26
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Mudcrush Durtfeet|r
    .accept 1177 >> Accept Hungry!
    .target Mudcrush Durtfeet

step
    >>Click the |cRXP_PICK_Hoofprints|r on the ground
    >>Click the |cRXP_PICK_Theramore Guard Badge|r on the wooden plank
    >>Click the |cRXP_PICK_Black Shield|r hanging on the fireplace
    .accept 1284 >> Accept Suspicious Hoofprints
    .goto 1445/1,-2534.51,-3700.91
    .accept 1252 >> Accept Lieutenant Paval Reethe
    .goto 1445/1,-2541.18,-3721.84
    .accept 1253 >> Accept The Black Shield
    .goto 1445/1,-2530.63,-3734.54

step
    #completewith next
    .goto 1413/1,-1857.33,-4550.35,0
    .goto 1441/1,-1845.29,-4621.68
    .zone Thousand Needles >> Travel to Thousand Needles

step
    .goto 1441/1,-1785.23,-4680.82
    >>Loot |T133741:0|t[|cRXP_LOOT_Henrig Lonebrow's Journal|r] from the ground next to the dwarf's corpse
    .collect 5791,1

step
    #sticky
    #label Journal
    .use 5791 >>|cRXP_WARN_Use |T133741:0|t[|cRXP_LOOT_Henrig Lonebrow's Journal|r] to start the quest|r
    .accept 1100 >> Accept Lonebrow's Journal

step
    #completewith next
    .goto 1441/1,-805.40,-4493.29,0
    .goto Feralas,89.50,45.85,50 >> Travel to Thalanaar

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Thyssiana|r
    .goto 1444/1,-778.37,-4491.19
    .fp Thalanaar >> Get the Thalanaar flight path
    .target Thyssiana

step
    #requires Journal
    .goto 1444/1,-787.90,-4524.09
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Falfindel Waywarder|r
    .turnin 1100 >> Turn in Lonebrow's Journal
    .target Falfindel Waywarder

step
    .dungeon RFK
    .goto 1444/1,-787.90,-4524.09
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Falfindel Waywarder|r
    .turnin 1100 >> Turn in Lonebrow's Journal
    .accept 1101 >> Accept The Crone of the Kraul
    .target Falfindel Waywarder

step
    .goto 1444/1,-787.90,-4524.09
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Falfindel Waywarder|r
    .turnin 1059 >> Turn in Reclaiming the Charred Vale
    .target Falfindel Waywarder
    .isOnQuest 1059

step
    .dungeon RFK
    #completewith next
    .goto 1441/1,-912.05,-4941.71,0
    .goto 1441/1,-917.77,-5090.43,0
    .goto 1441/1,-1017.21,-5095.12,0
    .goto 1441/1,-1201.57,-5187.52,0
    .zone The Barrens >> Grind |cRXP_ENEMY_Highperch Wyverns|r, |cRXP_ENEMY_Highperch Consorts|r and |cRXP_ENEMY_Highperch Patriarchs|r while looking for a group for Razorfen Kraul
    .mob Highperch Patriarch
    .mob Highperch Wyvern
    .mob Highperch Consort

step
    .dungeon RFK
    .goto 1413/1,-1781.03,-4480.29,0
    .goto 1413/1,-1781.03,-4480.29,40,0
    .goto 1414,50.877,70.339
    .subzone 491,2 >> Enter Razorfen Kraul

step
    .dungeon RFK
    >>Kill |cRXP_ENEMY_Charlga Razorflank|r. Loot her for |cRXP_LOOT_Razorflank's Heart|r
    .complete 1101,1
    .isOnQuest 1101

step
    .dungeon RFK
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Heralath Fallowbrook|r and |cRXP_FRIENDLY_Willix the Importer|r
    .accept 1142 >> Accept Mortality Wanes
    .target +Heralath Fallowbrook
    .accept 1144 >> Accept Willix the Importer
    .target +Willix the Importer

step
    .dungeon RFK
    #completewith next
    >>Kill all |cRXP_ENEMY_Monsters|r inside of RFK. Loot them for |cRXP_LOOT_Treshala's Pendant|r
    .complete 1142,1
    .isOnQuest 1142

step
    .dungeon RFK
    >>Escort |cRXP_FRIENDLY_Willix the Importer|r through Razorfen Krual
    >>|cRXP_WARN_Ensure you stay close to |cRXP_FRIENDLY_Willix|r otherwise the quest may not complete!|r
    .complete 1144,1
    .isOnQuest 1144

step
    .dungeon RFK
    #completewith next
    >>Kill all |cRXP_ENEMY_Monsters|r inside of RFK. Loot them for |cRXP_LOOT_Treshala's Pendant|r
    .complete 1142,1
    .isOnQuest 1142

step
    .dungeon RFK
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Willix the Importer|r
    .turnin 1144 >> Turn in Willix the Importer
    .target Willix the Importer
    .isQuestComplete 1144

step
    .dungeon RFK
    >>Kill all |cRXP_ENEMY_Monsters|r inside of RFK. Loot them for |cRXP_LOOT_Treshala's Pendant|r
    .complete 1142,1
    .isOnQuest 1142

step
    .dungeon RFK
    .goto 1444/1,-787.90,-4524.09
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Falfindel Waywarder|r
    .turnin 1101 >> Turn in The Crone of the Kraul
    .target Falfindel Waywarder
    .isQuestComplete 1101

step
    .dungeon RFK
    #completewith ABump
    .isQuestComplete 1142
    +NOTE: It is never time efficient to go to Darnassus to turn in Mortality Wanes. Buy a portal from a Mage to Darnassus when the guide tells you to use your Hearthstone next, so you can turn it in at Darnassus then use Hearthstone to remain on track with the guide, otherwise abandon Mortality Wanes

step
    #label HighperchVenomSacs
    .isOnQuest 1135
    .goto 1441/1,-1011.32,-4970.48,40,0
    .goto 1441/1,-912.05,-4941.71,50,0
    .goto 1441/1,-917.77,-5090.43,50,0
    .goto 1441/1,-1017.21,-5095.12,50,0
    .goto 1441/1,-1201.57,-5187.52,50,0
    .goto 1441/1,-920.41,-5010.64
    >>Kill |cRXP_ENEMY_Highperch Wyverns|r, |cRXP_ENEMY_Highperch Consorts|r and |cRXP_ENEMY_Highperch Patriarchs|r. Loot them for their |cRXP_LOOT_Venom Sacs|r
    .complete 1135,1
    .mob Highperch Patriarch
    .mob Highperch Wyvern
    .mob Highperch Consort

step
    #completewith next
    .goto 1441/1,-3855.74,-6233.05,100 >> Travel to the Mirage Raceway

step
    .goto 1441/1,-3855.74,-6233.05
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kravel Koalbeard|r
    >>|cRXP_WARN_Don't accept the other quests yet|r
    .accept 1110 >> Accept Rocket Car Parts
    .target Kravel Koalbeard

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Fizzle Brassbolts|r and |cRXP_FRIENDLY_Wizzle Brassbolts|r
    .accept 1104 >> Accept Salt Flat Venom
    .target +Fizzle Brassbolts
    .goto 1441/1,-3868.15,-6229.03
    .turnin 1179 >> Turn in The Brassbolts Brothers
    .accept 1105 >> Accept Hardened Shells
    .goto 1441/1,-3871.63,-6228.850
    .target +Wizzle Brassbolts
    .isOnQuest 1179

step
    #optional
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Fizzle Brassbolts|r and |cRXP_FRIENDLY_Wizzle Brassbolts|r
    .accept 1104 >> Accept Salt Flat Venom
    .target +Fizzle Brassbolts
    .goto 1441/1,-3868.15,-6229.03
    .accept 1105 >> Accept Hardened Shells
    .goto 1441/1,-3871.63,-6228.850
    .target +Wizzle Brassbolts

step
    .goto 1441/1,-3961.17,-6192.54
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Pozzik|r
    .accept 1176 >> Accept Load Lightening
    .target Pozzik

step
    #label ABump
    .goto 1441/1,-4025.27,-6253.29
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Trackmaster Zherin|r
    .accept 1175 >> Accept A Bump in the Road
    .target Trackmaster Zherin

step
    #optional
    >>|cRXP_WARN_Run circles around The Shimmering Flats until all objectives are complete|r
    >>Kill |cRXP_ENEMY_Salt Flats Scavengers|r and |cRXP_ENEMY_Salt Flats Vultures|r. Loot them for their |cRXP_LOOT_Bones|r
    >>Kill |cRXP_ENEMY_Sparkleshell Tortoises|r, |cRXP_ENEMY_Sparkleshell Borers|r and |cRXP_ENEMY_Sparkleshell Snappers|r. Loot them for their |cRXP_LOOT_Shells|r
    >>|cRXP_WARN_Don't go out of your way to collect all|r |cRXP_LOOT_Turtle Meat|r
    >>Kill |cRXP_ENEMY_Scorpid Reavers|r and |cRXP_ENEMY_Scorpid Terrors|r. Loot them for their |cRXP_LOOT_Venom|r
    >>Kill |cRXP_ENEMY_Saltstone Basilisks|r, |cRXP_ENEMY_Saltstone Crystalhides|r and |cRXP_ENEMY_Saltstone Gazers|r
    >>Loot |cRXP_ENEMY_Saltstone Basilisks|r for their |cRXP_LOOT_Scales|r
    >>Open the |cRXP_PICK_Rocket Car Rubble|r. Loot it for the |cRXP_LOOT_Rocket Car Parts|r
    .complete 1176,1
    .mob +Salt Flats Scavenger
    .mob +Salt Flats Vulture
    .goto 1441/1,-4283.33,-5890.93,0
    .complete 1105,1
    .mob +Sparkleshell Snapper
    .mob +Sparkleshell Borer
    .mob +Sparkleshell Tortoise
    .goto 1441/1,-4067.73,-5574.13,0
    .complete 1104,1
    .mob +Scorpid Reaver
    .mob +Scorpid Terror
    .goto 1441/1,-3592.53,-6119.73,0
    .complete 1175,1
    .mob +Saltstone Basilisk
    .goto 1441/1,-3667.33,-5723.73,0
    .complete 1078,1
    .goto 1441/1,-3667.33,-5723.73,0
    .complete 1175,2
    .mob +Saltstone Crystalhide
    .goto 1441/1,-3849.93,-6528.64,0
    .complete 1175,3
    .mob +Saltstone Gazer
    .goto 1441/1,-3849.93,-6528.64,0
    .complete 1110,1
    .isOnQuest 1078

step
    >>|cRXP_WARN_Run circles around The Shimmering Flats until all objectives are complete|r
    >>Kill |cRXP_ENEMY_Salt Flats Scavengers|r and |cRXP_ENEMY_Salt Flats Vultures|r. Loot them for their |cRXP_LOOT_Bones|r
    >>Kill |cRXP_ENEMY_Sparkleshell Tortoises|r, |cRXP_ENEMY_Sparkleshell Borers|r and |cRXP_ENEMY_Sparkleshell Snappers|r. Loot them for their |cRXP_LOOT_Shells|r
    >>|cRXP_WARN_Don't go out of your way to collect all|r |cRXP_LOOT_Turtle Meat|r
    >>Kill |cRXP_ENEMY_Scorpid Reavers|r and |cRXP_ENEMY_Scorpid Terrors|r. Loot them for their |cRXP_LOOT_Venom|r
    >>Kill |cRXP_ENEMY_Saltstone Basilisks|r, |cRXP_ENEMY_Saltstone Crystalhides|r and |cRXP_ENEMY_Saltstone Gazers|r
    >>Open the |cRXP_PICK_Rocket Car Rubble|r. Loot it for the |cRXP_LOOT_Rocket Car Parts|r
    #loop
    .goto 1441/1,-4283.33,-5890.93,0
    .goto 1441/1,-4067.73,-5574.13,0
    .goto 1441/1,-3667.33,-5723.73,0
    .goto 1441/1,-3592.53,-6119.73,0
    .goto 1441/1,-3849.93,-6528.64,0
    .complete 1176,1
    .mob +Salt Flats Scavenger
    .mob +Salt Flats Vulture
    .complete 1105,1
    .mob +Sparkleshell Snapper
    .mob +Sparkleshell Borer
    .mob +Sparkleshell Tortoise
    .complete 1104,1
    .mob +Scorpid Reaver
    .mob +Scorpid Terror
    .complete 1175,1
    .mob +Saltstone Basilisk
    .complete 1175,2
    .mob +Saltstone Crystalhide
    .complete 1175,3
    .mob +Saltstone Gazer
    .complete 1110,1

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Trackmaster Zherin|r
    .goto 1441/1,-4025.27,-6253.29
    .turnin 1175 >> Turn in A Bump in the Road
    .target Trackmaster Zherin

step
    .goto 1441/1,-3961.17,-6192.54
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Pozzik|r
    .turnin 1176 >> Turn in Load Lightening
    .accept 1178 >> Accept Goblin Sponsorship
    .target Pozzik

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Fizzle Brassbolts|r and |cRXP_FRIENDLY_Wizzle Brassbolts|r
    .turnin 1104 >> Turn in Salt Flat Venom
    .target +Fizzle Brassbolts
    .goto 1441/1,-3868.15,-6229.03
    .turnin 1105 >> Turn in Hardened Shells
    .target +Wizzle Brassbolts
    .goto 1441/1,-3871.63,-6228.850

step
    #label TurninShimmering
    .goto 1441/1,-3855.74,-6233.05
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Kravel Koalbeard|r
    .turnin 1110 >> Turn in Rocket Car Parts
    .accept 1111 >> Accept Wharfmaster Dizzywig
    .accept 5762 >> Accept Hemet Nesingwary
    .target Kravel Koalbeard

step
    #completewith next
    .goto 1446/1,-3738.44,-7225.10,150 >> Travel to Tanaris

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Bera Stonehammer|r
    .goto 1446/1,-3738.16,-7224.87
    .fp Tanaris>> Get the Tanaris Flight Path
    .target Bera Stonehammer

step
    #completewith DWallow
    .hs >> Hearth to Theramore
    >>|cRXP_BUY_Buy food/water if needed|r << !Warrior !Rogue
    >>|cRXP_BUY_Buy food if needed|r << Warrior/Rogue

step
    .isOnQuest 1135
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Fiora Longears|r
    .goto 1445/1,-4464.10,-3613.48
    .turnin 1135 >> Turn in Highperch Venom
    .target Fiora Longears

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to the |cRXP_FRIENDLY_Theramore Lieutenant|r
    .goto 1445/1,-4551.56,-3720.37
    .turnin 1219 >> Turn in The Orc Report
    .accept 1220 >> Accept Captain Vimes
    .target Theramore Lieutenant

step
    #completewith next
    .goto 1445/1,-4557.08,-3742.03,25 >> Travel upstairs in the Keep

step
    #label DWallow
    .goto 1445/1,-4556.13,-3735.030
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Captain Garran Vimes|r
    .turnin 1252 >> Turn in Lieutenant Paval Reethe
    .accept 1259 >> Accept Lieutenant Paval Reethe
    .turnin 1253 >> Turn in The Black Shield
    .accept 1319 >> Accept The Black Shield
    .turnin 1284 >> Turn in Suspicious Hoofprints
    .turnin 1220 >> Turn in Captain Vimes
    .target Captain Garran Vimes

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Captain Garran Vimes|r
    .turnin 1282 >> Turn in They Call Him Smiling Jim
    .goto 1445/1,-4556.13,-3735.030
    .target Captain Garran Vimes
    .isOnQuest 1282

step
    .goto 1445/1,-4547.10,-3717.18
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Adjutant Tesoran|r
    .turnin 1259 >> Turn in Lieutenant Paval Reethe
    .accept 1285 >> Accept Daelin's Men
    .target Adjutant Tesoran

step
    .goto 1445/1,-4556.13,-3735.030
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Captain Garran Vimes|r
    .turnin 1285 >> Turn in Daelin's Men
    .target Captain Garran Vimes

step
    .goto 1445/1,-4374.69,-3798.24
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Caz Twosprocket|r
    .turnin 1319 >> Turn in The Black Shield
    .accept 1320 >> Accept The Black Shield
    .target Caz Twosprocket

step
    .goto 1445/1,-4556.13,-3735.030
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Captain Garran Vimes|r
    .turnin 1320 >> Turn in The Black Shield
    .target Captain Garran Vimes

step << Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Baldruc|r
    .goto 1445/1,-4517.49,-3828.87
    .fly Ratchet>> Fly to Ratchet
    .target Baldruc

step << !Warlock
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Baldruc|r
    .goto 1445/1,-4517.49,-3828.87
    .fly Ratchet>> Fly to Ratchet
    .target Baldruc
    .dungeon WC

step << !Warlock
    .dungeon !WC
    #sticky
    #completewith ratchetTravel
    >>Loot any |cRXP_ENEMY_Mirefin Murlocs|r you kill for |T134302:0|t[|cRXP_LOOT_Mirefin Heads|r] for a quest later
    >>|cRXP_WARN_Don't aim to complete this objective now, you will finish later|r
    .complete 1177,1
    .mob Mirefin Puddlejumper
    .mob Mirefin Murloc
    .mob Mirefin Oracle
    .mob Mirefin Coastrunner
    .mob Mirefin Muckdweller
    .mob Mirefin Warrior
    .mob Burgle Eye

step << !Warlock
    #label ratchetTravel
    .goto 1445/1,-3823.13,-2355.330,80,0
    .goto 1413/1,-3728.66,-835.29
    .zone The Barrens >> Travel north to The Barrens grinding your way up
    .dungeon !WC

step << Warrior
    #completewith next
    .goto 1413/1,-3746.90,-1951.42,80,0
    .goto 1413/1,-4302.20,-1687.25,50 >> Travel to Fray Island

step << Warrior
    .goto 1413/1,-4330.07,-1709.08
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Klannoc Macleod|r
    .turnin 1718 >> Turn in The Islander
    .accept 1719 >> Accept The Affray
    .target Klannoc Macleod

step << Warrior
    .goto 1413/1,-4329.16,-1679.150
    >>|cRXP_WARN_Start the affray by stepping on the grate|r
    >>Kill |cRXP_ENEMY_Affray Challengers|r until |cRXP_ENEMY_Big Will|r appears
    >>Kill |cRXP_ENEMY_Big Will|r
    .complete 1719,2
    .complete 1719,1
    .mob Affray Challenger
    .mob Big Will

step << Warrior
    .goto 1413/1,-4330.07,-1709.08
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Klannoc Macleod|r
    .turnin 1719 >> Turn in The Affray
    .accept 1791 >> Accept The Windwatcher
    .target Klannoc Macleod

step
    .goto 1413/1,-3724.50,-915.76,-1
    .goto The Barrens,62.680,37.395,-1
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Fuzruckle|r or |cRXP_FRIENDLY_Zikkel|r
    .bankdeposit 3721,3521,4521,5847 >> Deposit the following items into your bank:
    >>|T133461:0|t[Farren's Report]
    >>|T134939:0|t[Cleverly Encrypted Letter] (If you found it)
    >>|T135234:0|t[Alterac Granite]
    >>|T134302:0|t[Mirefin Head]
    .target Fuzruckle
    .target Zikkel

step << !Warlock
    #season 0
    .goto 1413/1,-3769.60,-898.33
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Bragok|r
    .fp Ratchet>> Get the Ratchet Flight Path
    .target Bragok
    .dungeon !WC

step
    #label GSponsor
    .goto The Barrens,62.680,36.234
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gazlowe|r
    .turnin 1178 >> Turn in Goblin Sponsorship
    .accept 1180 >> Accept Goblin Sponsorship
    .target Gazlowe

step << Warlock
    .isOnQuest 4736
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Menara Voidrender|r
    .goto 1413/1,-3711.33,-782.52
    .turnin 4736 >> Turn in In Search of Menara Voidrender
    .target Menara Voidrender

step << Warlock
    .isOnQuest 4738
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Menara Voidrender|r
    .goto 1413/1,-3711.33,-782.52
    .turnin 4738 >> Turn in In Search of Menara Voidrender
    .target Menara Voidrender

step << Warlock
    .goto 1413/1,-3723.29,-785.9700
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Strahad Farsan|r
    .turnin 1798 >> Turn in Seeking Strahad
    .accept 1758 >> Accept Tome of the Cabal
    .target Strahad Farsan

step
    .goto 1413/1,-3796.75,-985.68
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Wharfmaster Dizzywig|r
    .turnin 1111 >> Turn in Wharfmaster Dizzywig
    .accept 1112 >> Accept Parts for Kravel
    .turnin 1039 >> Turn in The Barrens Port
    .accept 1040 >> Accept Passage to Booty Bay
    .target Wharfmaster Dizzywig
    .isQuestTurnedIn 1038

step
    #label Wharfmaster
    .goto 1413/1,-3796.75,-985.68
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Wharfmaster Dizzywig|r
    .turnin 1111 >> Turn in Wharfmaster Dizzywig
    .accept 1112 >> Accept Parts for Kravel
    .target Wharfmaster Dizzywig

step
    #label end
    .goto 1413/1,-3829.69,-996.63
    >>|cRXP_WARN_Level your|r |T135966:0|t[First Aid] |cRXP_WARN_while waiting|r
    .zone Stranglethorn Vale >> Take the boat to Booty Bay
]])
