-- Generated by Scripts/split_guide_vault.py; rerun the script to update.
if not RXPGuides or type(RXPGuides.RegisterGuide) ~= "function" then return end
local _, rxpGuideVaultAddon = ...
local rxpGuideVaultGame = rxpGuideVaultAddon and rxpGuideVaultAddon.game
if not rxpGuideVaultGame then
    local rxpGuideVaultVersion = select(4, GetBuildInfo())
    if rxpGuideVaultVersion > 60000 then
        rxpGuideVaultGame = "RETAIL"
    elseif rxpGuideVaultVersion > 50000 then
        rxpGuideVaultGame = "MOP"
    elseif rxpGuideVaultVersion > 40000 then
        rxpGuideVaultGame = "CATA"
    elseif rxpGuideVaultVersion > 30000 then
        rxpGuideVaultGame = "WOTLK"
    elseif rxpGuideVaultVersion > 20000 then
        rxpGuideVaultGame = "TBC"
    elseif rxpGuideVaultVersion >= 16000 and rxpGuideVaultVersion < 20000 then
        rxpGuideVaultGame = "FOREVER"
    else
        rxpGuideVaultGame = "CLASSIC"
    end
end
if rxpGuideVaultGame ~= "FOREVER" then return end

RXPGuides.RegisterGuide([[#forever
#version 23
#group RestedXP Forever Guide (A)
#subgroup Speedrun Guide 40-50

<< Alliance
#name 48-49 Tanaris/Hinterlands
#somname 47-49 Tanaris/Hinterlands
#next 49-50 Tanaris/Un'Goro

step
    #season 0
    .goto 1446/1,-3827.24,-7205.09
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gimblethorn|r
    .bankwithdraw 6257 >> Withdraw the following items from your bank:
    >>|T133707:0|t[Roc Gizzard] (If you have any)
    .target Gimblethorn

step
    .goto 1446/1,-3841.94,-7158.86
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Innkeeper Fizzgrimble|r
    .home >> Set your Hearthstone to Gadgetzan
    .bindlocation 976
    .target Innkeeper Fizzgrimble

step
    .goto 1446/1,-3833.45,-7115.53
    >>Click the |cRXP_PICK_Egg-O-Matic|r on the ground
    .turnin 2741 >> Turn in The Super Egg-O-Matic
    .itemcount 8564,1

step
    #optional
    +Open your |T132594:0|t[Egg Crate]
    .itemcount 8647,1
    .use 8647

step
    .goto 1446/1,-3831.45,-7112.58
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Curgle Cranklehop|r
    .turnin 2941 >> Turn in The Borrower
    .accept 2944 >> Accept The Super Snapper FX
    .target Curgle Cranklehop

step
    #optional
    .goto 1446/1,-3831.45,-7112.58
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Curgle Cranklehop|r
    .accept 2750 >> Accept A Bad Egg
    .turnin 2750 >> Turn in A Bad Egg
    .target Curgle Cranklehop
    .itemcount 8646,1

step
    #optional
    .goto 1446/1,-3831.45,-7112.58
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Curgle Cranklehop|r
    .accept 2749 >> Accept An Ordinary Egg
    .turnin 2749 >> Turn in An Ordinary Egg
    .target Curgle Cranklehop
    .itemcount 8645,1

step
    #optional
    .goto 1446/1,-3831.45,-7112.58
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Curgle Cranklehop|r
    .accept 2748 >> Accept A Fine Egg
    .turnin 2748 >> Turn in A Fine Egg
    .target Curgle Cranklehop
    .itemcount 8644,1

step
    #optional
    .goto 1446/1,-3831.45,-7112.58
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Curgle Cranklehop|r
    .accept 2747 >> Accept An Extraordinary Egg
    .turnin 2747 >> Turn in An Extraordinary Egg
    .target Curgle Cranklehop
    .itemcount 8643,1

step
    #optional
    +Open your |T132594:0|t[Box of Rations]
    .itemcount 9539,1
    .use 9539

step
    #optional
    +Open your |T132595:0|t[Box of Spells]
    .itemcount 9540,1
    .use 9540

step
    #optional
    +Open your |T132597:0|t[Box of Goodies]
    .itemcount 9541,1
    .use 9541

step
    #label start
    .goto Tanaris,50.210,27.483
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Senior Surveyor Fizzledowser|r
    .accept 992 >> Accept Gadgetzan Water Survey
    .target Senior Surveyor Fizzledowser

step
    #completewith vultures
    >>Kill |cRXP_ENEMY_Rocs|r. Loot them for their |cRXP_LOOT_Gizzards|r
    >>|cRXP_WARN_Don't go out of your way to finish this|r
    .complete 1452,1
    .isOnQuest 1452
    .mob Roc
    .mob Fire Roc

step
    .goto 1446/1,-2910.85,-7220.22
    .use 8584 >> |cRXP_WARN_Use the|r |T134867:0|t[Untapped Dowsing Widget] |cRXP_WARN_at the Sandsorrow Watch pond. Avoid the Elite |cRXP_ENEMY_Sandfury Trolls|r en-route|r
    >>|cRXP_WARN_Two level 47/48 |cRXP_ENEMY_Centipaar Tunnelers|r will spawn once you fill the|r |T134867:0|t[Untapped Dowsing Widget]|cRXP_WARN_. You may kill them or run away to reset them|r
    .complete 992,1
    .mob Centipaar Tunneler

step
    .goto Tanaris,50.210,27.483
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Senior Surveyor Fizzledowser|r
    .turnin 992 >> Turn in Gadgetzan Water Survey
    .accept 82 >> Accept Noxious Lair Investigation
    .target Senior Surveyor Fizzledowser

step
    #label vultures
    .goto 1446/1,-2680.67,-7704.88,70,0
    .goto 1446/1,-2740.70,-7806.08,70,0
    .goto 1446/1,-2674.46,-7902.68,70,0
    .goto Tanaris,35.60,48.79,70,0
    .goto Tanaris,31.70,49.12,70,0
    .goto 1446/1,-2346.02,-7995.600,70,0
    .goto 1446/1,-2680.67,-7704.88
    >>Kill |cRXP_ENEMY_Centipaar Sandreavers|r, |cRXP_ENEMY_Centipaar Swarmers|r, |cRXP_ENEMY_Centipaar Stingers|r, |cRXP_ENEMY_Centipaar Tunnelers|r, and |cRXP_ENEMY_Centipaar Wasps|r. Loot them for |cRXP_LOOT_Centipaar Insect Parts|r
    >>|cRXP_WARN_Be careful as all |cRXP_ENEMY_Centipaar|r cast|r |T132152:0|t[Thrash] |cRXP_WARN_(Charges 2 extra attacks every 10 seconds), |cRXP_ENEMY_Centipaar Sandreavers|r cast|r |T132338:0|t[Arcing Smash] |cRXP_WARN_(Deals an extra melee attack), |cRXP_ENEMY_Centipaar Swarmers|r cast|r |T136122:0|t[Silithid Swarm] |cRXP_WARN_(Summons a 1 health mob every 10 seconds that deals current-level attack damage, instantly dies to AoE), |cRXP_ENEMY_Centipaar Stingers|r cast|r |T132274:0|t[Venom Sting] |cRXP_WARN_(deals 11-12 damage every 5 seconds for 45 seconds), |cRXP_ENEMY_Centipaar Tunnelers|r cast|r |T136231:0|t[Pierce Armor] |cRXP_WARN_(Reduces armor by 50% for 20 seconds), and |cRXP_ENEMY_Centipaar Wasps|r cast|r |T136016:0|t[Poison] |cRXP_WARN_(deals 33-34 damage every 3 seconds for 30 seconds)|r
    .complete 82,1
    .mob Centipaar Sandreaver
    .mob Centipaar Swarmer
    .mob Centipaar Stinger
    .mob Centipaar Tunneler
    .mob Centipaar Wasp
    .mob Silithid Swarm

step
    .goto 1446/1,-4056.53,-7046.16,50,0
    .goto 1446/1,-3888.86,-7332.74,50,0
    .goto 1446/1,-3632.87,-7524.10
    .goto Tanaris,44.60,39.60,0
    >>Kill |cRXP_ENEMY_Rocs|r and |cRXP_ENEMY_Fire Rocs|r. Loot them for their |cRXP_LOOT_Gizzards|r
    >>|cRXP_WARN_The |cRXP_ENEMY_Rocs|r share spawns with |cRXP_ENEMY_Starving Blisterpaws|r. You may need to kill |cRXP_ENEMY_Starving Blisterpaws|r to force |cRXP_ENEMY_Rocs|r to spawn|r
    .complete 1452,1
    .isOnQuest 1452
    .mob Roc
    .mob Fire Roc

step
    #season 0
    #completewith next
    .deathskip >>Die and respawn at the Spirit Healer in Gadgetzan
    .target Spirit Healer

step
    .goto 1446/1,-3729.88,-7115.30
    .target Alchemist Pestlezugg
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Alchemist Pestlezugg|r
    .turnin 82 >> Turn in Noxious Lair Investigation

step
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Bera Stonehammer|r
    .goto 1446/1,-3738.16,-7224.87
    .fly Theramore >> Fly to Theramore
    .target Bera Stonehammer

step
    .goto 1445/1,-4723.50,-3996.83
    .zone Wetlands >> Take the boat to Menethil Harbor
    .zoneskip The Hinterlands

step
    #completewith next
    .goto Wetlands,9.490,59.693
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Shellei Brondir|r
    .fly Hinterlands >> Fly to Hinterlands
    .target Shellei Brondir

step
    .goto 1425/0,-1950.45,325.19
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gryphon Master Talonaxe|r
    .accept 2988 >> Accept Witherbark Cages
    .target Gryphon Master Talonaxe

step
    #sticky
    #completewith FinishFeathers
    >>Loot the |cRXP_LOOT_Wildkin Feathers|r on the ground
    >>|cRXP_WARN_These are scattered on the ground throughout all of The Hinterlands|r
    .complete 3661,1

step
    .goto 1425/0,-2612.31,219.57
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Rhapsody Shindigger|r
    .turnin 1452 >> Turn in Rhapsody's Kalimdor Kocktail
    .timer 35,Rhapsody's Kalimdor Kocktail RP
    .accept 1469 >> Accept Rhapsody's Tale
    .target Rhapsody Shindigger
    .isOnQuest 1452

step
    #optional
    .goto 1425/0,-2612.31,219.57
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Rhapsody Shindigger|r
    .accept 1469 >> Accept Rhapsody's Tale
    .target Rhapsody Shindigger
    .isQuestTurnedIn 1452
    .isQuestAvailable 1452

step
    #completewith FinalCages
    >>Kill |cRXP_ENEMY_Witherbark Trolls|r. Loot them for their |cRXP_LOOT_Tribal Necklaces|r
    .collect 9259,5,2880,1
    .mob Witherbark Venomblood
    .mob Witherbark Hideskinner
    .mob Witherbark Zealot
    .mob Witherbark Scalper

step
    .goto 1425/0,-2806.23,-4.29
    >>Click the |cRXP_PICK_Third Witherbark Cage|r
    .complete 2988,3

step
    #label FinalCages
    >>Click the |cRXP_PICK_First Witherbark Cage|r and |cRXP_PICK_Second Witherbark Cage|r
    .complete 2988,1
    .goto 1425/0,-2471.28,-42.79
    .complete 2988,2
    .goto 1425/0,-2465.12,-43.05

step
    #label TrollNecklaces
    .goto 1425/0,-2418.92,28.31,70,0
    .goto 1425/0,-2540.97,-52.800,70,0
    .goto 1425/0,-2815.86,-27.39
    >>Kill |cRXP_ENEMY_Witherbark Trolls|r. Loot them for their |cRXP_LOOT_Tribal Necklaces|r
    .collect 9259,5,2880,1
    .mob Witherbark Venomblood
    .mob Witherbark Hideskinner
    .mob Witherbark Zealot
    .mob Witherbark Scalper

step
    .goto 1425/0,-2120.55,303.20,25,0
    .goto 1425/0,-2146.11,322.78
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Fraggar Thundermantle|r
    .accept 2880 >> Accept Troll Necklace Bounty
    .turnin 2880 >> Turn in Troll Necklace Bounty
    .accept 2877 >> Accept Skulk Rock Clean-up
    .target Fraggar Thundermantle

step
    .goto 1425/0,-1950.45,325.19
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gryphon Master Talonaxe|r
    .turnin 2988 >> Turn in Witherbark Cages
    .accept 2989 >> Accept The Altar of Zul
    .target Gryphon Master Talonaxe

step
    .goto 1425/0,-3454.34,-288.60
    >>|cRXP_WARN_Clear your way to the top of The Altar of Zul. Ensure you are on full HP before you reach the top!|r
    >>|cRXP_WARN_Run to the exploration location, then jump off to the side to evade the Elites at the top. Wait on the ledge until you have dropped Combat. Watch the video below for an example|r
    .complete 2989,1
    .link https://youtu.be/Z4gDpWTXaFY >> |cRXP_WARN_Click here for video reference|r

step
    #label FinishFeathers
    .goto 1425/0,-3367.56,424.600,60,0
    .goto 1425/0,-3355.24,443.85,60,0
    .goto 1425/0,-3794.53,367.36
    >>Kill |cRXP_ENEMY_Green Sludges|r and |cRXP_ENEMY_Jade Oozes|r
    .complete 2877,1
    .mob +Green Sludge
    .complete 2877,2
    .mob +Jade Ooze

step
    .goto 1425/0,-3211.25,67.83,70,0
    .goto 1425/0,-2864.75,-24.57,70,0
    .goto 1425/0,-2714.60,-124.67,70,0
    .goto 1425/0,-2641.45,67.83,70,0
    .goto The Hinterlands,21.0,56.1,70,0
    .goto The Hinterlands,20.0,48.2,70,0
    .goto 1425/0,-2179.45,119.17,70,0
    .goto 1425/0,-2656.85,-24.57
    >>Loot the |cRXP_LOOT_Wildkin Feathers|r on the ground
    >>|cRXP_WARN_These are scattered on the ground throughout all of The Hinterlands|r
    .complete 3661,1

step
    .use 8704 >>|cRXP_WARN_Use the |T132836:0|t[|cRXP_LOOT_OOX-09/HL Distress Beacon|r] to start the quest|r
    >>|cRXP_WARN_If you are unlucky and have not found it yet, skip this step|r
    .collect 8704,1,485,1
    .accept 485 >> Accept Find OOX-09/HL!
    .itemcount 8704,1

step
    .isOnQuest 485
    .goto 1425/0,-3475.05,500.14
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to the |cRXP_FRIENDLY_Homing Robot OOX-09/HL|r
    .turnin 485 >> Turn in Find OOX-09/HL!
    .target Homing Robot OOX-09/HL

step
    .isQuestTurnedIn 485
    .goto 1425/0,-3475.05,500.14
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to the |cRXP_FRIENDLY_Homing Robot OOX-09/HL|r
    .accept 836,1 >> Accept Rescue OOX-09/HL!
    .target Homing Robot OOX-09/HL

step
    .isOnQuest 836
    .goto 1425/0,-4364.71,-231.44,40,0
    .goto 1425/0,-4509.47,-119.79,45,0
    .goto 1425/0,-4629.20,-105.67
    >>Escort the |cRXP_FRIENDLY_Homing Robot OOX-09/HL|r to safety
    >>|cRXP_WARN_This quest can be hard. You have to fight waves of 3/4 mobs along the way. Skip this step if its too difficult|r
    .complete 836,1
    .target Homing Robot OOX-22/FE

step
    #completewith GammeritaSnapshot
    +Grind until your Hearthstone cooldown is <6min
    .cooldown item,6948,<360

step
    #completewith next
    >>Loot the |cRXP_LOOT_Pupellyverbos Ports|r on the ground
    .complete 580,1

step
    #label GammeritaSnapshot
    .line 1425/0,-4730.07,198.48,81.21,52.91,81.98,54.30,81.97,56.42,80.77,58.37,80.34,59.40,79.45,60.76,78.69,61.39,76.86,62.73,75.91,63.81,75.29,65.60,76.72,66.85,78.53,67.51,78.60,68.97,77.90,70.97,76.71,71.26,76.52,72.95,77.07,74.64
    .goto 1425/0,-4730.07,198.48,70,0
    .goto 1425/0,-4701.58,108.64,70,0
    .goto 1425/0,-4731.23,72.970,70,0
    .goto 1425/0,-4730.84,18.55,70,0
    .goto 1425/0,-4684.65,-31.50,70,0
    .goto 1425/0,-4668.09,-57.930,70,0
    .goto 1425/0,-4633.82,-92.84,70,0
    .goto 1425/0,-4604.56,-109.01,70,0
    .goto 1425/0,-4534.11,-143.40,70,0
    .goto 1425/0,-4497.53,-171.12,70,0
    .goto 1425/0,-4473.66,-217.070,70,0
    .goto 1425/0,-4528.72,-249.15,70,0
    .goto 1425/0,-4598.41,-266.09,70,0
    .goto The Hinterlands,78.60,68.97,70,0
    .goto The Hinterlands,77.90,70.97,70,0
    .goto 1425/0,-4528.33,-362.34,70,0
    .goto 1425/0,-4521.02,-405.72,70,0
    .goto 1425/0,-4542.19,-449.09,70,0
    .goto 1425/0,-4701.58,108.64,70,0
    .goto 1425/0,-4497.53,-171.12
    .use 9328 >> |cRXP_WARN_Use the|r |T134442:0|t[Super Snapper FX] |cRXP_WARN_on|r |cRXP_ENEMY_Gammerita|r
    >>|cRXP_WARN_This will cause |cRXP_ENEMY_Gammerita|r to aggro you. Be ready to run away after using it|r
    .complete 2944,1
    .unitscan Gammerita

step
    .goto 1425/0,-4720.45,201.30,70,0
    .goto 1425/0,-4628.05,-86.17,70,0
    .goto 1425/0,-4558.75,-337.70,70,0
    .goto 1425/0,-4489.45,-188.83,70,0
    .goto 1425/0,-4728.15,108.90,70,0
    .goto 1425/0,-4574.15,-214.50
    >>Loot the |cRXP_LOOT_Pupellyverbos Ports|r on the ground
    .complete 580,1

step
    .goto 1425/0,-4685.03,264.95
    >>Click on |cRXP_PICK_Cortello's Treasure|r underwater
    .turnin 626 >> Turn in Cortello's Riddle
    .isOnQuest 626

step
    .goto The Hinterlands,47.20,65.95
    +Grind until your Hearthstone is off cooldown
    .cooldown item,6948,<0

step
    #label HinterlandsEnd
    .hs >> Hearth to Tanaris
    .cooldown item,6948,>0,1
]])
